pressgang_website_callback([
	{"topicId":8706,"target":"Connecting_to_virtual_machines1","title":"Connecting to Virtual Machines","newSince":""},
	{"topicId":8707,"target":"Turning_off_virtual_machines","title":"Turning Off a Virtual Machine from the User Portal","newSince":""},
	{"topicId":12581,"target":"sect-Running_Virtual_Machines","title":"Running Virtual Machines - Overview","newSince":""},
	{"topicId":7848,"target":"Red_Hat_Enterprise_Virtualization_Manager_Client_Requirements","title":"Browser and Client Requirements","newSince":""},
	{"topicId":7368,"target":"Logging_in_to_the_User_Portal1","title":"Logging in to and out of the User Portal","newSince":""},
	{"topicId":11500,"target":"What_To_Do_When_You_Exceed_Your_Quota","title":"What to Do When You Exceed Your Quota","newSince":""},
	{"topicId":8557,"target":"User_Portal_Graphical_Interface","title":"Basic Tab Graphical Interface","newSince":""},
	{"topicId":8558,"target":"Logging_out_of_a_virtual_machine","title":"Logging out of a Virtual Machine","newSince":""},
	{"topicId":12655,"target":"The_Power_User_Portal_Graphical_Interface","title":"Extended Tab Graphical Interface","newSince":""},
	{"topicId":7380,"target":"Turning_on_a_virtual_machine","title":"Turning on a Virtual Machine","newSince":""},
	{"topicId":7381,"target":"Connecting_to_a_poweredon_virtual_machine","title":"Connecting to a Powered-On Virtual Machine","newSince":""},
	{"topicId":34614,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":8727,"target":"Monitoring_virtual_resources","title":"Monitoring Resources","newSince":""},
	{"topicId":30299,"target":"Rebooting_a_Virtual_Machine_from_the_User_Portal","title":"Rebooting a Virtual Machine from the User Portal","newSince":""},
	{"topicId":44859,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":11709,"target":"Quota_-_A_Users_Introduction","title":"Quota - A User's Introduction","newSince":""},
	{"topicId":8702,"target":"Logging_in_for_the_first_time1","title":"Installing the Red Hat Enterprise Virtualization Manager Certificate in Firefox","newSince":""},
	{"topicId":30847,"target":"Installing_the_Red_Hat_Enterprise_Virtualization_Manager_Certificate_in_Internet_Explorer","title":"Installing the Red Hat Enterprise Virtualization Manager Certificate in Internet Explorer","newSince":""}], 23140, "Red Hat Enterprise Virtualization", "Introduction to the User Portal", "3.6-Beta");