:_content-type: PROCEDURE
[id="Connecting_to_the_Red_Hat_Enterprise_Virtualization_Manager_4"]
= Connecting to the {virt-product-fullname} {engine-name} in Version 4

In V4 of the Java software development kit, the `Connection` class is the main class you use to connect to and manipulate objects in a {virt-product-fullname} environment. To declare an instance of this class, you must declare an instance of the `ConnectionBuilder` class, pass the required arguments to this instance using builder methods, then call the `build` method on the instance. The `build` method returns an instance of the `Connection` class that you can then assign to a variable and use to perform subsequent actions.

The following is an example of a simple Java SE program that creates a connection with a {virt-product-fullname} environment using version 4 of the software development kit:

.Connecting to the {virt-product-fullname} {engine-name}
====

[source, Java]
----
package rhevm;

import org.ovirt.engine.sdk4.Connection;
import org.ovirt.engine.sdk4.ConnectionBuilder;

public class rhevm {

    public static void main(String[] args) {

            ConnectionBuilder myBuilder = ConnectionBuilder.connection()

            .url("https://rhevm.example.com/ovirt-engine/api")
            .user("admin@internal")
            .password("p@ssw0rd")
            .trustStoreFile("/home/username/server.truststore")
            .trustStorePassword("p@ssw0rd");
        
        try (Connection conn = myBuilder.build()) {

            // Requests

        } catch (Exception e) {
           
            // Error handling
 
        }
    }
}
----

====

This example creates a connection using basic authentication, but other methods are also available. For a list of the key arguments that can be passed to instances of the `ConnectionBuilder` class, see xref:ConnectionBuilder_Methods[].
