[id='proc-Customizing_Multipath_Configurations_for_SAN_Vendors_{context}']
= Customizing Multipath Configurations for SAN Vendors

To customize the multipath configuration settings, do not modify `/etc/multipath.conf`. Instead, create a new configuration file that overrides `/etc/multipath.conf`.

[WARNING]
====
Upgrading Virtual Desktop and Server Manager (VDSM)  overwrites the `/etc/multipath.conf` file. If `multipath.conf` contains customizations, overwriting it can trigger storage issues.
====

.Prerequisites

* This topic only applies to systems that have been configured to use multipath connections storage domains, and therefore have a `/etc/multipath.conf` file.
* Do not override the `user_friendly_names` and `find_multipaths` settings. For more information, see xref:ref-Recommended_Settings_for_Multipath.conf_{context}[]
* Avoid overriding `no_path_retry` and `polling_interval` unless required by the storage vendor. For more information, see xref:ref-Recommended_Settings_for_Multipath.conf_{context}[]

.Procedure

. To override the values of settings in `/etc/multipath.conf`, create a new configuration file in the `/etc/multipath/conf.d/` directory.
+
[NOTE]
====
The files in `/etc/multipath/conf.d/` execute in alphabetical order. Follow the convention of naming the file with a number at the beginning of its name. For example, `/etc/multipath/conf.d/90-myfile.conf`.
====
. Copy the settings you want to override from `/etc/multipath.conf` to the new configuration file in `/etc/multipath/conf.d/`. Edit the setting values and save your changes.
. Apply the new configuration settings by entering the `systemctl reload multipathd` command.
+
[NOTE]
====
Avoid restarting the multipathd service. Doing so generates errors in the VDSM logs.
====

.Verification steps

If you override the VDSM-generated settings in `/etc/multipath.conf`, verify that the new configuration performs as expected in a variety of failure scenarios.

For example, disable all of the storage connections. Then enable one connection at a time and verify that doing so makes the storage domain reachable.

.Troubleshooting

If a {hypervisor-fullname} has trouble accessing shared storage, check `/etc/multpath.conf` and files under `/etc/multipath/conf.d/` for values that are incompatible with the SAN.

.Additional resources

* link:{URL_rhel_docs_legacy}html-single/dm_multipath/[_{enterprise-linux} DM Multipath_] in the RHEL documentation.
* link:{URL_virt_product_docs}administration_guide#Configuring_iSCSI_Multipathing[Configuring iSCSI Multipathing] in the Administration Guide.
* link:https://access.redhat.com/solutions/3234761[How do I customize /etc/multipath.conf on my RHVH hypervisors? What values must not change and why?] on the Red Hat Customer Portal, which shows an example `multipath.conf` file and was the basis for this topic.
