:_content-type: PROCEDURE
[id='Adding_iSCSI_Storage_{context}']
= Adding iSCSI Storage

This procedure shows you how to attach existing iSCSI storage to your {virt-product-fullname} environment as a data domain.

.Procedure

. Click menu:Storage[Domains].
. Click *New Domain*.
. Enter the *Name* of the new storage domain.
. Select a *Data Center* from the drop-down list.
. Select *Data* as the *Domain Function* and *iSCSI* as the *Storage Type*.
. Select an active host as the *Host*.
+
[IMPORTANT]
====
Communication to the storage domain is from the selected host and not directly from the {engine-name}. Therefore, all hosts must have access to the storage device before the storage domain can be configured.
====

. The {engine-name} can map iSCSI targets to LUNs or LUNs to iSCSI targets. The *New Domain* window automatically displays known targets with unused LUNs when the iSCSI storage type is selected. If the target that you are using to add storage does not appear, you can use target discovery to find it; otherwise proceed to the next step.

.. Click *Discover Targets* to enable target discovery options. When targets have been discovered and logged in to, the *New Domain* window automatically displays targets with LUNs unused by the environment.
+
[NOTE]
====
LUNs used externally for the environment are also displayed.
====
+
You can use the *Discover Targets* options to add LUNs on many targets or multiple paths to the same LUNs.
+
[IMPORTANT]
====
If you use the REST API method `discoveriscsi` to discover the iscsi targets, you can use an FQDN or an IP address, but you must use the iscsi details from the discovered targets results to log in using the REST API method `iscsilogin`. See link:{URL_downstream_virt_product_docs}rest_api_guide/index#services-host-methods-discover_iscsi[discoveriscsi] in the _REST API Guide_ for more information.
====
.. Enter the FQDN or IP address of the iSCSI host in the *Address* field.
.. Enter the port with which to connect to the host when browsing for targets in the *Port* field. The default is `3260`.
.. If CHAP is used to secure the storage, select the *User Authentication* check box. Enter the *CHAP user name* and *CHAP password*.
+
[NOTE]
====
You can define credentials for an iSCSI target for a specific host with the REST API. See link:{URL_downstream_virt_product_docs}rest_api_guide/index#services-storage_server_connection_extensions-methods-add[StorageServerConnectionExtensions: add] in the _REST API Guide_ for more information.
====
+
.. Click *Discover*.
.. Select one or more targets from the discovery results and click *Login* for one target or *Login All* for multiple targets.
+
[IMPORTANT]
====
If more than one path access is required, you must discover and log in to the target through all the required paths. Modifying a storage domain to add additional paths is currently not supported.
====
+
[IMPORTANT]
====
When using the REST API `iscsilogin` method to log in, you must use the iscsi details from the discovered targets results in the `discoveriscsi` method. See link:{URL_downstream_virt_product_docs}rest_api_guide/index#services-host-methods-iscsi_login[iscsilogin] in the _REST API Guide_ for more information.
====
+
. Click the *+* button next to the desired target. This expands the entry and displays all unused LUNs attached to the target.
. Select the check box for each LUN that you are using to create the storage domain.
. Optionally, you can configure the advanced parameters:
.. Click *Advanced Parameters*.
.. Enter a percentage value into the *Warning Low Space Indicator* field. If the free space available on the storage domain is below this percentage, warning messages are displayed to the user and logged.
.. Enter a GB value into the *Critical Space Action Blocker* field. If the free space available on the storage domain is below this value, error messages are displayed to the user and logged, and any new action that consumes space, even temporarily, will be blocked.
.. Select the *Wipe After Delete* check box to enable the wipe after delete option. This option can be edited after the domain is created, but doing so will not change the wipe after delete property of disks that already exist.
.. Select the *Discard After Delete* check box to enable the discard after delete option. This option can be edited after the domain is created. This option is only available to block storage domains.
. Click btn:[OK].

If you have configured multiple storage connection paths to the same target, follow the procedure in link:{URL_virt_product_docs}{URL_format}administration_guide/index#Configuring_iSCSI_Multipathing[Configuring iSCSI Multipathing] to complete iSCSI bonding.

If you want to migrate your current storage network to an iSCSI bond, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Migrating_a_logical_network_to_an_iscsi_bond[Migrating a Logical Network to an iSCSI Bond].
