[id='ref-Recommended_Settings_for_Multipath_conf_{context}']
= Recommended Settings for Multipath.conf

When overriding `/etc/multipath.conf`, Do not override the following settings:

`user_friendly_names	no`:: This setting controls whether user-friendly names are assigned to devices in addition to the actual device names. Multiple hosts must use the same name to access devices. Disabling this setting prevents user-friendly names from interfering with this requirement.

`find_multipaths	no`:: This setting controls whether {hypervisor-shortname} tries to access all devices through multipath, even if only one path is available. Disabling this setting prevents {virt-product-shortname} from using the too-clever behavior when this setting is enabled.

Avoid overriding the following settings unless required by the storage system vendor:

`no_path_retry	4`:: This setting controls the number of polling attempts to retry when no paths are available. Before {virt-product-shortname} version 4.2, the value of `no_path_retry` was `fail` because QEMU had trouble with the I/O queuing when no paths were available. The `fail` value made it fail quickly and paused the virtual machine. {virt-product-shortname} version 4.2 changed this value to `4` so when multipathd detects the last path has failed, it checks all of the paths four more times. Assuming the default 5-second polling interval, checking the paths takes 20 seconds. If no path is up, multipathd tells the kernel to stop queuing and fails all outstanding and future I/O until a path is restored. When a path is restored, the 20-second delay is reset for the next time all paths fail. For more details, see link:https://gerrit.ovirt.org/#/c/88082/[the commit that changed this setting].

`polling_interval	5`:: This setting determines the number of seconds between polling attempts to detect whether a path is open or has failed. Unless the vendor provides a clear reason for increasing the value, keep the VDSM-generated default so the system responds to path failures sooner.
