:_content-type: CONCEPT
[id='Preparing_iSCSI_Storage_{context}']
= Preparing iSCSI Storage

{virt-product-fullname} supports iSCSI storage, which is a storage domain created from a volume group made up of LUNs. Volume groups and LUNs cannot be attached to more than one storage domain at a time.

For information on setting up and configuring iSCSI storage, see link:{URL_rhel_docs_latest}html-single/managing_storage_devices/index#getting-started-with-iscsi_managing-storage-devices[Getting started with iSCSI] in _Managing storage devices_ for Red Hat Enterprise Linux 8.

[IMPORTANT]
====
If you are using block storage and intend to deploy virtual machines on raw devices or direct LUNs and manage them with the Logical Volume Manager (LVM), you must create a filter to hide guest logical volumes. This will prevent guest logical volumes from being activated when the host is booted, a situation that could lead to stale logical volumes and cause data corruption. Use the `vdsm-tool config-lvm-filter` command to create filters for the LVM.
ifdef::storage-domain[]
See xref:Creating_LVM_filter_{context}[Creating an LVM filter] for details.
endif::storage-domain[]
ifdef::SHE_cli_deploy,migrating_to_SHE,SM_localDB_deploy,SM_remoteDB_deploy[]
See link:{URL_virt_product_docs}{URL_format}administration_guide/index#Creating_LVM_filter_storage_admin[Creating an LVM filter]
endif::SHE_cli_deploy,migrating_to_SHE,SM_localDB_deploy,SM_remoteDB_deploy[]
====

[IMPORTANT]
====
{virt-product-fullname} currently does not support block storage with a block size of 4K. You must configure block storage in legacy (512b block) mode.
====

[IMPORTANT]
====
If your host is booting from SAN storage and loses connectivity to the storage, the storage file systems become read-only and remain in this state after connectivity is restored.

To prevent this situation, add a drop-in multipath configuration file on the root file system of the SAN for the boot LUN to ensure that it is queued when there is a connection:

[source,terminal,subs="normal"]
----
# cat /etc/multipath/conf.d/host.conf
multipaths {
    multipath {
        wwid _boot_LUN_wwid_
        no_path_retry queue
    }
----
====
