:_content-type: CONCEPT
[id='Preparing_FCP_Storage_{context}']
= Preparing FCP Storage

{virt-product-fullname} supports SAN storage by creating a storage domain from a volume group made of pre-existing LUNs. Neither volume groups nor LUNs can be attached to more than one storage domain at a time.

{virt-product-fullname} system administrators need a working knowledge of Storage Area Networks (SAN) concepts. SAN usually uses Fibre Channel Protocol (FCP) for traffic between hosts and shared external storage. For this reason, SAN may occasionally be referred to as FCP storage.

For information on setting up and configuring FCP or multipathing on {enterprise-linux}, see the link:{URL_rhel_docs_legacy}html/Storage_Administration_Guide/index.html[_Storage Administration Guide_] and link:{URL_rhel_docs_legacy}html/DM_Multipath/index.html[_DM Multipath Guide_].

[IMPORTANT]
====
If you are using block storage and intend to deploy virtual machines on raw devices or direct LUNs and manage them with the Logical Volume Manager (LVM), you must create a filter to hide guest logical volumes. This will prevent guest logical volumes from being activated when the host is booted, a situation that could lead to stale logical volumes and cause data corruption. Use the `vdsm-tool config-lvm-filter` command to create filters for the LVM.
ifdef::storage-domain[]
See xref:Creating_LVM_filter_{context}[Creating an LVM filter] for details.
endif::storage-domain[]
ifdef::SHE_cli_deploy,migrating_to_SHE,SM_localDB_deploy,SM_remoteDB_deploy[]
See link:{URL_virt_product_docs}{URL_format}administration_guide/index#Creating_LVM_filter_storage_admin[Creating an LVM filter]
endif::SHE_cli_deploy,migrating_to_SHE,SM_localDB_deploy,SM_remoteDB_deploy[]
====

[IMPORTANT]
====
{virt-product-fullname} currently does not support block storage with a block size of 4K. You must configure block storage in legacy (512b block) mode.
====

[IMPORTANT]
====
If your host is booting from SAN storage and loses connectivity to the storage, the storage file systems become read-only and remain in this state after connectivity is restored.

To prevent this situation, add a drop-in multipath configuration file on the root file system of the SAN for the boot LUN to ensure that it is queued when there is a connection:

[source,terminal,subs="normal"]
----
# cat /etc/multipath/conf.d/host.conf
multipaths {
    multipath {
        wwid _boot_LUN_wwid_
        no_path_retry queue
    }
  }
----
====
