:ovirt-doc:
include::common/collateral_files/_attributes.adoc[]
= Migrating from a standalone {engine-name} to a self-hosted engine
// attributes for legal notice
:doc-path: migrating_from_a_standalone_manager_to_a_self-hosted_engine
:doc-name: Migrating from a standalone Manager to a self-hosted engine

// Make sure Jekyll displays a guide title
[discrete]
== Migrating from a standalone {engine-name} to a self-hosted engine

:context: migrating_to_SHE
:migrating_to_SHE:

You can convert a standalone {virt-product-fullname} {engine-name} to a self-hosted engine by backing up the standalone {engine-name} and restoring it in a new self-hosted environment.

The difference between the two environment types is explained below:

[discrete]
include::common/arch/con-Standalone_Manager_Architecture.adoc[leveloffset=+2]

[discrete]
include::common/arch/con-Self-hosted_Engine_Architecture.adoc[leveloffset=+2]

[id='Migration_overview']
== Migration Overview

When you specify a backup file during self-hosted engine deployment, the {engine-name} backup is restored on a new virtual machine, with a dedicated self-hosted engine storage domain. Deploying on a fresh host is highly recommended; if the host used for deployment existed in the backed up environment, it will be removed from the restored database to avoid conflicts in the new environment. If you deploy on a new host, you must assign a unique name to the host. Reusing the name of an existing host included in the backup can cause conflicts in the new environment.

At least two self-hosted engine nodes are required for the {engine-name} virtual machine to be highly available. You can add new nodes, or convert existing hosts.

The migration involves the following key steps:

. xref:Installing_the_self-hosted_engine_deployment_host_migrating_to_SHE[Install a new host to deploy the self-hosted engine on.] You can use either host type:
* xref:Installing_Red_Hat_Virtualization_Hosts_SHE_deployment_host[{hypervisor-fullname}]
* xref:Installing_Red_Hat_Enterprise_Linux_Hosts_SHE_deployment_host[{enterprise-linux}]

. xref:Preparing_Storage_for_RHV_migrating_to_SHE[Prepare storage for the self-hosted engine storage domain.] You can use one of the following storage types:
* xref:Preparing_NFS_Storage_migrating_to_SHE[NFS]
* xref:Preparing_iSCSI_Storage_migrating_to_SHE[iSCSI]
* xref:Preparing_FCP_Storage_migrating_to_SHE[Fibre Channel (FCP)]
* xref:Preparing_Red_Hat_Gluster_Storage_migrating_to_SHE[{gluster-storage-fullname}]

. xref:Updating_the_Red_Hat_Virtualization_Manager_migrating_to_SHE[Update the original {engine-name} to the latest minor version before you back it up.]

. xref:Backing_up_the_Original_Manager_migrating_to_SHE[Back up the original {engine-name} using the `engine-backup` tool.]

. xref:Restoring_the_Backup_on_a_New_Self-hosted_Engine_migrating_to_SHE[Deploy a new self-hosted engine and restore the backup.]

. xref:Enabling_the_Red_Hat_Virtualization_Manager_Repositories_migrating_to_SHE[Enable the {engine-name} repositories on the new {engine-name} virtual machine.]

. xref:Reinstalling_an_Existing_Host_as_a_Self-Hosted_Engine_Node_migrating_to_SHE[Convert regular hosts to self-hosted engine nodes that can host the new {engine-name}.]

This procedure assumes that you have access and can make changes to the original {engine-name}.

.Prerequisites

* FQDNs prepared for your {engine-name} and the deployment host. Forward and reverse lookup records must both be set in the DNS. The new {engine-name} must have the same FQDN as the original {engine-name}.

* The management network (*ovirtmgmt* by default) must be configured as a *VM network*, so that it can manage the {engine-name} virtual machine.


include::common/install/assembly-Installing_the_self-hosted_engine_deployment_host.adoc[leveloffset=+1]
// Adding context back after this assembly, which includes its own context. There's probably a better way that assemblies within assemblies is meant to be done.
:context: migrating_to_SHE

Although the existing storage domains will be migrated from the standalone {engine-name}, you must prepare additional storage for a self-hosted engine storage domain that is dedicated to the {engine-name} virtual machine.

include::common/storage/assembly-Preparing_Storage_for_RHV.adoc[leveloffset=+1]

Before backing up the {engine-name}, ensure it is updated to the latest minor version. The {engine-name} version in the backup file must match the version of the new {engine-name}.

include::common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc[leveloffset=+1]

include::common/backup-restore/proc-Backing_up_the_Original_Manager.adoc[leveloffset=+1]

After backing up the {engine-name}, deploy a new self-hosted engine and restore the backup on the new virtual machine.

include::common/backup-restore/proc-Restoring_the_Backup_on_a_New_Self-hosted_Engine.adoc[leveloffset=+1]

When the deployment is complete, log in to the new {engine-name} virtual machine and enable the required repositories.

include::common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc[leveloffset=+1]

The {virt-product-fullname} {engine-name} has been migrated to a self-hosted engine setup. The {engine-name} is now operating on a virtual machine on the new self-hosted engine node.

The hosts will be running in the new environment, but cannot host the {engine-name} virtual machine. You can convert some or all of these hosts to self-hosted engine nodes.

include::common/install/proc-Reinstalling_an_Existing_Host_as_a_Self-Hosted_Engine_Node.adoc[leveloffset=+1]

After reinstalling the hosts as self-hosted engine nodes, you can check the status of the new environment by running the following command on one of the nodes:

----
# hosted-engine --vm-status
----

If the new environment is running without issue, you can decommission the original {engine-name} machine.

:migrating_to_SHE!:

ifdef::context[:parent-context: {context}]
:context: Install_nodes_RHVH

[appendix]
include::common/install/proc-Preventing_Kernel_Modules_from_Loading_Automatically.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

[appendix]
include::common/collateral_files/ovirt-legal-notice.adoc[leveloffset=+1]
