[[Adding_a_Network_Interface]]
==== Adding a New Network Interface

You can add multiple network interfaces to virtual machines. Doing so allows you to put your virtual machine on multiple logical networks.

[NOTE]
====
You can create an overlay network for your virtual machines, isolated from the hosts, by defining a logical network that is not attached to the physical interfaces of the host. For example, you can create a DMZ environment, in which the virtual machines communicate among themselves over the bridge created in the host.

The overlay network uses OVN, which must be installed as an external network provider. See the  link:{URL_virt_product_docs}{URL_format}administration_guide/index#Adding_OVN_as_an_External_Network_Provider[_Administration Guide_] for more information
====

*Adding Network Interfaces to Virtual Machines*

. Click menu:Compute[Virtual Machines].
. Click a virtual machine name to go to the details view.
. Click the *Network Interfaces* tab.
. Click *New*.
. Enter the *Name* of the network interface.
. Select the *Profile* and the *Type* of network interface from the drop-down lists. The *Profile* and *Type* drop-down lists are populated in accordance with the profiles and network types available to the cluster and the network interface cards available to the virtual machine.
. Select the *Custom MAC address* check box and enter a MAC address for the network interface card as required.
. Click btn:[OK].


The new network interface is listed in the *Network Interfaces* tab in the details view of the virtual machine. The *Link State* is set to *Up* by default when the network interface card is defined on the virtual machine and connected to the network.

For more details on the fields in the *New Network Interface* window, see xref:Virtual_Machine_Network_Interface_dialogue_entries[].


