[[Adding_Host_Devices_to_a_Virtual_Machine]]
==== Adding a Host Device to a Virtual Machine

To improve performance, you can attach a host device to a virtual machine.

Host devices are physical devices connected to a particular host machine, such as:

* SCSI tape drives, disks, and changers
* PCI NICs, GPUs, and HBAs
* USB mice, cameras, and disks

To add a host device to a virtual machine, you use the virtual machine's *Host Devices* properties. First, you select one of the cluster hosts and a device type. Then, you choose and attach one or more of the host devices on that host.

[IMPORTANT]
====
When you change the *Pinned Host* setting, it removes the current host devices. When you save these changes, in the virtual machine's *Host* settings, it sets *Start Running On* to *Specific Host(s)* and specifies the host you selected earlier using the *Pinned Host* setting.
====

When you finish attaching one or more host devices, you run the virtual machine to apply the changes. The virtual machine starts on the host that has the attached host devices.

If the virtual machine cannot start on the specified host or access the host device, it cancels the start operation and produces an error message with information about the cause.

.Prerequisites

* The state of the host is `Up`.
* The host is configured for direct device assignment.

.Procedure

. In the Administration Portal, click menu:Compute[Virtual Machines].
. Shut down the virtual machine.
. Click the name of the virtual machine to go to the details view.
. Click the *Host Devices* tab.
. Click btn:[Add device]. This opens the *Add Host Devices* pane.
. Use *Pinned Host* to select the host where the virtual machine runs.
. Use *Capability* to list `pci`, `scsi`, or `usb_device` devices.
. Use *Available Host Devices* to select devices.
. Click the down arrow to move devices to *Host Devices to be attached*.
. Click btn:[OK] to attach these devices to the virtual machine and close the window.
. Optional: If you attach a SCSI host device, configure the optimal driver.
.. Click the btn:[Edit] button. This opens the *Edit Virtual Machine* pane.
.. Click the *Custom Properties* tab.
.. Click the *Please select a key* and select *scsi_hostdev* from the bottom of the drop-down list.
.. In most cases, select *scsi-hd*. Otherwise, for tape or CD changer devices, select the *scsi_generic* option. For more details, see link:{URL_virt_product_docs}virtual_machine_management_guide/index.html#Virtual_Machine_Custom_Properties_settings_explained[Virtual Machine Custom Properties Settings Explained].
.. Click the btn:[OK] button.
. Run the virtual machine.
. While the virtual machine starts running, watch for *Operation Canceled* error messages.

.Troubleshooting

If you cannot add a host device to a virtual machine, or a virtual machine cannot start running with the attached host devices, it generates *Operation Canceled* error messages. For example:

----
Operation Canceled
Error while executing action:

<vm name>:
* Cannot run VM. There is no host that satisfies current scheduling constraints. See below for details:
* The host <first_hostname> did not satisfy internal filter HostDevice because it does not support host device passthrough.
* The host <second_hostname> did not satisfy internal filter HostDevice because the host does not provide requested host devices.
----

You can fix the error by removing the host device from the virtual machine or correcting the issues the error message describes. For example:

* Respond to a `The host <hostname> did not satisfy internal filter HostDevice because it does not support host device passthrough` message by configuring the host for device passthrough and restarting the virtual machine.
* Respond to the `The host <hostname> did not satisfy internal filter HostDevice because the host does not provide requested host devices` message by adding the host device to the host.
* Respond to a `Cannot add Host devices because the VM is in Up status` message by shutting down the virtual machine before adding a host device.
* Verify that the state of the host is `Up`.

.Additional resources
* link:{URL_virt_product_docs}virtual_machine_management_guide[Host Devices] in the _Virtual Machine Management Guide_.
* link:{URL_virt_product_docs}virtual_machine_management_guide[Pinning a Virtual Machine to Multiple Hosts]
* link:{URL_virt_product_docs}administration_guide[Configuring a Host for PCI Passthrough]
* link:{URL_downstream_virt_product_docs}html-single/hardware_considerations_for_implementing_sr-iov/[Additional Hardware Considerations for Using Device Assignment] in _Hardware Considerations for Implementing SR-IOV_.
