[[Affinity_groups_examples]]
==== Affinity Groups Examples

The following examples illustrate how to apply affinity rules for various scenarios, using the different features of the affinity group capability described in this chapter.

[[Affinity_high_availability]]
.High Availability
====
Dalia is the DevOps engineer for a startup. For high availability, a particular system's two virtual machines should run on separate hosts anywhere in the cluster.

Dalia creates an affinity group named "high availability" and does the following:

* Adds the two virtual machines, *VM01* and *VM02*, to the affinity group.
* Sets *VM Affinity* to *Negative* so the virtual machines try to run on separate hosts.
* Leaves *Enforcing* unchecked (disabled) so both virtual machines can continue running in case only one host is available during an outage.
* Leaves the *Hosts* list empty so the virtual machines run on any host in the cluster.

====

[[Affinity_performance]]
.Performance
====
Sohni is a software developer who uses two virtual machines to build and test his software many times each day. There is heavy network traffic between these two virtual machines. Running the machines on the same host reduces both network traffic and the effects of network latency on the build and test process. Using high-specification hosts (faster CPUs, SSDs, and more memory) further accelerates this process.

Sohni creates an affinity group called "build and test" and does the following:

* Adds *VM01* and *VM02*, the build and test virtual machines, to the affinity group.
* Adds the high-specification hosts, *host03*, *host04*, and *host05*, to the affinity group.
* Sets *VM affinity* to *Positive* so the virtual machines try to run on the same host, reducing network traffic and latency effects.
* Sets *Host affinity* to *Positive* so the virtual machines try to run on the high specification hosts, accelerating the process.
* Leaves *Enforcing* unchecked (disabled) for both rules so the virtual machines can run if the high-specification hosts are not available.

====

[[Affinity_licensing]]
.Licensing
====
Bandile, a software asset manager, helps his organization comply with the restrictive licensing requirements of a 3D imaging software vendor. These terms require the virtual machines for its licensing server, *VM-LS*, and imaging workstations, *VM-WS__#__*, to run on the same host. Additionally, the physical CPU-based licensing model requires that the workstations run on either of two GPU-equipped hosts, *host-gpu-primary* or *host-gpu-backup*.

To meet these requirements, Bandile creates an affinity group called "3D seismic imaging" and does the following:

* Adds the previously mentioned virtual machines and hosts to the affinity group.
* Sets *VM affinity* to *Positive* and selects *Enforcing* so the licensing server and workstations _must_ run together on one of the hosts, not on multiple hosts.
* Sets *Host affinity* to *Positive* and selects *Enforcing* so the virtual machines _must_ run on either of the GPU-equipped the hosts, not other hosts in the cluster.

====
