:_content-type: CONCEPT
[id="About_Affinity_Labels"]
= About Affinity Labels

You can create and modify affinity labels in the Administration Portal.

Affinity labels are used to set hard (Enforced) positive affinity between virtual machines and hosts. See the xref:sect-Affinity_Groups[Affinity Groups] section for more information about affinity hardness and polarity.

Labels function identically to a hard positive affinity group, but simplify configuration in certain use cases. For example, if you have virtual machines that require specific host hardware, you can use affinity labels to ensure that those virtual machines run on the required hosts. If you use software that is license-limited to a certain number of physical machines, you can use affinity labels to ensure that virtual machines running that software are limited to the required physical hosts.

[WARNING]
====
Affinity labels are a subset of affinity groups and can conflict with them. If there is a conflict, the virtual machine will not start.
====
