:_content-type: PROCEDURE
[id="Assigning_virtual_machines_to_users_{context}"]
==== Assigning Virtual Machines to Users

If you are creating virtual machines for users other than yourself, you have to assign roles to the users before they can use the virtual machines. Note that permissions can only be assigned to existing users. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#chap-Users_and_Roles[Users and Roles] in the _Administration Guide_ for details on creating user accounts.

The VM Portal supports three default roles: User, PowerUser and UserVmManager. However, customized roles can be configured via the Administration Portal. The default roles are described below.


* A *User* can connect to and use virtual machines. This role is suitable for desktop end users performing day-to-day tasks.

* A *PowerUser* can create virtual machines and view virtual resources. This role is suitable if you are an administrator or manager who needs to provide virtual resources for your employees.

* A *UserVmManager* can edit and remove virtual machines, assign user permissions, use snapshots and use templates. It is suitable if you need to make configuration changes to your virtual environment.

When you create a virtual machine, you automatically inherit *UserVmManager* privileges. This enables you to make changes to the virtual machine and assign permissions to the users you manage, or users who are in your Identity Management (IdM) or RHDS group. See the  link:{URL_virt_product_docs}{URL_format}administration_guide/index#Introduction_to_Directory_Servers[_Administration Guide_] for more information.


*Assigning Permissions to Users*

. Click menu:Compute[Virtual Machines] and select a virtual machine.
. Click the virtual machine's name to go to the details view.
. Click the *Permissions* tab.
. Click btn:[Add].
. Enter a name, or user name, or part thereof in the *Search* text box, and click *Go*. A list of possible matches display in the results list.
. Select the check box of the user to be assigned the permissions.
. Select *UserRole* from the *Role to Assign* drop-down list.
. Click btn:[OK].


The user's name and role display in the list of users permitted to access this virtual machine.

[NOTE]
====
If a user is assigned permissions to only one virtual machine, single sign-on (SSO) can be configured for the virtual machine. With single sign-on enabled, when a user logs in to the VM Portal, and then connects to a virtual machine through, for example, a SPICE console, users are automatically logged in to the virtual machine and do not need to type in the user name and password again. Single sign-on can be enabled or disabled on a per virtual machine basis. See xref:sect-Configuring_Single_Sign-On_for_Virtual_Machines[] for more information on how to enable and disable single sign-on for virtual machines.
====
