:_content-type: PROCEDURE
[id="Automatic_virtual_machine_migration"]
==== Automatic Virtual Machine Migration

{virt-product-fullname} {engine-name} automatically initiates live migration of all virtual machines running on a host when the host is moved into maintenance mode. The destination host for each virtual machine is assessed as the virtual machine is migrated, in order to spread the load across the cluster.

From version 4.3, all virtual machines defined with manual or automatic migration modes are migrated when the host is moved into maintenance mode. However, for high performance and/or pinned virtual machines, a *Maintenance Host* window is displayed, asking you to confirm the action because the performance on the target host may be less than the performance on the current host.

The {engine-name} automatically initiates live migration of virtual machines in order to maintain load-balancing or power-saving levels in line with scheduling policy. Specify the scheduling policy that best suits the needs of your environment. You can also disable automatic, or even manual, live migration of specific virtual machines where required.

If your virtual machines are configured for high performance, and/or if they have been pinned (by setting Passthrough Host CPU, CPU Pinning, or NUMA Pinning), the migration mode is set to *Allow manual migration only*. However, this can be changed to *Allow Manual and Automatic* mode if required. Special care should be taken when changing the default migration setting so that it does not result in a virtual machine migrating to a host that does not support high performance or pinning.
