:_content-type: PROCEDURE
[id="Blacklisting_Network_Interfaces"]
= Configuring a virtual machine to ignore NICs

You can configure the `ovirt-guest-agent` on a virtual machine to ignore certain NICs. This prevents IP addresses associated with network interfaces created by certain software from appearing in reports. You must specify the name and number of the network interface you want to ignore (for example, `eth0`, `docker0`).
// Note that once https://bugzilla.redhat.com/show_bug.cgi?id=1546675 is resolved, this procedure can be simplified (it won't require configuring the blacklist before first start of the agent)

.Procedure

. In the `/etc/ovirt-guest-agent.conf` configuration file on the virtual machine, insert the following line, with the NICs to be ignored separated by spaces:
+
[source,terminal,subs="normal"]
----
ignored_nics = _first_NIC_to_ignore_ _second_NIC_to_ignore_
----
+
. Start the agent:
+
[source,terminal,subs="normal"]
----
# systemctl start ovirt-guest-agent
----

[NOTE]
====
Some virtual machine operating systems automatically start the guest agent during installation.

If your virtual machine's operating system automatically starts the guest agent or if you need to configure the denylist on many virtual machines, use the configured virtual machine as a template for creating additional virtual machines. See xref:Creating_a_template_from_an_existing_virtual_machine[Creating a template from an existing virtual machine] for details.
====
