:_content-type: PROCEDURE
[id="Configuring_Single_Sign-On_for_Red_Hat_Enterprise_Linux_Virtual_Machines"]
= Configuring Single Sign-On for {enterprise-linux} Virtual Machines Using IPA (IdM)

To configure single sign-on for {enterprise-linux} virtual machines using GNOME and KDE graphical desktop environments and IPA (IdM) servers, you must install the `ovirt-guest-agent` package on the virtual machine and install the packages associated with your window manager.

[IMPORTANT]
====
The following procedure assumes that you have a working IPA configuration and that the IPA domain is already joined to the {engine-name}. You must also ensure that the clocks on the {engine-name}, the virtual machine and the system on which IPA (IdM) is hosted are synchronized using NTP.
====

[NOTE]
====
Single sign-on with IPA (IdM) is deprecated for virtual machines running {enterprise-linux} version 7 or earlier and unsupported for virtual machines running {enterprise-linux} 8 or Windows operating systems.
====

[id="configure-sso-linux-74"]
Configuring Single Sign-On for {enterprise-linux} Virtual Machines

. Log in to the {enterprise-linux} virtual machine.
. Enable the repository:

* For {enterprise-linux} 6:
+
[source,terminal,subs="normal"]
----
# subscription-manager repos --enable=rhel-6-server-rhv-4-agent-rpms
----

* For {enterprise-linux} 7:
+
[source,terminal,subs="normal"]
----
# subscription-manager repos --enable=rhel-7-server-rh-common-rpms
----

. Download and install the guest agent, single sign-on, and IPA packages:
+
[source,terminal,subs="normal"]
----
# yum install ovirt-guest-agent-common ovirt-guest-agent-pam-module ovirt-guest-agent-gdm-plugin ipa-client
----

. Run the following command and follow the prompts to configure `ipa-client` and join the virtual machine to the domain:
+
[source,terminal,subs="normal"]
----
# ipa-client-install --permit --mkhomedir
----
+
[NOTE]
====
In environments that use DNS obfuscation, this command should be:

[source,terminal,subs="normal"]
----
# ipa-client-install --domain=_FQDN_ --server=_FQDN_
----
====
+
. For {enterprise-linux} 7.2 and later:
+
[source,terminal,subs="normal"]
----
# authconfig --enablenis --update
----
+
[NOTE]
====
{enterprise-linux} 7.2 has a new version of the System Security Services Daemon (SSSD), which introduces configuration that is incompatible with the {virt-product-fullname} {engine-name} guest agent single sign-on implementation. This command ensures that single sign-on works.
====

. Fetch the details of an IPA user:
+
[source,terminal,subs="normal"]
----
# getent passwd _ipa-user_
----

. Record the IPA user's UID and GID:
+
[source,terminal,subs="normal"]
----
_ipa-user_:*:936600010:936600001::/home/_ipa-user_:/bin/sh
----

. Create a home directory for the IPA user:
+
[source,terminal,subs="normal"]
----
# mkdir /home/_ipa-user_
----

. Assign ownership of the directory to the IPA user:
+
[source,terminal,subs="normal"]
----
# chown 936600010:936600001 /home/_ipa-user_
----

Log in to the VM Portal using the user name and password of a user configured to use single sign-on and connect to the console of the virtual machine. You will be logged in automatically.
