[[Configuring_Single_Sign-On_for_Red_Hat_Enterprise_Linux_Virtual_Machines_Using_Active_Directory]]
= Configuring Single Sign-On for {enterprise-linux} Virtual Machines Using Active Directory

To configure single sign-on for {enterprise-linux} virtual machines using GNOME and KDE graphical desktop environments and Active Directory, you must install the `ovirt-guest-agent` package on the virtual machine, install the packages associated with your window manager and join the virtual machine to the domain.

[IMPORTANT]
====
The following procedure assumes that you have a working Active Directory configuration and that the Active Directory domain is already joined to the {engine-name}. You must also ensure that the clocks on the {engine-name}, the virtual machine and the system on which Active Directory is hosted are synchronized using NTP.
====

*Configuring Single Sign-On for {enterprise-linux} Virtual Machines*

. Log in to the {enterprise-linux} virtual machine.
. Enable the {virt-product-fullname} Agent repository:
* For {enterprise-linux} 6
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos --enable=rhel-6-server-rhv-4-agent-rpms
----

* For {enterprise-linux} 7
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos --enable=rhel-7-server-rh-common-rpms
----

. Download and install the guest agent packages:
+
[options="nowrap" subs="normal"]
----
# yum install ovirt-guest-agent-common
----
+
. Install the single sign-on packages:
+
[options="nowrap" subs="normal"]
----
# yum install ovirt-guest-agent-gdm-plugin
----

. Install the Samba client packages:
+
[options="nowrap" subs="normal"]
----
# dnf install samba-client samba-winbind samba-winbind-clients
----

. On the virtual machine, modify the */etc/samba/smb.conf* file to contain the following, replacing `DOMAIN` with the short domain name and `REALM.LOCAL` with the Active Directory realm:
+
[options="nowrap" subs="normal"]
----
[global]
   workgroup = DOMAIN
   realm = REALM.LOCAL
   log level = 2
   syslog = 0
   server string = Linux File Server
   security = ads
   log file = /var/log/samba/%m
   max log size = 50
   printcap name = cups
   printing = cups
   winbind enum users = Yes
   winbind enum groups = Yes
   winbind use default domain = true
   winbind separator = +
   idmap uid = 1000000-2000000
   idmap gid = 1000000-2000000
template shell = /bin/bash
----
+
. Join the virtual machine to the domain:
+
[options="nowrap" subs="normal"]
----
net ads join -U _user_name_
----
+
. Start the `winbind` service and ensure it starts on boot:
* For {enterprise-linux} 6
+
[options="nowrap" subs="normal"]
----
# service winbind start
# chkconfig winbind on
----

* For {enterprise-linux} 7
+
[options="nowrap" subs="normal"]
----
# systemctl start winbind.service
# systemctl enable winbind.service

----

. Verify that the system can communicate with Active Directory:
.. Verify that a trust relationship has been created:
+
[options="nowrap" subs="normal"]
----
# wbinfo -t
----

.. Verify that you can list users:
+
[options="nowrap" subs="normal"]
----
# wbinfo -u
----

.. Verify that you can list groups:
+
[options="nowrap" subs="normal"]
----
# wbinfo -g
----

. Configure the NSS and PAM stack:
.. Open the *Authentication Configuration* window:
+
[options="nowrap" subs="normal"]
----
# authconfig-tui
----

.. Select the *Use Winbind* check box, select btn:[Next] and press `Enter`.
.. Select the btn:[OK] button and press `Enter`.


Log in to the VM Portal using the user name and password of a user configured to use single sign-on and connect to the console of the virtual machine. You will be logged in automatically.
