:_content-type: PROCEDURE
[id="Confirming_Watchdog_Functionality"]
= Confirming Watchdog Functionality

Confirm that a watchdog card has been attached to a virtual machine and that the `watchdog` service is active.

[WARNING]
====
This procedure is provided for testing the functionality of watchdogs only and must not be run on production machines.
====


*Confirming Watchdog Functionality*

. Log in to the virtual machine on which the watchdog card is attached.
. Confirm that the watchdog card has been identified by the virtual machine:
+
[source,terminal,subs="normal"]
----
# lspci | grep watchdog -i
----
+
. Run one of the following commands to confirm that the watchdog is active:
* Trigger a kernel panic:
+
[source,terminal,subs="normal"]
----
# echo c > /proc/sysrq-trigger
----
+
* Terminate the `watchdog` service:
+
[source,terminal,subs="normal"]
----
# kill -9 `pgrep watchdog`
----


The watchdog timer can no longer be reset, so the watchdog counter reaches zero after a short period of time. When the watchdog counter reaches zero, the action specified in the *Watchdog Action* drop-down menu for that virtual machine is performed.
