:_content-type: PROCEDURE
[id="Configuring_Single_Sign_On_for_Windows_Virtual_Machines"]
= Configuring single sign-on for Windows virtual machines

To configure single sign-on for Windows virtual machines, the Windows guest agent must be installed on the guest virtual machine. The virtio-win ISO image provides this agent. If the `virtio-win___version__.iso` image is not available in your storage domain, contact your system administrator.


.Procedure

. Select the Windows virtual machine. Ensure the machine is powered up.
. On the virtual machine, locate the CD drive and open the CD.
. Launch `virtio-win-guest-tools`.
. Click btn:[Options]
. Select *Install oVirt Guest Agent*.
. Click btn:[OK].
. Click btn:[Install].
. When the installation completes, you are prompted to restart the machine to apply the changes.

Log in to the VM Portal using the user name and password of a user configured to use single sign-on and connect to the console of the virtual machine. You will be logged in automatically.
