:_content-type: PROCEDURE
[id="Configuring_Satellite_Errata"]
= Configuring Satellite errata viewing for a virtual machine

In the Administration Portal, you can configure a virtual machine to display the available errata. The virtual machine needs to be associated with a Red Hat Satellite server to show available errata.

{virt-product-fullname} 4.4 supports viewing errata with Red Hat Satellite 6.6.

.Prerequisites

* The Satellite server must be added as an external provider.
* The {engine-name} and any virtual machines on which you want to view errata must all be registered in the Satellite server by their respective FQDNs. This ensures that external content host IDs do not need to be maintained in {virt-product-fullname}.
+
[IMPORTANT]
====
Virtual machines added using an IP address cannot report errata.
====
* The host that the virtual machine runs on also needs to be configured to receive errata information from Satellite.
* The virtual machine must have the `ovirt-guest-agent` package installed. This package enables the virtual machine to report its host name to the {virt-product-fullname} {engine-name}, which enables the Red Hat Satellite server to identify the virtual machine as a content host and report the applicable errata.
* The virtual machine must be registered to the Red Hat Satellite server as a content host.
* Use Red Hat Satellite remote execution to manage packages on hosts.

[NOTE]
====
The Katello agent is deprecated and will be removed in a future Satellite version. Migrate your processes to use the remote execution feature to update clients remotely.
====

.Procedure

. Click menu:Compute[Virtual Machines] and select a virtual machine.
. Click btn:[Edit].
. Click the *Foreman/Satellite* tab.
. Select the required Satellite server from the *Provider* drop-down list.
. Click btn:[OK].

.Additional resources

* link:{URL_virt_product_docs}{URL_format}administration_guide/index#Configuring_Satellite_Errata_Management_for_a_Host[Setting up Satellite errata viewing for a host] in the _Administration Guide_
* link:{URL_virt_product_docs}{URL_format}virtual_machine_management_guide/index#Installing_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux[Installing the Guest Agents, Tools, and Drivers on Linux] in the _Virtual Machine Management Guide_ for {enterprise-linux} virtual machines.
* link:{URL_virt_product_docs}{URL_format}virtual_machine_management_guide/index#Installing_the_Guest_Agents_and_Drivers_on_Windows[Installing the Guest Agents, Tools, and Drivers on Windows] in the _Virtual Machine Management Guide_ for Windows virtual machines.
