[[Creating_a_cloned_virtual_machine_based_on_a_template]]
=== Creating a Cloned Virtual Machine Based on a Template

Cloned virtual machines are based on templates and inherit the settings of the template. A cloned virtual machine does not depend on the template on which it was based after it has been created. This means the template can be deleted if no other dependencies exist.

[NOTE]
====
If you clone a virtual machine from a template, the name of the template on which that virtual machine was based is displayed in the *General* tab of the *Edit Virtual Machine* window for that virtual machine. If you change the name of that template, the name of the template in the *General* tab will also be updated. However, if you delete the template from the {engine-name}, the original name of that template will be displayed instead.
====

*Cloning a Virtual Machine Based on a Template*

. Click menu:Compute[Virtual Machines].
. Click btn:[New].
. Select the *Cluster* on which the virtual machine will run.
. Select a template from the *Based on Template* drop-down menu.
. Enter a *Name*, *Description* and any *Comments*. You can accept the default values inherited from the template in the rest of the fields, or change them if required.
. Click the *Resource Allocation* tab.
. Select the *Clone* radio button in the *Storage Allocation* area.
. Select the disk format from the *Format* drop-down list. This affects the speed of the clone operation and the amount of disk space the new virtual machine initially requires.

+
* *QCOW2* (Default)

** Faster clone operation
** Optimized use of storage capacity
** Disk space allocated only as required

* *Raw*

** Slower clone operation
** Optimized virtual machine read and write operations
** All disk space requested in the template is allocated at the time of the clone operation

. Use the *Target* drop-down menu to select the storage domain on which the virtual machine's virtual disk will be stored.
. Click btn:[OK].



[NOTE]
====
Cloning a virtual machine may take some time. A new copy of the template's disk must be created. During this time, the virtual machine's status is first *Image Locked*, then *Down*.
====
The virtual machine is created and displayed in the *Virtual Machines* tab. You can now assign users to it, and can begin using it when the clone operation is complete.
