[[Enabling_the_Required_Repositories]]
= Enabling the Required Repositories

To install packages signed by Red Hat you must register the target system to the Content Delivery Network. Then, use an entitlement from your subscription pool and enable the required repositories.


*Enabling the Required Repositories Using Subscription {engine-name}*

. Register your system with the Content Delivery Network, entering your Customer Portal user name and password when prompted:
+
[source,terminal]
----
# subscription-manager register
----
+
. Locate the relevant subscription pools and note down the pool identifiers:
+
[source,terminal]
----
# subscription-manager list --available
----
+
. Use the pool identifiers to attach the required subscriptions:
+
[source,terminal]
----
# subscription-manager attach --pool=_pool_id_
----
+
. When a system is attached to a subscription pool with multiple repositories, only the main repository is enabled by default. Others are available, but disabled. Enable any additional repositories:
+
[source,terminal]
----
# subscription-manager repos --enable=_repository_
----
+
. Ensure that all packages currently installed are up to date:
+
[source,terminal]
----
# dnf upgrade --nobest
----
//ansible lock addition
+
[NOTE]
====
For versions of {enterprise-linux} earlier than 8, use the command `yum update` instead of `dnf upgrade`:
[source,terminal]
----
# yum update
----
See also link:https://access.redhat.com/solutions/5480561[Cannot perform yum update on my RHV manager (ansible conflict)]
// ansible lock addition
====
