:_content-type: PROCEDURE
[id="Hot_Unplugging_Virtual_Memory"]
==== Hot Unplugging Virtual Memory

You can hot unplug virtual memory. Hot unplugging disables devices while a virtual machine is running.

.Prerequisites

* Only memory added with hot plugging can be hot unplugged.
* The virtual machine's operating system must support memory hot unplugging.
* The virtual machine must not have a memory balloon device enabled. This feature is disabled by default.
* All blocks of the hot-plugged memory must be set to *online_movable* in the virtual machine's device management rules. In virtual machines running up-to-date versions of {enterprise-linux} or CoreOS, this rule is set by default. For information on device management rules, consult the documentation for the virtual machine's operating system.
* To ensure that hot plugged memory can be hot unplugged later, add the `movable_node` option to the kernel command line of the virtual machine as follows and reboot the virtual machine:
+
[source, terminal]
----
# grubby --update-kernel=ALL --args="movable_node"
----


For more information, see link:{URL_rhel_docs_latest}/html-single/managing_monitoring_and_updating_the_kernel/configuring-kernel-command-line-parameters_managing-monitoring-and-updating-the-kernel#setting-kernel-command-line-parameters_configuring-kernel-command-line-parameters[Setting kernel command-line parameters] in the RHEL 8 document _Managing, monitoring and updating the kernel_.

.Procedure

. Click menu:Compute[Virtual Machines] and select a running virtual machine.
. Click the *Vm Devices* tab.
. In the *Hot Unplug* column, click btn:[Hot Unplug] beside the memory device to be removed.
. Click btn:[OK] in the *Memory Hot Unplug* window.
+
The *Physical Memory Guaranteed* value for the virtual machine is decremented automatically if necessary.
