[[Installing_Cloud-Init]]
==== Installing Cloud-Init

This procedure describes how to install Cloud-Init on a virtual machine. Once Cloud-Init is installed, you can create a template based on this virtual machine. Virtual machines created based on this template can leverage Cloud-Init functions, such as configuring the host name, time zone, root password, authorized keys, network interfaces, DNS service, etc on boot.


*Installing Cloud-Init*

. Log in to the virtual machine.
. Enable the repositories:

* For {enterprise-linux} 6:
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --enable=rhel-6-server-rpms \
    --enable=rhel-6-server-rh-common-rpms
----
+
* For {enterprise-linux} 7:
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --enable=rhel-7-server-rpms \
    --enable=rhel-7-server-rh-common-rpms
----
+
* For {enterprise-linux} 8, you normally do not need to enable repositories to install Cloud-Init. The Cloud-Init package is part of the AppStream repo, `rhel-8-for-x86_64-appstream-rpms`, which is enabled by default in {enterprise-linux} 8.
+
. Install the `cloud-init` package and dependencies:
+
[options="nowrap" subs="normal"]
----
# dnf install cloud-init
----
+
[NOTE]
====
For versions of {enterprise-linux} earlier than version 8, use the command `yum install cloud-init` instead of `dnf install cloud-init`.
====
