:_content-type: PROCEDURE
[id="Managing_System_Permissions_for_a_Virtual_Machine_{context}"]
==== Managing System Permissions for a Virtual Machine

As the *SuperUser*, the system administrator manages all aspects of the Administration Portal. More specific administrative roles can be assigned to other users. These restricted administrator roles are useful for granting a user administrative privileges that limit them to a specific resource. For example, a *DataCenterAdmin* role has administrator privileges only for the assigned data center with the exception of the storage for that data center, and a *ClusterAdmin* has administrator privileges only for the assigned cluster.

A *UserVmManager* is a system administration role for virtual machines in a data center. This role can be applied to specific virtual machines, to a data center, or to the whole virtualized environment; this is useful to allow different users to manage certain virtual resources.

The user virtual machine administrator role permits the following actions:

* Create, edit, and remove virtual machines.

* Run, suspend, shutdown, and stop virtual machines.



[NOTE]
====
You can only assign roles and permissions to existing users.
====
Many end users are concerned solely with the virtual machine resources of the virtualized environment. As a result, {virt-product-fullname} provides several user roles which enable the user to manage virtual machines specifically, but not other resources in the data center.
