:_content-type: PROCEDURE
[id="Opening_a_Console_to_a_Virtual_Machine_{context}"]
= Opening a console to a virtual machine

Use Remote Viewer to connect to a virtual machine.

.Procedure

. Install Remote Viewer if it is not already installed. See xref:sect-Installing_Console_Components[Installing Console Components].

. Click menu:Compute[Virtual Machines] and select a virtual machine.

. Click btn:[Console]. By default, the browser prompts you to download a file named `console.vv`. When you click to open the file, a console window opens for the virtual machine. You can configure your browser to automatically open these files, such that clicking btn:[Console] simply opens the console.

[NOTE]
====
`console.vv` expires after 120 seconds. If more than 120 seconds elapse between the time the file is downloaded and the time that you open the file, click btn:[Console] again.
====


.Additional resources

* xref:Automatically_connecting_to_a_Virtual_Machine[Automatically connecting to a Virtual Machine]

* xref:sect-Configuring_Console_Options[Configuring Console Options]
