:_content-type: PROCEDURE
:_content-type: PROCEDURE
:_content-type: PROCEDURE
[id="Pinning_a_Virtual_Machine_to_Multiple_Hosts_{context}"]
=== Pinning a Virtual Machine to Multiple Hosts

Virtual machines can be pinned to multiple hosts. Multi-host pinning allows a virtual machine to run on a specific subset of hosts within a cluster, instead of one specific host or all hosts in the cluster. The virtual machine cannot run on any other hosts in the cluster even if all of the specified hosts are unavailable. Multi-host pinning can be used to limit virtual machines to hosts with, for example, the same physical hardware configuration.

If a host fails, a highly available virtual machine is automatically restarted on one of the other hosts to which the virtual machine is pinned. 

*Pinning Virtual Machines to Multiple Hosts*

. Click menu:Compute[Virtual Machines] and select a virtual machine.
. Click btn:[Edit].
. Click the *Host* tab.
. Select the *Specific Host(s)* radio button under *Start Running On* and select two or more hosts from the list.
. Click the *High Availability* tab.
. Select the *Highly Available* check box.
. Select *Low*, *Medium*, or *High* from the *Priority* drop-down list. When migration is triggered, a queue is created in which the high priority virtual machines are migrated first. If a cluster is running low on resources, only the high priority virtual machines are migrated.
. Click btn:[OK].


