:_content-type: PROCEDURE
[id="Powering_on_a_virtual_machine"]
= Starting a Virtual Machine

.Procedure

. Click menu:Compute[Virtual Machines] and select a virtual machine with a status of `Down`.
. Click btn:[Run].

The *Status* of the virtual machine changes to `Up`, and the operating system installation begins. Open a console to the virtual machine if one does not open automatically.

[NOTE]
====
A virtual machine will not start on a host with an overloaded CPU. By default, a host's CPU is considered overloaded if it has a load of more than 80% for 5 minutes, but these values can be changed using scheduling policies. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-Scheduling_Policies[Scheduling Policies] in the _Administration Guide_ for more information.
====

.Troubleshooting

Scenario - the virtual machine fails to boot with the following error message:

[source,terminal,subs="normal"]
----
Boot failed: not a bootable disk - No Bootable device
----

Possible solutions to this problem:

* Make sure that *hard disk* is selected in the boot sequence, and the disk that the virtual machine is booting from must be set as *Bootable*.

* Create a link:{URL_virt_product_docs}{URL_format}/virtual_machine_management_guide/index#Creating_a_cloned_virtual_machine_based_on_a_template[Cloned Virtual Machine Based on a Template].

* Create a new virtual machine with a local boot disk managed by {virt-product-shortname} that contains the OS and application binaries.

* Install the OS by booting from the *Network (PXE)* boot option.

Scenario - the virtual machine on IBM POWER9 fails to boot with the following error message:

[source,terminal]
----
qemu-kvm: Requested count cache flush assist capability level not supported by kvm, try appending -machine cap-ccf-assist=off
----

Default risk level protections can prevent VMs from starting on IBM POWER9. To resolve this issue:

. Create or edit the `/var/lib/obmc/cfam_overrides` on the BMC.
. Set the firmware risk level to `0`:
+
[options="nowrap" subs="quotes"]
----
# Control speculative execution mode
0 0x283a 0x00000001  # bits 28:31 are used for init level -- in this case 1 (Kernel protection only)
0 0x283F 0x20000000  # Indicate override register is valid
----
+
. Reboot the host system for the changes to take affect.

[NOTE]
====
Overriding the risk level can cause unexpected behavior when running virtual machines.
====
