[[Setting_migration_priority]]
==== Setting Migration Priority

{virt-product-fullname} {engine-name} queues concurrent requests for migration of virtual machines off of a given host. The load balancing process runs every minute. Hosts already involved in a migration event are not included in the migration cycle until their migration event has completed. When there is a migration request in the queue and available hosts in the cluster to action it, a migration event is triggered in line with the load balancing policy for the cluster.

You can influence the ordering of the migration queue by setting the priority of each virtual machine; for example, setting mission critical virtual machines to migrate before others. Migrations will be ordered by priority; virtual machines with the highest priority will be migrated first.


*Setting Migration Priority*

. Click menu:Compute[Virtual Machines] and select a virtual machine.
. Click btn:[Edit].
. Select the *High Availability* tab.
. Select *Low*, *Medium*, or *High* from the *Priority* drop-down list.
. Click btn:[OK].


