:_content-type: PROCEDURE
[id="Updating_the_Guest_Agents_and_Drivers_on_Windows_{context}"]
= Updating Windows guest agents and drivers using the command prompt

When you do not have access to Windows Update to update Windows drivers, or when you need to update the Windows guest agents, you can do so from the `virtio-win` package by using the virtual machine's command prompt. During this procedure, you must remove and reinstall the drivers, which can lead to network disruption. This procedure restores your settings after reinstalling the drivers.

.Procedure

. If you are updating the drivers, on the Windows virtual machine, use the `netsh` utility to save TCP settings before uninstalling the netkvm driver:
+
----
C:\WINDOWS\system32>netsh dump > filename.txt
----

. On the {engine-name} machine, update the `virtio-win` package to the latest version:
+
----
# dnf upgrade -y virtio-win
----
+
The `virtio-win___version__.iso` file is located in `/usr/share/virtio-win/` on the {engine-name} machine.

. Upload the ISO file to a data domain. For more information, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Uploading_Images_to_a_Data_Storage_Domain_storage_tasks[Uploading Images to a Data Storage Domain] in the _Administration Guide_.

. In the Administration or VM Portal, if the virtual machine is running, use the *Change CD* drop-down list to attach the virtio-win___version__.iso file to each of your virtual machines. If the virtual machine is powered off, click the btn:[Run Once] button and attach the ISO as a CD.

. Log in to the virtual machine.

. Select the CD Drive (`D:\` for this example) containing the virtio-win___version__.iso file.

. Reinstall the guest agents or drivers:
** To reinstall only the guest agents, use `qemu-ga-x86_64.msi`:
+
----
C:\WINDOWS\system32>msiexec.exe /i D:\guest-agent\qemu-ga-x86_64.msi /passive /norestart
----

** To install the guest agents and drivers, or just the drivers, use `virtio-win-gt-x64.msi`:
+
----
C:\WINDOWS\system32>msiexec.exe /i D:\virtio-win-gt-x64.msi /passive /norestart
----

. If you are updating the drivers, restore the settings you saved using `netsh`:
+
----
C:\WINDOWS\system32>netsh -f filename.txt
----
