:_content-type: REFERENCE
[id="Virtual_Machine_Custom_Properties_settings_explained_{context}"]
==== Virtual Machine Custom Properties Settings Explained

The following table details the options available on the *Custom Properties* tab of the *New Virtual Machine* and *Edit Virtual Machine* windows.

[id="New_VMs_Custom_Properties"]
.Virtual Machine Custom Properties Settings
[cols="1,2,2,1", options="header"]
|===

|Field Name
|Description
|Recommendations and Limitations
|Power cycle required?


|*sndbuf*
|Enter the size of the buffer for sending the virtual machine's outgoing data over the socket. Default value is 0.
|-
| Yes


|*hugepages*
|Enter the huge page size in KB.
a|
* Set the huge page size to the largest size supported by the pinned host.
* The recommended size for x86_64 is 1 GB.
* The virtual machine’s huge page size must be the same size as the pinned host’s huge page size.
* The virtual machine’s memory size must fit into the selected size of the pinned host’s free huge pages. The NUMA node size must be a multiple of the huge page’s selected size.
| Yes


|*vhost*
a|Disables vhost-net, which is the kernel-based virtio network driver on virtual network interface cards attached to the virtual machine. To disable vhost, the format for this property is `_LogicalNetworkName_: false`.

This will explicitly start the virtual machine without the vhost-net setting on the virtual NIC attached to _LogicalNetworkName_.
|vhost-net provides better performance than virtio-net, and if it is present, it is enabled on all virtual machine NICs by default. Disabling this property makes it easier to isolate and diagnose performance issues, or to debug vhost-net errors; for example, if migration fails for virtual machines on which vhost does not exist.
| Yes


|*sap_agent*
|Enables SAP monitoring on the virtual machine. Set to *true* or *false*.
|-
| Yes


// |*nvram_template*
// |TBD
// |TBD
// |TBD


|*mdev_type*
|Enter the name of the mediated device, my_GPU, supported by the host’s kernel to enable the host to work with the device.
|-
|


|*viodiskcache*
|Caching mode for the virtio disk. *writethrough* writes data to the cache and the disk in parallel, *writeback* does not copy modifications from the cache to the disk, and *none* disables caching. See link:https://access.redhat.com/solutions/2361311[] for more information about the limitations of the `viodiskcache` custom property.
|In order to ensure data integrity in the event of a fault in storage, in the network, or in a host during migration, do not migrate virtual machines with viodiskcache enabled, unless virtual machine clustering or application-level clustering is also enabled.
| Yes


|*scsi_hostdev*
a|
Optionally, if you add a SCSI host device to a virtual machine, you can specify the optimal SCSI host device driver. For details, see link:{URL_virt_product_docs}{URL_format}virtual_machine_management_guide/index#Adding_Host_Devices_to_a_Virtual_Machine[Adding Host Devices to a Virtual Machine].

* *scsi_generic*: (Default) Enables the guest operating system to access OS-supported SCSI host devices attached to the host. Use this driver for SCSI media changers that require raw access, such as tape or CD changers.
* *scsi_block*: Similar to *scsi_generic* but better speed and reliability. Use for SCSI disk devices. If trim or discard for the underlying device is desired, and it’s a hard disk, use this driver.
* *scsi_hd*: Provides performance with lowered overhead. Supports large numbers of devices. Uses the standard SCSI device naming scheme. Can be used with aio-native. Use this driver for high-performance SSDs.
* *virtio_blk_pci*: Provides the highest performance without the SCSI overhead. Supports identifying devices by their serial numbers.
|If you are not sure, try *scsi_hd*.
|Yes
|===


[WARNING]
====
Increasing the value of the sndbuf custom property results in increased occurrences of communication failure between hosts and unresponsive virtual machines.
====
