[[Virtual_Machine_Host_settings_explained]]
==== Virtual Machine Host Settings Explained

The following table details the options available on the *Host* tab of the *New Virtual Machine* and *Edit Virtual Machine* windows.
[[New_VMs_Host]]

.Virtual Machine: Host Settings
[cols="1,1,2,1", options="header"]
|===
|Field Name
|Sub-element
|Description
|Power cycle required?


|*Start Running On*
|
a|Defines the preferred host on which the virtual machine is to run. Select either:

* *Any Host in Cluster* - The virtual machine can start and run on any available host in the cluster.

* *Specific Host(s)* - The virtual machine will start running on a particular host in the cluster. However, the {engine-name} or an administrator can migrate the virtual machine to a different host in the cluster depending on the migration and high-availability settings of the virtual machine. Select the specific host or group of hosts from the list of available hosts.
| No. The virtual machine can migrate to that host while running.

|*CPU options*
|*Pass-Through Host CPU*
|When selected, allows virtual machines to use the host's CPU flags.
When selected, *Migration Options* is set to *Allow manual migration only*.
| Yes

|
|*Migrate only to hosts with the same TSC frequency*
|When selected, this virtual machine can only be migrated to a host with the same TSC frequency. THis option is only valid for High Performance virtual machines.
|

|*Migration Options*
|*Migration mode*
a|Defines options to run and migrate the virtual machine. If the options here are not used, the virtual machine will run or migrate according to its cluster's policy.

* *Allow manual and automatic migration* - The virtual machine can be automatically migrated from one host to another in accordance with the status of the environment, or manually by an administrator.

* *Allow manual migration only* - The virtual machine can only be migrated from one host to another manually by an administrator.

* *Do not allow migration* - The virtual machine cannot be migrated, either automatically or manually.
| No

|
|*Migration policy*
a|Defines the migration convergence policy. If the check box is left unselected, the host determines the policy.

* *Legacy* - Legacy behavior of 3.6 version. Overrides in `vdsm.conf` are still applied. The guest agent hook mechanism is disabled.

* *Minimal downtime* - Allows the virtual machine to migrate in typical situations. Virtual machines should not experience any significant downtime. The migration will be aborted if virtual machine migration does not converge after a long time (dependent on QEMU iterations, with a maximum of 500 milliseconds). The guest agent hook mechanism is enabled.

* *Suspend workload if needed* - Allows the virtual machine to migrate in most situations, including when the virtual machine is running a heavy workload. Because of this, virtual machines may experience a more significant downtime than with some other settings. The migration may still be aborted for extreme workloads. The guest agent hook mechanism is enabled.
| No

|
|*Enable migration encryption*
a| Allows the virtual machine to be encrypted during migration.

* *Cluster default (Don't encrypt)*
* *Encrypt*
* *Don't encrypt*
|

|*Configure NUMA*
|*NUMA Node Count*
|The number of virtual NUMA nodes available in a host that can be assigned to the virtual machine.
| No
|
|*NUMA Pinning*
|Opens the *NUMA Topology* window. This window shows the host's total CPUs, memory, and NUMA nodes, and the virtual machine's virtual NUMA nodes.
You can manually pin virtual NUMA nodes to host NUMA nodes by clicking and dragging each vNUMA from the box on the right to a NUMA node on the left.

You can also set *Tune Mode* for memory allocation:

*Strict* - Memory allocation will fail if the memory cannot be allocated on the target node.

*Preferred* - Memory is allocated from a single preferred node. If sufficient memory is not available, memory can be allocated from other nodes.

*Interleave* - Memory is allocated across nodes in a round-robin algorithm.

If you define NUMA pinning, *Migration Options* is set to *Allow manual migration only*.

| Yes

|
|*Auto Pinning Policy*
a| Allows you to set NUMA Pinning automatically.

* Select *None* to make no changes to the virtual machine.

//* Select *Pin* to use the existing CPU topology that has been set, in order to configure CPU pinning and NUMA pinning.

* Select *Resize and Pin* to maximize the CPU topology and generate the CPU pinning and NUMA pinning configurations.
|No

|===
