[[storage_considerations_active-passive]]
==== Storage Considerations

The storage domain for {virt-product-fullname} can be made of either block devices (SAN - iSCSI or FCP) or a file system (NAS - NFS, GlusterFS, or other POSIX compliant file systems). For more information about {virt-product-fullname} storage see link:{URL_virt_product_docs}administration_guide/#chap-Storage[Storage] in the _Administration Guide_. 

IMPORTANT: Local storage domains are unsupported for disaster recovery.

A primary and secondary storage replica is required. The primary storage domain’s block devices or shares that contain virtual machine disks or templates must be replicated. The secondary storage must not be attached to any data center, and will be added to the backup site’s data center during failover.

If you are implementing disaster recovery using self-hosted engine, ensure that the  storage domain used by the self-hosted engine {engine-name} virtual machine does not contain virtual machine disks because the storage domain will not be failed over.

All storage solutions that have replication options that are supported by {enterprise-linux} 7 and later can be used.
