[id="contributing-to-docs-tools-and-setup"]
= Install and set up the tools and software
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:linkattrs:
:description: How to set up and install the tools to contribute

toc::[]

== Create a GitHub account
Before you can contribute to oVirt documentation, you must
https://www.github.com/join[sign up for a GitHub account].

== Set up authentication
When you have your account set up, follow the instructions to
https://help.github.com/articles/generating-ssh-keys/[generate and set up SSH
keys on GitHub] for proper authentication between your workstation and GitHub.

Confirm authentication is working correctly with the following command:

----
$ ssh -T git@github.com
----

== Fork and clone the oVirt site repository
You must fork and set up the oVirt site repository on your
workstation so that you can create PRs and contribute. You only need to perform these steps during initial setup.

. Fork the https://github.com/ovirt/ovirt-site repository into your
GitHub account from the GitHub UI. Do this by clicking on *Fork* in the
upper right-hand corner.

. In the terminal on your workstation, change to the directory where you want
to clone the forked repository.

.  Clone the forked repository onto your workstation with the following
command, replacing _<user_name>_ with your actual GitHub username.
+
----
$ git clone git@github.com:<user_name>/ovirt-site.git
----

. Change into the directory for the local repository you just cloned.
+
----
$ cd ovirt-site
----

. Add an upstream pointer back to the oVirt site's remote repository, in this
case _ovirt-site_.
+
----
$ git remote add upstream git@github.com:ovirt/ovirt-site.git
----

This ensures that you are tracking the remote repository to keep your local
repository in sync with it.

== Install AsciiDoctor and dependencies
When you have the documentation repository cloned and set up, you are ready to
install the software and tools you will use to create the content. All oVirt
documentation is created in AsciiDoc, and is processed with http://asciidoctor.org/[AsciiDoctor].


=== What you require
The following are minimum requirements:

* A bash shell environment (Linux and OS X include a bash shell environment out
of the box, but if you are on Windows you can use http://cygwin.com/[Cygwin])
* https://www.ruby-lang.org/en/[Ruby]
* http://www.git-scm.com/[Git]
* A web browser (Firefox, Chrome, or Safari)
* An editor that can strip trailing whitespace, such as
link:https://atom.io/[Atom].

=== Install the required software dependencies on a Linux system
The following instructions describe how to install all the required tools to do
live content editing on a Fedora Linux system.

1. Install the _RubyGems_ package with `yum install rubygems`.
+
[NOTE]
====
On certain systems, `yum` installs an older version of RubyGems that can cause issues. As an alternative, you can install RubyGems by using RVM. The following example is referenced from the link:https://rvm.io/rvm/install[RVM site]:

[source,terminal]
----
$ curl -sSL https://get.rvm.io | bash -s stable --ruby
----
====

2. Install _Ruby_ development packages with `yum install ruby-devel`.
3. Install _gcc_ with `yum install gcc-c++`.
4. Install _redhat-rpm-config_ with `yum install redhat-rpm-config`.
5. Install _make_ with `yum install make`.
6. Install _asciidoctor-diagram_ with `gem install asciidoctor-diagram`.
