[[Live_migration_prerequisites]]
==== Live Migration Prerequisites

include::../common/sriov/conc-Set_Up_and_Configure_SR-IOV.adoc[]

You can use live migration to seamlessly move virtual machines to support a number of common maintenance tasks. Your {virt-product-fullname} environment must be correctly configured to support live migration well in advance of using it.

At a minimum, the following prerequisites must be met to enable successful live migration of virtual machines:

* The source and destination hosts are members of the same cluster, ensuring CPU compatibility between them.

[NOTE]
====
Live migrating virtual machines between different clusters is generally not recommended.
====

* The source and destination hosts' status is `Up`.

* The source and destination hosts have access to the same virtual networks and VLANs.

* The source and destination hosts have access to the data storage domain on which the virtual machine resides.

* The destination host has sufficient CPU capacity to support the virtual machine's requirements.

* The destination host has sufficient unused RAM to support the virtual machine's requirements.

* The migrating virtual machine does not have the `cache!=none` custom property set.

Live migration is performed using the management network and involves transferring large amounts of data between hosts. Concurrent migrations have the potential to saturate the management network. For best performance, create separate logical networks for management, storage, display, and virtual machine data to minimize the risk of network saturation.

[[Configuring_virtual_machines_with_SR-IOV-Enabled_vNICs]]
==== Configuring Virtual Machines with SR-IOV-Enabled vNICs to Reduce Network Outage during Migration

Virtual machines with vNICs that are directly connected to a virtual function (VF) of an SR-IOV-enabled host NIC can be further configured to reduce network outage during live migration:

. Ensure that the destination host has an available VF.
. Set the *Passthrough* and *Migratable* options in the passthrough vNIC's profile. See link:{URL_virt_product_docs}{URL_format}administration_guide/#Enabling_Passthrough_on_a_vNIC_Profile[Enabling Passthrough on a vNIC Profile] in the _Administration Guide_.
. Enable hotplugging for the virtual machine's network interface.
. Ensure that the virtual machine has a backup VirtIO vNIC, in addition to the passthrough vNIC, to maintain the virtual machine's network connection during migration.
. Set the VirtIO vNIC's `No Network Filter` option before configuring the bond. See link:{URL_virt_product_docs}{URL_format}administration_guide/#Explanation_of_Settings_in_the_VM_Interface_Profile_Window[Explanation of Settings in the VM Interface Profile Window] in the _Administration Guide_.
. Add both vNICs as slaves under an `active-backup` bond on the virtual machine, with the passthrough vNIC as the primary interface.
+
The bond and vNIC profiles can be configured in one of the following ways:

* The bond is not configured with `fail_over_mac=active` and the VF vNIC is the primary slave (recommended).
+
Disable the VirtIO vNIC profile's MAC-spoofing filter to ensure that traffic passing through the VirtIO vNIC is not dropped because it uses the VF vNIC MAC address.
//See link:{URL_rhel_docs_legacy}html-single/virtualization_deployment_and_administration_guide/index#sect-Virtual_Networking-Applying_network_filtering[Applying Network Filtering] in the _RHEL 7 Virtualization Deployment and Administration Guide_.
* The bond is configured with `fail_over_mac=active`.
+
This failover policy ensures that the MAC address of the bond is always the MAC address of the active slave. During failover, the virtual machine's MAC address changes, with a slight disruption in traffic.

[[Configuring_virtual_machines_with_SR-IOV-Enabled_vNICs_minimal_downtime]]
==== Configuring Virtual Machines with SR-IOV-Enabled vNICs with minimal downtime.
To configure virtual machines for migration with SR-IOV enabled vNICs and minimal downtime follow the procedure described below.
[NOTE]
====
The following steps are provided only as a Technology Preview. For more information see link:https://access.redhat.com/support/offerings/techpreview/[Red Hat Technology Preview Features Support Scope].
====

. Create a vNIC profile with SR-IOV enabled vNICS.
See link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/administration_guide/index#Creating_a_VNIC_Profile[Creating a vNIC profile] and link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html/administration_guide/sect-hosts_and_networking#setting-up-and-configuring-sr-iov[Setting up and configuring SR-IOV].
. In the Administration Portal, go to menu:Network[VNIC profiles], select the vNIC profile, click btn:[Edit] and select a `Failover vNIC profile` from the drop down list.
. Click btn:[OK] to save the profile settings.
. Hotplug a network interface with the failover vNIC profile you created into the virtual machine, or start a virtual machine with this network interface plugged in.
+
[NOTE]
====
The virtual machine will have three interfaces available, in order for migration to work properly, the main interface should be activated and used for connection. The main interface acts as a master for the remaining two interfaces.
====
+
. For automatic deployment of virtual machines with this configuration, use the following `udev` rule:
+
----
  UBSYSTEM=="net",
  ACTION=="add|change",
  ENV{ID_NET_DRIVER}!="net_failover",
  ENV{NM_UNMANAGED}="1",
  RUN+="/bin/sh -c '/sbin/ip link set up $INTERFACE'"
----
+
This `udev` rule works only on systems that manage interfaces with `NetworkManager`. This rule ensures that only the master interface is activated.
