[[Using_USB_Devices_on_a_Windows_Client]]
= Using USB Devices on a Windows Client

The `usbdk` driver must be installed on the Windows client for the USB device to be redirected to the guest. Ensure the version of `usbdk` matches the architecture of the client machine. For example, the 64-bit version of `usbdk` must be installed on 64-bit Windows machines.

[NOTE]
====
USB redirection is only supported when you open the virtual machine from the VM Portal.
====

.Procedure

. When the `usbdk` driver is installed, click menu:Compute[Virtual Machines] and select a virtual machine that is configured to use the SPICE protocol.
. Click the *Console* tab.
. Select the *USB enabled* checkbox and click btn:[OK].
. Click menu:Console[Console Options].
. Select the *Enable USB Auto-Share* check box and click btn:[OK].
. Start the virtual machine from the VM Portal and click btn:[Console] to connect to that virtual machine.
. Plug your USB device into the client machine to make it appear automatically on the guest machine.
