# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: oVirt
description: > # this means to ignore newlines until "baseurl:"
  oVirt is a free open-source virtualization solution for your
  entire enterprise
lang: en
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ovirt.org" # the base hostname & protocol for your site
twitter:
  username: ovirt
logo: /images/logo.svg

# historical (Middlemam time)
source: source

# Build settings
strict_front_matter: true
markdown: kramdown
highlighter: rouge

liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: false

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true

asciidoctor:
  base_dir: :docdir
  # to be able to resolve includes in parent directories
  safe: unsafe
  attributes:
    chunk_section_depth: 1
    site-baseurl: /
    page-liquid: ''
    source-highlighter: coderay
    coderay-css: style
    icons: font
    experimental: ''

# YAML defaults for pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: "application"
  -
    scope:
      path: 'develop/release-management/features'
    values:
      layout: "feature"
  -
    scope:
      path: 'develop/api'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: 'develop/architecture'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: 'develop/infra'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: 'develop/internal'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: 'develop/networking'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: '/community/get-involved/resources'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: 'develop/sdk'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: 'develop/sla'
    values:
      layout: "developer_outdated"
  -
    scope:
      path: 'develop/storage'
    values:
      layout: "developer_outdated"

excerpt_separator: READMORE

# Don't compile these files/dirs into the website
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  # used for local installation of gems
  - vendor
  - README.md
  - README_ORGANIZATION.md
  - MAINTAINING.md
  - LICENSE.md
  - CONTRIBUTING.md
  - CODEOWNERS
  # avoid generating paginated asciidoc content
  - documentation/common/**/*.adoc
  - documentation/upgrade_guide/topics
  - documentation/upgrade_guide/assembly*
  - documentation/administration_guide/topics
  - documentation/administration_guide/appe*
  - documentation/administration_guide/chap*
  - documentation/administration_guide/part*
  - documentation/upgrade_guide/chap-*
  - documentation/intro-vm-portal/topics
  - documentation/intro-vm-portal/chap*
  - documentation/virtual_machine_management_guide/appe*
  - documentation/virtual_machine_management_guide/chap*
  - documentation/virtual_machine_management_guide/topics

sass:
  add_charset: true
  style: :compressed

font-awesome:
  assets: true

favicon:
  source: images/favicon_base.png
  path: /images

breadcrumbs:
  root:
    hide: True
    image: false

jekyll_analytics:
  Piwik:
    url: stats.phx.ovirt.org
    siteId: '1'

