[[generate_mapping]]
= Creating the Playbook to Generate the Mapping File

The Ansible playbook used to generate the mapping file will prepopulate the file with the target (primary) site’s entities. You then must manually add the backup site’s entities, such as IP addresses, cluster, affinity groups, affinity label, external LUN disks, authorization domains, roles, and vNIC profiles, to the file.

[IMPORTANT]
====
The mapping file generation will fail if you have any virtual machine disks on the self-hosted engine’s storage domain. Also, the mapping file will not contain an attribute for this storage domain because it must not be failed over.
====
In this example the Ansible playbook is named `dr-rhv-setup.yml`, and is executed on the {engine-name} machine in the primary site.

.Procedure

. Create an Ansible playbook to generate the mapping file. For example:
+
[source,yaml,options="nowrap" subs="quotes"]
----
---
- name: Generate mapping
  hosts: localhost
  connection: local

  vars:
    site: https://example.engine.redhat.com/ovirt-engine/api
    username: admin@internal
    password: my_password
    ca: /etc/pki/ovirt-engine/ca.pem
    var_file: disaster_recovery_vars.yml

  roles:
    - oVirt.disaster-recovery
----
+
[NOTE]
====
For extra security you can encrypt your {engine-name} password in a `.yml` file. See link:{URL_virt_product_docs}{URL_format}administration_guide/index[Using Ansible Roles to Configure {virt-product-fullname}] in the _Administration Guide_ for more information.
====

. Run the Ansible command to generate the mapping file. The primary site’s configuration will be prepopulated.
+
[options="nowrap" subs="normal"]
----
# ansible-playbook dr-rhv-setup.yml --tags "generate_mapping"
----

. Configure the mapping file (`disaster_recovery_vars.yml` in this case) with the backup site’s configuration. See <<mapping_file_attributes>> for more information about the mapping file’s attributes.

If you have multiple Ansible machines that can perform the failover and failback, then copy the mapping file to all relevant machines.
