:_content-type: PROCEDURE
[id='Manually_Updating_Hosts_{context}']
= Manually Updating Hosts

:man_host_update:

[CAUTION]
====
This information is provided for advanced system administrators who need to update hosts manually, but {org-fullname} does not support this method. The procedure described in this topic does not include important steps, including certificate renewal, assuming advanced knowledge of such information. {org-fullname} supports updating hosts using the Administration Portal. For details, see  link:{URL_virt_product_docs}{URL_format}administration_guide/index#Updating_Individual_Hosts_admin[Updating individual hosts] or link:{URL_virt_product_docs}{URL_format}administration_guide/index#Updating_all_hosts_in_a_cluster_admin[Updating all hosts in a cluster] in the _Administration Guide_.
====

You can use the `dnf` command to update your hosts. Update your systems regularly, to ensure timely application of security and bug fixes.

//Limitations
include::snip-Host_update_limitations.adoc[]

.Procedure

. Ensure the correct repositories are enabled. You can check which repositories are currently enabled by running `dnf repolist`.

ifdef::rhv-doc[]
* For {hypervisor-fullname}s:
+
[source,terminal,subs="normal"]
----
# subscription-manager repos --enable=rhvh-4-for-rhel-8-x86_64-rpms
----
* For {enterprise-linux-host-fullname}s:
+
[source,terminal,subs="normal"]
----
# subscription-manager repos \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms \
    --enable=rhv-4-mgmt-agent-for-rhel-8-x86_64-rpms \
    --enable=advanced-virt-for-rhel-8-x86_64-rpms \
    --enable=fast-datapath-for-rhel-8-x86_64-rpms
----
endif::[]
ifdef::ovirt-doc[]
Upgrading from an older 4.5 to latest 4.5:

* For {hypervisor-fullname}s, the `centos-release-ovirt45` RPM package enabling the correct repositories is already installed.
* For {enterprise-linux-host-fullname}s:
* If you are going to install on RHEL or derivatives please follow link:/download/install_on_rhel.html[Installing on RHEL or derivatives] first.
+
[source,terminal,subs="normal"]
----
# dnf update -y centos-release-ovirt45
----

Upgrading from an older 4.4 to latest 4.4:

* For {hypervisor-fullname}s, the `ovirt-release44` RPM package enabling the correct repositories is already installed.
* For {enterprise-linux-host-fullname}s ensure `ovirt-release44` RPM package is updated to the latest version:
+
[source,terminal,subs="normal"]
----
# dnf update -y ovirt-release44
----

Common procedure valid for both 4.4 and 4.5:

endif::[]

. In the Administration Portal, click menu:Compute[Hosts] and select the host to be updated.
. Click menu:Management[Maintenance] and btn:[OK].
// START FOR RHEL HOSTS ONLY
. For {enterprise-linux} hosts:

.. Identify the current version of {enterprise-linux}:
+
[source,terminal,subs="normal"]
----
# cat /etc/redhat-release
----
.. Check which version of the redhat-release package is available:
+
[source,terminal,subs="normal"]
----
# dnf --refresh info --available redhat-release
----
+
This command shows any available updates. For example, when upgrading from {enterprise-linux} 8.2._z_ to 8.3, compare the version of the package with the currently installed version:
+
[source,terminal,subs="normal"]
----
Available Packages
Name         : redhat-release
Version      : 8.3
Release      : 1.0.el8
...
----
+
[CAUTION]
====
The {enterprise-linux} Advanced Virtualization module is usually released later than the {enterprise-linux} y-stream. If no new Advanced Virtualization module is available yet, or if there is an error enabling it, stop here and cancel the upgrade. Otherwise you risk corrupting the host.
====
.. If the Advanced Virtualization stream is available for {enterprise-linux} 8.3 or later, reset the `virt` module:
+
[source,terminal,subs="normal"]
+
----
# dnf module reset virt
----
+
[NOTE]
====
If this module is already enabled in the Advanced Virtualization stream, this step is not necessary, but it has no negative impact.

You can see the value of the stream by entering:
----
# dnf module list virt
----
====
+
.. Enable the `virt` module in the Advanced Virtualization stream with the following command:
+
include::../install/snip-Enable_virt_module.adoc[]
+
// END FOR RHEL HOSTS ONLY
. Update the host:
+
[source,terminal,subs="normal"]
----
# dnf upgrade --nobest
----
//ansible lock addition

. Reboot the host to ensure all updates are correctly applied.
+
[NOTE]
====
Check the imgbased logs to see if any additional package updates have failed for a {hypervisor-fullname}. If some packages were not successfully reinstalled after the update, check that the packages are listed in */var/imgbased/persisted-rpms*. Add any missing packages then run `rpm -Uvh /var/imgbased/persisted-rpms/*`.
====

Repeat this process for each host in the {virt-product-fullname} environment.

:man_host_update!:
