[id="Upgrading_the_Manager_to_4-2_{context}"]
= Upgrading the {engine-name} from 4.1 to 4.2

Upgrade the {virt-product-fullname} {engine-name} from 4.1 to 4.2.

// Included in:
// Upgrade Guide

[IMPORTANT]
====
If the upgrade fails, the `engine-setup` command attempts to roll your {virt-product-fullname} {engine-name} installation back to its previous state. For this reason, the previous version's repositories must not be removed until after the upgrade is complete. If the upgrade fails, detailed instructions display that explain how to restore your installation.
====

.Procedure

ifdef::SHE_upgrade[. Log in to the {engine-name} virtual machine.]
ifdef::local_database_upgrade,remote_database_upgrade[. Log in to the {engine-name} machine.]


. Enable the {virt-product-fullname} 4.2 repositories:
+
ifdef::rhv-doc[]
----
# subscription-manager repos \
    --enable=rhel-7-server-rhv-4.2-manager-rpms \
    --enable=rhel-7-server-rhv-4-manager-tools-rpms \
    --enable=jb-eap-7-for-rhel-7-server-rpms \
    --enable=rhel-7-server-ansible-2-rpms
----
endif::[]
ifdef::ovirt-doc[]
----
# yum install https://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm
----
endif::[]
+
All other repositories remain the same across {virt-product-fullname} releases.

. Update the setup packages:
+
ifdef::rhv-doc[]
[options="nowrap" subs="normal"]
----
# yum update ovirt\\*setup\* rh\*vm-setup-plugins
----
endif::[]
ifdef::ovirt-doc[]
[options="nowrap" subs="normal"]
----
# yum update ovirt\\*setup\*
----
endif::[]

. Run `engine-setup` and follow the prompts to upgrade the {virt-product-fullname} {engine-name}:
+
----
# engine-setup
----
+
[NOTE]
====
If you changed the default trust keystore password, you might get a keystore certificate error. If so, update the configuration to reflect the correct password. For more information, see link:{URL_customer-portal}solutions/3545011[_RHV 4.2 - Failed to import provider certificate into the external provider keystore_]
====

ifdef::rhv-doc[]
. Disable the {virt-product-fullname} 4.1 repositories to ensure the system does not use any 4.1 packages:
+
----
# subscription-manager repos \
    --disable=rhel-7-server-rhv-4.1-rpms \
    --disable=rhel-7-server-rhv-4.1-manager-rpms \
    --disable=rhel-7-server-rhv-4-tools-rpms \
    --disable=jb-eap-7.0-for-rhel-7-server-rpms \
    --disable=jb-eap-7.1-for-rhel-7-server-rpms
----
endif::[]

. Update the base operating system:
+
----
# yum update
----
+
[IMPORTANT]
====
If any kernel packages were updated, reboot the machine to complete the upgrade.
====
