[id="Upgrading_Remote_Databases_from_PG_92_to_95_{context}"]
= Upgrading Remote Databases from PostgreSQL 9.2 to 9.5

{virt-product-fullname} 4.2 uses PostgreSQL 9.5 instead of PostgreSQL 9.2. If your databases are installed locally, the upgrade script will automatically upgrade them from version 9.2 to 9.5.
However, if either of your databases ({engine-name} or Data Warehouse) is installed on a separate machine, you must perform the following procedure on each remote database before upgrading the {engine-name}.

. Stop the service running on the machine:
* Stop the `ovirt-engine` service on the {engine-name} machine:
+
----
# systemctl stop ovirt-engine
----
* Stop the `ovirt-engine-dwh` service on the Data Warehouse machine:
+
----
# systemctl stop ovirt-engine-dwhd
----

. Enable the required repository to receive the PostgreSQL 9.5 package:
+
ifdef::rhv-doc[]
Enable either the {virt-product-fullname} {engine-name} repository:
// Leave this repo at 4.2.
+
----
# subscription-manager repos --enable=rhel-7-server-rhv-4.2-manager-rpms
----
+
or the SCL repository:
+
----
# subscription-manager repos --enable rhel-server-rhscl-7-rpms
----
endif::[]
ifdef::ovirt-doc[]
* Ensure the correct repositories are enabled:
+
[options="nowrap" subs="normal"]
----
# yum install https://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm
----
endif::[]

. Install the PostgreSQL 9.5 packages:
+
----
# yum install rh-postgresql95 rh-postgresql95-postgresql-contrib
----

. Stop and disable the PostgreSQL 9.2 service:
+
----
# systemctl stop postgresql
# systemctl disable postgresql
----

. Upgrade the PostgreSQL 9.2 database to PostgreSQL
9.5:
+
----
# scl enable rh-postgresql95 -- postgresql-setup upgrade
----

. Start and enable the `rh-postgresql95-postgresql.service` and check that it is running:
+
----
# systemctl start rh-postgresql95-postgresql.service
# systemctl enable rh-postgresql95-postgresql.service
# systemctl status rh-postgresql95-postgresql.service
----
+
Ensure that you see an output similar to the following:
+
[options="nowrap" subs="normal"]
----
rh-postgresql95-postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/rh-postgresql95-postgresql.service;
enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-05-07 08:48:27 CEST; 1h 59min ago
----

. Log in to the database and enable the `uuid-ossp` extension:
+
[options="nowrap" subs="quotes"]
----
# su - postgres -c "scl enable rh-postgresql95 -- psql -d _database-name_"
----
+
. Execute the following SQL commands:
+
[options="nowrap" subs="normal"]
----
# _database-name_=# DROP FUNCTION IF EXISTS uuid_generate_v1();
# _database-name_=# CREATE EXTENSION "uuid-ossp";
----

. Copy the [filename]`pg_hba.conf` client configuration file from the 9.2 environment to your 9.5 environment:
+
[options="nowrap" subs="normal"]
----
# cp -p /var/lib/pgsql/data/pg_hba.conf  /var/opt/rh/rh-postgresql95/lib/pgsql/data/pg_hba.conf
----

. Update the following parameters in [filename]`/var/opt/rh/rh-postgresql95/lib/pgsql/data/postgresql.conf`:
+
[options="nowrap" subs="normal"]
----
listen_addresses='*'
autovacuum_vacuum_scale_factor = 0.01
autovacuum_analyze_scale_factor = 0.075
autovacuum_max_workers = 6
maintenance_work_mem = 65536
max_connections = 150
work_mem = 8192
----

. Restart the PostgreSQL 9.5 service to apply the configuration changes:
+
----
# systemctl restart rh-postgresql95-postgresql.service
----

. Start the `ovirt-engine-dwhd` service:
+
[options="nowrap" subs="normal"]
----
# systemctl start ovirt-engine-dwhd
----
