[id="Updating_the_Red_Hat_Virtualization_Manager_{context}"]
= Updating the {virt-product-fullname} {engine-name}

// Included in:
// Upgrade Guide
// Administration Guide
// Migrating from a standalone {engine-name} to a self-hosted engine

// Although most of the {virt-product-fullname} doc set now uses `dnf` instead of `yum`, this topic still
// uses `yum` because it is included in 4.2 and 4.3 sections in the Upgrade Guide, where the OS is still
// {enterprise-linux} 7.

ifdef::migrating_to_SHE[]
.Prerequisites
* The data center compatibility level must be set to the latest version to ensure compatibility with the updated storage version.
endif::migrating_to_SHE[]
ifdef::upgrade[]
.Prerequisites
ifdef::ovirt-doc[]
* The RPM package link:https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm[ovirt-release44.rpm] is installed. This package includes the necessary repositories.
endif::ovirt-doc[]

ifdef::rhv-doc[]
* Ensure the {engine-name} has the correct repositories enabled. For the list of required repositories, see
ifdef::4-2_local_db,4-2_remote_db,4-2_SHE[]
link:{URL_customer-portal}{URL_docs}{URL_lang-locale}{URL_product_rhv}4.2/html-single/installation_guide/index#Enabling_the_Red_Hat_Virtualization_Manager_Repositories_standalone_install[Enabling the {virt-product-fullname} {engine-name} Repositories] for {virt-product-fullname} 4.2.
endif::4-2_local_db,4-2_remote_db,4-2_SHE[]
ifdef::4-3_local_db,4-3_remote_db,4-3_SHE[]
link:{URL_customer-portal}{URL_docs}{URL_lang-locale}{URL_product_rhv}4.3/html-single/installing_red_hat_virtualization_as_a_self-hosted_engine_using_the_cockpit_web_interface/index#Enabling_the_Red_Hat_Virtualization_Manager_Repositories_install_RHVM[Enabling the {virt-product-fullname} {engine-name} Repositories] for {virt-product-fullname} 4.3.
endif::4-3_local_db,4-3_remote_db,4-3_SHE[]
ifdef::SHE_minor_updates,migrating_to_SHE,minor_updates[]
link:{URL_virt_product_docs}{URL_format}installing_{URL_product_virt}_as_a_standalone_manager_with_local_databases/index#Enabling_the_Red_Hat_Virtualization_Manager_Repositories_install_RHVM[Enabling the {virt-product-fullname} {engine-name} Repositories] for {virt-product-fullname} 4.4.
+
[NOTE]
====
If you are upgrading from {virt-product-shortname} version 4.4.0 through 4.4.8 to {virt-product-shortname} version 4.4.9 or later, you must add the EAP 7.4 channel to the list of subscription repositories `jb-eap-7.4-for-rhel-8-x86_64-rpms`, and following the upgrade, remove the `jb-eap-7.3-for-rhel-8-x86_64-rpms` from the lisat of subscription repositories.
====
endif::SHE_minor_updates,migrating_to_SHE,minor_updates[]
+
Updates to the {virt-product-fullname} {engine-name} are released through the Content Delivery Network.
endif::rhv-doc[]
endif::upgrade[]

.Procedure

// ifdef::SHE_upgrade,SHE_minor_updates[. Log in to the {engine-name} virtual machine.]
// ifdef::local_database_upgrade,remote_database_upgrade,minor_updates[. Log in to the {engine-name} machine.]

. On the {engine-name} machine, check if updated packages are available:
+
----
# engine-upgrade-check
----

. Update the setup packages:
+
ifdef::rhv-doc[]
[options="nowrap" subs="normal"]
----
# yum update ovirt\\*setup\* rh\*vm-setup-plugins
----
endif::[]
ifdef::ovirt-doc[]
[options="nowrap" subs="normal"]
----
# yum update ovirt\\*setup\*
----
endif::[]

. Update the {virt-product-fullname} {engine-name} with the `engine-setup` script. The `engine-setup` script prompts you with some configuration questions, then stops the `ovirt-engine` service, downloads and installs the updated packages, backs up and updates the database, performs post-installation configuration, and starts the `ovirt-engine` service.
+
----
# engine-setup
----
+
When the script completes successfully, the following message appears:
+
----
Execution of setup completed successfully
----
+
[NOTE]
====
The `engine-setup` script is also used during the {virt-product-fullname} {engine-name} installation process, and it stores the configuration values supplied. During an update, the stored values are displayed when previewing the configuration, and might not be up to date if `engine-config` was used to update configuration after installation. For example, if `engine-config` was used to update `SANWipeAfterDelete` to `true` after installation, `engine-setup` will output "Default SAN wipe after delete: False" in the configuration preview. However, the updated values will not be overwritten by `engine-setup`.
====
+
[IMPORTANT]
====
The update process might take some time. Do not stop the process before it completes.
====

. Update the base operating system and any optional packages installed on the {engine-name}:
+
----
# yum update
----
+
[IMPORTANT]
====
If you encounter a required Ansible package conflict during the update, see link:https://access.redhat.com/solutions/5480561[Cannot perform yum update on my RHV manager (ansible conflict)].
====
//ansible lock addition
+
[IMPORTANT]
====
ifdef::SHE_minor_updates[]
If any kernel packages were updated:

. Disable global maintenance mode
. Reboot the machine to complete the update.
endif::[]

ifndef::SHE_minor_updates[If any kernel packages were updated, reboot the machine to complete the update.]
====

ifdef::appendices[]
ifdef::rhv-doc[]
[NOTE]
====
If the update from {virt-product-shortname} 4.2.7 to {virt-product-shortname} 4.2.8 fails with a message indicating a dependency error with an `eap7-jboss-server-migration-wildfly` package:

. Check if all the required repositories are enabled.
. Update the `eap7-jboss-server-migration-wildfly` packages installed on the Manager:
+
----
# yum update eap7-jboss-server-migration-wildfly*
----
. Run `engine-setup` again.
====
endif::[]
endif::[]

ifdef::SHE_minor_updates[]
.Related Information
xref:Disabling_Global_Maintenance_Mode_SHE_minor_updates[Disabling global maintenance mode]
endif::[]
