:_content-type: ASSEMBLY
[id="Red_Hat_Virtualization_Upgrade_Overview"]

//{virt-product-fullname} Upgrade Overview

This guide explains how to upgrade the following environments to {virt-product-fullname} 4.3 or 4.4 :

* *Standalone manager, local database*: Both the Data Warehouse database and the {engine-name} database are installed on the {engine-name}.

* *Standalone manager, remote database*: Either the Data Warehouse database or the {engine-name} database, or both, are on a separate machine.

* *Self-hosted engine, local database*: Both the Data Warehouse database and the {engine-name} database are installed on the {engine-name}.


ifdef::rhv-doc[]
[NOTE]
====
For a checklist of upgrade instructions, you can use the link:https://access.redhat.com/labs/rhvupgradehelper/[RHV Upgrade Helper]. This application asks you to fill in a checklist for your upgrade path and current environment, and presents the applicable upgrade steps.
====
endif::[]
////
To save time when upgrading a {engine-name} with local databases, use the `ovirt-fast-forward-upgrade` tool.

[NOTE]
====
`ovirt-fast-forward-upgrade` supports local database environments only.
====

Alternatively, you can manually upgrade the {engine-name}. For remote database environments, this path is required.
////

[IMPORTANT]
====
Plan any necessary downtime in advance. After you update the clusters' compatibility versions during the upgrade, a new hardware configuration is automatically applied to each virtual machine once it reboots. You must reboot any running or suspended VMs as soon as possible to apply the configuration changes.
====

Select the appropriate instructions for your environment from the following table. If your {engine-name} and host versions differ (if you have previously upgraded the {engine-name} but not the hosts), follow the instructions that match the {engine-name}'s version.

.Supported Upgrade Paths

[cols="2,2,6", options="header"]
|===

|Current {engine-name} version |Target {engine-name} version |Relevant section
|4.3 |4.4 a|*Local database environment -* xref:Upgrading_from_4-3[Upgrading from {virt-product-fullname} 4.3 to 4.4]

*Remote database environment:* xref:Remote_Upgrading_from_4-3[Upgrading a Remote Database Environment from {virt-product-fullname} 4.3 to 4.4]

*Self-hosted engine, local database environment:* xref:SHE_Upgrading_from_4-3[Upgrading a self-Hosted engine from {virt-product-fullname} 4.3 to 4.4]

|4.2 |4.3 a| *Local database environment:* xref:Upgrading_from_4-2[Upgrading from {virt-product-fullname} 4.2 to 4.3]

*Remote database environment:* xref:Remote_Upgrading_from_4-2[Upgrading a Remote Database Environment from {virt-product-fullname} 4.2 to 4.3]

*Self-hosted engine, local database environment:* xref:SHE_Upgrading_from_4-2[Upgrading a Self-Hosted Engine from {virt-product-fullname} 4.2 to 4.3]

|===
