[[chap-Overview]]
== Overview

Version 4 of the Python software development kit is a collection of classes that allows you to interact with the {virt-product-fullname} {engine-name} in Python-based projects. By downloading these classes and adding them to your project, you can access a range of functionality for high-level automation of administrative tasks.

[NOTE]
====
Version 3 of the SDK is no longer supported. For more information, consult link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html-single/python_sdk_guide/[the RHV 4.3 version of this guide].
====

.Python 3.7 and `async`

In Python 3.7 and later versions, link:https://docs.python.org/3/reference/compound_stmts.html#async[`async`] is a reserved keyword. You cannot use the `async` parameter in methods of services that previously supported it, as in the following example, because `async=True` will cause an error:

[source, Python]
----
dc = dc_service.update(
    types.DataCenter(
        description='Updated description',
    ),
    async=True,
)
----

The solution is to add an underscore to the parameter (`async_`):

[source, Python]
----
dc = dc_service.update(
    types.DataCenter(
        description='Updated description',
    ),
    async_=True,
)
----

[NOTE]
====
This limitation applies only to Python 3.7 and later. Earlier versions of Python do not require this modification.
====

include::topics/Python_SDK_Prerequisites.adoc[]

include::topics/Installing_the_Software_Development_Kit.adoc[]
