:_content-type: CONCEPT
[id="Directory_Services2"]
= Directory Services

The {virt-product-fullname} platform relies on directory services for user authentication and authorization. Interactions with all {engine-name} interfaces, including the VM Portal, Administration Portal, and REST API are limited to authenticated, authorized users. Virtual machines within the {virt-product-fullname} environment can use the same directory services to provide authentication and authorization, however they must be configured to do so. The currently supported providers of directory services for use with the {virt-product-fullname} {engine-name} are Identity Management (IdM), Red Hat Directory Server 9 (RHDS), Active Directory (AD), and OpenLDAP. The {virt-product-fullname} {engine-name} interfaces with the directory server for:

* Portal logins (User, Power User, Administrator, REST API).

* Queries to display user information.

* Adding the {engine-name} to a domain.



Authentication is the verification and identification of a party who generated some data, and of the integrity of the generated data. A principal is the party whose identity is verified. The verifier is the party who demands assurance of the principal's identity. In the case of {virt-product-fullname}, the {engine-name} is the verifier and a user is a principal. Data integrity is the assurance that the data received is the same as the data generated by the principal.

Confidentiality and authorization are closely related to authentication. Confidentiality protects data from disclosure to those not intended to receive it. Strong authentication methods can optionally provide confidentiality. Authorization determines whether a principal is allowed to perform an operation. {virt-product-fullname} uses directory services to associate users with roles and provide authorization accordingly. Authorization is usually performed after the principal has been authenticated, and may be based on information local or remote to the verifier.

During installation, a local, internal domain is automatically configured for administration of the {virt-product-fullname} environment. After the installation is complete, more domains can be added.
