:_content-type: CONCEPT
[id="Storage_Domain_Types1"]
= Storage Domain Types

{virt-product-fullname} supports the following types of storage domains, as well as the storage types that each storage domain supports.

* The *Data Domain* stores the hard disk images of all virtual machines in the {virt-product-fullname} environment. Disk images may contain an installed operating system or data stored or generated by a virtual machine. Data storage domains support NFS, iSCSI, FCP, GlusterFS and POSIX compliant storage. A data domain cannot be shared between multiple data centers.

* The *Export Domain* provides transitory storage for hard disk images and virtual machine templates being transferred between data centers. Additionally, export storage domains store backed up copies of virtual machines. Export storage domains support NFS storage. Multiple data centers can access a single export storage domain but only one data center can use it at a time.
+
[NOTE]
====
The Export domain is deprecated. Storage data domains can be unattached from a data center and imported to another data center in the same environment, or in a different environment. Virtual machines, floating virtual disks, and templates can then be uploaded from the imported storage domain to the attached data center.
====
* The *ISO Domain* stores ISO files, also called images. ISO files are representations of physical CDs or DVDs. In the {virt-product-fullname} environment the common types of ISO files are operating system installation disks, application installation disks, and guest agent installation disks. These images can be attached to virtual machines and booted in the same way that physical disks are inserted into a disk drive and booted. ISO storage domains allow all hosts within the data center to share ISOs, eliminating the need for physical optical media.
+
[NOTE]
====
The ISO domain is a deprecated storage domain type. The ISO Uploader tool has been deprecated. Red Hat recommends uploading ISO images to the data domain with the Administration Portal or with the REST API.
====
