:_content-type: CONCEPT
[id="Storage_Domains1"]
= Storage Domains Overview

A storage domain is a collection of images that have a common storage interface. A storage domain contains complete images of templates and virtual machines (including snapshots), ISO files, and metadata about themselves. A storage domain can be made of either block devices (SAN - iSCSI or FCP) or a file system (NAS - NFS, GlusterFS, or other POSIX compliant file systems).

ifdef::rhv-doc[]
[NOTE]
====
GlusterFS Storage is deprecated, and will no longer be supported in future releases.
====
endif::rhv-doc[]

On NAS, all virtual disks, templates, and snapshots are files.

On SAN (iSCSI/FCP), each virtual disk, template or snapshot is a logical volume. Block devices are aggregated into a logical entity called a volume group, and then divided by LVM (Logical Volume Manager) into logical volumes for use as virtual hard disks. See the link:{URL_rhel_docs_legacy}html-single/configuring_and_managing_logical_volumes/index[Red Hat Enterprise Linux Configuring and managing logical volumes] guide for more information on LVM.

Virtual disks can have one of two formats, either QCOW2 or raw. The type of storage can be either sparse or preallocated. Snapshots are always sparse but can be taken for disks of either format.

Virtual machines that share the same storage domain can be migrated between hosts that belong to the same cluster.
