:_content-type: CONCEPT
[id="The_Effect_of_Storage_Domain_Actions_on_Storage_Capacity"]
= The Effect of Storage Domain Actions on Storage Capacity

Power on, power off, and reboot a stateless virtual machine:: These three processes affect the copy-on-write (COW) layer in a stateless virtual machine. For more information, see the *Stateless* row of the link:{URL_virt_product_docs}{URL_format}virtual_machine_management_guide/index#Virtual_Machine_General_settings_explained[Virtual Machine General Settings table] in the _Virtual Machine Management Guide_.

Create a storage domain:: Creating a block storage domain results in files with the same names as the seven LVs shown below, and initially should take less capacity.
+
[source, Bash, options="nowrap"]
----
ids              64f87b0f-88d6-49e9-b797-60d36c9df497 -wi-ao---- 128.00m
inbox            64f87b0f-88d6-49e9-b797-60d36c9df497 -wi-a----- 128.00m
leases           64f87b0f-88d6-49e9-b797-60d36c9df497 -wi-a-----   2.00g
master           64f87b0f-88d6-49e9-b797-60d36c9df497 -wi-ao----   1.00g
metadata         64f87b0f-88d6-49e9-b797-60d36c9df497 -wi-a----- 512.00m
outbox           64f87b0f-88d6-49e9-b797-60d36c9df497 -wi-a----- 128.00m
xleases          64f87b0f-88d6-49e9-b797-60d36c9df497 -wi-a-----   1.00g
----

Delete a storage domain:: Deleting a storage domain frees up capacity on the disk by the same of amount of capacity the process deleted.

Migrate a storage domain:: Migrating a storage domain does not use additional storage capacity. For more information about migrating storage domains, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Migrating_SD_between_DC_Same_Env[Migrating Storage Domains Between Data Centers in the Same Environment] in the _Administration Guide_.

Move a virtual disk to other storage domain:: Migrating a virtual disk requires enough free space to be available on the target storage domain. You can see the target domain's approximate free space in the Administration Portal.
+
The storage types in the move process affect the visible capacity. For example, if you move a preallocated disk from block storage to file storage, the resulting free space may be considerably smaller than the initial free space.
+
Live migrating a virtual disk to another storage domain also creates a snapshot, which is automatically merged after the migration is complete. To learn more about moving virtual disks, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Moving_a_Virtual_Disk[Moving a Virtual Disk] in the _Administration Guide_.

Pause a storage domain:: Pausing a storage domain does not use any additional storage capacity.

Create a snapshot of a virtual machine:: Creating a snapshot of a virtual machine can affect the storage domain capacity.
* Creating a live snapshot uses memory snapshots by default and generates two additional volumes per virtual machine. The first volume is the sum of the memory, video memory, and 200 MB of buffer. The second volume contains the virtual machine configuration, which is several MB in size. When using block storage, rounding up occurs to the nearest unit {virt-product-fullname} can provide.
* Creating an offline snapshot initially consumes 1 GB of block storage and is dynamic up to the size of the disk.
* Cloning a snapshot creates a new disk the same size as the original disk.
* Committing a snapshot removes all child volumes, depending on where in the chain the commit occurs.
* Deleting a snapshot eventually removes the child volume for each disk and is only supported with a running virtual machine.
* Previewing a snapshot creates a temporary volume per disk, so sufficient capacity must be available to allow the creation of the preview.
* Undoing a snapshot preview removes the temporary volume created by the preview.

Attach and remove direct LUNs:: Attaching and removing direct LUNs does not affect the storage domain since they are not a storage domain component. For more information, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Overview_of_Live_Storage_Migration[Overview of Live Storage Migration] in the _Administration Guide_.
