[id='CPU_Requirements_{context}']
= CPU Requirements

// Included in:
// PPG
// Install

All CPUs must have support for the Intel® 64 or AMD64 CPU extensions, and the AMD-V™ or Intel VT® hardware virtualization extensions enabled. Support for the No eXecute flag (NX) is also required.

The following CPU models are supported:

* AMD
** Opteron G4
** Opteron G5
** EPYC
* Intel
** Nehalem
** Westmere
** SandyBridge
** IvyBridge
** Haswell
** Broadwell
** Skylake Client
** Skylake Server
** Cascadelake Server

ifndef::SHE_cockpit_deploy,SHE_cli_deploy[]
* IBM
** POWER8
** POWER9
endif::SHE_cockpit_deploy,SHE_cli_deploy[]

For each CPU model with security updates, the *CPU Type* lists a basic type and a secure type. For example:

* *Intel Cascadelake Server Family*
* *Secure Intel Cascadelake Server Family*

The Secure CPU type contains the latest updates. For details, see BZ#link:https://bugzilla.redhat.com/1731395[1731395]

include::proc-Checking_Processor_Flag_Support.adoc[leveloffset=+1]
