:_content-type: REFERENCE
[id='RHV-manager-firewall-requirements_{context}']
= {virt-product-fullname} {engine-name} Firewall Requirements

// Included in:
// PPG
// Install

The {virt-product-fullname} {engine-name} requires that a number of ports be opened to allow network traffic through the system's firewall.

The `engine-setup` script can configure the firewall automatically.

The firewall configuration documented here assumes a default configuration.

ifdef::rhv-doc[]
[NOTE]
====
A diagram of these firewall requirements is available at https://access.redhat.com/articles/3932211.
You can use the IDs in the table to look up connections in the diagram.
====
endif::[]

.{virt-product-fullname} {engine-name} Firewall Requirements
[options="header", cols="3,3,3,4,4,4,4", frame=all, grid=all]
|===
|ID |Port(s) |Protocol |Source |Destination |Purpose |Encrypted by default
|M1 |- |ICMP |{hypervisor-fullname}s

{enterprise-linux-host-fullname}s |{virt-product-fullname} {engine-name} |Optional.

May help in diagnosis.
|No
|M2 |22 |TCP |System(s) used for maintenance of the {engine-name} including backend configuration, and software upgrades. |{virt-product-fullname} {engine-name} |Secure Shell (SSH) access.

Optional.
|Yes
|M3 |2222 |TCP |Clients accessing virtual machine serial consoles. |{virt-product-fullname} {engine-name} |Secure Shell (SSH) access to enable connection to virtual machine serial consoles.
|Yes
|M4 |80, 443 |TCP |Administration Portal clients

VM Portal clients

{hypervisor-fullname}s

{enterprise-linux-host-fullname}s

REST API clients |{virt-product-fullname} {engine-name}|Provides HTTP (port 80, not encrypted) and HTTPS (port 443, encrypted) access to the {engine-name}. HTTP redirects connections to HTTPS.
|Yes
|M5 |6100 |TCP |Administration Portal clients

VM Portal clients |{virt-product-fullname} {engine-name} |Provides websocket proxy access for a web-based console client, `noVNC`, when the websocket proxy is running on the {engine-name}.
|No
|M6 |7410 |UDP |{hypervisor-fullname}s

{enterprise-linux-host-fullname}s |{virt-product-fullname} {engine-name} |If Kdump is enabled on the hosts, open this port for the fence_kdump listener on the {engine-name}. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-fence_kdump_Advanced_Configuration[fence_kdump Advanced Configuration]. `fence_kdump` doesn't provide a way to encrypt the connection. However, you can manually configure this port to block access from hosts that are not eligible.
|No
|M7 |54323 |TCP |Administration Portal clients |{virt-product-fullname} {engine-name} (`ovirt-imageio` service) |Required for communication with the `ovirt-imageo` service.
|Yes
|M8 |6442 |TCP |{hypervisor-fullname}s

{enterprise-linux-host-fullname}s |Open Virtual Network (OVN) southbound database |Connect to Open Virtual Network (OVN) database
|Yes
|M9 |9696 |TCP |Clients of external network provider for OVN |External network provider for OVN |OpenStack Networking API
|Yes, with configuration generated by engine-setup.
|M10 |35357 |TCP |Clients of external network provider for OVN |External network provider for OVN |OpenStack Identity API
|Yes, with configuration generated by engine-setup.
|M11 |53 |TCP, UDP |{virt-product-fullname} {engine-name} | DNS Server | DNS lookup requests from ports above 1023 to port 53, and responses. Open by default.
|No
|M12 |123 |UDP |{virt-product-fullname} {engine-name} | NTP Server |NTP requests from ports above 1023 to port 123, and responses.  Open by default.
|No
|===

[NOTE]
====
* A port for the OVN northbound database (6641) is not listed because, in the default configuration, the only client for the OVN northbound database (6641) is `ovirt-provider-ovn`. Because they both run on the same host, their communication is not visible to the network.
* By default, {enterprise-linux} allows outbound traffic to DNS and NTP on any destination address. If you disable outgoing traffic, make exceptions for the {engine-name} to send requests to DNS and NTP servers. Other nodes may also require DNS and NTP. In that case, consult the requirements for those nodes and configure the firewall accordingly.
====
