[id='browser-requirements_{context}']
= Browser Requirements

// Included in:
// PPG
// Install
// Introduction_to_the_Administration_Portal
// Introduction_to_the_VM_Portal

The following browser versions and operating systems can be used to access the Administration Portal and the VM Portal.

ifdef::rhv-doc[]
Browser support is divided into tiers:

* Tier 1: Browser and operating system combinations that are fully tested and fully supported. Red Hat Engineering is committed to fixing issues with browsers on this tier.

* Tier 2: Browser and operating system combinations that are partially tested, and are likely to work. Limited support is provided for this tier. Red Hat Engineering will attempt to fix issues with browsers on this tier.

* Tier 3: Browser and operating system combinations that are not tested, but may work. Minimal support is provided for this tier. Red Hat Engineering will attempt to fix only minor issues with browsers on this tier.
endif::[]

ifdef::ovirt-doc[]
Browser testing is divided into tiers:

* Tier 1: Browser and operating system combinations that are fully tested.

* Tier 2: Browser and operating system combinations that are partially tested, and are likely to work.

* Tier 3: Browser and operating system combinations that are not tested, but may work.
endif::[]

.Browser Requirements
[options="header"]
|===
|Support Tier |Operating System Family |Browser
|Tier 1 |{enterprise-linux} |Mozilla Firefox Extended Support Release (ESR) version
| |Any |Most recent version of Google Chrome, Mozilla Firefox, or Microsoft Edge
|Tier 2 | |
|Tier 3 |Any |Earlier versions of Google Chrome or Mozilla Firefox
| |Any |Other browsers
|===
