[id='client-requirements_{context}']
= Client Requirements

// Included in:
// PPG
// Install
// Introduction_to_the_Administration_Portal
// Introduction_to_the_VM_Portal

Virtual machine consoles can only be accessed using supported Remote Viewer (`virt-viewer`) clients on {enterprise-linux} and Windows. To install `virt-viewer`, see link:{URL_virt_product_docs}{URL_format}virtual_machine_management_guide/index#sect-installing_supporting_components[Installing Supporting Components on Client Machines] in the _Virtual Machine Management Guide_. Installing `virt-viewer` requires Administrator privileges.

You can access virtual machine consoles using the SPICE, VNC, or RDP (Windows only) protocols. You can install the QXLDOD graphical driver in the guest operating system to improve the functionality of SPICE. SPICE currently supports a maximum resolution of 2560x1600 pixels.

.Client Operating System SPICE Support

Supported QXLDOD drivers are available on {enterprise-linux} 7.2 and later, and Windows 10.

[NOTE]
====
SPICE may work with Windows 8 or 8.1 using QXLDOD drivers, but it is neither certified nor tested.
====
