[id='client-requirements_{context}']
= Client Requirements

// Included in:
// PPG
// Install
// Introduction_to_the_Administration_Portal
// Introduction_to_the_VM_Portal

Virtual machine consoles can only be accessed using supported Remote Viewer (`virt-viewer`) clients on {enterprise-linux} and Windows. To install `virt-viewer`, see link:{URL_virt_product_docs}vmm-guide/Virtual_Machine_Management_Guide.html[Installing Supporting Components on Client Machines] in the _Virtual Machine Management Guide_. Installing `virt-viewer` requires Administrator privileges.

Virtual machine consoles are accessed through the SPICE, VNC, or RDP (Windows only) protocols. The QXL graphical driver can be installed in the guest operating system for improved/enhanced SPICE functionalities. SPICE currently supports a maximum resolution of 2560x1600 pixels.

Supported QXL drivers are available on {enterprise-linux}, Windows XP, and Windows 7.

SPICE support is divided into tiers:

* Tier 1: Operating systems on which Remote Viewer has been fully tested and is supported.

* Tier 2: Operating systems on which Remote Viewer is partially tested and is likely to work. Limited support is provided for this tier. Red Hat Engineering will attempt to fix issues with remote-viewer on this tier.

.Client Operating System SPICE Support
[options="header"]
|====
|Support Tier |Operating System
|Tier 1 |{enterprise-linux} 7.2 and later
| |Microsoft Windows 7
|Tier 2 |Microsoft Windows 8
| |Microsoft Windows 10
|====
