:_content-type: PROCEDURE
[id="Allowing_Read_Only_Access_to_the_History_Database"]
= Allowing Read-Only Access to the History Database

To allow access to the history database without allowing edits, you must create a read-only PostgreSQL user that can log in to and read from the `ovirt_engine_history` database. This procedure must be executed on the system on which the history database is installed.


*Allowing Read-Only Access to the History Database*

. Log in as root to the postgres user shell:
+
[source,terminal]
----
# su - postgres
----

. Create the user to be granted read-only access to the history database:
+
[source,terminal]
----
# psql -U postgres -c "CREATE ROLE _username_ WITH LOGIN ENCRYPTED PASSWORD '_password_';" -d ovirt_engine_history
----

. Grant the newly created user permission to connect to the history database:
+
[source,terminal]
----
# psql -U postgres -c "GRANT CONNECT ON DATABASE ovirt_engine_history TO _username_;"
----

. Grant the newly created user usage of the `public` schema:
+
[source,terminal]
----
# psql -U postgres -c "GRANT USAGE ON SCHEMA public TO _username_;" ovirt_engine_history
----

. Generate the rest of the permissions that will be granted to the newly created user and save them to a file:
+
[source,terminal]
----
# psql -U postgres -c "SELECT 'GRANT SELECT ON ' || relname || ' TO _username_;' FROM pg_class JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace WHERE nspname = 'public' AND relkind IN ('r', 'v');" --pset=tuples_only=on  ovirt_engine_history > grant.sql
----

. Use the file you created in the previous step to grant permissions to the newly created user:
+
[source,terminal]
----
# psql -U postgres -f grant.sql ovirt_engine_history
----

. Remove the file you used to grant permissions to the newly created user:
+
[source,terminal]
----
# rm grant.sql
----

. Exit the postgres user shell by pressing kbd:[Ctrl+d].

. Add the following lines for the newly created user to `/var/lib/pgsql/data/pg_hba.conf` preceding the line beginning `local all all`:
+
[source,terminal]
----
# TYPE  DATABASE                USER           ADDRESS                 METHOD
host    ovirt_engine_history    _username_    0.0.0.0/0               md5
host    ovirt_engine_history    _username_    ::0/0                   md5
local   all             all                                     peer
----

. Reload the PostgreSQL service:
+
[source,terminal]
----
# systemctl reload postgresql
----

.  To test the read-only user's access permissions:
+
[options="nowrap" ]
----
# su - postgres -c 'psql -U username ovirt_engine_history -h localhost'
Password for user username:
psql (9.2.23)
Type "help" for help.

ovirt_engine_history=>
----

. To exit the `ovirt_engine_history` database, enter `\q`.

The read-only user's `SELECT` statements against tables and views in the `ovirt_engine_history` database succeed, while modifications fail.
