:_content-type: PROCEDURE
[id="Changing_the_Data_Warehouse_Sampling_Scale"]
= Changing the Data Warehouse Sampling Scale

Data Warehouse is required in {virt-product-fullname}. It can be installed and configured on the same machine as the {engine-name}, or on a separate machine with access to the {engine-name}. The default data retention settings may not be required for all setups, so `engine-setup` offers two data sampling scales: `Basic` and `Full`.

* `Full` uses the default values for the data retention settings listed in xref:Application_Settings_for_the_Data_Warehouse_service_in_ovirt-engine-dwhd_file[Application Settings for the Data Warehouse service] (recommended when Data Warehouse is installed on a remote host).

* `Basic` reduces the values of `DWH_TABLES_KEEP_HOURLY` to `720` and `DWH_TABLES_KEEP_DAILY` to `0`, easing the load on the {engine-name} machine. Use `Basic` when the {engine-name} and Data Warehouse are installed on the same machine.

The sampling scale is configured by `engine-setup` during installation:

[source,terminal,subs="normal"]
----
--== MISC CONFIGURATION ==--

Please choose Data Warehouse sampling scale:
(1) Basic
(2) Full
(1, 2)[1]:
----

You can change the sampling scale later by running `engine-setup` again with the `--reconfigure-dwh-scale` option.

*Changing the Data Warehouse Sampling Scale*

[options="nowrap" ]

----
# engine-setup --reconfigure-dwh-scale
[...]
Setup can automatically configure the firewall on this system.
Note: automatic configuration of the firewall may overwrite current settings.
Do you want Setup to configure the firewall? (Yes, No) [Yes]:
[...]
Perform full vacuum on the oVirt engine history
database ovirt_engine_history@localhost?
This operation may take a while depending on this setup health and the
configuration of the db vacuum process.
See https://www.postgresql.org/docs/12/static/sql-vacuum.html
(Yes, No) [No]:
[...]
Setup can backup the existing database. The time and space required for the database backup depend on its size. This process takes time, and in some cases (for instance, when the size is few GBs) may take several hours to complete.
If you choose to not back up the database, and Setup later fails for some reason, it will not be able to restore the database and all DWH data will be lost.
Would you like to backup the existing database before upgrading it? (Yes, No) [Yes]:
[...]
Please choose Data Warehouse sampling scale:
(1) Basic
(2) Full
(1, 2)[1]: 2
[...]
During execution engine service will be stopped (OK, Cancel) [OK]:
[...]
Please confirm installation settings (OK, Cancel) [OK]:
----

You can also adjust individual data retention settings if necessary, as documented in xref:Application_Settings_for_the_Data_Warehouse_service_in_ovirt-engine-dwhd_file[Application Settings for the Data Warehouse service].
