==== Enabling Debug Mode

You can enable debug mode to record log sampling, hourly, and daily job times in the */var/log/ovirt-engine-dwh/ovirt-engine-dwhd.log* file. This is useful for checking the ETL process. Debug mode is disabled by default.

. Log in to the {engine-name} machine and create a configuration file (for example, */etc/ovirt-engine-dwh/ovirt-engine-dwhd.conf.d/logging.conf*).
. Add the following line to the configuration file:
+
[options="nowrap" subs="normal"]
----
DWH_AGGREGATION_DEBUG=true
----

. Restart the *ovirt-engine-dwhd* service:
+
[options="nowrap" subs="normal"]
----
# systemctl restart ovirt-engine-dwhd.service
----

 To disable debug mode, delete the configuration file and restart the service.

[NOTE]
====
The move to daylight savings time/summer time in different time zones can cause the events log to report that the _ETL service aggregation to hourly tables has encountered an error_.
If all the records are in the hourly aggregation views, there is no issue and this warning can be ignored.
If this warning continues to appear, contact your system administrator
ifdef::rhv-doc[]
 or the the Red Hat Support Team
endif::[]
.
====
