:_content-type: ASSEMBLY
[id="Adding_OVN_as_an_External_Network_Provider"]
= Adding Open Virtual Network (OVN) as an External Network Provider

You can use Open Virtual Network (OVN) to create overlay virtual networks that enable communication among the virtual machines without adding VLANs or changing the infrastructure. OVN is an extension of Open vSwitch (OVS) that provides native support for virtual L2 and L3 overlays.

You can also connect an OVN network to a native {virt-product-fullname} network. See xref:Connecting_an_OVN_Network_to_a_Physical_Network[Connecting an OVN Network to a Physical Network] for more information.
ifdef::rhv-doc[This feature is available as a Technology Preview only.]


The `ovirt-provider-ovn` exposes an OpenStack Networking REST API. You can use this API to create networks, subnets, ports, and routers. For details, see link:https://developer.openstack.org/api-ref/network/v2/[_OpenStack Networking API v2.0_].

For more details, see the link:http://docs.openvswitch.org/en/latest/[Open vSwitch Documentation] and link:http://openvswitch.org/support/dist-docs/[Open vSwitch Manpages].

include::Installing_a_new_OVN_network_provider.adoc[leveloffset=+1]

include::Configuring_Hosts_for_an_OVN_tunnel_network.adoc[leveloffset=+1]

include::Connecting_an_OVN_Network_to_a_Physical_Network.adoc[leveloffset=+1]
