:_content-type: PROCEDURE
[id="Adding_an_External_Network_Provider"]
= Adding an External Network Provider

Any network provider that implements the OpenStack Networking REST API can be added to {virt-product-fullname}. The virtual interface driver needs to be provided by the implementer of the external network provider.

.Procedure

. Click menu:Administration[Providers].
. Click *Add* and enter the details in the *General Settings* tab. For more information on these fields, see xref:Add_Provider_General_Settings_Explained[Add Provider General Settings Explained].

. Enter a *Name* and *Description*.
. Select *External Network Provider* from the *Type* drop-down list.
. Optionally, click the *Networking Plugin* text box and select the appropriate driver from the drop-down menu.
. Optionally, select the *Automatic Synchronization* check box. This enables automatic synchronization of the external network provider with existing networks. This feature is disabled by default when adding external network providers.
+
[NOTE]
====
Automatic synchronization is enabled by default on the *ovirt-provider-ovn* network provider created by the *engine-setup* tool.
====

. Enter the URL or fully qualified domain name of the machine on which the external network provider is installed in the *Provider URL* text field, followed by the port number. The *Read-Only* check box is selected by default. This prevents users from modifying the external network provider.
+
[IMPORTANT]
====
You must leave the *Read-Only* check box selected for your setup to be supported by Red Hat.
====
+

. Optionally, select the *Requires Authentication* check box and enter the *Username* and *Password* for the external network provider user registered in Keystone.
You must also define the authentication URL of the Keystone server by defining the *Protocol*, *Hostname*, and *API Port*.
+
Optionally, enter the *Tenant* for the external network provider.



. Test the credentials:
.. Click *Test* to test whether you can authenticate successfully with the external network provider using the provided credentials.
.. If the external network provider uses SSL, the *Import provider certificates* window opens; click btn:[OK] to import the certificate that the external network provider provides to ensure the {engine-name} can communicate with the instance.
. Click btn:[OK].

Before you can use networks from this provider, you must install the virtual interface driver on the hosts and import the networks. To import networks, see xref:Importing_Networks[Importing Networks].
