:_content-type: PROCEDURE
[id="Assigning_Additional_IPv4_Addresses_to_a_Host_Network_{context}"]
==== Assigning Additional IPv4 Addresses to a Host Network

A host network, such as the *ovirtmgmt* management network, is created with only one IP address when initially set up. This means that if a NIC's configuration file is configured with multiple IP addresses, only the first listed IP address will be assigned to the host network. Additional IP addresses may be required if connecting to storage, or to a server on a separate private subnet using the same NIC.

The `vdsm-hook-extra-ipv4-addrs` hook allows you to configure additional IPv4 addresses for host networks. For more information about hooks, see xref:appe-VDSM_and_Hooks[].

In the following procedure, the host-specific tasks must be performed on each host for which you want to configure additional IP addresses.


*Assigning Additional IPv4 Addresses to a Host Network*

. On the host that you want to configure additional IPv4 addresses for, install the VDSM hook package. The package is available by default on {hypervisor-fullname}s but needs to be installed on {enterprise-linux-host-fullname}s.
+
[source,terminal]
----
# dnf install vdsm-hook-extra-ipv4-addrs
----
+
. On the {engine-name}, run the following command to add the key:
+
[source,terminal]
----
# engine-config -s 'UserDefinedNetworkCustomProperties=ipv4_addrs=.*'
----
+
. Restart the `ovirt-engine` service:
+
[source,terminal]
----
# systemctl restart ovirt-engine.service
----
+
. In the Administration Portal, click menu:Compute[Hosts].
. Click the host's name. This opens the details view.
. Click the *Network Interfaces* tab and click *Setup Host Networks*.
. Edit the host network interface by hovering the cursor over the assigned logical network and clicking the pencil icon.
. Select *ipv4_addr* from the *Custom Properties* drop-down list and add the additional IP address and prefix (for example 5.5.5.5/24). Multiple IP addresses must be comma-separated.
. Click btn:[OK] to close the *Edit Network* window.
. Click btn:[OK] to close the *Setup Host Networks* window.


The additional IP addresses will not be displayed in the {engine-name}, but you can run the command `ip addr show` on the host to confirm that they have been added.
