:_content-type: PROCEDURE
[id="Assigning_Security_Groups_to_VNIC_Profiles"]
= Assigning Security Groups to vNIC Profiles


[NOTE]
====
This feature is only available when `ovirt-provider-ovn` is added as an external network provider. Security groups cannot be created through the {virt-product-fullname} {engine-name}. You must create security groups through OpenStack Networking on the `ovirt-provider-ovn`. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/10/html-single/users_and_identity_management_guide/index#project-security[Project Security Management] in the _Red Hat OpenStack Platform Users and Identity Management Guide_.
====

You can assign security groups to the vNIC profile of networks that have been imported from an OpenStack Networking instance and that use the Open vSwitch plug-in. A security group is a collection of strictly enforced rules that allow you to filter inbound and outbound traffic over a network interface. The following procedure outlines how to attach a security group to a vNIC profile.

[NOTE]
====
A security group is identified using the ID of that security group as registered in the Open Virtual Network (OVN) External Network Provider. You can find the IDs of security groups for a given tenant using the OpenStack Networking API, see link:https://docs.openstack.org/api-ref/network/v2/index.html?expanded=#list-security-groups[List Security Groups] in the _OpenStack API Reference_.

====


.Procedure

. Click menu:Network[Networks].
. Click the logical network's name. This opens the details view.
. Click the *vNIC Profiles* tab.
. Click *New*, or select an existing vNIC profile and click *Edit*.
. From the custom properties drop-down list, select *SecurityGroups*. Leaving the custom property drop-down blank applies the default security settings, which permit all outbound traffic and intercommunication but deny all inbound traffic from outside of the default security group. Note that removing the *SecurityGroups* property later will not affect the applied security group.
. In the text field, enter the ID of the security group to attach to the vNIC profile.
. Click btn:[OK].


You have attached a security group to the vNIC profile. All traffic through the logical network to which that profile is attached will be filtered in accordance with the rules defined for that security group.
