:_content-type: PROCEDURE
[id="Attaching_an_export_domain"]
= Attaching an Existing Export Domain to a Data Center

[NOTE]
====
The export storage domain is deprecated. Storage data domains can be unattached from a data center and imported to another data center in the same environment, or in a different environment. Virtual machines, floating virtual disks, and templates can then be uploaded from the imported storage domain to the attached data center. See xref:sect-Importing_Existing_Storage_Domains[Importing Existing Storage Domains] for information on importing storage domains.
====

An export domain that is *Unattached* can be attached to a data center. Only one export domain can be attached to a data center.

.Procedure

. Click menu:Compute[Data Centers].
. Click a data center's name. This opens the details view.
. Click the *Storage* tab to list the storage domains already attached to the data center.
. Click *Attach Export*.
. Click the radio button for the appropriate export domain.
. Click btn:[OK].

The export domain is attached to the data center and is automatically activated.
