[id="Cluster_Scheduling_Policy_Settings"]
==== Scheduling Policy Settings Explained

Scheduling policies allow you to specify the usage and distribution of virtual machines between available hosts. Define the scheduling policy to enable automatic load balancing across the hosts in a cluster. Regardless of the scheduling policy, a virtual machine will not start on a host with an overloaded CPU. By default, a host's CPU is considered overloaded if it has a load of more than 80% for 5 minutes, but these values can be changed using scheduling policies. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-Scheduling_Policies[Scheduling Policies] in the _Administration Guide_ for more information.

[id="Cluster-General"]
.Scheduling Policy Tab Properties
[cols="1,3", options="header"]
|===
|Field |Description/Action
|*Select Policy* a|Select a policy from the drop-down list.

* *none*: Disables load-balancing or power-sharing between hosts for already-running virtual machines. This is the default mode. When a virtual machine is started, the memory and CPU processing load is spread evenly across all hosts in the cluster. Additional virtual machines attached to a host will not start if that host has reached the defined *CpuOverCommitDurationMinutes*, *HighUtilization*, or *MaxFreeMemoryForOverUtilized*.

* *evenly_distributed*: Distributes the memory and CPU processing load evenly across all hosts in the cluster. Additional virtual machines attached to a host will not start if that host has reached the defined *CpuOverCommitDurationMinutes*, *HighUtilization*, or *MaxFreeMemoryForOverUtilized*.

* *cluster_maintenance*: Limits activity in a cluster during maintenance tasks. No new virtual machines may be started, except highly available virtual machines. If host failure occurs, highly available virtual machines will restart properly and any virtual machine can migrate.

* *power_saving*: Distributes the memory and CPU processing load across a subset of available hosts to reduce power consumption on underutilized hosts. Hosts with a CPU load below the low utilization value for longer than the defined time interval will migrate all virtual machines to other hosts so that it can be powered down. Additional virtual machines attached to a host will not start if that host has reached the defined high utilization value.

* *vm_evenly_distributed*: Distributes virtual machines evenly between hosts based on a count of the virtual machines. The cluster is considered unbalanced if any host is running more virtual machines than the *HighVmCount* and there is at least one host with a virtual machine count that falls outside of the *MigrationThreshold*.

|*Properties* a|The following properties appear depending on the selected policy. Edit them if necessary:

* *HighVmCount*: Sets the minimum number of virtual machines that must be running per host to enable load balancing. The default value is 10 running virtual machines on one host. Load balancing is only enabled when there is at least one host in the cluster that has at least `HighVmCount` running virtual machines.

* *MigrationThreshold*: Defines a buffer before virtual machines are migrated from the host. It is the maximum inclusive difference in virtual machine count between the most highly-utilized host and the least-utilized host. The cluster is balanced when every host in the cluster has a virtual machine count that falls inside the migration threshold. The default value is *5*.

* *SpmVmGrace*: Defines the number of slots for virtual machines to be reserved on SPM hosts. The SPM host will have a lower load than other hosts, so this variable defines how many fewer virtual machines the SPM host can run in comparison to other hosts. The default value is *5*.

* *CpuOverCommitDurationMinutes*: Sets the time (in minutes) that a host can run a CPU load outside of the defined utilization values before the scheduling policy takes action. The defined time interval protects against temporary spikes in CPU load activating scheduling policies and instigating unnecessary virtual machine migration. Maximum two characters. The default value is *2*.

* *HighUtilization*: Expressed as a percentage. If the host runs with CPU usage at or above the high utilization value for the defined time interval, the {virt-product-fullname} {engine-name} migrates virtual machines to other hosts in the cluster until the host's CPU load is below the maximum service threshold. The default value is *80*.

* *LowUtilization*: Expressed as a percentage. If the host runs with CPU usage below the low utilization value for the defined time interval, the {virt-product-fullname} {engine-name} will migrate virtual machines to other hosts in the cluster. The {engine-name} will power down the original host machine, and restart it again when load balancing requires or there are not enough free hosts in the cluster. The default value is *20*.

* *ScaleDown*: Reduces the impact of the *HA Reservation* weight function, by dividing a host's score by the specified amount. This is an optional property that can be added to any policy, including *none*.

* *HostsInReserve*: Specifies a number of hosts to keep running even though there are no running virtual machines on them. This is an optional property that can be added to the *power_saving* policy.

* *EnableAutomaticHostPowerManagement*: Enables automatic power management for all hosts in the cluster. This is an optional property that can be added to the *power_saving* policy. The default value is *true*.

* *MaxFreeMemoryForOverUtilized*: Specifies the minimum amount of free memory a host should have, in MB. If a host has less free memory than this amount, the {virt-product-shortname} {engine-name} considers the host overutilized. For example, if you set this property to `1000`, a host that has less than 1 GB of free memory is overutilized.
+
For details on how this property interacts with the *power_saving* and *evenly_distributed* policies, see xref:conc_maxfreememoryforoverutilized_and_minfreememoryforunderutilized_scheduling_policy_properties[].
+
You can add this property to the *power_saving* and *evenly_distributed* policies. Although it appears among the list of properties for the *vm_evenly_distributed* policy, it does not apply to that policy.

* *MinFreeMemoryForUnderUtilized*: Specifies the maximum amount of free memory a host should have, in MB. If a host has more free memory than this amount, the {virt-product-shortname} {engine-name} scheduler considers the host underutilized. For example, if you set this parameter to `10000`, a host that has more than 10 GB of free memory is underutilized.
+
For details on how this property interacts with the *power_saving* and *evenly_distributed* policies, see xref:conc_maxfreememoryforoverutilized_and_minfreememoryforunderutilized_scheduling_policy_properties[].
+
You can add this property to the *power_saving* and *evenly_distributed* policies. Although it appears among the list of properties for the *vm_evenly_distributed* policy, it does not apply to that policy.

* *HeSparesCount*: Sets the number of additional self-hosted engine nodes that must reserve enough free memory to start the {engine-name} virtual machine if it migrates or shuts down. Other virtual machines are prevented from starting on a self-hosted engine node if doing so would not leave enough free memory for the {engine-name} virtual machine. This is an optional property that can be added to the *power_saving*, *vm_evenly_distributed*, and *evenly_distributed* policies. The default value is *0*.

|*Scheduler Optimization* a|Optimize scheduling for host weighing/ordering.

* *Optimize for Utilization*: Includes weight modules in scheduling to allow best selection.

* *Optimize for Speed*: Skips host weighting in cases where there are more than ten pending requests.

|*Enable Trusted Service* |Enable integration with an OpenAttestation server. Before this can be enabled, use the `engine-config` tool to enter the OpenAttestation server's details. *IMPORTANT*: OpenAttestation and Intel Trusted Execution Technology (Intel TXT) are no longer available.
|*Enable HA Reservation* |Enable the {engine-name} to monitor cluster capacity for highly available virtual machines. The {engine-name} ensures that appropriate capacity exists within a cluster for virtual machines designated as highly available to migrate in the event that their existing host fails unexpectedly.
|*Serial Number Policy* a|Configure the policy for assigning serial numbers to each new virtual machine in the cluster:

* *System Default*: Use the system-wide defaults in the {engine-name} database. To configure these defaults, link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-the_engine_configuration_tool[use the engine configuration tool] to set the values of the `DefaultSerialNumberPolicy` and `DefaultCustomSerialNumber`. These key-value pairs are saved in the `vdc_options` table of the {engine-name} database.
+
For `DefaultSerialNumberPolicy`:
+
  - Default value: `HOST_ID`
  - Possible values: `HOST_ID`, `VM_ID`, `CUSTOM`
  - Command line example: `engine-config --set DefaultSerialNumberPolicy=VM_ID`
  - Important: Restart the {engine-name} to apply the configuration.
+
For `DefaultCustomSerialNumber`:
+
  - Default value: Dummy serial number
  - Possible values: Any string (max length 255 characters)
  - Command line example: `engine-config --set DefaultCustomSerialNumber="My very special string value"`
  - Important: Restart the {engine-name} to apply the configuration.

* *Host ID*: Set each new virtual machine's serial number to the UUID of the host.

* *Vm ID*: Set each new virtual machine's serial number to the UUID of the virtual machine.

* *Custom serial number*: Set each new virtual machine's serial number to the value you specify in the following *Custom Serial Number* parameter.


|*Custom Serial Number* |Specify the custom serial number to apply to new virtual machines in the cluster.


|===

When a host's free memory drops below 20%, ballooning commands like `mom.Controllers.Balloon - INFO Ballooning guest:half1 from 1096400 to 1991580` are logged to */var/log/vdsm/mom.log*. */var/log/vdsm/mom.log* is the Memory Overcommit Manager log file.
