// This assembly is included in the following assemblies:
//
// doc-Administration_Guide/chap-Logical_Networks.adoc

:_content-type: CONCEPT
[id="con-Network-Manager-Stateful-Configuration-nmstate"]
= Network Manager Stateful Configuration (nmstate)
:context: nmstate

Version 4.4 of {virt-product-fullname} ({virt-product-shortname}) uses _Network Manager Stateful Configuration (nmstate)_ to configure networking for {virt-product-shortname} hosts that are based on {enterprise-linux-shortname} 8. {virt-product-shortname} version 4.3 and earlier use interface configuration (ifcfg) network scripts to manage host networking.

To use nmstate, upgrade the {virt-product-fullname} {engine-name} and hosts as described in the link:{URL_virt_product_docs}{URL_format}upgrade_guide/index#[{virt-product-shortname} Upgrade Guide].

As an administrator, you do not need to install or configure nmstate. It is enabled by default and runs in the background.

IMPORTANT: Always use {virt-product-shortname} {engine-name} to modify the network configuration of hosts in your clusters. Otherwise, you might create an unsupported configuration.

The change to nmstate is nearly transparent. It only changes how you configure host networking in the following ways:

* After you add a host to a cluster, always use the {virt-product-shortname} {engine-name} to modify the host network.
* Modifying the host network without using the {engine-name} can create an unsupported configuration.
* To fix an unsupported configuration, you replace it with a supported one by using the {engine-name} to synchronize the host network. For details, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Synchronizing_host_networks[Synchronizing Host Networks].
* The only situation where you modify host networks outside the {engine-name} is to configure a static route on a host. For more details, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#proc-Adding-a-static-route-on-a-host[Adding a static route on a host].


The change to nmstate improves how {virt-product-shortname} {engine-name} applies configuration changes you make in Cockpit and Anaconda before adding the host to the {engine-name}. This fixes some issues, such as link:https://bugzilla.redhat.com/show_bug.cgi?id=1680970[BZ#1680970 Static IPv6 Address is lost on host deploy if NM manages the interface].

[IMPORTANT]
====
If you use `dnf` or `yum` to manually update the `nmstate` package, restart `vdsmd` and `supervdsmd` on the host. For example:
----
# dnf update nmstate
# systemctl restart vdsmd supervdsmd
----
====
[IMPORTANT]
====
If you use `dnf` or `yum` to manually update the Network Manager package, restart `NetworkManager` on the host. For example:
----
# dnf update NetworkManager
# systemctl restart NetworkManager
----
====
