[id="Configuring_the_Red_Hat_Enterprise_Virtualization_Manager_to_Send_SNMP_Traps"]
= Configuring the {virt-product-fullname} {engine-name} to Send SNMP Traps

Configure your {virt-product-fullname} {engine-name} to send Simple Network Management Protocol (SNMP) traps to one or more external SNMP managers. SNMP traps contain system event information; they are used to monitor your {virt-product-fullname} environment. The number and type of traps sent to the SNMP manager can be defined within the {virt-product-fullname} {engine-name}.

{virt-product-fullname} supports SNMP version 2 and version 3. SNMP version 3 supports the following security levels:

*NoAuthNoPriv*:: SNMP traps are sent without any authorization or privacy.
*AuthNoPriv*:: SNMP traps are sent with password authorization but no privacy.
*AuthPriv*:: SNMP traps are sent with password authorization and privacy.

.Prerequisites

* One or more external SNMP managers are configured to receive traps.

* The IP addresses or fully qualified domain names of machines that will act as SNMP managers. Optionally, determine the port through which {engine-name} receives trap notifications. The default is UDP port 162.

* The SNMP community (SNMP version 2 only). Multiple SNMP managers can belong to a single community. Management systems and agents can communicate only if they are within the same community. The default community is `public`.

* The trap object identifier for alerts. The {virt-product-fullname} {engine-name} provides a default OID of 1.3.6.1.4.1.2312.13.1.1. All trap types are sent, appended with event information, to the SNMP manager when this OID is defined. Note that changing the default trap prevents generated traps from complying with the {engine-name}'s management information base.

* An SNMP username, for SNMP version 3, security levels 1, 2, and 3.

* An SNMP passphrase, for SNMP version 3, security levels 2 and 3.

* An SNMP private passphrase, for SNMP version 3, security level 3.

[NOTE]
====
The {virt-product-fullname} {engine-name} provides management information bases at `/usr/share/doc/ovirt-engine/mibs/OVIRT-MIB.txt` and `/usr/share/doc/ovirt-engine/mibs/REDHAT-MIB.txt`. Load the MIBs in your SNMP manager before proceeding.
====

Default SNMP configuration values exist on the {engine-name} in the events notification daemon configuration file `/usr/share/ovirt-engine/services/ovirt-engine-notifier/ovirt-engine-notifier.conf`. The values outlined in the following procedure are based on the default or example values provided in this file. Do not edit this file directly, because system changes, such as upgrades, might remove any changes you make to this file. Instead, copy this file to `/etc/ovirt-engine/notifier/notifier.conf.d/<__integer__>-snmp.conf`, where `<__integer__>` is a number indicating the priority with which the file should run.

.Procedure

. On the {engine-name}, create the SNMP configuration file with the file name `<__integer__>-snmp.conf`, where `<__integer__>` is an integer that indicates the order in which files are processed. For example:
+
[options="nowrap" subs="normal"]
----
# vi /etc/ovirt-engine/notifier/notifier.conf.d/20-snmp.conf
----
+
[TIP]
====
Copy the default SNMP settings from the events notification daemon configuration file `/usr/share/ovirt-engine/services/ovirt-engine-notifier/ovirt-engine-notifier.conf`. This file includes inline comments for all settings.
====

. Specify the SNMP manager(s), the SNMP community (SNMP version 2 only), and the OID in the format in this example:
+
[options="nowrap" subs="normal"]
----
SNMP_MANAGERS="_manager1.example.com_ _manager2.example.com:162_"
SNMP_COMMUNITY=public
SNMP_OID=1.3.6.1.4.1.2312.13.1.1

----

. Define whether to use SNMP version 2 (default) or 3:
+
[options="nowrap" subs="normal"]
----
SNMP_VERSION=3
----

. Specify a value for SNMP_ENGINE_ID. For example:
+
[options="nowrap" subs="normal"]
----
SNMP_ENGINE_ID="80:00:00:00:01:02:05:05"
----

. With SNMP version 3, specify the security level for SNMP traps:
+
Security level 1, NoAuthNoPriv traps:
+
[options="nowrap" subs="normal"]
----
SNMP_USERNAME=NoAuthNoPriv
SNMP_SECURITY_LEVEL=1
----
+
Security level 2, AuthNoPriv traps, as user `ovirtengine`, with SNMP Auth passphrase `authpass`.
+
[options="nowrap" subs="normal"]
----
SNMP_USERNAME=ovirtengine
SNMP_AUTH_PROTOCOL=MD5
SNMP_AUTH_PASSPHRASE=authpass
SNMP_SECURITY_LEVEL=2
----
+
Security level 3, AuthPriv traps, as user `ovirtengine` with SNMP Auth passphrase `authpass` and SNMP Priv passphrase `privpass`. For example:
+
[options="nowrap" subs="normal"]
----
SNMP_USERNAME=ovirtengine
SNMP_AUTH_PROTOCOL=MD5
SNMP_AUTH_PASSPHRASE=authpass
SNMP_PRIVACY_PROTOCOL=AES128
SNMP_PRIVACY_PASSPHRASE=privpass
SNMP_SECURITY_LEVEL=3
----

. Define which events to send to the SNMP manager:
+
.Event examples
====
Send all events to the default SNMP profile:

[options="nowrap" subs="normal"]
----
FILTER="include:*(snmp:) ${FILTER}"
----
Send all events with the severity `ERROR` or `ALERT` to the default SNMP profile:

[options="nowrap" subs="normal"]
----
FILTER="include:*:ERROR(snmp:) ${FILTER}"
----

[options="nowrap" subs="normal"]
----
FILTER="include:*:ALERT(snmp:) ${FILTER}"
----
Send events for _VDC_START_ to the specified email address:

[options="nowrap" subs="normal"]
----
FILTER="include:__VDC_START__(snmp:__mail@example.com__) ${FILTER}"
----
Send events for everything but _VDC_START_ to the default SNMP profile:

[options="nowrap" subs="normal"]
----
FILTER="exclude:__VDC_START__ include:*(snmp:) ${FILTER}"
----
This the default filter defined in `ovirt-engine-notifier.conf`; if you do not disable this filter or apply overriding filters, no notifications will be sent:

[options="nowrap" subs="normal"]
----
FILTER="exclude:*"
----
====
+
`VDC_START` is an example of the audit log messages available. A full list of audit log messages can be found in `/usr/share/doc/ovirt-engine/AuditLogMessages.properties`. Alternatively, filter results within your SNMP manager.

. Save the file.

. Start the `ovirt-engine-notifier` service, and ensure that this service starts on boot:
+
[options="nowrap" subs="normal"]
----
# systemctl start ovirt-engine-notifier.service
# systemctl enable ovirt-engine-notifier.service
----


Check your SNMP manager to ensure that traps are being received.

[NOTE]
====
`SNMP_MANAGERS`, `MAIL_SERVER`, or both must be properly defined in `/usr/share/ovirt-engine/services/ovirt-engine-notifier/ovirt-engine-notifier.conf` or in an override file in order for the notifier service to run.
====

.Additional resources

* xref:SNMPv3-traps-configuration-file[Sample SNMP version 3 configuration file]
