<<<<<<< HEAD
:_content-type: PROCEDURE
[id="Configuring_Hosts_for_an_OVN_tunnel_network"]
= Configuring Hosts for an OVN Tunnel Network

You can configure your hosts to use an existing network, other than the default `ovirtmgmt` network, with the `ovirt-provider-ovn-driver` Ansible playbook. The network must be accessible to all the hosts in the cluster.

[NOTE]
====
The `ovirt-provider-ovn-driver` Ansible playbook updates existing hosts. If you add new hosts to the cluster, you must run the playbook again.
====

.Procedure

. On the {engine-name} machine, go to the *playbooks* directory:
+
[source,terminal]
=======
[[Configuring_Hosts_for_an_OVN_tunnel_network]]
===== Updating the OVN Tunnel Network on a Single Host

You can update the OVN tunnel network on a single host with `vdsm-tool`:

[options="nowrap" subs="normal"]
>>>>>>> c42c3d5f0d... BZ2006228 - Updates for OVN/OVS upgrade to the Admin Guide
----
# vdsm-tool ovn-config OVN_Central_IP Tunneling_IP_or_Network_Name Host_FQDN
----

[NOTE]
====
The Host_FQDN must match FQDN that is specified in engine for this host.
====

<<<<<<< HEAD
*Updating the OVN Tunnel Network on a Single Host*

You can update the OVN tunnel network on a single host with `vdsm-tool`:

[source,terminal]
----
# vdsm-tool ovn-config _OVN_Central_IP_ _Tunneling_IP_or_Network_Name_
----

=======
>>>>>>> c42c3d5f0d... BZ2006228 - Updates for OVN/OVS upgrade to the Admin Guide
.Updating a Host with `vdsm-tool`
====

[source,terminal]
----
# vdsm-tool ovn-config 192.168.0.1 MyNetwork MyFQDN
----

====
