[id="Configure_grafana"]


.Installation

Grafana integration is enabled and installed by default when running {virt-product-fullname} {engine-name} `engine-setup` for Stand Alone Manager installations. For Self-Hosted engine installations, you must enable Grafana integration manually when running `engine-setup`.

To enable Grafana integration in the Self-Hosted engine:

. Put the environment in global maintenance mode:
+
[options="nowrap" subs="normal"]
----
# hosted-engine --set-maintenance --mode=global
----
. Log in to the machine where you want to install Grafana.
. Run the `engine-setup` command as follows:
+
----
# engine-setup --reconfigure-optional-components
----
+
. Answer `Yes` to install Grafana on this machine:
+
----
Configure Grafana on this host (Yes, No) [Yes]:
----
. Disable global maintenance mode:
+
[options="nowrap" subs="normal"]
----
# hosted-engine --set-maintenance --mode=none
----

To access the Grafana dashboards:

* Go to `\https://<engine FQDN or IP address>/ovirt-engine-grafana`

or

* Click *Monitoring Portal* in the web administration welcome page for the *Administration Portal*.

include::Configure_grafana_SSO.adoc[leveloffset=+1]
