[[Configuring_event_notifications]]
=== Configuring Event Notifications in the Administration Portal

The {virt-product-fullname} {engine-name} can notify designated users via email when specific events occur in the environment that the {virt-product-fullname} {engine-name} manages. To use this functionality, you must set up a mail transfer agent to deliver messages. Only email notifications can be configured through the Administration Portal. SNMP traps must be configured on the {engine-name} machine.


*Configuring Event Notifications*

. Ensure that you have access to an email server that can accept automated messages from {engine-name} and deliver them to a distribution list.
. Click menu:Administration[Users] and select a user.
. Click the user's *User Name* to go to the details page.
. In the *Event Notifier* tab, click *Manage Events*.
. Use the *Expand All* button or the subject-specific expansion buttons to view the events.
. Select the appropriate check boxes.
. Enter an email address in the *Mail Recipient* field.
+
[NOTE]
====
The email address can be a text message email address (for example, `_1234567890@carrierdomainname.com_`) or an email group address that includes email addresses and text message email addresses.
====

. Click btn:[OK].
. On the {engine-name} machine, copy `ovirt-engine-notifier.conf` to a new file called `90-email-notify.conf`:
+
[source,terminal]
----
# cp /usr/share/ovirt-engine/services/ovirt-engine-notifier/ovirt-engine-notifier.conf /etc/ovirt-engine/notifier/notifier.conf.d/90-email-notify.conf
----

. Edit `90-email-notify.conf`, deleting everything except the `EMAIL Notifications` section.

. Enter the correct email variables, as in the example below. This file overrides the values in the original `ovirt-engine-notifier.conf` file.
+
[options="nowrap" ]
----
#---------------------#
# EMAIL Notifications #
#---------------------#

# The SMTP mail server address. Required.
MAIL_SERVER=myemailserver.example.com

# The SMTP port (usually 25 for plain SMTP, 465 for SMTP with SSL, 587 for SMTP with TLS)
MAIL_PORT=25

# Required if SSL or TLS enabled to authenticate the user. Used also to specify 'from' user address if mail server
# supports, when MAIL_FROM is not set. Address is in RFC822 format
MAIL_USER=

# Required to authenticate the user if mail server requires authentication or if SSL or TLS is enabled
SENSITIVE_KEYS="${SENSITIVE_KEYS},MAIL_PASSWORD"
MAIL_PASSWORD=

# Indicates type of encryption (none, ssl or tls) should be used to communicate with mail server.
MAIL_SMTP_ENCRYPTION=none

# If set to true, sends a message in HTML format.
HTML_MESSAGE_FORMAT=false

# Specifies 'from' address on sent mail in RFC822 format, if supported by mail server.
MAIL_FROM=rhevm2017@example.com

# Specifies 'reply-to' address on sent mail in RFC822 format.
MAIL_REPLY_TO=

# Interval to send smtp messages per # of IDLE_INTERVAL
MAIL_SEND_INTERVAL=1

# Amount of times to attempt sending an email before failing.
MAIL_RETRIES=4
----
+
[NOTE]
====
See `/etc/ovirt-engine/notifier/notifier.conf.d/README` for more options.
====

. Enable and restart the `ovirt-engine-notifier` service to activate the changes you have made:
+
[source,terminal]
----
# systemctl daemon-reload
# systemctl enable ovirt-engine-notifier.service
# systemctl restart ovirt-engine-notifier.service
----

The specified user now receives emails based on events in the {virt-product-fullname} environment. The selected events are displayed on the *Event Notifier* tab for that user.
