:_content-type: PROCEDURE
[id="Creating_a_Backup_with_the_engine-backup_Command"]
= Creating a backup with the engine-backup command

You can back up the {virt-product-fullname} {engine-name} with the [command]`engine-backup` command while the {engine-name} is active. Append one of the following values to the `--scope` option to specify what you want to back up:

`all`:: A full backup of all databases and configuration files on the {engine-name}. This is the default setting for the `--scope` option.

`files`:: A backup of only the files on the system

`db`:: A backup of only the {engine-name} database

`dwhdb`:: A backup of only the Data Warehouse database

`cinderlibdb`:: A backup of only the Cinderlib database

`grafanadb`:: A backup of only the Grafana database

You can specify the `--scope` option more than once.

You can also configure the [command]`engine-backup` command to back up additional files. It restores everything that it backs up.

[IMPORTANT]
====
To restore a database to a fresh installation of {virt-product-fullname} {engine-name}, a database backup alone is not sufficient. The {engine-name} also requires access to the configuration files. If you specify a scope other than `all`, you must also include `--scope=files`, or back up the file system.
====

For a complete explanation of the [command]`engine-backup` command, enter `engine-backup --help` on the {engine-name} machine.

.Procedure
. Log on to the {engine-name} machine.

. Create a backup:
+
[source,terminal,subs="normal"]
----
# engine-backup
----

The following settings are applied by default:

`--scope=all`

`--mode=backup`

The command generates the backup in `/var/lib/ovirt-engine-backup/_file_name_.backup`, and a log file in `/var/log/ovirt-engine-backup/_log_file_name_`.

Use `_file_name_.tar` to restore the environment.

The following examples demonstrate several different backup scenarios.

.Full backup
====

[source,terminal,subs="normal"]
----
# engine-backup
----

====

.{engine-name} database backup
====

[source,terminal,subs="normal"]
----
# engine-backup --scope=files --scope=db
----

====

.Data Warehouse database backup
====

[source,terminal,subs="normal"]
----
# engine-backup --scope=files --scope=dwhdb
----

====

.Adding specific files to the backup
====

. Make a directory to store configuration customizations for the [command]`engine-backup` command:
+
[source,terminal,subs="normal"]
----
# mkdir -p /etc/ovirt-engine-backup/engine-backup-config.d
----
. Create a text file in the new directory named `ntp-chrony.sh` with the following contents:
+
[source,terminal,subs="normal"]
----
BACKUP_PATHS="${BACKUP_PATHS}
/etc/chrony.conf
/etc/ntp.conf
/etc/ovirt-engine-backup"
----
. When you run the [command]`engine-backup` command, use `--scope=files`. The backup and restore includes `/etc/chrony.conf`, `/etc/ntp.conf`, and `/etc/ovirt-engine-backup`.

====
