[id="Creating_a_Storage_Quality_of_Service_Entry"]
==== Creating a Storage Quality of Service Entry

*Creating a Storage Quality of Service Entry*

. Click menu:Compute[Data Centers].
. Click a data center's name. This opens the details view.
. Click the *QoS* tab.
. Under *Storage*, click *New*.
. Enter a *QoS Name* and a *Description* for the quality of service entry.
. Specify the *Throughput* quality of service by clicking one of the radio buttons:
* *None*
* *Total* - Enter the maximum permitted total throughput in the *MB/s* field.
* *Read/Write* - Enter the maximum permitted throughput for read operations in the left *MB/s* field, and the maximum permitted throughput for write operations in the right *MB/s* field.
. Specify the input and output (*IOps*) quality of service by clicking one of the radio buttons:
* *None*
* *Total* - Enter the maximum permitted number of input and output operations per second in the *IOps* field.
* *Read/Write* - Enter the maximum permitted number of input operations per second in the left *IOps* field, and the maximum permitted number of output operations per second in the right *IOps* field.
. Click btn:[OK].

You have created a storage quality of service entry, and can create disk profiles based on that entry in data storage domains that belong to the data center.
