:_content-type: PROCEDURE
[id="Creating_a_Virtual_Disk"]
= Creating a Virtual Disk

*Image* disk creation is managed entirely by the {engine-name}. *Direct LUN* disks require externally prepared targets that already exist.

You can create a virtual disk that is attached to a specific virtual machine. Additional options are available when creating an attached virtual disk, as specified in xref:Explanation_of_Settings_in_the_New_Virtual_Disk_Window[Explanation of Settings in the New Virtual Disk Window].

*Creating a Virtual Disk Attached to a Virtual Machine*

. Click menu:Compute[Virtual Machines].
. Click the virtual machine's name. This opens the details view.
. Click the *Disks* tab.
. Click *New*.
. Click the appropriate button to specify whether the virtual disk will be an *Image* or *Direct LUN* disk.
. Select the options required for your virtual disk. The options change based on the disk type selected. See xref:Explanation_of_Settings_in_the_New_Virtual_Disk_Window[Explanation of Settings in the New Virtual Disk Window] for more details on each option for each disk type.
. Click btn:[OK].

You can also create a floating virtual disk that does not belong to any virtual machines. You can attach this disk to a single virtual machine, or to multiple virtual machines if the disk is shareable. Some options are not available when creating a virtual disk, as specified in xref:Explanation_of_Settings_in_the_New_Virtual_Disk_Window[Explanation of Settings in the New Virtual Disk Window].

*Creating a Floating Virtual Disk*

. Click menu:Storage[Disks].
. Click *New*.
. Click the appropriate button to specify whether the virtual disk will be an *Image* or *Direct LUN* disk.
. Select the options required for your virtual disk. The options change based on the disk type selected. See xref:Explanation_of_Settings_in_the_New_Virtual_Disk_Window[Explanation of Settings in the New Virtual Disk Window] for more details on each option for each disk type.
. Click btn:[OK].
