:_content-type: PROCEDURE
[id="Creating_a_Scheduling_Policy"]
==== Creating a Scheduling Policy

You can create new scheduling policies to control the logic by which virtual machines are distributed amongst a given cluster in your {virt-product-fullname} environment.


.Procedure

. Click menu:Administration[Configure].
. Click the *Scheduling Policies* tab.
. Click *New*.
. Enter a *Name* and *Description* for the scheduling policy.
. Configure filter modules:
.. In the *Filter Modules* section, drag and drop the preferred filter modules to apply to the scheduling policy from the *Disabled Filters* section into the *Enabled Filters* section.
.. Specific filter modules can also be set as the *First*, to be given highest priority, or *Last*, to be given lowest priority, for basic optimization. To set the priority, right-click any filter module, hover the cursor over *Position* and select *First* or *Last*.
. Configure weight modules:
.. In the *Weights Modules* section, drag and drop the preferred weights modules to apply to the scheduling policy from the *Disabled Weights* section into the *Enabled Weights &amp; Factors* section.
.. Use the *+* and *-* buttons to the left of the enabled weight modules to increase or decrease the weight of those modules.
. Specify a load balancing policy:
.. From the drop-down menu in the *Load Balancer* section, select the load balancing policy to apply to the scheduling policy.
.. From the drop-down menu in the *Properties* section, select a load balancing property to apply to the scheduling policy and use the text field to the right of that property to specify a value.
.. Use the *+* and *-* buttons to add or remove additional properties.
. Click btn:[OK].
