:_content-type: PROCEDURE
[id="Detaching_storage_domains_from_a_data_center"]
= Detaching a Storage Domain from a Data Center

Detaching a storage domain from a data center stops the data center from associating with that storage domain. The storage domain is not removed from the {virt-product-fullname} environment; it can be attached to another data center.

Data, such as virtual machines and templates, remains attached to the storage domain.

[NOTE]
====
The `master` storage, if it is the last available storage domain, cannot be removed.
====


.Procedure

. Click menu:Compute[Data Centers].
. Click a data center's name. This opens the details view.
. Click the *Storage* tab to list the storage domains attached to the data center.
. Select the storage domain to detach. If the storage domain is `Active`, click *Maintenance*.
. Click btn:[OK] to initiate maintenance mode.
. Click *Detach*.
. Click btn:[OK].

It can take up to several minutes for the storage domain to disappear from the details view.
