:_content-type: PROCEDURE
[id="Editing_Host_Network_Interfaces_and_Assigning_Logical_Networks_to_Hosts"]
= Editing Host Network Interfaces and Assigning Logical Networks to Hosts

You can change the settings of physical host network interfaces, move the management network from one physical host network interface to another, and assign logical networks to physical host network interfaces. Bridge and ethtool custom properties are also supported.

[WARNING]
====
The only way to change the IP address of a host in {virt-product-fullname} is to remove the host and then to add it again.

To change the VLAN settings of a host, see xref:Editing-VLAN-Settings[Editing VLAN Settings].
====

[IMPORTANT]
====
You cannot assign logical networks offered by external providers to physical host network interfaces; such networks are dynamically assigned to hosts as they are required by virtual machines.
====

[NOTE]
====
If the switch has been configured to provide Link Layer Discovery Protocol (LLDP) information, you can hover your cursor over a physical network interface to view the switch port's current configuration. This can help to prevent incorrect configuration. Check the following information prior to assigning logical networks:

* *Port Description (TLV type 4)* and *System Name (TLV type 5)* help to detect to which ports and on which switch the host's interfaces are
patched.
* *Port VLAN ID* shows the native
VLAN ID configured on the switch port for untagged ethernet frames. All
VLANs configured on the switch port are shown as *VLAN Name* and *VLAN ID*
combinations.
====

.Procedure

. Click menu:Compute[Hosts].
. Click the host's name. This opens the details view.
. Click the *Network Interfaces* tab.
. Click *Setup Host Networks*.
. Optionally, hover your cursor over host network interface to view configuration information provided by the switch.
. Attach a logical network to a physical host network interface by selecting and dragging the logical network into the *Assigned Logical Networks* area next to the physical host network interface.
+
[NOTE]
====
If a NIC is connected to more than one logical network, only one of the networks can be non-VLAN. All the other logical networks must be unique VLANs.
====

. Configure the logical network:
.. Hover your cursor over an assigned logical network and click the pencil icon. This opens the *Edit Management Network* window.
.. From the *IPv4* tab, select a *Boot Protocol* from *None*, *DHCP*, or *Static*. If you selected *Static*, enter the *IP*, *Netmask / Routing Prefix*, and the *Gateway*.
+
[NOTE]
====
For IPv6, only static IPv6 addressing is supported.
To configure the logical network, select the *IPv6* tab and make the following entries:

* Set *Boot Protocol* to *Static*.
* For *Routing Prefix*, enter the _length_ of the prefix using a forward slash and decimals. For example: `/48`
* *IP*: The complete IPv6 address of the host network interface. For example: `2001:db8::1:0:0:6`
* *Gateway*: The source router's IPv6 address. For example: `2001:db8::1:0:0:1`
====
+
[NOTE]
====
If you change the host's management network IP address, you must xref:Reinstalling_Hosts_admin[reinstall the host] for the new IP address to be configured.

Each logical network can have a separate gateway defined from the management network gateway. This ensures traffic that arrives on the logical network will be forwarded using the logical network's gateway instead of the default gateway used by the management network.
====
ifdef::rhv-doc[]
+
[IMPORTANT]
====
Set *all* hosts in a cluster to use the same IP stack for their management network; either IPv4 or IPv6 only. Dual stack is not supported.
====
endif::[]

.. Use the *QoS* tab to override the default host network quality of service. Select *Override QoS* and enter the desired values in the following fields:

* *Weighted Share*: Signifies how much of the logical link's capacity a specific network should be allocated, relative to the other networks attached to the same logical link. The exact share depends on the sum of shares of all networks on that link. By default this is a number in the range 1-100.

* *Rate Limit [Mbps]*: The maximum bandwidth to be used by a network.

* *Committed Rate [Mbps]*: The minimum bandwidth required by a network. The Committed Rate requested is not guaranteed and will vary depending on the network infrastructure and the Committed Rate requested by other networks on the same logical link.

.. To configure a network bridge, click the *Custom Properties* tab and select *bridge_opts* from the drop-down list. Enter a valid key and value with the following syntax: _key_=_value_. Separate multiple entries with a whitespace character. The following keys are valid, with the values provided as examples. For more information on these parameters, see xref:Explanation_of_bridge_opts_Parameters[Explanation of bridge_opts Parameters].
+
[source,terminal,subs="normal"]
----
forward_delay=1500
group_addr=1:80:c2:0:0:0
group_fwd_mask=0x0
hash_max=512
hello_time=200
max_age=2000
multicast_last_member_count=2
multicast_last_member_interval=100
multicast_membership_interval=26000
multicast_querier=0
multicast_querier_interval=25500
multicast_query_interval=13000
multicast_query_response_interval=1000
multicast_query_use_ifaddr=0
multicast_router=1
multicast_snooping=1
multicast_startup_query_count=2
multicast_startup_query_interval=3125
----
+
.. To configure ethernet properties, click the *Custom Properties* tab and select *ethtool_opts* from the drop-down list. Enter a valid value using the format of the command-line arguments of ethtool. For example:
:
+
[source,terminal,subs="normal"]
----
--coalesce em1 rx-usecs 14 sample-interval 3 --offload em2 rx on lro on tso off --change em1 speed 1000 duplex half
----
+
This field can accept wild cards. For example, to apply the same option to all of this network's interfaces, use:
+
[source,terminal,subs="normal"]
----
--coalesce * rx-usecs 14 sample-interval 3
----
+
The *ethtool_opts* option is not available by default; you need to add it using the engine configuration tool. See xref:How_to_Set_Up_Red_Hat_Enterprise_Virtualization_Manager_to_Use_Ethtool[How to Set Up {engine-name} to Use Ethtool] for more information. For more information on ethtool properties, see the manual page by typing `man ethtool` in the command line.
.. To configure Fibre Channel over Ethernet (FCoE), click the *Custom Properties* tab and select *fcoe* from the drop-down list. Enter a valid key and value with the following syntax: _key_=_value_. At least `enable=yes` is required. You can also add `dcb=[yes|no]` and `auto_vlan=[yes|no]. Separate multiple entries with a whitespace character. The *fcoe* option is not available by default; you need to add it using the engine configuration tool. See xref:How_to_Set_Up_RHVM_to_Use_FCoE[How to Set Up {engine-name} to Use FCoE] for more information.
+
[NOTE]
====
A separate, dedicated logical network is recommended for use with FCoE.
====
+
.. To change the default network used by the host from the management network (ovirtmgmt) to a non-management network, configure the non-management network's default route. See xref:Configuring_a_Default_Route[Configuring a Default Route] for more information.

.. If your logical network definition is not synchronized with the network configuration on the host, select the *Sync network* check box. For more information about unsynchronized hosts and how to synchronize them, see xref:Synchronizing_host_networks[Synchronizing host networks].
+
. Select the *Verify connectivity between Host and Engine* check box to check network connectivity. This action only works if the host is in maintenance mode.
. Click btn:[OK].

[NOTE]
====
If not all network interface cards for the host are displayed, click menu:Management[Refresh Capabilities] to update the list of network interface cards available for that host.
====

.Troubleshooting

In some cases, making multiple concurrent changes to a host network configuration using the *Setup Host Networks* window or `setupNetwork` command fails with an `Operation failed: [Cannot setup Networks]. Another Setup Networks or Host Refresh process in progress on the host. Please try later.]` error in the event log. This error indicates that some of the changes were not configured on the host. This happens because, to preserve the integrity of the configuration state, only a single setup network command can be processed at a time. Other concurrent configuration commands are queued for up to a default timeout of 20 seconds. To help prevent the above failure from happening, use the `engine-config` command to increase the timeout period of `SetupNetworksWaitTimeoutSeconds` beyond 20 seconds. For example:

[source,terminal,subs="normal"]
----
# engine-config --set SetupNetworksWaitTimeoutSeconds=40
----

.Additional resources
* xref:Syntax_for_the_engine-config_Command[Syntax for the engine-config Command]
* link:{URL_rest_api_doc}index#services-host-methods-setup_networks[setupnetworks POST]
