:_content-type: PROCEDURE
[id="Editing_Storage_Domains"]
= Editing Storage Domains

You can edit storage domain parameters through the Administration Portal. Depending on the state of the storage domain, either active or inactive, different fields are available for editing. Fields such as *Data Center*, *Domain Function*, *Storage Type*, and *Format* cannot be changed.

* *Active*: When the storage domain is in an active state, the *Name*, *Description*, *Comment*, *Warning Low Space Indicator (%)*, *Critical Space Action Blocker (GB)*, *Wipe After Delete*, and *Discard After Delete* fields can be edited. The *Name* field can only be edited while the storage domain is active. All other fields can also be edited while the storage domain is inactive.

* *Inactive*: When the storage domain is in maintenance mode or unattached, thus in an inactive state, you can edit all fields except *Name*, *Data Center*, *Domain Function*, *Storage Type*, and *Format*. The storage domain must be inactive to edit storage connections, mount options, and other advanced parameters. This is only supported for NFS, POSIX, and Local storage types.

[NOTE]
====
iSCSI storage connections cannot be edited via the Administration Portal, but can be edited via the REST API. See link:{URL_downstream_virt_product_docs}rest_api_guide/index#services-storage_server_connection_extension-methods-update[Updating Storage Connections] in the _REST API Guide_.
====

.Editing an Active Storage Domain*

. Click menu:Storage[Domains] and select a storage domain.
. Click *Manage Domain*.
. Edit the available fields as required.
. Click btn:[OK].

.Editing an Inactive Storage Domain

. Click menu:Storage[Domains].
. If the storage domain is active, move it to maintenance mode:
.. Click the storage domain's name. This opens the details view.
.. Click the *Data Center* tab.
.. Click *Maintenance*.
.. Click btn:[OK].
. Click *Manage Domain*.
. Edit the storage path and other details as required. The new connection details must be of the same storage type as the original connection.
. Click btn:[OK].
. Activate the storage domain:
.. Click the storage domain's name. This opens the details view.
.. Click the *Data Center* tab.
.. Click *Activate*.
