:_content-type: CONCEPT
[id="Host_high_availability"]
==== Host High Availability

The {virt-product-fullname} {engine-name} uses fencing to keep hosts in a cluster responsive. A *Non Responsive* host is different from a *Non Operational* host. *Non Operational* hosts can be communicated with by the {engine-name}, but have an incorrect configuration, for example a missing logical network. *Non Responsive* hosts cannot be communicated with by the {engine-name}.

Fencing allows a cluster to react to unexpected host failures and enforce power saving, load balancing, and virtual machine availability policies. You should configure the fencing parameters for your host's power management device and test their correctness from time to time. In a fencing operation, a non-responsive host is rebooted, and if the host does not return to an active status within a prescribed time, it remains non-responsive pending manual intervention and troubleshooting.

[NOTE]
====
To automatically check the fencing parameters, you can configure the `PMHealthCheckEnabled` (false by default) and `PMHealthCheckIntervalInSec` (3600 sec by default) engine-config options.

When set to true, `PMHealthCheckEnabled` will check all host agents at the interval specified by `PMHealthCheckIntervalInSec`, and raise warnings if it detects issues. See <<Syntax_for_the_engine-config_Command>> for more information about configuring engine-config options. 
====
Power management operations can be performed by {virt-product-fullname} {engine-name} after it reboots, by a proxy host, or manually in the Administration Portal. All the virtual machines running on the non-responsive host are stopped, and highly available virtual machines are started on a different host. At least two hosts are required for power management operations.

After the {engine-name} starts up, it automatically attempts to fence non-responsive hosts that have power management enabled after the quiet time (5 minutes by default) has elapsed. The quiet time can be configured by updating the `DisableFenceAtStartupInSec` engine-config option.

NOTE: The `DisableFenceAtStartupInSec` engine-config option helps prevent a scenario where the {engine-name} attempts to fence hosts while they boot up. This can occur after a data center outage because a host's boot process is normally longer than the {engine-name} boot process.

Hosts can be fenced automatically by the proxy host using the power management parameters, or manually by right-clicking on a host and using the options on the menu. 

IMPORTANT: If a host runs virtual machines that are highly available, power management must be enabled and configured.
