[[How_to_Set_Up_RHVM_to_Use_FCoE]]
=== How to Set Up {virt-product-fullname} {engine-name} to Use FCoE

You can configure Fibre Channel over Ethernet (FCoE) properties for host network interface cards from the Administration Portal. The *fcoe* key is not available by default and needs to be added to the {engine-name} using the engine configuration tool. You can check whether *fcoe* has already been enabled by running the following command: 

[source,terminal]
----
# engine-config -g UserDefinedNetworkCustomProperties
----

You also need to install the required VDSM hook package on the hosts. Depending on the FCoE card on the hosts, special configuration may also be needed; see link:{URL_rhel_docs_legacy}html/Storage_Administration_Guide/fcoe-config.html[Configuring a Fibre Channel over Ethernet Interface] in the _{enterprise-linux} Storage Administration Guide_.


*Adding the fcoe Key to the {engine-name}*

. On the {engine-name}, run the following command to add the key:
+
[source,terminal]
----
# engine-config -s UserDefinedNetworkCustomProperties='fcoe=^((enable|dcb|auto_vlan)=(yes|no),?)*$'
----
+
. Restart the `ovirt-engine` service: 
+
[source,terminal]
----
# systemctl restart ovirt-engine.service
----
+
. Install the VDSM hook package on each of the {enterprise-linux-host-fullname}s on which you want to configure FCoE properties. The package is available by default on {hypervisor-fullname} ({hypervisor-shortname}). 
+
[source,terminal]
----
# dnf install vdsm-hook-fcoe
----


The *fcoe* key is now available in the Administration Portal. See xref:Editing_Host_Network_Interfaces_and_Assigning_Logical_Networks_to_Hosts[] to apply FCoE properties to logical networks.
