[id="How_to_Set_Up_Red_Hat_Enterprise_Virtualization_Manager_to_Use_Ethtool_{context}"]
=== How to Set Up {virt-product-fullname} {engine-name} to Use Ethtool

You can configure ethtool properties for host network interface cards from the Administration Portal. The *ethtool_opts* key is not available by default and needs to be added to the {engine-name} using the engine configuration tool. You also need to install the required VDSM hook package on the hosts.


*Adding the ethtool_opts Key to the {engine-name}*

. On the {engine-name}, run the following command to add the key:
+
[source,terminal]
----
# engine-config -s UserDefinedNetworkCustomProperties=ethtool_opts=.* --cver=4.4
----
+
. Restart the `ovirt-engine` service:
+
[source,terminal]
----
# systemctl restart ovirt-engine.service
----
+
. On the hosts that you want to configure ethtool properties, install the VDSM hook package. The package is available by default on {hypervisor-fullname} but needs to be installed on {enterprise-linux-host-fullname}s.
+
[source,terminal]
----
# dnf install vdsm-hook-ethtool-options
----


The *ethtool_opts* key is now available in the Administration Portal. See xref:Editing_Host_Network_Interfaces_and_Assigning_Logical_Networks_to_Hosts[] to apply ethtool properties to logical networks.
