:_content-type: PROCEDURE
[id="Data_center_logical_network_entities"]
= Managing System Permissions for a Virtual Machine Pool

As the *SuperUser*, the system administrator manages all aspects of the Administration Portal. More specific administrative roles can be assigned to other users. These restricted administrator roles are useful for granting a user administrative privileges that limit them to a specific resource. For example, a *DataCenterAdmin* role has administrator privileges only for the assigned data center with the exception of the storage for that data center, and a *ClusterAdmin* has administrator privileges only for the assigned cluster.

A virtual machine pool administrator is a system administration role for virtual machine pools in a data center. This role can be applied to specific virtual machine pools, to a data center, or to the whole virtualized environment; this is useful to allow different users to manage certain virtual machine pool resources.

The virtual machine pool administrator role permits the following actions:

* Create, edit, and remove pools.

* Add and detach virtual machines from the pool.



[NOTE]
====
You can only assign roles and permissions to existing users.
====

