[id="Managing_Groups"]
==== Managing Groups

You can use the `ovirt-aaa-jdbc-tool` tool to manage group accounts on your internal domain. Managing group accounts is similar to managing user accounts. For a full list of group options, run `ovirt-aaa-jdbc-tool group --help`. Common examples are provided in this section.


*Creating a Group*

This procedure shows you how to create a group account, add users to the group, and view the details of the group.

. Log in to the machine on which the {virt-product-fullname} {engine-name} is installed.
. Create a new group: 
+
[source,terminal]
----
# ovirt-aaa-jdbc-tool group add _group1_
----
+
. Add users to the group. The users must be created already. 
+
[source,terminal]
----
# ovirt-aaa-jdbc-tool group-manage useradd _group1_ --user=_test1_
----
+
[NOTE]
====
For a full list of the group-manage options, run `ovirt-aaa-jdbc-tool group-manage --help`.
====
+
. View group account details: 
+
[source,terminal]
----
# ovirt-aaa-jdbc-tool group show _group1_
----
+
. Add the newly created group in the Administration Portal and assign the group appropriate roles and permissions. The users in the group inherit the roles and permissions of the group. See xref:Adding_users[] for more information.


*Creating Nested Groups*

This procedure shows you how to create groups within groups.

. Log in to the machine on which the {virt-product-fullname} {engine-name} is installed.
. Create the first group: 
+
[source,terminal]
----
# ovirt-aaa-jdbc-tool group add _group1_
----
+
. Create the second group: 
+
[source,terminal]
----
# ovirt-aaa-jdbc-tool group add _group1-1_
----
+
. Add the second group to the first group: 
+
[source,terminal]
----
# ovirt-aaa-jdbc-tool group-manage groupadd _group1_ --group=_group1-1_
----
+
. Add the first group in the Administration Portal and assign the group appropriate roles and permissions. See xref:Adding_users[] for more information.

