:_content-type: PROCEDURE
[id="Migrating_SD_between_DC_Same_Env"]
= Migrating Storage Domains between Data Centers in the Same Environment

Migrate a storage domain from one data center to another in the same {virt-product-fullname} environment to allow the destination data center to access the data contained in the storage domain. This procedure involves detaching the storage domain from one data center, and attaching it to a different data center.

[WARNING]
====
Migrating a data storage domain to a data center that has a higher compatibility level than the original data center upgrades the storage domain’s storage format version.
====

If you want to move the storage domain back to the original data center for any reason, such as to migrate virtual machines to the new data center, be aware that the higher version prevents reattaching the data storage domain to the original data center.

The Administration Portal prompts you to confirm that you want to update the storage domain format, for example, from *V3* to *V5*. It also warns that you will not be able to attach it back to an older data center with a lower DC level.

To work around this issue, you can create a target data center that has the same compatibility version as the source data center. When you no longer need to maintain the lower compatibility version, you can increase the target data center’s compatibility version.

For details, see link:https://access.redhat.com/solutions/4303801[Supportability and constraints regarding importing Storage Domains and Virtual Machines from older RHV versions].

.Procedure

. Shut down all virtual machines running on the required storage domain.
. Click menu:Storage[Domains].
. Click the storage domain's name. This opens the details view.
. Click the *Data Center* tab.
. Click *Maintenance*, then click btn:[OK].
. Click *Detach*, then click btn:[OK].
. Click *Attach*.
. Select the destination data center and click btn:[OK].

The storage domain is attached to the destination data center and is automatically activated. You can now import virtual machines and templates from the storage domain to the destination data center.
