[[Moving_storage_domains_to_maintenance_mode]]
==== Moving Storage Domains to Maintenance Mode

A storage domain must be in maintenance mode before it can be detached and removed. This is required to redesignate another data domain as the master data domain.

[IMPORTANT]
====
You cannot move a storage domain into maintenance mode if a virtual machine has a lease on the storage domain. The virtual machine needs to be shut down, or the lease needs to be to removed or moved to a different storage domain first. See the link:{URL_virt_product_docs}virtual_machine_management_guide#What_is_high_availability[_Virtual Machine Management Guide_] for information about virtual machine leases.
====

Expanding iSCSI domains by adding more LUNs can only be done when the domain is active.


*Moving storage domains to maintenance mode*

. Shut down all the virtual machines running on the storage domain.
. Click menu:Storage[Domains].
. Click the storage domain's name. This opens the details view.
. Click the *Data Center* tab.
. Click *Maintenance*.
+
[NOTE]
====
The `Ignore OVF update failure` check box allows the storage domain to go into maintenance mode even if the OVF update fails.
====

. Click btn:[OK]. 

The storage domain is deactivated and has an `Inactive` status in the results list. You can now edit, detach, remove, or reactivate the inactive storage domains from the data center.

[NOTE]
====
You can also activate, detach, and place domains into maintenance mode using the Storage tab in the details view of the data center it is associated with.
====

