:_content-type: PROCEDURE
[id="pre-encrypting-a-user-password"]
= Pre-encrypting a User Password

You can create a pre-encrypted user password using the `ovirt-engine-crypto-tool` script. This option is useful if you are adding users and passwords to the database with a script.

[NOTE]
====
Passwords are stored in the {engine-name} database in encrypted form. The `ovirt-engine-crypto-tool` script is used because all passwords must be encrypted with the same algorithm.

If the password is pre-encrypted, password validity tests cannot be performed. The password will be accepted even if it does not comply with the password validation policy.
====

. Run the following command:
+
[source,terminal,subs="normal"]
----
# /usr/share/ovirt-engine/bin/ovirt-engine-crypto-tool.sh pbe-encode
----
+
The script will prompt you to enter the password.
+
Alternatively, you can use the `--password=file:__file__` option to encrypt a single password that appears as the first line of a file. This option is useful for automation. In the following example, `_file_` is a text file containing a single password for encryption:
+
[source,terminal,subs="normal"]
----
# /usr/share/ovirt-engine/bin/ovirt-engine-crypto-tool.sh pbe-encode --password=file:__file__
----

. Set the new password with the `ovirt-aaa-jdbc-tool` script, using the `--encrypted` option:
+
[source,terminal,subs="normal"]
----
# ovirt-aaa-jdbc-tool user password-reset __test1__ --password-valid-to="2025-08-01 12:00:00-0800" --encrypted
----

. Enter and confirm the encrypted password:
+
[options="nowrap" ]
----
Password:
Reenter password:
updating user test1...
user updated successfully
----
