:_module-type: PROCEDURE
[id="monitoring-available-space-in-a-storage-domain"]
= Monitoring available space in a storage domain

[role="_abstract"]
You can monitor available space in a storage domain and create an alert to warn you when a storage domain is nearing capacity. You can also define a critical threshold at which point the domain shuts down.

With Virtual Data Optimizer (VDO) and thin pool support, you might see more available space than is physically available. For VDO this behavior is expected, but the {engine-name} cannot predict how much data you can actually write. The *Warning Low Confirmed Space Indicator* parameter notifies you when the domain is nearing physical space capacity and shows how much confirmed space remains. Confirmed space refers to the actual space available to write data.

.Procedure

. In the Administration Portal, click menu:Storage[Storage Domain] and click the name of a storage domain.
. Click *Manage Domain*. The *Manage Domains* dialog box opens.
. Expand *Advanced Parameters*.
. For *Warning Low Space Indicator (%)* enter a percentage value. When the available space in the storage domain reaches this value, the {engine-name} alerts you that the domain is nearing capacity.
. For *Critical Space Action Blocker (GB)*, enter a value in gigabytes. When the available space in the storage domain reaches this value, the {engine-name} shuts down.
. For *Warning Low Confirmed Space Indicator (%)* enter a percentage value. When the available space in the storage domain reaches this value, the {engine-name} alerts you that the actual space available to write data is nearing capacity.
