// Module included in the following assemblies:
//
// doc-Administration_Guide/chap-Logical_Networks.adoc

:_content-type: PROCEDURE
[id="proc-Removing-a-static-route-on-a-host"]
= Removing a static route on a host

You can use nmstate to remove static routes from hosts. This method requires you to configure the hosts directly, without using {virt-product-fullname} {engine-name}.

IMPORTANT: Except for adding or removing a static route on a host, always use the {virt-product-shortname} {engine-name} to configure host network settings in your cluster. For details, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#con-Network-Manager-Stateful-Configuration-nmstate[Network Manager Stateful Configuration (nmstate)].

[NOTE]
====
The custom static-route is preserved so long as its interface/bond exists and has an IP address. Otherwise, it will be removed.

As a result, VM networks behave differently from non-VM networks:

* VM networks are based on a bridge. Moving the network from one interfaces/bond to another does not affect the route on a VM Network.
* Non-VM networks are based on an interface. Moving the network from one interfaces/bond to another deletes the route related to the Non-VM network.
====


.Prerequisites

This procedure requires nmstate, which is only available if your environment uses:

* {virt-product-fullname} {engine-name} version 4.4
* {enterprise-linux-host-fullname}s and {hypervisor-fullname}s that are based on {enterprise-linux} 8

.Procedure

. Connect to the host you want to reconfigure.
. On the host, edit the `static_route.yml` file.
. Insert a line `state: absent` as shown in the following example.
. Add the value of `next-hop-interface` between the brackets of `interfaces: []`. The result should look similar to the example shown here.
+
[source,yaml]
----
routes:
  config:
  - destination: 192.168.123.0/24
    next-hop-address: 192.168.178.
    next-hop-interface: eth1
    state: absent
interfaces: [{“name”: eth1}]
----
. Run this command:
+
----
$ nmstatectl set static_route.yml
----

.Verification steps

* Run the IP route command, `ip route`, with the destination parameter value you set in `static_route.yml`. This should no longer show the desired route. For example, run the following command:
+
----
$ ip route | grep 192.168.123.0`
----

.Additional resources

* link:{URL_virt_product_docs}{URL_format}administration_guide/index#con-Network-Manager-Stateful-Configuration-nmstate[Network Manager Stateful Configuration (nmstate)]
* link:{URL_virt_product_docs}{URL_format}administration_guide/index#proc-Adding-a-static-route-on-a-host[Adding a static route on a host]
