[id="Enabling-4K-support-more-than-250-nodes-{context}"]
= Enabling 4K support on environments with more than 250 hosts

// Module included in the following assemblies:
// chap-Storage (part of Administration Guide)

By default, GlusterFS domains and local storage domains support 4K block size on {virt-product-fullname} environments with up to 250 hosts. 4K block size can provide better performance, especially when using large files, and it is also necessary when you use tools that require 4K compatibility, such as VDO.

The lockspace area that Sanlock allocates is 1 MB when the maximum number of hosts is the default 250. When you increase the maximum number of hosts when using 4K storage, the lockspace area is larger. For example, when using 2000 hosts, the lockspace area could be as large as 8 MB.

You can enable 4K block support on environments with more than 250 hosts by setting the engine configuration parameter `MaxNumberOfHostsInStoragePool`.

.Procedure

. On the {engine-name} machine enable the required maximum number of hosts:
+
[options="nowrap" subs="normal"]
----
# engine-config -s MaxNumberOfHostsInStoragePool=_NUMBER_OF_HOSTS_
----

. Restart the JBoss Application Server:
+
[options="nowrap" subs="normal"]
----
# service jboss-as restart
----

For example, if you have a cluster with 300 hosts, enter:

[options="nowrap" subs="normal"]
----
# engine-config -s MaxNumberOfHostsInStoragePool=300
# service jboss-as restart
----

.Verification

View the value of the `MaxNumberOfHostsInStoragePool` parameter on the {engine-name}:

[options="nowrap" subs="normal"]
----
 # engine-config --get=MaxNumberOfHostsInStoragePool
 MaxNumberOfHostsInStoragePool: 250 version: general
----
