// Module included in the following assemblies:
//
// doc-Administration_Guide/chap-Hosts.adoc

[id="proc-enabling-nested-virtualization-for-individual-virtual-machines_{context}"]
= Enabling nested virtualization for individual virtual machines

[IMPORTANT]
====
Nested virtualization is a Technology Preview feature. Technology Preview features are not supported with Red Hat production service-level agreements (SLAs) and might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information see link:https://access.redhat.com/support/offerings/techpreview/[Red Hat Technology Preview Features Support Scope].
====

Nested virtualization enables virtual machines to host other virtual machines. For clarity, we will call these the _parent virtual machines_ and _nested virtual machines_.

Child virtual machines are only visible to and managed by users who have access to the parent virtual machine. They are not visible to {virt-product-fullname} ({virt-product-shortname}) administrators.

To enable nested virtualization _on specific virtual machines_, not all virtual machines, you configure a host or hosts to support nested virtualization. Then you configure the virtual machine or virtual machines on run on those specific hosts and enable *Pass-Through Host CPU*. This option lets the virtual machines use the nested virtualization settings you just configured on the host. This option also restricts which hosts the virtual machines can run on and requires manual migration.

Otherwise, to enable nested virtualization for _all of the virtual machines_ in a cluster, see xref:proc-enabling-nested-virtualization-for-all-virtual-machines[]

Only run parent virtual machines on hosts that support nested virtualization. If you migrate a parent virtual machine to a host that does not support nested virtualization, its child virtual machines will fail.

WARNING: Do not migrate parent virtual machines to hosts that do not support nested virtualization.

Avoid live migration of parent virtual machines that are running child virtual machines. Even if the source and destination hosts are identical and support nested virtualization, the live migration can cause the child virtual machines to fail. Instead, shut down virtual machines before migration.

.Procedure

Configure the hosts to support nested virtualization:

. In the Administration Portal, click menu:Compute[Hosts].

. Select a host in the cluster where you want to enable nested virtualization and click menu:Management[Maintenance] and btn:[OK].

. Select the host again, click btn:[Host Console], and log into the host console.

. In the *Edit Host* window, select the *Kernel* tab.

. Under *Kernel boot parameters*, if the checkboxes are greyed-out, click btn:[RESET].

. Select *Nested Virtualization* and click btn:[OK].
+
This action displays a `kvm-<architecture>.nested=1` parameter in *Kernel command line*. The following steps add this parameter to the *Current kernel CMD line*.

. Click menu:Installation[Reinstall].

. When the host status returns to `Up`, click menu:Management[Restart] under *Power Management* or *SSH Management*.

. Verify that nested virtualization is enabled. Log into the host console and enter:
+
----
$ cat /sys/module/kvm*/parameters/nested
----
+
If this command returns `Y` or `1`, the feature is enabled.

. Repeat this procedure for all of the hosts you need to run parent virtual machines.

Enable nested virtualization in specific virtual machines:

. In the Administration Portal, click menu:Compute[Virtual Machines].

. Select a virtual machine and click btn:[Edit]

. In the *Edit Vitual Machine* window, click btn:[Show Advanced Options] and select the *Host* tab.

. Under *Start Running On*, click *Specific Host* and select the host or hosts you configured to support nested virtualization.

. Under *CPU Options*, select *Pass-Through Host CPU*. This action automatically sets the *Migration mode* to *Allow manual migration only*.
+
NOTE: In RHV version 4.2, you can only enable *Pass-Through Host CPU* when *Do not allow migration* is selected.

.Additional resources

* xref:VDSM_hooks[]
* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_virtualization/creating-nested-virtual-machines_configuring-and-managing-virtualization[Creating Child virtual Machines] in the {enterprise-linux-shortname} documentation.
