:_content-type: PROCEDURE
[id="enabling_fips_rhel_hosts_and_rhvm_{context}"]
= Enabling FIPS in {virt-product-shortname} hosts and the standalone Manager

You can enable FIPS mode when installing a Red Hat Enterprise Linux ({enterprise-linux-shortname}) host or {hypervisor-fullname} ({hypervisor-shortname}). For details, see link:{URL_rhel_docs_latest}html/security_hardening/assembly_securing-rhel-during-installation-security-hardening#assembly_installing-a-rhel-8-system-with-fips-mode-enabled_securing-rhel-during-installation[Installing a {enterprise-linux-shortname} 8 system with FIPS mode enabled] in the guide _Security hardening_ for Red Hat Enterprise Linux 8. Red Hat does not support switching a provisioned host or Manager machine to FIPS mode

.Verification

Verify that FIPS is enabled by entering the command `fips-mode-setup --check` on the host. The command should return `FIPS mode is enabled`:

[source,terminal,subs="normal"]
----
# fips-mode-setup --check
FIPS mode is enabled.
----
