[[Querying_Users_and_Groups]]
==== Querying Users and Groups

The `query` module allows you to query user and group information. For a full list of options, run `ovirt-aaa-jdbc-tool query --help`.


*Listing All User or Group Account Details*

This procedure shows you how to list all account information.

. Log in to the machine on which the {virt-product-fullname} {engine-name} is installed.
. List the account details.
* All user account details: 
+
[options="nowrap" subs="normal"]
----
# ovirt-aaa-jdbc-tool query --what=user
----
+
* All group account details: 
+
[options="nowrap" subs="normal"]
----
# ovirt-aaa-jdbc-tool query --what=group
----


*Listing Filtered Account Details*

This procedure shows you how to apply filters when listing account information.

. Log in to the machine on which the {virt-product-fullname} {engine-name} is installed.
. Filter account details using the `--pattern` parameter.
* List user account details with names that start with the character _j_. 
+
[options="nowrap" subs="normal"]
----
# ovirt-aaa-jdbc-tool query --what=user --pattern="name=_j*_"
----
+
* List groups that have the department attribute set to _marketing_: 
+
[options="nowrap" subs="normal"]
----
# ovirt-aaa-jdbc-tool query --what=group --pattern="department=_marketing_"
----

