:_content-type: PROCEDURE
[id="Renaming_the_Manager_with_the_Ovirt_Engine_Rename_Tool"]
= Renaming the {engine-name} with the oVirt Engine Rename Tool

You can use the `ovirt-engine-rename` command to update records of the fully qualified domain name (FQDN) of the {engine-name}.

The tool checks whether the {engine-name} provides a local ISO or Data storage domain. If it does, the tool prompts the user to eject, shut down, or place into maintenance mode any virtual machine or storage domain connected to the storage before continuing with the operation. This ensures that virtual machines do not lose connectivity with their virtual disks, and prevents ISO storage domains from losing connectivity during the renaming process.

.Procedure

. Prepare all DNS and other relevant records for the new FQDN.
. Update the DHCP server configuration if DHCP is used.
. Update the host name on the {engine-name}.
. Run the following command:
+
[source,terminal,subs="normal"]
----
# /usr/share/ovirt-engine/setup/bin/ovirt-engine-rename
----
+
. When prompted, press `Enter` to stop the engine service:
+
[source,terminal,subs="normal"]
----
During execution engine service will be stopped (OK, Cancel) [OK]:
----
+
. When prompted, enter the new FQDN for the {engine-name}:
+
[source,terminal,subs="normal"]
----
New fully qualified server name:__new_engine_fqdn__
----

The `ovirt-engine-rename` command updates records of the FQDN of the {engine-name}.

*For a self-hosted engine, complete these additional steps:*

. Run the following command on every existing self-hosted engine node:
+
[source,terminal,subs="normal"]
----
# hosted-engine --set-shared-config fqdn __new_engine_fqdn__ --type=he_local
----
+
This command modifies the FQDN in each self-hosted engine node's local copy of [filename]`/etc/ovirt-hosted-engine-ha/hosted-engine.conf`

. Run the following command on one of the self-hosted engine nodes:
+
[source,terminal,subs="normal"]
----
# hosted-engine --set-shared-config fqdn __new_engine_fqdn__ --type=he_shared
----
+
This command modifies the FQDN in the main copy of [filename]`/etc/ovirt-hosted-engine-ha/hosted-engine.conf` on the shared storage domain.

Now, all new and existing self-hosted engine nodes use the new FQDN.


[NOTE]
====
The oVirt Engine Rename Tool is designed to work only on local machines. Changing the {engine-name} name does not automatically update the name on remote Data Warehouse machines. Changing the names on remote DWH machines must be performed manually.
====

*For remote Data Warehouse deployments, follow these steps on the remote machine (not on the {engine-name} machine):*

. Remove the following PKI files:
+
`/etc/pki/ovirt-engine/apache-ca.pem`
`/etc/pki/ovirt-engine/apache-grafana-ca.pem`
`/etc/pki/ovirt-engine/certs/\*`
`/etc/pki/ovirt-engine/keys/*`
. In the following files, update the engine fqdn to the new name (for example, `vm-new-name.local_lab_server.redhat.com`):
+
`/etc/grafana/grafana.ini`
`/etc/ovirt-engine-dwh/ovirt-engine-dwhd.conf.d/10-setup-database.conf`
`/etc/ovirt-engine-setup.conf.d/20-setup-ovirt-post.conf`
. Run engine-setup with the --offline switch to prevent updates at this time:
+
----
# engine-setup --offline
----
