// old ID to prevent broken links
:_content-type: PROCEDURE
[id="Replacing_the_Manager_SSL_Certificate"]
[id="Replacing_the_Manager_CA_Certificate"]
= Replacing the {virt-product-fullname} {engine-name} CA Certificate

You can configure your organization's third-party CA certificate to authenticate users connecting to the {virt-product-fullname} {engine-name} over HTTPS.

Using a third-party CA certificate for HTTPS connections does not affect the certificate used for authentication between the {engine-name} and hosts, or disk transfer URLs(link:{URL_rest_api_doc}index#types/image_transfer[transfer_url]). They will continue to use the self-signed certificate generated by the {engine-name}.

If you received the private key and certificate from your CA in a P12 file, use the following procedure to extract them. For other file formats, contact your CA. After extracting the private key and certificate, proceed to xref:replacing-manager-apache-ca-certificate[Replacing the {virt-product-fullname} {engine-name} Apache CA Certificate].

[id="extracting-certificate-and-private-key-from-p12-bundle"]
== Extracting the Certificate and Private Key from a P12 Bundle

The internal CA stores the internally generated key and certificate in a P12 file, in `/etc/pki/ovirt-engine/keys/apache.p12`. Store your new file in the same location. The following procedure assumes that the new P12 file is in `/tmp/apache.p12`.

[WARNING]
====
Do not change the permissions and ownerships for the `/etc/pki` directory or any subdirectories. The permission for the `/etc/pki` and the `/etc/pki/ovirt-engine` directory must remain as the default, `755`.
====

.Procedure

. Back up the current `apache.p12` file:
+
[source,terminal,subs="normal"]
----
# cp -p /etc/pki/ovirt-engine/keys/apache.p12 /etc/pki/ovirt-engine/keys/apache.p12.bck
----

. Replace the current file with the new file:
+
[source,terminal,subs="normal"]
----
# cp /tmp/apache.p12 /etc/pki/ovirt-engine/keys/apache.p12
----

. Extract the private key and certificate to the required locations:
+
[source,terminal,subs="normal"]
----
# openssl pkcs12 -in /etc/pki/ovirt-engine/keys/apache.p12 -nocerts -nodes > /tmp/apache.key
# openssl pkcs12 -in /etc/pki/ovirt-engine/keys/apache.p12 -nokeys > /tmp/apache.cer
----
+
If the file is password protected, add `-passin pass:__password__` to the command, replacing _password_ with the required password.

[IMPORTANT]
====
For new {virt-product-fullname} installations, you must complete all of the steps in this procedure.
====

[id="replacing-manager-apache-ca-certificate"]
== Replacing the {virt-product-fullname} {engine-name} Apache CA Certificate

You configure your organization's third-party CA certificate to authenticate users connecting to the Administration Portal and the VM Portal over HTTPS.

[WARNING]
====
Do not change the permissions and ownerships for the `/etc/pki` directory or any subdirectories. The permission for the `/etc/pki` and the `/etc/pki/ovirt-engine` directory must remain as the default, `755`.
====

.Prerequisites

* Third-party CA (Certificate Authority) certificate. It is provided as a `PEM` file. The certificate chain must be complete up to the root certificate. The chain's order is critical and must be from the last intermediate certificate to the root certificate. This procedure assumes that the third-party CA certificate is provided in `/tmp/3rd-party-ca-cert.pem`.

* Private key that you want to use for Apache httpd. It must not have a password. This procedure assumes that it is located in `/tmp/apache.key`.

* Certificate issued by the CA. This procedure assumes that it is located in `/tmp/apache.cer`.

.Procedure

. If you are using a self-hosted engine, put the environment into global maintenance mode.
+
[source,terminal,subs="normal"]
----
# hosted-engine --set-maintenance --mode=global
----
+
For more information, see xref:Maintaining_the_Self-Hosted_Engine[Maintaining the Self-Hosted Engine].

. Add your CA certificate to the host-wide trust store:
+
[source,terminal,subs="normal"]
----
# cp /tmp/3rd-party-ca-cert.pem /etc/pki/ca-trust/source/anchors
# update-ca-trust
----

. The {engine-name} has been configured to use `/etc/pki/ovirt-engine/apache-ca.pem`, which is symbolically linked to `/etc/pki/ovirt-engine/ca.pem`. Remove the symbolic link:
+
[source,terminal,subs="normal"]
----
# rm /etc/pki/ovirt-engine/apache-ca.pem
----

. Save your CA certificate as `/etc/pki/ovirt-engine/apache-ca.pem`:
+
[source,terminal,subs="normal"]
----
# cp /tmp/3rd-party-ca-cert.pem /etc/pki/ovirt-engine/apache-ca.pem
----

. Back up the existing private key and certificate:
+
[source,terminal,subs="normal"]
----
# cp /etc/pki/ovirt-engine/keys/apache.key.nopass /etc/pki/ovirt-engine/keys/apache.key.nopass.bck
# cp /etc/pki/ovirt-engine/certs/apache.cer /etc/pki/ovirt-engine/certs/apache.cer.bck
----

. Copy the private key to the required location:
+
[source,terminal,subs="normal"]
----
# cp /tmp/apache.key /etc/pki/ovirt-engine/keys/apache.key.nopass
----

. Set the private key owner to root and set the permissions to `0640`:
+
[source,terminal,subs="normal"]
----
# chown root:ovirt  /etc/pki/ovirt-engine/keys/apache.key.nopass
# chmod 640 /etc/pki/ovirt-engine/keys/apache.key.nopass
----

. Copy the certificate to the required location:
+
[source,terminal,subs="normal"]
----
# cp /tmp/apache.cer /etc/pki/ovirt-engine/certs/apache.cer
----

. Set the certificate owner to root and set the permissions to `0644`:
+
[source,terminal,subs="normal"]
----
# chown root:ovirt /etc/pki/ovirt-engine/certs/apache.cer
# chmod 644 /etc/pki/ovirt-engine/certs/apache.cer
----

. Restart the Apache server:
+
[source,terminal,subs="normal"]
----
# systemctl restart httpd.service
----

. Create a new trust store configuration file, `/etc/ovirt-engine/engine.conf.d/99-custom-truststore.conf`, with the following parameters:
+
[source,terminal,subs="normal"]
----
ENGINE_HTTPS_PKI_TRUST_STORE="/etc/pki/java/cacerts"
ENGINE_HTTPS_PKI_TRUST_STORE_PASSWORD=""
----

. Copy the `/etc/ovirt-engine/ovirt-websocket-proxy.conf.d/10-setup.conf` file, and rename it with an index number that is greater than 10 (for example, `99-setup.conf`). Add the following parameters to the new file:
+
----
SSL_CERTIFICATE=/etc/pki/ovirt-engine/certs/apache.cer
SSL_KEY=/etc/pki/ovirt-engine/keys/apache.key.nopass
----

. Restart the `websocket-proxy` service:
+
[source,terminal,subs="normal"]
----
# systemctl restart ovirt-websocket-proxy.service
----

. If you manually changed the `/etc/ovirt-provider-ovn/conf.d/10-setup-ovirt-provider-ovn.conf` file, or are using a configuration file from an older installation, make sure that the {engine-name} is still configured to use `/etc/pki/ovirt-engine/apache-ca.pem` as the certificate source.

. Create the `/etc/ovirt-engine-backup/engine-backup-config.d` directory:
+
[source,terminal]
----
# mkdir -p /etc/ovirt-engine-backup/engine-backup-config.d
----

. Enable `ovirt-engine-backup` to update the system on restore by creating the `/etc/ovirt-engine-backup/engine-backup-config.d/update-system-wide-pki.sh` file with the following content:
+
[source,terminal,subs="normal"]
----
BACKUP_PATHS="${BACKUP_PATHS}
/etc/ovirt-engine-backup"
cp -f /etc/pki/ovirt-engine/apache-ca.pem \
/etc/pki/ca-trust/source/anchors/_3rd-party-ca-cert_.pem
update-ca-trust
----

. Restart the `ovirt-provider-ovn` service:
+
[source,terminal,subs="normal"]
----
# systemctl restart ovirt-provider-ovn.service
----

. Restart the `ovirt-imageio` service:
+
[source,terminal,subs="normal"]
----
# systemctl restart ovirt-imageio.service
----

. Restart the `ovirt-engine` service:
+
[source,terminal,subs="normal"]
----
# systemctl restart ovirt-engine.service
----

. If you are using a self-hosted engine, turn off global maintenance mode:
+
[source,terminal,subs="normal"]
----
# hosted-engine --set-maintenance --mode=none
----

Your users can now connect to the Administration Portal and VM Portal without seeing a certificate warning.
