// old ID to prevent broken links
[[Replacing_the_Manager_SSL_Certificate]]
[[Replacing_the_Manager_CA_Certificate]]
=== Replacing the {virt-product-fullname} {engine-name} CA Certificate

[WARNING]
====
Do not change the permissions and ownerships for the `/etc/pki` directory or any subdirectories. The permission for the `/etc/pki` and the `/etc/pki/ovirt-engine` directory must remain as the default, `755`.
====

You can configure your organization's third-party CA certificate to identify the {virt-product-fullname} {engine-name} to users connecting over HTTPS.

[NOTE]
====
Using a third-party CA certificate for HTTPS connections does not affect the certificate used for authentication between the {engine-name} and hosts. They will continue to use the self-signed certificate generated by the {engine-name}.
====

*Prerequisites*

* A third-party CA certificate. This is the certificate of the CA (Certificate Authority) that issued the certificate you want to use. It is provided as a *PEM* file. The certificate chain must be complete up to the root certificate. The chain's order is critical and must be from the last intermediate certificate to the root certificate. This procedure assumes that the third-party CA certificate is provided in `/tmp/3rd-party-ca-cert.pem`.

* The private key that you want to use for Apache httpd. It must not have a password. This procedure assumes that it is located in `/tmp/apache.key`.

* The certificate issued by the CA. This procedure assumes that it is located in `/tmp/apache.cer`.

If you received the private key and certificate from your CA in a P12 file, use the following procedure to extract them. For other file formats, contact your CA. After extracting the private key and certificate, proceed to xref:Replace[Replacing the {virt-product-fullname} {engine-name} Apache CA Certificate].

[[Extracting]]
*Extracting the Certificate and Private Key from a P12 Bundle*

The internal CA stores the internally generated key and certificate in a P12 file, in `/etc/pki/ovirt-engine/keys/apache.p12`. Store your new file in the same location. The following procedure assumes that the new P12 file is in `/tmp/apache.p12`.

. Back up the current `apache.p12` file:
+
[source,terminal]
----
# cp -p /etc/pki/ovirt-engine/keys/apache.p12 /etc/pki/ovirt-engine/keys/apache.p12.bck
----
+
. Replace the current file with the new file:
+
[source,terminal]
----
# cp /tmp/apache.p12 /etc/pki/ovirt-engine/keys/apache.p12
----
+
. Extract the private key and certificate to the required locations. If the file is password protected, you must add `-passin pass:_password_`, replacing _password_ with the required password.
+
[source,terminal]
----
# openssl pkcs12 -in /etc/pki/ovirt-engine/keys/apache.p12 -nocerts -nodes > /tmp/apache.key
# openssl pkcs12 -in /etc/pki/ovirt-engine/keys/apache.p12 -nokeys > /tmp/apache.cer

----

[IMPORTANT]
====
For new {virt-product-fullname} installations, you must complete all of the steps in this procedure.
====

[[Replace]]
*Replacing the {virt-product-fullname} {engine-name} Apache CA Certificate*


.  If you are using a self-hosted engine, put the environment into global maintenance mode.
+
[source,terminal]
----
# hosted-engine --set-maintenance --mode=global
----
+
For more information, see xref:Maintaining_the_Self-Hosted_Engine[].
. Add your CA certificate to the host-wide trust store:
+
[source,terminal]
----
# cp /tmp/_3rd-party-ca-cert_.pem /etc/pki/ca-trust/source/anchors
# update-ca-trust
----
+
. The {engine-name} has been configured to use `/etc/pki/ovirt-engine/apache-ca.pem`, which is symbolically linked to `/etc/pki/ovirt-engine/ca.pem`. Remove the symbolic link:
+
[source,terminal]
----
# rm /etc/pki/ovirt-engine/apache-ca.pem
----
+
. Save your CA certificate as `/etc/pki/ovirt-engine/apache-ca.pem`:
+
[source,terminal]
----
# cp /tmp/_3rd-party-ca-cert_.pem /etc/pki/ovirt-engine/apache-ca.pem
----
+
. Back up the existing private key and certificate:
+
[source,terminal]
----
# cp /etc/pki/ovirt-engine/keys/apache.key.nopass /etc/pki/ovirt-engine/keys/apache.key.nopass.bck
# cp /etc/pki/ovirt-engine/certs/apache.cer /etc/pki/ovirt-engine/certs/apache.cer.bck
----
+
. Copy the private key to the required location:
+
[source,terminal]
----
# cp /tmp/apache.key /etc/pki/ovirt-engine/keys/apache.key.nopass
----
. Set the private key owner to root and set the permissions to `0640`:
+
[source,terminal]
----
# chown root:ovirt  /etc/pki/ovirt-engine/keys/apache.key.nopass
# chmod 640 /etc/pki/ovirt-engine/keys/apache.key.nopass
----
+
. Copy the certificate to the required location:
+
[source,terminal]
----
# cp /tmp/apache.cer /etc/pki/ovirt-engine/certs/apache.cer
----

. Set the certificate owner to root and set the permissions to `0644`:
+
[source,terminal]
----
# chown root:ovirt /etc/pki/ovirt-engine/certs/apache.cer
# chmod 644 /etc/pki/ovirt-engine/certs/apache.cer
----
+
. Restart the Apache server:
+
[source,terminal]
----
# systemctl restart httpd.service
----
+
. Create a new trust store configuration file, `/etc/ovirt-engine/engine.conf.d/99-custom-truststore.conf`, with the following parameters:
+
[source,terminal]
----
ENGINE_HTTPS_PKI_TRUST_STORE="/etc/pki/java/cacerts"
ENGINE_HTTPS_PKI_TRUST_STORE_PASSWORD=""
----

. Copy the `/etc/ovirt-engine/ovirt-websocket-proxy.conf.d/10-setup.conf` file, and rename it with an index number that is greater than 10 (for example, `99-setup.conf`). Add the following parameters to the new file:
+
----
SSL_CERTIFICATE=/etc/pki/ovirt-engine/certs/apache.cer
SSL_KEY=/etc/pki/ovirt-engine/keys/apache.key.nopass
----
+
. Restart the `websocket-proxy` service:
+
[source,terminal]
----
# systemctl restart ovirt-websocket-proxy.service
----

. If you manually changed the `/etc/ovirt-provider-ovn/conf.d/10-setup-ovirt-provider-ovn.conf` file, or are using a configuration file from an older installation, make sure that the {engine-name} is still configured to use `/etc/pki/ovirt-engine/apache-ca.pem` as the certificate source.

. Enable `engine-backup` to update the system on restore by creating a new file, `/etc/ovirt-engine-backup/engine-backup-config.d/update-system-wide-pki.sh`, with the following content:
+
[source,terminal]
----
BACKUP_PATHS="${BACKUP_PATHS}
/etc/ovirt-engine-backup"
cp -f /etc/pki/ovirt-engine/apache-ca.pem \
/etc/pki/ca-trust/source/anchors/_3rd-party-ca-cert_.pem
update-ca-trust
----
. Restart the `ovirt-provider-ovn` service:
+
[source,terminal]
----
# systemctl restart ovirt-provider-ovn.service
----
. Restart the `ovirt-imageio` service:
+
[source,terminal]
----
# systemctl restart ovirt-imageio.service
----
. Restart the `ovirt-engine` service:
+
[source,terminal]
----
# systemctl restart ovirt-engine.service
----
. If you are using a self-hosted engine, turn off global maintenance mode.
+
[source,terminal]
----
# hosted-engine --set-maintenance --mode=none
----

Your users can now connect to the Administration Portal and VM Portal, without seeing a warning about the authenticity of the certificate used to encrypt HTTPS traffic.
