:_content-type: PROCEDURE
[id="Restoring_a_Backup_with_Different_Credentials"]
==== Restoring a Backup with Different Credentials

The `engine-backup` command can restore a backup to a machine on which the {virt-product-fullname} {engine-name} has already been installed and set up, but the credentials of the database in the backup are different to those of the database on the machine on which the backup is to be restored. This is useful when you have taken a backup of an installation and want to restore the installation from the backup to a different system.

[IMPORTANT]
====
When restoring a backup to overwrite an existing installation, you must run the `engine-cleanup` command to clean up the existing installation before using the `engine-backup` command. The `engine-cleanup` command only cleans the engine database, and does not drop the database or delete the user that owns that database. So you do not need to create a new database or specify the database credentials. However, if the credentials for the owner of the engine database are not known, you must change them before you can restore the backup.
====

*Restoring a Backup with Different Credentials*

. Log in to the {virt-product-fullname} {engine-name} machine.
. Run the following command and follow the prompts to remove the {engine-name}'s configuration files and to clean the {engine-name}'s database:
+
[source,terminal]
----
# engine-cleanup
----

. Change the password for the owner of the `engine` database if the credentials of that user are not known:
.. Enter the postgresql command line:
+
[options="nowrap" ]
----
# su - postgres -c 'psql'
----

.. Change the password of the user that owns the `engine` database:
+
[source,terminal]
----
postgres=# alter role _user_name_ encrypted password '_new_password_';
----
Repeat this for the user that owns the `ovirt_engine_history` database if necessary.

. Restore a complete backup or a database-only backup with the `--change-db-credentials` parameter to pass the credentials of the new database. The _database_location_ for a database local to the {engine-name} is `localhost`.
+
[NOTE]
====
The following examples use a `--*password` option for each database without specifying a password, which prompts for a password for each database. Alternatively, you can use `--*passfile=_password_file_` options for each database to securely pass the passwords to the `engine-backup` tool without the need for interactive prompts.
====


* Restore a complete backup:
+
[source,terminal]
----
# engine-backup --mode=restore --file=_file_name_ --log=_log_file_name_ --change-db-credentials --db-host=_database_location_ --db-name=_database_name_ --db-user=engine --db-password --no-restore-permissions
----
+
If Data Warehouse is also being restored as part of the complete backup, include the revised credentials for the additional database:
+
[source,terminal]
----
engine-backup --mode=restore --file=_file_name_ --log=_log_file_name_ --change-db-credentials --db-host=_database_location_ --db-name=_database_name_ --db-user=engine --db-password --change-dwh-db-credentials --dwh-db-host=_database_location_ --dwh-db-name=_database_name_ --dwh-db-user=ovirt_engine_history --dwh-db-password --no-restore-permissions
----

* Restore a database-only backup by restoring the configuration files and the database backup:
+
[source,terminal]
----
# engine-backup --mode=restore --scope=files --scope=db --file=_file_name_ --log=_log_file_name_ --change-db-credentials --db-host=_database_location_ --db-name=_database_name_ --db-user=engine --db-password --no-restore-permissions
----
+
The example above restores a backup of the {engine-name} database.
+
[source,terminal]
----
# engine-backup --mode=restore --scope=files --scope=dwhdb --file=_file_name_ --log=_log_file_name_ --change-dwh-db-credentials --dwh-db-host=_database_location_ --dwh-db-name=_database_name_ --dwh-db-user=ovirt_engine_history --dwh-db-password --no-restore-permissions
----
+
The example above restores a backup of the Data Warehouse database.
+
If successful, the following output displays:
+
[source,terminal]
----
You should now run engine-setup.
Done.
----

. Run the following command and follow the prompts to reconfigure the firewall and ensure the `ovirt-engine` service is correctly configured:
+
[source,terminal]
----
# engine-setup
----
