:_content-type: PROCEDURE
[id="Restoring_a_Backup_with_the_engine-backup_Command_{context}"]
==== Restoring a Backup with the engine-backup Command

Restoring a backup using the engine-backup command involves more steps than creating a backup does, depending on the restoration destination. For example, the `engine-backup` command can be used to restore backups to fresh installations of {virt-product-fullname}, on top of existing installations of {virt-product-fullname}, and using local or remote databases.

[IMPORTANT]
====
The version of the {virt-product-fullname} {engine-name} (such as 4.4.8) used to restore a backup must be later than or equal to the {virt-product-fullname} {engine-name} version (such as 4.4.7) used to create the backup.
Starting with {virt-product-fullname} 4.4.7, this policy is strictly enforced by the engine-backup command.
To view the version of {virt-product-fullname} contained in a backup file, unpack the backup file and read the value in the *version* file located in the root directory of the unpacked files.
====
