[[Restoring_a_Backup_with_the_engine-backup_Command]]
==== Restoring a Backup with the engine-backup Command

Restoring a backup using the engine-backup command involves more steps than creating a backup does, depending on the restoration destination. For example, the `engine-backup` command can be used to restore backups to fresh installations of {virt-product-fullname}, on top of existing installations of {virt-product-fullname}, and using local or remote databases.

[IMPORTANT]
====
Backups can only be restored to environments of the same major release as that of the backup. For example, a backup of a {virt-product-fullname} version 4.2 environment can only be restored to another {virt-product-fullname} version 4.2 environment. Starting with {virt-product-fullname} 4.4.7, when using the engine-backup command, the minor version of the {engine-name} (such as 4.4.8) must be later than or equal to the minor version of the backup (such as 4.4.7). 
To view the version of {virt-product-fullname} contained in a backup file, unpack the backup file and read the value in the *version* file located in the root directory of the unpacked files.
====
