[id="set_up_configure_grafana"]

Grafana is a web-based UI tool used to display the data stored in the oVirt Data Warehouse PostgreSQL database under the database name `ovirt_engine_history`.
Data from the {engine-name} is aggregated in hourly and daily aggregations. The data is retained according to the scale setting defined in the DWH configuration during engine-setup (Basic or Full scale):

* *Basic* (default) - sampled every 24 hours, hourly data saved for 1 month, daily data - no daily aggregations saved.
* *Full* - sampled every 24 hours, hourly data saved for 2 months, daily aggregations saved for 5 years

=== Setting up Grafana

.Installation
Grafana integration is installed by default during {virt-product-fullname} {engine-name} engine-setup.

To access the Grafana dashboards, go to `\https://<engine FQDN or IP address>/ovirt-engine-grafana`
or use the link:https://dwh.engineering.redhat.com//ovirt-engine-grafana/[`Monitoring Portal`] link in the web administration welcome page for the `Administration Portal`. 


.Configuring Grafana dashboards

The following dashboards are available in the initial Grafana setup to report Data Center, Cluster, Host, and Virtual Machine data:

* *Executive* dashboards - display the user console connection activity, operating system count for hosts, and active virtual machines.
* *Trend* dashboards - display trends in virtual machines, CPU, memory, network, interface, transmit and receive, disks, read and write activity.
* *Service Level* dashboards - display uptime, downtime, quality of service, and intervals for important thresholds (CPU, memory).
* *Inventory* dashboards - displays an inventory list of hosts in a cluster, disk usage in a storage domain, virtual machines in a cluster, and data per data center.

You can create your own custom dashboards in Grafana....
