:_content-type: PROCEDURE
[id="setting-a-user-password_{context}"]
= Setting a User Password

You can create a password. You must set a value for `--password-valid-to`, otherwise the password expiry time defaults to the current time. The date format is `yyyy-MM-dd HH:mm:ssX`. In this example, `-0800` stands for GMT minus 8 hours. For more options, run `ovirt-aaa-jdbc-tool user password-reset --help`.

[options="nowrap" subs="quotes"]
----
# ovirt-aaa-jdbc-tool user password-reset _test1_ --password-valid-to=_"2025-08-01 12:00:00-0800"_
Password:
updating user test1...
user updated successfully
----

[NOTE]
====
By default, the password policy for user accounts on the internal domain has the following restrictions:

* A minimum of 6 characters.

* Three previous passwords used cannot be set again during the password change.

For more information on the password policy and other default settings, run `ovirt-aaa-jdbc-tool settings show`.
====

Once the admin password is updated, the change must be manually propagated to `ovirt-provider-ovn`. Otherwise, the the admin user will become locked because the Red Hat Virtualization Manager will continue to use the old password to synchronize networks from `ovirt-provider-ovn`. To propogate the new password to `ovirt-provider-ovn`, do the following:

. In the Administration Portal, click menu:Administration[Providers].
. Select *ovirt-provider-ovn*.
. Click *Edit* and enter the new password in the *Password* field.
. Click btn:[Test] to test if authentication succeeds with the credentials you provided.
. When the authentication test succeeds, click btn:[OK].
