:_content-type: PROCEDURE
[id="Setting_Up_Encrypted_Communication_between_the_Manager_and_an_LDAP_Server"]
// old ID to prevent broken links:
[id="Setting_Up_SSL_or_TLS_Connections_between_the_Manager_and_an_LDAP_Server"]
= Setting Up Encrypted Communication between the {engine-name} and an LDAP Server

To set up encrypted communication between the {virt-product-fullname} {engine-name} and an LDAP server, obtain the root CA certificate of the LDAP server, copy the root CA certificate to the {engine-name}, and create a PEM-encoded CA certificate. The keystore type can be any Java-supported type. The following procedure uses the Java KeyStore (JKS) format.

[NOTE]
====
For more information on creating a PEM-encoded CA certificate and importing certificates, see the `X.509 CERTIFICATE TRUST STORE` section of the README file at `/usr/share/doc/ovirt-engine-extension-aaa-ldap-<__version__>.`
====


.Procedure

. On the {virt-product-fullname} {engine-name}, copy the root CA certificate of the LDAP server to the */tmp* directory and import the root CA certificate using `keytool` to create a PEM-encoded CA certificate. The following command imports the root CA certificate at _/tmp/myrootca.pem_ and creates a PEM-encoded CA certificate _myrootca.jks_ under _/etc/ovirt-engine/aaa/_. Note down the certificate's location and password. If you are using the interactive setup tool, this is all the information you need. If you are configuring the LDAP server manually, follow the rest of the procedure to update the configuration files.
+
[source,terminal,subs="normal"]
----
$ keytool -importcert -noprompt -trustcacerts -alias _myrootca_ -file _/tmp/myrootca.pem_ -keystore _/etc/ovirt-engine/aaa/myrootca.jks_ -storepass _password_
----
+
. Update the */etc/ovirt-engine/aaa/profile1.properties* file with the certificate information:
+
[NOTE]
====
`${local:_basedir}` is the directory where the LDAP property configuration file resides and points to the */etc/ovirt-engine/aaa* directory. If you created the PEM-encoded CA certificate in a different directory, replace `${local:_basedir}` with the full path to the certificate.
====
+
* To use startTLS (recommended):
+
[source,terminal,subs="normal"]
----
# Create keystore, import certificate chain and uncomment
pool.default.ssl.startTLS = true
pool.default.ssl.truststore.file = ${local:_basedir}/_myrootca.jks_
pool.default.ssl.truststore.password = _password_
----
+
* To use SSL:
+
[source,terminal,subs="normal"]
----
# Create keystore, import certificate chain and uncomment
pool.default.serverset.single.port = 636
pool.default.ssl.enable = true
pool.default.ssl.truststore.file = ${local:_basedir}/_myrootca.jks_
pool.default.ssl.truststore.password = _password_
----


To continue configuring an external LDAP provider, see xref:Configuring_an_External_LDAP_Provider[Configuring an External LDAP Provider]. To continue configuring LDAP and Kerberos for Single Sign-on, see xref:Configuring_LDAP_and_Kerberos_for_Single_Sign-on[Configuring LDAP and Kerberos for Single Sign-on].
