:_content-type: PROCEDURE
[id="Configuring_scheduling_policy"]
= Setting Load and Power Management Policies for Hosts in a Cluster

The *evenly_distributed* and *power_saving* scheduling policies allow you to specify acceptable memory and CPU usage values, and the point at which virtual machines must be migrated to or from a host. The *vm_evenly_distributed* scheduling policy distributes virtual machines evenly between hosts based on a count of the virtual machines. Define the scheduling policy to enable automatic load balancing across the hosts in a cluster. For a detailed explanation of each scheduling policy, see xref:Cluster_Scheduling_Policy_Settings[Cluster Scheduling Policy Settings].

.Procedure

. Click menu:Compute[Clusters] and select a cluster.
. Click *Edit*.
. Click the *Scheduling Policy* tab.
. Select one of the following policies:
* *none*
* *vm_evenly_distributed*
.. Set the minimum number of virtual machines that must be running on at least one host to enable load balancing in the *HighVmCount* field.
.. Define the maximum acceptable difference between the number of virtual machines on the most highly-utilized host and the number of virtual machines on the least-utilized host in the *MigrationThreshold* field.
.. Define the number of slots for virtual machines to be reserved on SPM hosts in the *SpmVmGrace* field.
.. Optionally, in the *HeSparesCount* field, enter the number of additional self-hosted engine nodes on which to reserve enough free memory to start the {engine-name} virtual machine if it migrates or shuts down. See xref:Configuring_Memory_Slots_Reserved_for_the_SHE[Configuring Memory Slots Reserved for the self-hosted engine] for more information.
* *evenly_distributed*
.. Set the time (in minutes) that a host can run a CPU load outside of the defined utilization values before the scheduling policy takes action in the *CpuOverCommitDurationMinutes* field.
.. Enter the CPU utilization percentage at which virtual machines start migrating to other hosts in the *HighUtilization* field.
.. Optionally, in the *HeSparesCount* field, enter the number of additional self-hosted engine nodes on which to reserve enough free memory to start the {engine-name} virtual machine if it migrates or shuts down. See xref:Configuring_Memory_Slots_Reserved_for_the_SHE[Configuring Memory Slots Reserved for the self-hosted engine] for more information.
.. Optionally, to prevent the host from over utilization of all the physical CPUs, define the virtual CPU to physical CPU ratio - *VCputophysicalCpuRatio* with a value between 0.1 and 2.5. When this parameter is set, hosts with a lower CPU utilization are preferred when scheduling a virtual machine.
+
If adding an additional virtual machine causes the ratio to exceed 2.5, both
the *VCputophysicalCpuRatio* and the CPU utilization are considered.
+
In a running environment, if the host *VCputophysicalCpuRatio* exceeds 2.5, some virtual machines may be load balanced and moved to hosts with a lower *VCputophysicalCpuRatio*.
* *power_saving*
.. Set the time (in minutes) that a host can run a CPU load outside of the defined utilization values before the scheduling policy takes action in the *CpuOverCommitDurationMinutes* field.
.. Enter the CPU utilization percentage below which the host will be considered under-utilized in the *LowUtilization* field.
.. Enter the CPU utilization percentage at which virtual machines start migrating to other hosts in the *HighUtilization* field.
.. Optionally, in the *HeSparesCount* field, enter the number of additional self-hosted engine nodes on which to reserve enough free memory to start the {engine-name} virtual machine if it migrates or shuts down. See xref:Configuring_Memory_Slots_Reserved_for_the_SHE[Configuring Memory Slots Reserved for the self-hosted engine] for more information.
. Choose one of the following as the *Scheduler Optimization* for the cluster:
* Select *Optimize for Utilization* to include weight modules in scheduling to allow best selection.
* Select *Optimize for Speed* to skip host weighting in cases where there are more than ten pending requests.
. If you are using an OpenAttestation server to verify your hosts, and have set up the server's details using the `engine-config` tool, select the *Enable Trusted Service* check box.
[IMPORTANT]
====
OpenAttestation and Intel Trusted Execution Technology (Intel TXT) are no longer available.
====
. Optionally select the *Enable HA Reservation* check box to enable the {engine-name} to monitor cluster capacity for highly available virtual machines.
. Optionally select a *Serial Number Policy* for the virtual machines in the cluster:
* *System Default*: Use the system-wide defaults, which are configured in the {engine-name} database link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-the_engine_configuration_tool[using the engine configuration tool] and the `DefaultSerialNumberPolicy` and `DefaultCustomSerialNumber` key names. The default value for `DefaultSerialNumberPolicy` is to use the Host ID. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-Scheduling_Policies[Scheduling Policies] in the _Administration Guide_ for more information.
* *Host ID*: Set each virtual machine's serial number to the UUID of the host.
* *Vm ID*: Set each virtual machine's serial number to the UUID of the virtual machine.
* *Custom serial number*: Set each virtual machine's serial number to the value you specify in the following *Custom Serial Number* parameter.
. Click btn:[OK].
