:_content-type: PROCEDURE
[id="Soft-Fencing_Hosts"]
= Soft-Fencing Hosts

Hosts can sometimes become non-responsive due to an unexpected problem, and though VDSM is unable to respond to requests, the virtual machines that depend upon VDSM remain alive and accessible. In these situations, restarting VDSM returns VDSM to a responsive state and resolves this issue.

"SSH Soft Fencing" is a process where the {engine-name} attempts to restart VDSM via SSH on non-responsive hosts. If the {engine-name} fails to restart VDSM via SSH, the responsibility for fencing falls to the external fencing agent if an external fencing agent has been configured.

Soft-fencing over SSH works as follows. Fencing must be configured and enabled on the host, and a valid proxy host (a second host, in an UP state, in the data center) must exist. When the connection between the {engine-name} and the host times out, the following happens:

. On the first network failure, the status of the host changes to "connecting".
. The {engine-name} then makes three attempts to ask VDSM for its status, or it waits for an interval determined by the load on the host. The formula for determining the length of the interval is configured by the configuration values TimeoutToResetVdsInSeconds (the default is 60 seconds) + [DelayResetPerVmInSeconds (the default is 0.5 seconds)]*(the count of running virtual machines on host) + [DelayResetForSpmInSeconds (the default is 20 seconds)] * 1 (if host runs as SPM) or 0 (if the host does not run as SPM). To give VDSM the maximum amount of time to respond, the {engine-name} chooses the longer of the two options mentioned above (three attempts to retrieve the status of VDSM or the interval determined by the above formula).
. If the host does not respond when that interval has elapsed, `vdsm restart` is executed via SSH.
. If `vdsm restart` does not succeed in re-establishing the connection between the host and the {engine-name}, the status of the host changes to `Non Responsive` and, if power management is configured, fencing is handed off to the external fencing agent.

[NOTE]
====
Soft-fencing over SSH can be executed on hosts that have no power management configured. This is distinct from "fencing": fencing can be executed only on hosts that have power management configured.
====
