:_content-type: PROCEDURE
[id="SPICE_Proxy_Machine_Setup"]
= SPICE Proxy Machine Setup

This procedure explains how to set up a machine as a SPICE Proxy. A SPICE Proxy makes it possible to connect to the {virt-product-fullname} network from outside the network. We use `Squid` in this procedure to provide proxy services.

.Procedure

. Install `Squid` on the Proxy machine:
+
[source,terminal,subs="normal"]
----
# dnf install squid
----
+
. Open */etc/squid/squid.conf*. Change:
+
[source,terminal,subs="normal"]
----
http_access deny CONNECT !SSL_ports
----
+
to:
+
[source,terminal,subs="normal"]
----
http_access deny CONNECT !Safe_ports
----
+
. Start the squid service and enable it to run automatically after reboot:
+
[source,terminal,subs="normal"]
----
# systemctl enable squid.service --now
----
+
. Enable incoming requests to the squid service in the default firewalld zone:
+
[source,terminal,subs="normal"]
----
# firewall-cmd --permanent --add-service=squid
----
+
. Make this firewall rule persistent in the runtime configuration:
+
[source,terminal,subs="normal"]
----
# firewall-cmd --reload
----
+
. Confirm that the squid service appears in the list of firewall services:
+
[source,terminal,subs="normal"]
----
# firewall-cmd --list-services
ssh dhcpv6-client squid
----

You have now set up a machine as a SPICE proxy. Before connecting to the {virt-product-fullname} network from outside the network, activate the SPICE proxy.
