[id="Syntax_for_the_engine-config_Command"]
==== Syntax for the engine-config Command

You can run the engine configuration tool from the machine on which the {virt-product-fullname} {engine-name} is installed. For detailed information on usage, print the help output for the command: 

[source,terminal]
----
# engine-config --help
----


*Common tasks:*

* List available configuration keys 
+
[source,terminal]
----
# engine-config --list
----

* List available configuration values
+
[source,terminal]
----
# engine-config --all
----

* Retrieve value of configuration key
+
[source,terminal]
----
# engine-config --get _KEY_NAME_
----
+
Replace _KEY_NAME_ with the name of the preferred key to retrieve the value for the given version of the key. Use the `--cver` parameter to specify the configuration version of the value to be retrieved. If no version is provided, values for all existing versions are returned.

* Set value of configuration key
+
[source,terminal]
----
# engine-config --set _KEY_NAME_=_KEY_VALUE_ --cver=_VERSION_
----
+
Replace _KEY_NAME_ with the name of the specific key to set, and replace _KEY_VALUE_ with the value to be set. You must specify the _VERSION_ in environments with more than one configuration version.

* Restart the ovirt-engine service to load changes
+
The *ovirt-engine* service needs to be restarted for your changes to take effect. 
+
[source,terminal]
----
# systemctl restart ovirt-engine.service
----
