:_content-type: PROCEDURE
[id="Uploading_the_VirtIO_and_Guest_Tool_Image_Files_to_an_ISO_Storage_Domain"]
= Uploading the VirtIO and guest tool image files to a storage domain

[NOTE]
====
The ISO domain is a deprecated storage domain type. The ISO Uploader tool has been removed in {virt-product-fullname} 4.4. {org-fullname} recommends uploading ISO images to the data domain with the Administration Portal or with the REST API. See xref:Uploading Images to a Data Storage Domain[] for details.
====

The `virtio-win___version__.iso` image contains the following for Windows virtual machines to improve performance and usability:

* VirtIO drivers
* an installer for the guest agents
* an installer for the drivers

To install and upload the most recent version of `virtio-win___version__.iso`:

. Install the image files on the {engine-name} machine:
+
[source,terminal]
----
# dnf -y install virtio-win
----
+
After you install it on the {engine-name} machine, the image file is [filename]`/usr/share/virtio-win/virtio-win___version__.iso`
. Upload the image file to a data storage domain that was not created locally during installation. For more information, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Uploading_Images_to_a_Data_Storage_Domain_storage_tasks[Uploading Images to a Data Storage Domain] in the _Administration Guide_.

. Attach the image file to virtual machines.

The virtual machines can now use the virtio drivers and agents.

For information on attaching the image files to a virtual machine, see link:{URL_virt_product_docs}{URL_format}virtual_machine_management_guide/index#Installing_the_Guest_Agents_and_Drivers_on_Windows[Installing the Guest Agents, Tools, and Drivers on Windows] in the _Virtual Machine Management Guide_.
