[id='Uploading_Images_to_a_Data_Storage_Domain_{context}']
==== Uploading Images to a Data Storage Domain

You can upload virtual disk images and ISO images to your data storage domain in the Administration Portal or with the REST API.

[NOTE]
====
To upload images with the REST API, see link:http://ovirt.github.io/ovirt-engine-api-model/4.4#services-image_transfers[IMAGETRANSFERS] and link:http://ovirt.github.io/ovirt-engine-api-model/4.4#services-image_transfer[IMAGETRANSFER] in the _REST API Guide_.
====

QEMU-compatible virtual disks can be attached to virtual machines. Virtual disk types must be either QCOW2 or raw. Disks created from a QCOW2 virtual disk cannot be shareable, and the QCOW2 virtual disk file must not have a backing file.

ISO images can be attached to virtual machines as CDROMs or used to boot virtual machines.

*Prerequisites*

The upload function uses HTML 5 APIs, which requires your environment to have the following:

* Image I/O Proxy (`ovirt-imageio-proxy`), configured with `engine-setup`. See link:{URL_virt_product_docs}installing_ovirt_as_a_standalone_manager_with_local_databases/[Configuring the {virt-product-fullname} {engine-name}] for details.

* Certificate authority, imported into the web browser used to access the Administration Portal.
+
To import the certificate authority, browse to `https://_engine_address_/ovirt-engine/services/pki-resource?resource=ca-certificate&amp;format=X509-PEM-CA` and enable all the trust settings. Refer to the instructions to install the certificate authority in link:https://access.redhat.com/solutions/95103[Firefox], link:https://access.redhat.com/solutions/17864[Internet Explorer], or link:https://access.redhat.com/solutions/1168383[Google Chrome].

* Browser that supports HTML 5, such as Firefox 35, Internet Explorer 10, Chrome 13, or later.

*Uploading an Image to a Data Storage Domain*

. Click menu:Storage[Disks].
. Select *Start* from the *Upload* menu.
. Click *Choose File* and select the image to upload.
. Fill in the *Disk Options* fields. See xref:Explanation_of_Settings_in_the_New_Virtual_Disk_Window[] for descriptions of the relevant fields.
. Click btn:[OK].
+
A progress bar indicates the status of the upload. You can pause, cancel, or resume uploads from the *Upload* menu.

*Increasing the Upload Timeout Value*

. If the upload times out and you see the message, *Reason: timeout due to transfer inactivity*, increase the timeout value:
+
[options="nowrap" subs="normal"]
----
# engine-config -s TransferImageClientInactivityTimeoutInSeconds=6000
----
. Restart the `ovirt-engine` service:
+
[options="nowrap" subs="normal"]
----
# systemctl restart ovirt-engine
----
