:_content-type: PROCEDURE
[id="VDSM_hooks_defining_custom_properties"]
= Defining Custom Properties

The custom properties that are accepted by the {virt-product-fullname} {engine-name} - and in turn passed to custom hooks - are defined using the `engine-config` command. Run this command as the *root* user on the host where {virt-product-fullname} {engine-name} is installed.

The `UserDefinedVMProperties` and `CustomDeviceProperties` configuration keys are used to store the names of the custom properties supported. Regular expressions defining the valid values for each named custom property are also contained in these configuration keys.

Multiple custom properties are separated by a semi-colon. Note that when setting the configuration key, any existing value it contained is overwritten. When combining new and existing custom properties, all of the custom properties in the command used to set the key's value must be included.

Once the configuration key has been updated, the *ovirt-engine* service must be restarted for the new values to take effect.

.Virtual Machine Properties - Defining the `smartcard` Custom Property
====
. Check the existing custom properties defined by the `UserDefinedVMProperties` configuration key using the following command:
+
[source,terminal,subs="normal"]
----
# engine-config -g UserDefinedVMProperties
----
+
As shown by the output below, the custom property `memory` is already defined. The regular expression `^[0-9]+$` ensures that the custom property will only ever contain numeric characters.
+
[options="nowrap" ]
----
# engine-config -g UserDefinedVMProperties
UserDefinedVMProperties:  version: 4.3
UserDefinedVMProperties:  version: 4.4
UserDefinedVMProperties : memory=^[0-9]+$ version: 4.4
----
+
. Because the `memory` custom property is already defined in the `UserDefinedVMProperties` configuration key, the new custom property must be appended to it. The additional custom property, `smartcard`, is added to the configuration key's value. The new custom property is able to hold a value of `true` or `false`.
+
[options="nowrap" ]
----
# engine-config -s UserDefinedVMProperties='memory=^[0-9]+$;smartcard=^(true|false)$' --cver=4.4
----
+
. Verify that the custom properties defined by the `UserDefinedVMProperties` configuration key have been updated correctly.
+
[options="nowrap" ]
----
# engine-config -g UserDefinedVMProperties
UserDefinedVMProperties:  version: 4.3
UserDefinedVMProperties:  version: 4.4
UserDefinedVMProperties : memory=^[0-9]+$;smartcard=^(true|false)$ version: 4.4
----
+
. Finally, the *ovirt-engine* service must be restarted for the configuration change to take effect.
+
[options="nowrap" ]
----
# systemctl restart ovirt-engine.service
----
====

.Device Properties - Defining the `interface` Custom Property
====
. Check the existing custom properties defined by the `CustomDeviceProperties` configuration key using the following command:
+
[options="nowrap" ]
----
# engine-config -g CustomDeviceProperties
----
+
As shown by the output below, no custom properties have yet been defined.
+
[options="nowrap" ]
----
# engine-config -g CustomDeviceProperties
CustomDeviceProperties:  version: 4.3
CustomDeviceProperties:  version: 4.4
----
+
. The `interface` custom property does not already exist, so it can be appended as is. In this example, the value of the `speed` sub-property is set to a range of 0 to 99999, and the value of the `duplex` sub-property is set to a selection of either `full` or `half`.
+
[options="nowrap" ]
----
# engine-config -s CustomDeviceProperties="{type=interface;prop={speed=^([0-9]{1,5})$;duplex=^(full|half)$}}" --cver=4.4
----
+
. Verify that the custom properties defined by the `CustomDeviceProperties` configuration key have been updated correctly.
+
[options="nowrap" ]
----
# engine-config -g CustomDeviceProperties
UserDefinedVMProperties:  version: 4.3
UserDefinedVMProperties:  version: 4.4
UserDefinedVMProperties : {type=interface;prop={speed=^([0-9]{1,5})$;duplex=^(full|half)$}} version: 4.4
----
+
. Finally, the *ovirt-engine* service must be restarted for the configuration change to take effect.
+
[options="nowrap" ]
----
# systemctl restart ovirt-engine.service
----
====
