:_content-type: CONCEPT
[id="VDSM_hooks_domain_xml"]
= The VDSM Hook Domain XML Object

VDSM uses the link:https://libvirt.org/formatdomain.html[`libvirt` domain XML format] to define virtual machines. The UUID of the virtual machine may be deduced from the domain XML, but it is also available as the environment variable `vmId`.

When hook scripts are started, the `_hook_domxml` variable is appended to the environment. This variable contains the path of the `libvirt` domain XML representation of the relevant virtual machine.

Some hooks are an exception to this rule. The following hooks contain the XML representation of the NIC, not the virtual machine:

* `\*\_nic_hotplug_*`
* `\*\_nic_hotunplug_*`
* `*_update_device`
* `*_device_create`
* `\*\_device_migrate_*`

//Although the above looks like exposed markup when rendered, it is supposed to be that way; see the 4.1 version.

[IMPORTANT]
====
The `before_migration_destination` and `before_dehibernation` hooks currently receive the domain XML from the source host. The domain XML at the destination will be different.
====
