[id="VDSM_hooks_domain_xml"]
=== The VDSM Hook Domain XML Object

When hook scripts are started, the _hook_domxml variable is appended to the environment. This variable contains the path of the libvirt domain XML representation of the relevant virtual machine. Several hooks are an exception to this rule, as outlined below.
The _hook_domxml variable of the following hooks contains the XML representation of the NIC and not the virtual machine.

* \*\_nic_hotplug_*

* \*\_nic_hotunplug_*

* *_update_device

* *_device_create

* \*\_device_migrate_*
//Although the above looks like exposed markup when rendered, it is supposed to be that way; see the 4.1 version.

[IMPORTANT]
====
The *before_migration_destination* and *before_dehibernation* hooks currently receive the XML of the domain from the source host. The XML of the domain at the destination will have various differences.
====

The libvirt domain XML format is used by VDSM to define virtual machines. Details on the libvirt domain XML format can be found at link:http://libvirt.org/formatdomain.html[http://libvirt.org/formatdomain.html]. The UUID of the virtual machine may be deduced from the domain XML, but it is also available as the environment variable vmId.
