= Installing the CA certificate

The first time you access the VM Portal, you must install the certificate used by the {virt-product-fullname} {engine-name} to avoid security warnings.

*Installing the CA certificate in Firefox*

. Go to the VM Portal URL, and on the welcome page, click *CA Certificate*
. A file named `pki-resource` (with no file extension) will download.
. Open the Options/Preferences window:
** Windows: Open the Tools menu and select *Options...*
** Mac: Open the Firefox menu and select *Preferences...*
** Linux: Open the Edit menu and select *Preferences*
. Select *Privacy & Security*, and scroll down to *Certificates*.
. Click *View Certificates...* to open the Certificate Manager, and select the *Authorities* tab.
. Click *Import...*
. Select the file of the Root Certificate that you want to import (change file type to *All Files* to view the downloaded file).
. Select the check boxes indicating the trust options, and click *OK*.
. Click *OK* in the Certificate Manager, and close the Options/Preferences window.
. Make sure all Firefox processes are stopped.
. Restart Firefox and go to the VM Portal URL.  A lock icon in the address bar indicates that the CA certificate is installed.

*Installing the CA certificate in Google Chrome*

. Go to the VM Portal URL, and on the welcome page, click *CA Certificate*
. A file named `pki-resource` (with no file extension) will download.
. Go to menu:Settings[Advanced > Manage Certificates > Authorities] tab and click *IMPORT*.
. Select the file of the Root Certificate that you want to import (change file type to *All Files* to view the downloaded file).
. Select all the check boxes indicating the trust options, and click *OK*.
. Close Chrome and makes sure all the Chrome processes are stopped.
. Restart Chrome and go to the VM Portal URL. A lock icon in the address bar indicates that the CA certificate is installed.
