pressgang_website_callback([
	{"topicId":9476,"target":"Virtual_Machine_Network_Interface_dialogue_entries","title":"Explanation of Settings in the New Network Interface and Edit Network Interface Windows","newSince":""},
	{"topicId":9477,"target":"Adding_a_Network_Interface","title":"Adding a Network Interface","newSince":""},
	{"topicId":42245,"target":"sect-Sealing_Virtual_Machines_in_Preparation_for_Deployment_as_Templates","title":"Sealing Virtual Machines in Preparation for Deployment as Templates","newSince":""},
	{"topicId":41478,"target":"Cloning_a_Virtual_Machine","title":"Cloning a Virtual Machine","newSince":""},
	{"topicId":44809,"target":"Virtual_Machine_Icon_Settings_Explained","title":"Virtual Machine Icon Settings Explained","newSince":""},
	{"topicId":8715,"target":"Assigning_virtual_machines_to_users","title":"Assigning Virtual Machines to Users","newSince":""},
	{"topicId":30476,"target":"Removing_a_Network_Interface","title":"Removing a Network Interface","newSince":""},
	{"topicId":8719,"target":"Editing_network_interfaces1","title":"Editing a Network Interface","newSince":""},
	{"topicId":8721,"target":"Changing_ISO_images","title":"Changing the CD for a Virtual Machine","newSince":""},
	{"topicId":7189,"target":"To_remove_a_system_administrator_role_to_a_data_center","title":"Removing an Administrator or User Role from a Resource","newSince":""},
	{"topicId":8731,"target":"Configuring_SPICE_console_options1","title":"Accessing Console Options","newSince":""},
	{"topicId":29467,"target":"SPICE_Console_Options","title":"SPICE Console Options","newSince":""},
	{"topicId":29468,"target":"VNC_Console_Options","title":"VNC Console Options","newSince":""},
	{"topicId":29469,"target":"RDP_Console_Options","title":"RDP Console Options","newSince":""},
	{"topicId":8734,"target":"Using_SPICE_connection_options1","title":"Remote Viewer Options","newSince":""},
	{"topicId":8735,"target":"SPICE_hotkeys1","title":"Remote Viewer Hotkeys","newSince":""},
	{"topicId":8736,"target":"sect-Configuring_USB_Devices","title":"Using USB Devices on Virtual Machines - Introduction","newSince":""},
	{"topicId":8738,"target":"sect-Configuring_Single_Sign-On_for_Virtual_Machines","title":"Configuring Single Sign-On for Virtual Machines","newSince":""},
	{"topicId":13602,"target":"Updating_the_Red_Hat_Enterprise_Virtualization_Guest_Tools","title":"Updating the Guest Agents and Drivers on Windows","newSince":""},
	{"topicId":11555,"target":"Automating_Guest_Additions_on_Windows_Guests_with_Red_Hat_Enterprise_Virtualization_APT","title":"Automating Guest Additions on Windows Guests with Red Hat Enterprise Virtualization Application Provisioning Tool(APT)","newSince":""},
	{"topicId":8739,"target":"Configuring_Single_Sign_On_for_Windows_Virtual_Machines","title":"Configuring Single Sign-On for Windows Virtual Machines","newSince":""},
	{"topicId":30245,"target":"Adding_a_Watchdog_Card_to_a_Virtual_machine","title":"Adding a Watchdog Card to a Virtual Machine","newSince":""},
	{"topicId":30246,"target":"Configuring_a_Watchdog","title":"Installing a Watchdog","newSince":""},
	{"topicId":30247,"target":"Confirming_Watchdog_Functionality","title":"Confirming Watchdog Functionality","newSince":""},
	{"topicId":30248,"target":"Parameters_for_Watchdogs_in_watchdog.conf","title":"Parameters for Watchdogs in watchdog.conf","newSince":""},
	{"topicId":30763,"target":"sect-Sealing_a_Linux_Virtual_Machine_for_Deployment_as_a_Template","title":"Sealing a Linux Virtual Machine for Deployment as a Template","newSince":""},
	{"topicId":7468,"target":"Creating_a_new_virtual_machine_from_an_existing_template","title":"Creating a Virtual Machine Based on a Template","newSince":""},
	{"topicId":44845,"target":"Optimizing_Live_Migration","title":"Optimizing Live Migration","newSince":""},
	{"topicId":10803,"target":"Configuring_qxl_drivers_on_virtual_machines","title":"Installing and Configuring QXL Drivers","newSince":""},
	{"topicId":7476,"target":"Creating_a_new_virtual_machine_from_a_blank_template","title":"Creating a Linux Virtual Machine","newSince":""},
	{"topicId":10804,"target":"Configuring_a_virtual_machines_tablet_and_mouse_to_use_SPICE","title":"Configuring a Virtual Machine's Tablet and Mouse to use SPICE","newSince":""},
	{"topicId":7477,"target":"Creating_a_cloned_virtual_machine_from_an_existing_template","title":"Creating a Cloned Virtual Machine Based on a Template","newSince":""},
	{"topicId":34614,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":44860,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":44353,"target":"Updating_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux","title":"Updating the Guest Agents and Drivers on Red Hat Enterprise Linux","newSince":""},
	{"topicId":7491,"target":"Logging_in_to_a_virtual_machine_using_SPICE","title":"Opening a Console to a Virtual Machine","newSince":""},
	{"topicId":8771,"target":"sect-Exporting_and_Importing_Virtual_Machines_and_Templates","title":"Exporting and Importing Virtual Machines and Templates","newSince":""},
	{"topicId":8773,"target":"chap-Templates","title":"Introduction to Templates","newSince":""},
	{"topicId":10821,"target":"Virtual_Machine_Run_Once_settings_explained","title":"Explanation of Settings in the Run Once Window","newSince":""},
	{"topicId":8774,"target":"sect-Sealing_a_Windows_Virtual_Machine_for_Deployment_as_a_Template","title":"Considerations when Sealing a Windows Template with Sysprep","newSince":""},
	{"topicId":10822,"target":"Virtual_Machine_Custom_Properties_settings_explained","title":"Virtual Machine Custom Properties Settings Explained","newSince":""},
	{"topicId":7496,"target":"Powering_on_a_virtual_machine","title":"Starting a Virtual Machine","newSince":""},
	{"topicId":7497,"target":"Pausing_a_virtual_machine","title":"Suspending a Virtual Machine","newSince":""},
	{"topicId":7498,"target":"Shutting_down_a_virtual_machine","title":"Shutting Down a Virtual Machine","newSince":""},
	{"topicId":44878,"target":"Audience","title":"Audience","newSince":""},
	{"topicId":41551,"target":"Virtual_Machine_Random_Generator_Settings_Explained","title":"Virtual Machine Random Generator Settings Explained","newSince":""},
	{"topicId":44882,"target":"Importing_a_Virtual_Machine_from_a_VMware_Provider","title":"Importing a Virtual Machine from a VMware Provider","newSince":""},
	{"topicId":44883,"target":"Hot_Plugging_Virtual_Memory","title":"Hot Plugging Virtual Memory","newSince":""},
	{"topicId":7510,"target":"Removing_a_virtual_machine","title":"Removing a Virtual Machine","newSince":""},
	{"topicId":7511,"target":"Creating_a_snapshot_of_a_virtual_machine","title":"Creating a Snapshot of a Virtual Machine","newSince":""},
	{"topicId":7512,"target":"Using_a_snapshot_to_restore_a_virtual_machine","title":"Using a Snapshot to Restore a Virtual Machine","newSince":""},
	{"topicId":7513,"target":"Deleting_a_snapshot","title":"Deleting a Snapshot","newSince":""},
	{"topicId":30298,"target":"Rebooting_a_Virtual_Machine","title":"Rebooting a Virtual Machine","newSince":""},
	{"topicId":7514,"target":"Performing_an_exportimport_of_virtual_resources","title":"Graphical Overview for Exporting and Importing Virtual Machines and Templates","newSince":""},
	{"topicId":7515,"target":"Exporting_individual_virtual_machines_to_the_export_domain","title":"Exporting a Virtual Machine to the Export Domain","newSince":""},
	{"topicId":7516,"target":"Importing_the_virtual_machine_into_the_destination_data_center","title":"Importing a Virtual Machine into the Destination Data Center","newSince":""},
	{"topicId":24414,"target":"Installing_Cloud-Init","title":"Installing Cloud-Init","newSince":""},
	{"topicId":30303,"target":"sect-Installing_Console_Components","title":"Console Components","newSince":""},
	{"topicId":8799,"target":"sect-Migrating_Virtual_Machines_Between_Hosts","title":"What is Live Migration?","newSince":""},
	{"topicId":8800,"target":"Automatic_virtual_machine_migration","title":"Automatic Virtual Machine Migration","newSince":""},
	{"topicId":23136,"target":"Copying_a_Virtual_Machine_Hard_Disk","title":"Copying a Template's Virtual Hard Disk","newSince":""},
	{"topicId":44897,"target":"Creating_a_Windows_Virtual_Machine","title":"Creating a Windows Virtual Machine","newSince":""},
	{"topicId":14178,"target":"sect-Console_Options","title":"Introduction to Connection Protocols","newSince":""},
	{"topicId":8802,"target":"Why_use_high_availability","title":"Why Use High Availability?","newSince":""},
	{"topicId":8803,"target":"What_is_high_availability","title":"What is High Availability?","newSince":""},
	{"topicId":14180,"target":"Using_USB_Devices_on_a_Windows_Client","title":"Using USB Devices on a Windows Client","newSince":""},
	{"topicId":13412,"target":"Event_and_Log_Notification_upon_Automatic_Migration_of_Highly_Available_Virtual_Servers","title":"Event and Log Notification upon Automatic Migration of Highly Available Virtual Servers","newSince":""},
	{"topicId":14181,"target":"Using_USB_Devices_on_a_Red_Hat_Enterprise_Linux_Client","title":"Using USB Devices on a Red Hat Enterprise Linux Client","newSince":""},
	{"topicId":24421,"target":"Using_Cloud-Init","title":"Using Cloud-Init to Initialize a Virtual Machine","newSince":""},
	{"topicId":44905,"target":"chap-Installing_Linux_Virtual_Machines","title":"Introduction to Installing Linux Virtual Machines","newSince":""},
	{"topicId":44906,"target":"chap-Installing_Windows_Virtual_Machines","title":"Introduction to Installing Windows Virtual Machines","newSince":""},
	{"topicId":8298,"target":"High_availability_considerations","title":"High Availability Considerations","newSince":""},
	{"topicId":8299,"target":"Live_migration_prerequisites","title":"Live Migration Prerequisites","newSince":""},
	{"topicId":28523,"target":"Editing_a_Template","title":"Editing a Template","newSince":""},
	{"topicId":8300,"target":"Virtual_machine_performance_parameters","title":"Virtual Machine Performance Parameters","newSince":""},
	{"topicId":8301,"target":"Supported_virtual_machines","title":"Supported Virtual Machine Operating Systems","newSince":""},
	{"topicId":11633,"target":"Subscribing_to_channels_using_Subscription_Manager","title":"Subscribing to the Required Entitlements","newSince":""},
	{"topicId":24434,"target":"sect-Using_Cloud-Init_to_Automate_the_Configuration_of_Virtual_Machines","title":"Cloud-Init Overview","newSince":""},
	{"topicId":12659,"target":"Using_USB_Devices_on_Virtual_Machines_-_Native_Mode","title":"Using USB Devices on Virtual Machines","newSince":""},
	{"topicId":44916,"target":"Opening_a_Serial_Console_to_a_Virtual_Machine","title":"Opening a Serial Console to a Virtual Machine","newSince":""},
	{"topicId":8308,"target":"sect-Configuring_Red_Hat_Enterprise_Linux_5.4_and_Higher_Virtual_Machines_to_use_SPICE","title":"Using SPICE on virtual machines running versions of Red Hat Enterprise Linux released prior to 5.4","newSince":""},
	{"topicId":44926,"target":"Installing_usbdk_on_Windows","title":"Installing usbdk on Windows","newSince":""},
	{"topicId":8320,"target":"KVM_virtual_machine_timing_management","title":"KVM virtual machine timing management","newSince":""},
	{"topicId":12677,"target":"Editing_Virtual_Machine_Properties1","title":"Editing Virtual Machine Properties","newSince":""},
	{"topicId":12678,"target":"Associating_a_Virtual_Disk_with_a_Virtual_Machine","title":"Attaching an Existing Disk to a Virtual Machine","newSince":""},
	{"topicId":7559,"target":"Creating_a_template_from_an_existing_virtual_machine","title":"Creating a Template","newSince":""},
	{"topicId":7563,"target":"Sealing_a_Windows_XP_template","title":"Sealing a Windows XP Template","newSince":""},
	{"topicId":11148,"target":"Virtual_Machine_User_Roles_Explained","title":"Virtual Machine User Roles Explained","newSince":""},
	{"topicId":7564,"target":"Sealing_a_Linux_template","title":"Sealing a Linux Virtual Machine Manually for Deployment as a Template","newSince":""},
	{"topicId":12941,"target":"Removing_Access_to_Virtual_Machines_from_Users","title":"Removing Access to Virtual Machines from Users","newSince":""},
	{"topicId":11150,"target":"Template_User_Roles_Explained","title":"Template User Roles Explained","newSince":""},
	{"topicId":11151,"target":"Hot_plugging_virtual_machine_disks_and_network_interfaces","title":"Hot Plugging a Virtual Disk","newSince":""},
	{"topicId":9360,"target":"Red_Hat_Enterprise_Virtualization_Guest_Agents_and_Drivers","title":"Red Hat Enterprise Virtualization Guest Agents and Drivers","newSince":""},
	{"topicId":7571,"target":"Sealing_a_Windows_7_or_Windows_2008_template","title":"Sealing a Windows 7 or Windows 2008 Template","newSince":""},
	{"topicId":7575,"target":"Deleting_a_template","title":"Deleting a Template","newSince":""},
	{"topicId":7576,"target":"Exporting_individual_templates_to_the_export_domain","title":"Migrating Templates to the Export Domain","newSince":""},
	{"topicId":7320,"target":"To_assign_a_system_administrator_role_to_a_data_center","title":"Assigning an Administrator or User Role to a Resource","newSince":""},
	{"topicId":10393,"target":"Creating_a_virtual_machine_from_a_snapshot","title":"Creating a Virtual Machine from a Snapshot","newSince":""},
	{"topicId":10394,"target":"Virtual_Machine_General_settings_explained","title":"Virtual Machine General Settings Explained","newSince":""},
	{"topicId":10395,"target":"Virtual_Machine_Console_settings_explained","title":"Virtual Machine Console Settings Explained","newSince":""},
	{"topicId":10396,"target":"Virtual_Machine_Host_settings_explained","title":"Virtual Machine Host Settings Explained","newSince":""},
	{"topicId":10397,"target":"Virtual_Machine_High_Availability_settings_explained","title":"Virtual Machine High Availability Settings Explained","newSince":""},
	{"topicId":10398,"target":"Virtual_Machine_Resource_Allocation_settings_explained","title":"Virtual Machine Resource Allocation Settings Explained","newSince":""},
	{"topicId":7328,"target":"To_remove_a_system_administrator_role_to_a_cluster","title":"Explanation of Settings in the New Template and Edit Template Windows","newSince":""},
	{"topicId":10400,"target":"Virtual_Machine_Boot_Options_settings_explained","title":"Virtual Machine Boot Options Settings Explained","newSince":""},
	{"topicId":7586,"target":"Importing_a_template_into_a_data_center","title":"Importing a Template into a Data Center","newSince":""},
	{"topicId":30116,"target":"Importing_a_Virtual_Disk_Image_from_an_OpenStack_Image_Service_as_a_Template","title":"Importing a Virtual Disk Image from an OpenStack Image Service as a Template","newSince":""},
	{"topicId":12718,"target":"Configuring_Single_Sign-On_for_Red_Hat_Enterprise_Linux_Virtual_Machines","title":"Configuring Single Sign-On for Red Hat Enterprise Linux Virtual Machines Using IPA (IdM)","newSince":""},
	{"topicId":24495,"target":"Sealing_a_Linux_Virtual_Machine_for_Deployment_as_a_Template_using_sys-unconfig","title":"Sealing a Linux Virtual Machine for Deployment as a Template using sys-unconfig","newSince":""},
	{"topicId":42680,"target":"Disabling_Single_Sign-on_for_Virtual_Machines","title":"Disabling Single Sign-on for Virtual Machines","newSince":""},
	{"topicId":7608,"target":"Enabling_SAP_monitoring_for_a_virtual_machine_from_the_Administration_Portal","title":"Enabling SAP Monitoring","newSince":""},
	{"topicId":21952,"target":"Installing_Windows_on_Virtio_Optimized_Hardware","title":"Installing Windows on VirtIO-Optimized Hardware","newSince":""},
	{"topicId":13761,"target":"Hot_Plugging_Network_Interfaces","title":"Hot Plugging a Network Interface","newSince":""},
	{"topicId":9412,"target":"Adding_a_Virtual_Disk","title":"Adding a Virtual Disk","newSince":""},
	{"topicId":9415,"target":"Add_Virtual_Disk_dialogue_entries","title":"Explanation of Settings in the New Virtual Disk and Edit Virtual Disk Windows","newSince":""},
	{"topicId":25799,"target":"Virtual_Machine_System_Settings_Explained","title":"Virtual Machine System Settings Explained","newSince":""},
	{"topicId":8648,"target":"chap-Introduction","title":"Introduction to Virtual Machines","newSince":""},
	{"topicId":30154,"target":"Removing_Virtual_Disks_From_Virtual_Machines","title":"Removing a Virtual Disk from a Virtual Machine","newSince":""},
	{"topicId":40908,"target":"Installing_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux","title":"Installing the Guest Agents and Drivers on Red Hat Enterprise Linux","newSince":""},
	{"topicId":40909,"target":"Installing_the_Guest_Agents_and_Drivers_on_Windows","title":"Installing the Guest Agents and Drivers on Windows","newSince":""},
	{"topicId":7375,"target":"Installing_the_SPICE_plugin_for_Mozilla_Firefox_on_Linux","title":"Installing Remote Viewer on Red Hat Enterprise Linux","newSince":""},
	{"topicId":30432,"target":"sect-Affinity_Groups","title":"Introduction to Virtual Machine Affinity","newSince":""},
	{"topicId":11488,"target":"Cancelling_ongoing_virtual_machine_migrations","title":"Canceling Ongoing Virtual Machine Migrations","newSince":""},
	{"topicId":13537,"target":"Enabling_and_Disabling_Smartcards","title":"Smart Card Authentication","newSince":""},
	{"topicId":30433,"target":"Creating_an_Affinity_Group","title":"Creating an Affinity Group","newSince":""},
	{"topicId":30434,"target":"Editing_an_Affinity_Group","title":"Editing an Affinity Group","newSince":""},
	{"topicId":7906,"target":"Data_center_related_entities","title":"Managing System Permissions for a Template","newSince":""},
	{"topicId":7907,"target":"Data_center_storage_entities","title":"Virtual Machines Administrator Roles Explained","newSince":""},
	{"topicId":30435,"target":"Removing_an_Affinity_Group","title":"Removing an Affinity Group","newSince":""},
	{"topicId":7909,"target":"Data_center_cluster_entities","title":"Managing System Permissions for a Virtual Machine","newSince":""},
	{"topicId":30182,"target":"Cloud-Init_Use_Case_Scenarios","title":"Cloud-Init Use Case Scenarios","newSince":""},
	{"topicId":30183,"target":"Using_Cloud-Init_to_Prepare_a_Template","title":"Using Cloud-Init to Prepare a Template","newSince":""},
	{"topicId":25066,"target":"Installing_Remote_Viewer_on_Windows","title":"Installing Remote Viewer on Windows","newSince":""},
	{"topicId":7659,"target":"Preventing_automatic_migration_of_a_virtual_machine","title":"Preventing Automatic Migration of a Virtual Machine","newSince":""},
	{"topicId":7660,"target":"Manually_migrating_virtual_machines","title":"Manually Migrating Virtual Machines","newSince":""},
	{"topicId":7661,"target":"Setting_migration_priority","title":"Setting Migration Priority","newSince":""},
	{"topicId":7918,"target":"Logical_network_properties","title":"Template Administrator Roles Explained","newSince":""},
	{"topicId":30447,"target":"Manually_Associating_console.vv_Files_with_Remote_Viewer","title":"Manually Associating console.vv Files with Remote Viewer","newSince":""},
	{"topicId":7665,"target":"Configuring_a_highly_available_virtual_machine","title":"Configuring a Highly Available Virtual Machine","newSince":""},
	{"topicId":25076,"target":"Installing_USB_Clerk_on_Windows","title":"Installing USB Clerk on Windows","newSince":""},
	{"topicId":25077,"target":"Configuring_Multiple_Displays_for_Red_Hat_Enterprise_Linux_Guest_Virtual_Machines","title":"Configuring Multiple Displays for Red Hat Enterprise Linux Virtual Machines","newSince":""},
	{"topicId":10742,"target":"Virtual_Machine_Initial_Run_settings_explained","title":"Virtual Machine Initial Run Settings Explained","newSince":""},
	{"topicId":25079,"target":"Configuring_Multiple_Displays_for_Windows_Guest_Virtual_Machines","title":"Configuring Multiple Displays for Windows Virtual Machines","newSince":""},
	{"topicId":28668,"target":"Configuring_Single_Sign-On_for_Red_Hat_Enterprise_Linux_Virtual_Machines_Using_Active_Directory","title":"Configuring Single Sign-On for Red Hat Enterprise Linux Virtual Machines Using Active Directory","newSince":""},
	{"topicId":25597,"target":"Extending_the_Size_of_an_Online_Virtual_Disk","title":"Extending the Available Size of a Virtual Disk","newSince":""}], 23141, "Red Hat Enterprise Virtualization", "Virtual Machine Management Guide", "3.6-Beta");