pressgang_website_callback([
	{"topicId":41971,"target":"Installing_and_Configuring_Data_Warehouse_and_Reports_on_Separate_Machines","title":"Installing and Configuring Data Warehouse and Reports on Separate Machines","newSince":""},
	{"topicId":34614,"target":"Author_Group","title":"Author Group","newSince":""},
	{"topicId":30615,"target":"Upgrading_the_Self-Hosted_Engine","title":"Upgrading a RHEL-Based Self-Hosted Engine","newSince":""},
	{"topicId":25803,"target":"chap-Introduction","title":"About the Self-Hosted Engine","newSince":""},
	{"topicId":25665,"target":"Migrating_to_a_Self-Hosted_Environment","title":"Migrating to a Self-Hosted Environment","newSince":""},
	{"topicId":44843,"target":"Upgrading_a_RHEV-H-Based_Self-Hosted_Engine_Environment","title":"Upgrading a RHEV-H-Based Self-Hosted Engine Environment","newSince":""},
	{"topicId":7523,"target":"Installing_and_Configuring_Red_Hat_Enterprise_Virtualization_Manager_Reports1","title":"Installing and Configuring Data Warehouse and Reports on the Red Hat Enterprise Virtualization Manager","newSince":""},
	{"topicId":42445,"target":"Data_Warehouse_and_Reports_Configuration_Notes","title":"Data Warehouse and Reports Configuration Notes","newSince":""},
	{"topicId":25750,"target":"chap-Installing_Additional_Hosts_to_a_Self-Hosted_Environment","title":"Installing Additional Hosts to a Self-Hosted Environment","newSince":""},
	{"topicId":42377,"target":"Migrating_the_Data_Warehouse_Service_to_a_Separate_Machine","title":"Migrating the Data Warehouse Service to a Separate Machine","newSince":""},
	{"topicId":42376,"target":"Migrating_Data_Warehouse_and_Reports_to_Separate_Machines","title":"Migrating Data Warehouse and Reports to Separate Machines","newSince":""},
	{"topicId":8654,"target":"Data_Collection_Setup_and_Reports_Installation_Overview","title":"Overview of Configuring Data Warehouse and Reports","newSince":""},
	{"topicId":42378,"target":"Migrating_the_Reports_Service_to_a_Separate_Machine","title":"Migrating the Reports Service to a Separate Machine","newSince":""},
	{"topicId":25814,"target":"Maintaining_the_Self-Hosted_Engine","title":"Maintaining a RHEL-Based Self-Hosted Engine","newSince":""},
	{"topicId":44507,"target":"Creating_a_New_Self-Hosted_Engine_Environment_to_be_Used_as_the_Restored_Environment","title":"Creating a New Self-Hosted Engine Environment to be Used as the Restored Environment","newSince":""},
	{"topicId":44527,"target":"Restoring_the_Self-Hosted_Engine_Manager","title":"Restoring the Self-Hosted Engine Manager","newSince":""},
	{"topicId":44526,"target":"Backing_up_the_Self-Hosted_Engine_Manager_Virtual_Machine","title":"Backing up the Self-Hosted Engine Manager Virtual Machine","newSince":""},
	{"topicId":44525,"target":"chap-Backing_up_and_Restoring_a_RHEL-Based_Self-Hosted_Environment","title":"Backing up and Restoring a Self-Hosted Engine Environment","newSince":""},
	{"topicId":41538,"target":"Installing_and_Configuring_Data_Warehouse_and_Reports_on_the_Same_Separate_Machine","title":"Installing and Configuring Data Warehouse and Reports on the Same Separate Machine","newSince":""},
	{"topicId":44934,"target":"Migrating_the_Self-Hosted_Engine_Database_to_a_Remote_Server_Database","title":"Migrating the Self-Hosted Engine Database to a Remote Server Database","newSince":""},
	{"topicId":25552,"target":"Configuring_the_Self-Hosted_Engine","title":"Configuring a RHEL-Based Self-Hosted Engine","newSince":""},
	{"topicId":42757,"target":"Migrating_the_Data_Warehouse_Database_to_a_Separate_Machine","title":"Migrating the Data Warehouse Database to a Separate Machine","newSince":""},
	{"topicId":25551,"target":"Installing_the_Self-Hosted_Engine","title":"Installing the Self-Hosted Engine Packages","newSince":""},
	{"topicId":44546,"target":"Removing_Non-Operational_Hosts_from_a_Restored_Self-Hosted_Engine_Environment","title":"Removing Non-Operational Hosts from a Restored Self-Hosted Engine Environment","newSince":""},
	{"topicId":44545,"target":"Installing_Additional_Hosts_to_a_Restored_Self-Hosted_Engine_Environment","title":"Installing Additional Hosts to a Restored Self-Hosted Engine Environment","newSince":""},
	{"topicId":42468,"target":"Installing_and_Configuring_Data_Warehouse_on_a_Separate_Machine_and_Reports_on_the_Red_Hat_Enterprise_Virtualization_Manager","title":"Installing and Configuring Data Warehouse on a Separate Machine and Reports on the Red Hat Enterprise Virtualization Manager","newSince":""},
	{"topicId":30633,"target":"Upgrading_Additional_Hosts_in_a_Self-Hosted_Environment","title":"Upgrading Additional Hosts in a RHEL-Based Self-Hosted Environment","newSince":""},
	{"topicId":11568,"target":"Workflow_Progress_Data_Collection_Setup_and_Reports_Installation1","title":"Workflow Progress - Data Collection Setup and Reports Installation","newSince":""},
	{"topicId":42467,"target":"Installing_and_Configuring_Data_Warehouse_on_the_Red_Hat_Enterprise_Virtualization_Manager_and_Reports_on_a_Separate_Machine","title":"Installing and Configuring Data Warehouse on the Red Hat Enterprise Virtualization Manager and Reports on a Separate Machine","newSince":""},
	{"topicId":43241,"target":"Subscribing_to_the_Required_Entitlements","title":"Subscribing to the Required Entitlements","newSince":""},
	{"topicId":44824,"target":"appe-Revision_History","title":"Revision History","newSince":""},
	{"topicId":42466,"target":"sect-Data_Warehouse_and_Reports_Installation_Options","title":"Data Warehouse and Reports Installation Options","newSince":""},
	{"topicId":44623,"target":"Configuring_Self-Hosted_Engine_on_Red_Hat_Enterprise_Virtualization_Hypervisor","title":"Configuring Self-Hosted Engine on Red Hat Enterprise Virtualization Hypervisor","newSince":""},
	{"topicId":44826,"target":"Installing_Red_Hat_Enterprise_Virtualization_Hypervisor","title":"Installing Red Hat Enterprise Virtualization Hypervisor","newSince":""}], 23136, "Red Hat Enterprise Virtualization", "Self-Hosted Engine Guide", "3.6-Beta");