:_content-type: CONCEPT
[id="general-recommendations"]
= General Recommendations

* Take a full backup as soon as the deployment is complete, and store it in a separate location. Take regular backups thereafter. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#chap-Backups_and_Migration[Backups and Migration] in the _Administration Guide_.

* Avoid running any service that {virt-product-fullname} depends on as a virtual machine in the same environment. If this is done, it must be planned carefully to minimize downtime, if the virtual machine containing that service incurs downtime.

* Ensure the bare-metal host or virtual machine that the {virt-product-fullname} {engine-name} will be installed on has enough entropy. Values below 200 can cause the {engine-name} setup to fail. To check the entropy value, run `cat /proc/sys/kernel/random/entropy_avail`. To increase entropy, install the `rng-tools` package and follow the steps in link:https://access.redhat.com/solutions/1395493[].

* You can automate the deployment of hosts and virtual machines using PXE, Kickstart, Satellite, CloudForms, Ansible, or a combination thereof. However, installing a self-hosted engine using PXE is not supported. See:

** link:{URL_virt_product_docs}{URL_format}installing_{URL_product_virt}_as_a_standalone_manager_with_local_databases/index#Automating_RHVH_Deployment[Automating {hypervisor-fullname} Deployment] for the additional requirements for automated {hypervisor-shortname} deployment using PXE and Kickstart.
** link:{URL_rhel_docs_latest}html/performing_a_standard_rhel_installation/preparing-for-your-rhel-installation[Preparing for your installation] in  _Performing a Standard RHEL Installation_.
** link:{URL_rhel_docs_latest}html/performing_an_advanced_rhel_installation/performing_an_automated_installation_using_kickstart[Performing an Automated Installation Using Kickstart] in  _Performing an Advanced RHEL Installation_.
** link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.2/html/provisioning_guide/[_Red Hat Satellite 6.2 Provisioning Guide_].
** link:https://access.redhat.com/documentation/en-us/red_hat_cloudforms/5.0/html/provisioning_virtual_machines_and_instances/index[_Red Hat CloudForms 5.0 Provisioning Virtual Machines and Hosts_].

** link:{URL_virt_product_docs}{URL_format}administration_guide/index#chap-Automating_RHV_Configuration_using_Ansible[Automating Configuration Tasks using Ansible] in the _Administration Guide_.

* Set the system time zone for all machines in your deployment to UTC. This ensures that data collection and connectivity are not interrupted by variations in your local time zone, such as daylight savings time.

* Use Network Time Protocol (NTP) on all hosts and virtual machines in the environment in order to synchronize time. Authentication and certificates are particularly sensitive to time skew. Previously, NTP could be implemented using *chrony* (`chronyd`) or *ntp* (`ntpd`) but in {enterprise-linux} 8, only *chrony* is supported.
+
For information about migrating from *ntp* to *chrony*, see {URL_rhel_docs_latest}html/configuring_basic_system_settings/using-chrony-to-configure-ntp_configuring-basic-system-settings#proc_migrating-to-chrony_using-chrony-to-configure-ntp[Migrating to *chrony*].
+
For more information on *chrony*, see link:{URL_rhel_docs_latest}html/configuring_basic_system_settings/using-chrony-to-configure-ntp_configuring-basic-system-settings[Using the Chrony Suite to configure NTP].

* Document everything, so that anyone who works with the environment is aware of its current state and required procedures.
