[id="Upgrading_with_ovirt-fast-forward-upgrade_{context}"]
:Upgrading_with_ovirt-fast-forward-upgrade:

= Upgrading to {virt-product-fullname} {engine-name} 4.3 with `ovirt-fast-forward-upgrade`

.Procedure

. Log in to the {engine-name} machine and install the `ovirt-fast-forward-upgrade` tool:
+
[options="nowrap" subs="normal"]
----
# yum install ovirt-fast-forward-upgrade
----

. Run the following command to upgrade the {engine-name}, while creating a backup of the current version:
+
[options="nowrap" subs="normal"]
----
# ovirt-fast-forward-upgrade --backup --backup-dir=_/backup_
----
+
[NOTE]
====
{org-fullname} recommends using the `--backup` and `--backup-dir` options to create a backup of the current {engine-name}. If a backup directory is not specified, the backup is saved in `/tmp`.

The `--backup` option is a wrapper for the `engine-backup` tool and is equivalent to running the following command:
[options="nowrap" subs="normal"]
----
# engine-backup --scope=all --mode=backup --file=_file_name_ --log=_log_file_name_
----

To restore your backup, run `engine-backup` in `restore` mode:
[options="nowrap" subs="normal"]
----
# engine-backup --mode=restore
----

See link:{URL_virt_product_docs}admin-guide/administration-guide.html[Backing Up and Restoring the {virt-product-fullname} {engine-name}] in the _Administration Guide_ for details.
====
+
Alternatively, to upgrade without creating a backup, run the following command:
+
[options="nowrap" subs="normal"]
----
# ovirt-fast-forward-upgrade
----

. If there are errors, check the log: `/var/log/ovirt-engine/ovirt-fast-forward-upgrade.log`.

:Upgrading_with_ovirt-fast-forward-upgrade!:
