:_content-type: ASSEMBLY
[id='Set_up_Cinderlib']
= Setting up Cinderlib

ifdef::rhv-doc[]
[IMPORTANT]
====
Cinderlib is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features support scope, see link:https://access.redhat.com/support/offerings/techpreview/[Red Hat Technology Preview Features Support Scope].
====
endif::[]

.Setting up Cinderlib on the {engine-name}

. Enable the `openstack-cinderlib` repositories on Red Hat Enterprise Linux:
+
----

# subscription-manager repos --enable=openstack-16.2-cinderlib-for-rhel-8-x86_64-rpms
----

. Install the `OpenStack Cinderlib` package:
+
----
# dnf install -y python3-cinderlib
----
. In the {virt-product-fullname} {engine-name}, enable managed block domain support:
+
----
# engine-config -s ManagedBlockDomainSupported=true
----
. Restart the {engine-name} to save the new configuration:
+
----
# systemctl restart ovirt-engine
----

.Setting up Cinderlib on the host

. Enable the `openstack-cinderlib` repositories on Red Hat Enterprise Linux:
+
----
# subscription-manager repos --enable=openstack-16.2-cinderlib-for-rhel-8-x86_64-rpms
----

. Install the Python `brick` package:
+
----
# yum install -y python3-os-brick
----
. Restart the VDSM on the host to save the new configuration:
+
----
# systemctl restart vdsmd
----


.Using Cinderlib with a ceph driver

If you are using Cinderlib together with a ceph driver:

. Enable the following repositories on Red Hat Enterprise Linux:
+
----
# subscription-manager repos --enable=rhceph-4-tools-for-rhel-8-x86_64-rpms
----


. Run the following command on the {engine-name} and on the hosts:
+
----
# yum install -y ceph-common
----
