:_content-type: CONCEPT
[id="Recommended_practices_for_configuring_host_networks_{context}"]
= Recommended Practices for Configuring Host Networks

IMPORTANT: Always use the {virt-product-shortname} {engine-name} to modify the network configuration of hosts in your clusters. Otherwise, you might create an unsupported configuration. For details, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#con-Network-Manager-Stateful-Configuration-nmstate[Network Manager Stateful Configuration (nmstate)].

If your network environment is complex, you may need to configure a host network manually before adding the host to the {virt-product-fullname} {engine-name}.

Consider the following practices for configuring a host network:

* Configure the network with Cockpit. Alternatively, you can use `nmtui` or `nmcli`.

* If a network is not required for a self-hosted engine deployment or for adding a host to the {engine-name}, configure the network in the Administration Portal after adding the host to the {engine-name}. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#Creating_a_new_logical_network_in_a_data_center_or_cluster[Creating a New Logical Network in a Data Center or Cluster].

* Use the following naming conventions:

** VLAN devices: `_VLAN_NAME_TYPE_RAW_PLUS_VID_NO_PAD_`
** VLAN interfaces: `__physical_device__.__VLAN_ID__` (for example, `eth0.23`, `eth1.128`, `enp3s0.50`)
** Bond interfaces: `bond__number__` (for example, `bond0`, `bond1`)
** VLANs on bond interfaces: `bond__number__.__VLAN_ID__` (for example, `bond0.50`, `bond1.128`)

* Use link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-Network_Bonding[network bonding]. Network teaming is not supported in {virt-product-fullname} and will cause errors if the host is used to deploy a self-hosted engine or added to the {engine-name}.

* Use recommended bonding modes:

** If the `ovirtmgmt` network is not used by virtual machines, the network may use any supported bonding mode.
** If the `ovirtmgmt` network is used by virtual machines, see link:https://access.redhat.com/solutions/67546[_Which bonding modes work when used with a bridge that virtual machine guests or containers connect to?_].
** {virt-product-fullname}'s default bonding mode is `(Mode 4) Dynamic Link Aggregation`. If your switch does not support Link Aggregation Control Protocol (LACP), use `(Mode 1) Active-Backup`. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#Bonding_Modes[Bonding Modes] for details.

* Configure a VLAN on a physical NIC as in the following example (although `nmcli` is used, you can use any tool):
+
[source,terminal]
----
# nmcli connection add type vlan con-name __vlan50__ ifname __eth0.50__ dev __eth0__ id __50__
# nmcli con mod __vlan50__ +ipv4.dns 8.8.8.8 +ipv4.addresses __123.123__.0.1/24 +ivp4.gateway __123.123__.0.254
----

* Configure a VLAN on a bond as in the following example (although `nmcli` is used, you can use any tool):
+
[source,terminal]
----
# nmcli connection add type bond con-name __bond0__ ifname __bond0__ bond.options "mode=active-backup,miimon=100" ipv4.method disabled ipv6.method ignore
# nmcli connection add type ethernet con-name __eth0__ ifname __eth0__ master __bond0__ slave-type bond
# nmcli connection add type ethernet con-name __eth1__ ifname __eth1__ master __bond0__ slave-type bond
# nmcli connection add type vlan con-name __vlan50__ ifname __bond0.50__ dev __bond0__ id __50__
# nmcli con mod vlan50 +ipv4.dns 8.8.8.8 +ipv4.addresses __123.123__.0.1/24 +ivp4.gateway __123.123__.0.254
----

* Do not disable `firewalld`.

* Customize the firewall rules in the Administration Portal after adding the host to the {engine-name}. See link:{URL_virt_product_docs}{URL_format}administration_guide/index#Configuring_Host_Firewall_Rules[Configuring Host Firewall Rules].
