[id='Enabling_the_Red_Hat_Enterprise_Linux_Host_Repositories_{context}'']
= Enabling the {enterprise-linux-host-fullname} Repositories

To use a {enterprise-linux} machine as a host, you must register the system with the Content Delivery Network, attach the `{enterprise-linux} Server` and `{virt-product-fullname}` subscriptions, and enable the host repositories.

.Procedure

. Register your system with the Content Delivery Network, entering your Customer Portal user name and password when prompted:
+
[options="nowrap" subs="normal"]
----
# subscription-manager register
----
+
. Find the `{enterprise-linux} Server` and `{virt-product-fullname}` subscription pools and record the pool IDs:
+
[options="nowrap" subs="normal"]
----
# subscription-manager list --available
----
+
. Use the pool IDs to attach the subscriptions to the system:
+
[options="nowrap" subs="normal"]
----
# subscription-manager attach --pool=_poolid_
----
+
[NOTE]
====
To view currently attached subscriptions:
[options="nowrap" subs="normal"]
----
# subscription-manager list --consumed
----
To list all enabled repositories:
[options="nowrap" subs="normal"]
----
# dnf repolist
----
====

. Configure the repositories:
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms \
    --enable=rhv-4-mgmt-agent-for-rhel-8-x86_64-rpms \
    --enable=fast-datapath-for-rhel-8-x86_64-rpms \
    --enable=advanced-virt-for-rhel-8-x86_64-rpms \
    --enable=openstack-16.2-cinderlib-for-rhel-8-x86_64-rpms \
    --enable=rhceph-4-tools-for-rhel-8-x86_64-rpms
----
+
ifdef::SM_localDB_deploy,SM_remoteDB_deploy[]
//Not supported for SHE (doesn't appear as an option in the deployment)
For {enterprise-linux} 8 hosts, little endian, on IBM POWER8 or IBM POWER9 hardware:
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhv-4-mgmt-agent-for-rhel-8-ppc64le-rpms \
    --enable=rhv-4-tools-for-rhel-8-ppc64le-rpms \
    --enable=advanced-virt-for-rhel-8-ppc64le-rpms \
    --enable=rhel-8-for-ppc64le-appstream-rpms \
    --enable=rhel-8-for-ppc64le-baseos-rpms \
    --enable=openstack-16.2-cinderlib-for-rhel-8-x86_64-rpms \
    --enable=rhceph-4-tools-for-rhel-8-x86_64-rpms
----
endif::SM_localDB_deploy,SM_remoteDB_deploy[]

ifdef::SHE_deployment_host[]
. Reset the `virt` module:
+
[options="nowrap" subs="normal"]
+
----
# dnf module reset virt
----
+
[NOTE]
====
If this module is already enabled in the Advanced Virtualization stream, this step is not necessary, but it has no negative impact.

You can see the value of the stream by entering:
----
# dnf module list virt
----
====
+
. Enable the `virt` module in the Advanced Virtualization stream with the following command:

include::snip-Enable_virt_module.adoc[]

endif::SHE_deployment_host[]
+
. Ensure that all packages currently installed are up to date:
+
[options="nowrap" subs="normal"]
----
# dnf upgrade --nobest
----
//ansible lock addition

. Reboot the machine.
+
[NOTE]
====
include::snip-prevent_auto_module_loading.adoc[]
====
