[id='Deploying_the_Self-Hosted_Engine_Using_Cockpit_{context}']
= Deploying the self-hosted engine using Cockpit

[NOTE]
====
Using Cockpit to install the self-hosted engine is deprecated. Support for this installation method will be removed in a later release.
====

Deploy a self-hosted engine, using Cockpit to collect the details of your environment. Cockpit is enabled by default on {hypervisor-fullname}s. You can manually install Cockpit on {enterprise-linux-host-fullname}s.

You can customize the {engine-name} virtual machine during deployment, either manually, by pausing the deployment, or using automation.

* Selecting the *Pause Host* check-box pauses deployment after installing the {engine-name} and adding the deployment host to the {engine-name}. It also creates a lock file at `/tmp` with the suffix `_he_setup_lock` on the deployment host, enabling you to manually customize the virtual machine as needed. The deployment continues after you delete the lock file, or after 24 hours, whichever comes first.
* Adding an Ansible playbook to either the `enginevm_before_engine_setup` hook or the `enginevm_after_engine_setup` hook automatically runs the playbook.

.Prerequisites

* FQDNs prepared for your {engine-name} and the deployment host. Forward and reverse lookup records must both be set in the DNS.
* When using a block storage domain, either FCP or iSCSI, a single target LUN is the only supported setup for a self-hosted engine.
* (Optional) If you want to customize the {engine-name} virtual machine during deployment using automation, an Ansible playbook must be added. See xref:customizing_engine_vm_during_deployment_auto_SHE_cockpit_deploy[].

.Procedure

. Log in to Cockpit at `https://__HostIPorFQDN__:9090` and click menu:Virtualization[Hosted Engine].
. Click btn:[Start] under the *Hosted Engine* option.
. Enter the details for the {engine-name} virtual machine:
.. Enter the *Engine VM FQDN*. This is the FQDN for the {engine-name} virtual machine, not the base host.
.. Enter a *MAC Address* for the {engine-name} virtual machine, or accept a randomly generated one.
.. Choose either *DHCP* or *Static* from the *Network Configuration* drop-down list.
+
[NOTE]
====
For IPv6, {virt-product-fullname} supports only static addressing.
====
+
* If you choose *DHCP*, you must have a DHCP reservation for the {engine-name} virtual machine so that its host name resolves to the address received from DHCP. Specify its MAC address in the *MAC Address* field.
* If you choose *Static*, enter the following details:
** *VM IP Address* - The IP address must belong to the same subnet as the host. For example, if the host is in 10.1.1.0/24, the {engine-name} virtual machine’s IP must be in the same subnet range (10.1.1.1-254/24).
** *Gateway Address*
** *DNS Servers*
.. Select the *Bridge Interface* from the drop-down list.
.. Enter and confirm the virtual machine's *Root Password*.
.. Specify whether to allow *Root SSH Access*.
.. Enter the *Number of Virtual CPUs* for the virtual machine.
.. Enter the *Memory Size (MiB)*. The available memory is displayed next to the input field.
. Optionally expand the *Advanced* fields:
.. Enter a *Root SSH Public Key* to use for root access to the {engine-name} virtual machine.
.. Select or clear the *Edit Hosts File* check box to specify whether to add entries for the {engine-name} virtual machine and the base host to the virtual machine's `/etc/hosts` file. You must ensure that the host names are resolvable.
.. Change the management *Bridge Name*, or accept the default `ovirtmgmt`.
.. Enter the *Gateway Address* for the management bridge.
.. Enter the *Host FQDN* of the first host to add to the {engine-name}. This is the FQDN of the base host you are running the deployment on.
.. Select the *Pause Host* check-box to create a lock file, which pauses the deployment after adding the deployment host to the {engine-name}. Pausing the deployment enables you to customize the virtual machine as needed.
.. Specify how to check network connectivity by selecting one of the following options from the *Network Test* pop-up menu: *DNS*, *Ping*, *TCP*, *None*.
+
*DNS*:: Checks the connection to the DNS server.
*Ping*:: Attempts to ping the gateway.
*TCP*:: Creates a TCP connection to a host and port combination. Specify a destination IP address and port. Once the connection is successfully created, the network is considered to be alive. Ensure that the given host is able to accept incoming TCP connections on the given port.
*None*:: The network is always considered connected.
. Click *Next*.
. Enter and confirm the *Admin Portal Password* for the `admin@internal` user.
. Configure event notifications:
.. Enter the *Server Name* and *Server Port Number* of the SMTP server.
.. Enter the *Sender E-Mail Address*.
.. Enter the *Recipient E-Mail Addresses*.
. Click *Next*.
. Review the configuration of the {engine-name} and its virtual machine. If the details are correct, click *Prepare VM*.
+
The deployment script begins installing and configuring the {engine-name} virtual machine.

. (Optional) If you selected *Pause Host*, the deployment pauses after adding the deployment host to the {engine-name} and displays a message on the *Prepare VM* screen similar to `Pause execution until /tmp/ansible.<id>_he_setup_lock is removed, delete it once you are ready to proceed`.
+
You can now log in from the deployment host to the {engine-name} virtual machine to customize it.  You can log in with either the FQDN or the IP address of the {engine-name}. For example, if the FQDN of the {engine-name} is `manager.example.com`:
+
[options="nowrap" subs="normal"]
----
$ ssh \root@manager.example.com
----
+
[TIP]
====
In the installation log, the IP address is in `local_vm_ip`. The installation log is the most recent instance of `/var/log/ovirt-hosted-engine-setup/ovirt-hosted-engine-setup-ansible-bootstrap_local_vm*`.
====
+
.. Customize the {engine-name} virtual machine as needed.
.. When you are done, log in to the Administration Portal using a browser with the {engine-name} FQDN and make sure that the host's state is *Up*.
.. Delete the lock file and the deployment script automatically continues, configuring the {engine-name} virtual machine.
. When the virtual machine and {engine-name} installation is complete, click *Next*.
. Select the *Storage Type* from the drop-down list, and enter the details for the self-hosted engine storage domain:
* For NFS:
.. Enter the full address and path to the storage in the *Storage Connection* field.
.. If required, enter any *Mount Options*.
.. Enter the *Disk Size (GiB)*.
.. Select the *NFS Version* from the drop-down list.
.. Enter the *Storage Domain Name*.
* For iSCSI:
.. Enter the *Portal IP Address*, *Portal Port*, *Portal Username*, and *Portal Password*.
.. Click *Retrieve Target List* and select a target. You can only select one iSCSI target during the deployment, but multipathing is supported to connect all portals of the same portal group.
+
[NOTE]
====
To specify more than one iSCSI target, you must enable multipathing before deploying the self-hosted engine. See link:{URL_rhel_docs_legacy}html-single/dm_multipath/[_{enterprise-linux} DM Multipath_] for details. There is also a link:https://access.redhat.com/labs/multipathhelper/#/[Multipath Helper] tool that generates a script to install and configure multipath with different options.
====
+
.. Enter the *Disk Size (GiB)*.
.. Enter the *Discovery Username* and *Discovery Password*.
* For Fibre Channel:
.. Enter the *LUN ID*. The host bus adapters must be configured and connected, and the LUN must not contain any existing data. To reuse an existing LUN, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Reusing_LUNs[Reusing LUNs] in the _Administration Guide_.
.. Enter the *Disk Size (GiB)*.
* For {gluster-storage-fullname}:
.. Enter the full address and path to the storage in the *Storage Connection* field.
.. If required, enter any *Mount Options*.
.. Enter the *Disk Size (GiB)*.
. Click *Next*.
. Review the storage configuration. If the details are correct, click *Finish Deployment*.
. When the deployment is complete, click *Close*.
+
One data center, cluster, host, storage domain, and the {engine-name} virtual machine are already running. You can log in to the Administration Portal to add further resources.
. Optionally, add a directory server using the `ovirt-engine-extension-aaa-ldap-setup` interactive setup script so you can add additional users to the environment. For more information, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#sect-configuring_an_external_ldap_provider[Configuring an External LDAP Provider] in the _Administration Guide_.
. Optionally, deploy Grafana so you can monitor and display reports from your {virt-product-shortname} environment.
For more information, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#configuring_grafana[Configuring Grafana] in the _Administration Guide_.

The self-hosted engine's status is displayed in Cockpit's menu:Virtualization[Hosted Engine] tab. The {engine-name} virtual machine, the host running it, and the self-hosted engine storage domain are flagged with a gold crown in the Administration Portal.

[NOTE]
====
Both the {engine-name}'s I/O scheduler and the hypervisor that hosts the {engine-name} reorder I/O requests. This double reordering might delay I/O requests to the storage layer, impacting performance.

Depending on your data center, you might improve performance by changing the I/O scheduler to `none`. For more information, see link:{URL_rhel_docs_latest}html/monitoring_and_managing_system_status_and_performance/setting-the-disk-scheduler_monitoring-and-managing-system-status-and-performance[Available disk schedulers] in _Monitoring and managing system status and performance_ for RHEL.
====
