[id='Enabling_the_Red_Hat_Enterprise_Linux_Host_Repositories_{context}'']
= Enabling the {enterprise-linux-host-fullname} Repositories

To use a {enterprise-linux} machine as a host, you must register the system with the Content Delivery Network, attach the `{enterprise-linux} Server` and `{virt-product-fullname}` subscriptions, and enable the host repositories.

.Procedure

. Register your system with the Content Delivery Network, entering your Customer Portal user name and password when prompted:
+
[options="nowrap" subs="normal"]
----
# subscription-manager register
----
+
. Find the `{enterprise-linux} Server` and `{virt-product-fullname}` subscription pools and record the pool IDs:
+
[options="nowrap" subs="normal"]
----
# subscription-manager list --available
----
+
. Use the pool IDs to attach the subscriptions to the system:
+
[options="nowrap" subs="normal"]
----
# subscription-manager attach --pool=_poolid_
----
+
[NOTE]
====
To view currently attached subscriptions:
[options="nowrap" subs="normal"]
----
# subscription-manager list --consumed
----
To list all enabled repositories:
[options="nowrap" subs="normal"]
----
# yum repolist
----
====

. Configure the repositories:
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-7-server-rpms \
    --enable=rhel-7-server-rhv-4-mgmt-agent-rpms \
    --enable=rhel-7-server-ansible-2-rpms
----
+
For {enterprise-linux} 7 hosts, little endian, on IBM POWER8 hardware:
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-7-server-rhv-4-mgmt-agent-for-power-le-rpms \
    --enable=rhel-7-for-power-le-rpms
----
For {enterprise-linux} 7 hosts, little endian, on IBM POWER9 hardware:
+
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-7-server-rhv-4-mgmt-agent-for-power-9-rpms \
    --enable=rhel-7-for-power-9-rpms
----
. Ensure that all packages currently installed are up to date:
+
[options="nowrap" subs="normal"]
----
# yum update
----

. Reboot the machine.






