[id='Installing_Red_Hat_Enterprise_Linux_Hosts_{context}']
= Installing {enterprise-linux-host-fullname}s

ifdef::rhv-doc[]
A {enterprise-linux-host-fullname} is based on a standard basic installation of {enterprise-linux} 8 on a physical server, with the `{enterprise-linux} Server` and `{virt-product-fullname}` subscriptions attached.
endif::[]
ifdef::ovirt-doc[]
A {enterprise-linux-host-fullname} is based on a standard basic installation of {enterprise-linux} 8 on a physical server, with the `{enterprise-linux} Server` and `{virt-product-fullname}` repositories enabled.
endif::[]

For detailed installation instructions, see the link:{URL_rhel_docs_latest}html/performing_a_standard_rhel_installation/index.html[_Performing a standard {enterprise-linux-shortname} installation_].

The host must meet the minimum link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html/planning_and_prerequisites_guide/rhv_requirements#host-requirements[host requirements].

[IMPORTANT]
====
Virtualization must be enabled in your host's BIOS settings. For information on changing your host's BIOS settings, refer to your host's hardware documentation.
====

[IMPORTANT]
====
Do not install third-party watchdogs on {enterprise-linux-host-fullname}s. They can interfere with the watchdog daemon provided by VDSM.
====
