:_content-type: PROCEDURE
[id='Installing_Red_Hat_Virtualization_Hosts_{context}']
= Installing {hypervisor-fullname}s

{hypervisor-fullname} ({hypervisor-shortname}) is a minimal operating system based on {enterprise-linux} that is designed to provide a simple method for setting up a physical machine to act as a hypervisor in a {virt-product-fullname} environment. The minimal operating system contains only the packages required for the machine to act as a hypervisor, and features a Cockpit web interface for monitoring the host and performing administrative tasks. See link:http://cockpit-project.org/running.html[] for the minimum browser requirements.

{hypervisor-shortname} supports NIST 800-53 partitioning requirements to improve security. {hypervisor-shortname} uses a NIST 800-53 partition layout by default.

ifdef::rhv-doc[]
The host must meet the minimum  link:{URL_downstream_virt_product_docs}planning_and_prerequisites_guide/index#host-requirements[host requirements].
endif::rhv-doc[]

ifdef::ovirt-doc[]
The host must meet the minimum  link:{URL_virt_product_docs}installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#host-requirements[host requirements].
endif::ovirt-doc[]

include::../upgrade/snip_WARNING-detach_data_storage.adoc[]

.Procedure
ifdef::rhv-doc[]
. Go to the link:https://access.redhat.com/products/red-hat-virtualization#getstarted[Get Started with Red Hat Virtualization] on the Red Hat Customer Portal and log in.
. Click *Download Latest* to access the product
download page.
. Choose the appropriate *Hypervisor Image for RHV* from the list and click *Download Now*.
endif::[]
ifdef::ovirt-doc[]
. Visit the link:https://ovirt.org/download/node.html[oVirt Node Download] page.
. Choose the version of *oVirt Node* to download and click its *Installation ISO* link.
. Write the {hypervisor-fullname} Installation ISO disk image to a USB, CD, or DVD.
endif::[]
. Start the machine on which you are installing {hypervisor-shortname}, booting from the prepared installation media.
. From the boot menu, select *Install {hypervisor-shortname} {vername_rhv}* and press `Enter`.
+
[NOTE]
====
You can also press the `Tab` key to edit the kernel parameters. Kernel parameters must be separated by a space, and you can boot the system using the specified kernel parameters by pressing the `Enter` key. Press the `Esc` key to clear any changes to the kernel parameters and return to the boot menu.
====

. Select a language, and click btn:[Continue].
. Select a keyboard layout from the *Keyboard Layout* screen and click btn:[Done].
. Select the device on which to install {hypervisor-shortname} from the *Installation Destination* screen. Optionally, enable encryption. Click btn:[Done].
+
[IMPORTANT]
====
Use the *Automatically configure partitioning* option.
====
. Select a time zone from the *Time &amp; Date* screen and click btn:[Done].

. Select a network from the *Network &amp; Host Name* screen and click *Configure...* to configure the connection details.
+
[NOTE]
====
To use the connection every time the system boots, select the *Connect automatically with priority* check box. For more information, see link:{URL_rhel_docs_latest}html/performing_a_standard_rhel_installation/graphical-installation_graphical-installation#network-hostname_configuring-system-settings[Configuring network and host name options] in the _{enterprise-linux} 8 Installation Guide_.
====
+
Enter a host name in the *Host Name* field, and click *Done*.
. Optionally configure *Language Support*, *Security Policy*, and *Kdump*. See link:{URL_rhel_docs_latest}html/performing_a_standard_rhel_installation/graphical-installation_graphical-installation[Customizing your RHEL installation using the GUI] in _Performing a standard RHEL installation_ for _{enterprise-linux} 8 for more information on each of the sections in the *Installation Summary* screen.
. Click *Begin Installation*.
. Set a root password and, optionally, create an additional user while {hypervisor-shortname} installs.
+
[WARNING]
====
Do not create untrusted users on {hypervisor-shortname}, as this can lead to exploitation of local security vulnerabilities.
====
+
. Click *Reboot* to complete the installation.
+
[NOTE]
====
When {hypervisor-shortname} restarts, `nodectl check` performs a health check on the host and displays the result when you log in on the command line. The message `node status: OK` or `node status: DEGRADED` indicates the health status. Run `nodectl check` to get more information.
====
+
[NOTE]
====
include::snip-prevent_auto_module_loading.adoc[]
====
