:_content-type: PROCEDURE
[id='Enabling_the_Red_Hat_Virtualization_Manager_Repositories_{context}']
= Enabling the {virt-product-fullname} {engine-name} Repositories

ifdef::rhv-doc[]

You need to log in and register the
ifndef::offline_install,install_DWH_remote,remote_database_install,migrate_SHE_DB,migrate_DWH_DB[{engine-name} machine ]
ifdef::install_DWH_remote,migrate_DWH_DB[Data Warehouse machine ]
ifdef::remote_database_install,migrate_SHE_DB[database machine ]
ifdef::offline_install[online machine ]
with Red Hat Subscription Manager, attach the `{virt-product-fullname} {engine-name}` subscription, and enable the {engine-name} repositories.

.Procedure

. Register your system with the Content Delivery Network, entering your Customer Portal user name and password when prompted:
+
[source,terminal,subs="normal"]
----
# subscription-manager register
----
+
[NOTE]
====
If you are using an IPv6 network, use an IPv6 transition mechanism to access the Content Delivery Network and subscription manager.
====

. Find the `{virt-product-fullname} {engine-name}` subscription pool and record the pool ID:
+
[source,terminal,subs="normal"]
----
# subscription-manager list --available
----

. Use the pool ID to attach the subscription to the system:
+
[source,terminal,subs="normal"]
----
# subscription-manager attach --pool=_pool_id_
----
+
[NOTE]
====
To view currently attached subscriptions:
[source,terminal,subs="normal"]
----
# subscription-manager list --consumed
----
To list all enabled repositories:
[source,terminal,subs="normal"]
----
# dnf repolist
----
====
. Set the RHEL version to 8.6
+
[source,terminal,subs="normal"]
----
# subscription-manager release --set=8.6
----

. Configure the repositories:
+
ifndef::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
[source,terminal,subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-eus-rpms \
    --enable=rhel-8-for-x86_64-appstream-eus-rpms
    --enable=rhv-4.4-manager-for-rhel-8-x86_64-rpms \
    --enable=fast-datapath-for-rhel-8-x86_64-rpms \
    --enable=jb-eap-7.4-for-rhel-8-x86_64-rpms \
    --enable=openstack-16.2-cinderlib-for-rhel-8-x86_64-rpms \
    --enable=rhceph-4-tools-for-rhel-8-x86_64-rpms

----
endif::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
ifdef::remote_database_install,manual_database_install,migrate_DWH_DB,install_DWH_remote[]
[source,terminal,subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-eus-rpms \
    --enable=rhel-8-for-x86_64-appstream-eus-rpms
    --enable=rhv-4.4-manager-for-rhel-8-x86_64-rpms
----
endif::remote_database_install,manual_database_install,migrate_DWH_DB,install_DWH_remote[]
ifdef::migrate_SHE_DB,migrate_manager_db[]
[source,terminal,subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-eus-rpms \
    --enable=rhel-8-for-x86_64-appstream-eus-rpms
----
endif::migrate_SHE_DB,migrate_manager_db[]
endif::rhv-doc[]

ifdef::ovirt-doc[]

Ensure the correct repositories are enabled.

For oVirt 4.5:
If you are going to install on RHEL or derivatives please follow link:/download/install_on_rhel.html[Installing on RHEL or derivatives] first.

[source,terminal,subs="normal"]
----
# dnf install -y centos-release-ovirt45
----

For oVirt 4.4:

[source,terminal,subs="normal"]
----
# dnf install https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm
----

Common procedure valid for both 4.4 and 4.5 on {enterprise-linux} 8 only:

You can check which repositories are currently enabled by running `dnf repolist`.

. Enable the `javapackages-tools` module.
+
[source,terminal,subs="normal"]
----
# dnf module -y enable javapackages-tools
----
endif::ovirt-doc[]

ifndef::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,migrate_manager_db[]
. Enable the `pki-deps` module.
+
[source,terminal,subs="normal"]
+
----
# dnf module -y enable pki-deps
----
endif::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,migrate_manager_db[]
. Enable version 12 of the `postgresql` module.
+
[source,terminal,subs="normal"]
+
----
# dnf module -y enable postgresql:12
----
ifdef::ovirt-doc[]
. Enable version 2.3 of the `mod_auth_openidc` module.
+
[source,terminal,subs="normal"]
+
----
# dnf module -y enable mod_auth_openidc:2.3
----
endif::ovirt-doc[]
. Enable version 14 of the `nodejs` module:
[source,terminal,subs="normal"]
+
----
# dnf module -y enable nodejs:14
----
ifdef::SHE_cli_deploy[]
. Update the Self-Hosted Engine using the procedure  link:{URL_virt_product_docs}{URL_format}/upgrade_guide/index#Updating_a_self-hosted_engine_minor_updates[Updating a Self-Hosted Engine] in the _Upgrade Guide_.
endif::SHE_cli_deploy[]

ifndef::SHE_cli_deploy[]
. Synchronize installed packages to update them to the latest available versions.
+
[source,terminal,subs="normal"]
----
# dnf distro-sync --nobest
----
endif::SHE_cli_deploy[]

//ansible lock addition
.Additional resources
For information on modules and module streams, see the following sections in _Installing, managing, and removing user-space components_

* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#module-streams_introduction-to-modules[Module streams]
* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#selecting-a-stream-before-installation-of-packages_installing-rhel-8-content[Selecting a stream before installation of packages]
* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#resetting-module-streams_removing-rhel-8-content[Resetting module streams]
* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#switching-to-a-later-stream_managing-versions-of-appstream-content[Switching to a later stream]

////
//for later build
ifdef::rhv-doc[]
. Enable the `maven` module:
[source,terminal,subs="normal"]
+
----
# dnf module -y enable maven:3.5
----
endif::rhv-doc[]
ifdef::ovirt-doc[]
. Enable the `maven` module:
[source,terminal,subs="normal"]
+
----
# dnf module -y enable maven:3.6
----
endif::ovirt-doc[]
////
