:_content-type: PROCEDURE
[id='Installing_a_vGPU_on_a_Virtual_Machine']
= Installing a vGPU on a Virtual Machine

:context: install_vgpu
:install_vgpu:

You can use a host with a compatible graphics processing unit (GPU) to run virtual machines with virtual GPUs (vGPUs). A virtual machine with a vGPU is better suited for graphics-intensive tasks than a virtual machine without a vGPU. A virtual machine with a vGPU can also run software that cannot run without a GPU, such as CAD.

include::../prereqs/ref-vGPU_Requirements.adoc[leveloffset=+1]

== Preparing a Host for vGPU Installation

. Install vGPU-capable drivers onto your host. Consult the documentation for your GPU card for more information.
. Install *vdsm-hook-vfio-mdev*:
+
[source,terminal,subs="normal"]
----
# dnf install vdsm-hook-vfio-mdev
----

You can now install vGPUs on the virtual machines running on this host.

== Installing a vGPU on a Virtual Machine

. Confirm the vGPU instance to use:
* Click menu:Compute[Hosts], click the required host's name to go to the details view, and click the *Host Devices* tab. Available vGPU instances appear in the *Mdev Types* column.

* Alternatively, run the following command on the host:
+
[source,terminal,subs="normal"]
----
# vdsm-client Host hostdevListByCaps
----
+
Available vGPU instances appear in the *mdev* key *available_instances*.

. Install the required virtual machine operating system. See xref:Installing_Red_Hat_Enterprise_Linux_Virtual_Machines[Installing Red Hat Enterprise Linux Virtual Machines] or xref:chap-Installing_Windows_Virtual_Machines[Installing Windows Virtual Machines].

. Shut down the virtual machine.

. Add the vGPU instance to the virtual machine:
.. Select the virtual machine and click btn:[Edit].
.. Click btn:[Show Advanced Options], then click the *Custom Properties* tab.
.. Select *mdev_type* from the drop-down list and enter the vGPU instance in the text field.
.. Click btn:[OK].
. Start the virtual machine and install the vGPU driver through the vendor's installer. Consult the documentation for your GPU card for more information.
. Restart the virtual machine.
. Verify that the vGPU is recognized by checking the virtual machine operating system's device manager.

[IMPORTANT]
====
You cannot migrate a virtual machine using a vGPU to a different host. When upgrading the virtual machine, verify the operating system and GPU vendor support in the vendor's documentation.
====
