[id='Enabling_the_Red_Hat_Virtualization_Manager_Repositories_{context}']
= Enabling the {virt-product-fullname} {engine-name} Repositories

ifdef::rhv-doc[]

Register the system with Red Hat Subscription Manager, attach the `{virt-product-fullname} {engine-name}` subscription, and enable {engine-name} repositories.
// review above

.Procedure

. Register your system with the Content Delivery Network, entering your Customer Portal user name and password when prompted:
+
[options="nowrap" subs="normal"]
----
# subscription-manager register
----
+
[NOTE]
====
If you are using an IPv6 network, use an IPv6 transition mechanism to access the Content Delivery Network and subscription manager.
====

. Find the `{virt-product-fullname} {engine-name}` subscription pool and record the pool ID:
+
[options="nowrap" subs="normal"]
----
# subscription-manager list --available
----

. Use the pool ID to attach the subscription to the system:
+
[options="nowrap" subs="normal"]
----
# subscription-manager attach --pool=_pool_id_
----
+
[NOTE]
====
To view currently attached subscriptions:
[options="nowrap" subs="normal"]
----
# subscription-manager list --consumed
----
To list all enabled repositories:
[options="nowrap" subs="normal"]
----
# yum repolist
----
====

. Configure the repositories:
+
ifndef::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms \
    --enable=rhv-4-manager-beta-for-rhel-8-x86_64-rpms \
    --enable=fast-datapath-for-rhel-8-x86_64-rpms \    
    --enable=ansible-2.9-for-rhel-8-x86_64-rpms \
    --enable=jb-eap-7.3-for-rhel-8-x86_64-rpms
----
endif::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
ifdef::remote_database_install,manual_database_install,migrate_DWH_DB,install_DWH_remote[]
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms \
    --enable=rhv-4-manager-beta-for-rhel-8-x86_64-rpms \
----
endif::remote_database_install,manual_database_install,migrate_DWH_DB,install_DWH_remote[]
ifdef::migrate_SHE_DB,migrate_manager_db[]
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms \
----
endif::migrate_SHE_DB,migrate_manager_db[]

endif::rhv-doc[]

ifdef::ovirt-doc[]

Ensure the correct repositories are enabled:

[options="nowrap" subs="normal"]
----
# yum install https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm
----

You can check which repositories are currently enabled by running `yum repolist`.

. Enable version the `javapackages-tools` module.
+
[options="nowrap" subs="normal"]
+
----
# yum module -y javapackages-tools
----


endif::ovirt-doc[]



ifndef::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
. Enable the `pki-deps` module.
+
[options="nowrap" subs="normal"]
+
----
# yum module -y enable pki-deps
----
endif::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
. Enable version 12 of the `postgresql` module.
+
[options="nowrap" subs="normal"]
+
----
# yum module -y enable postgresql:12
----
