:_content-type: PROCEDURE
[id='Configuring_the_Red_Hat_Virtualization_Manager_{context}']
= Installing and Configuring the {virt-product-fullname} {engine-name}

Install the package and dependencies for the {virt-product-fullname} {engine-name}, and configure it using the `engine-setup` command. The script asks you a series of questions and, after you provide the required values for all questions, applies that configuration and starts the `ovirt-engine` service.

[IMPORTANT]
====
The `engine-setup` command guides you through several distinct configuration stages, each comprising several steps that require user input. Suggested configuration defaults are provided in square brackets; if the suggested value is acceptable for a given step, press `Enter` to accept that value.

You can run `engine-setup --accept-defaults` to automatically accept all questions that have default answers. This option should be used with caution and only if you are familiar with `engine-setup`.
====


.Procedure

. Ensure all packages are up to date:
+
[source,terminal]
----
# dnf upgrade --nobest
----
//ansible lock addition
+
[NOTE]
====
Reboot the machine if any kernel-related packages were updated.
====

. Install the `{engine-package}` package and dependencies.
+
ifdef::rhv-doc[]
[source,terminal]
----
# dnf install rhvm
----
endif::rhv-doc[]

ifdef::ovirt-doc[]
[source,terminal]
----
# dnf install ovirt-engine
----
endif::ovirt-doc[]
. Run the `engine-setup` command to begin configuring the {virt-product-fullname} {engine-name}:
+
[source,terminal]
----
# engine-setup
----
. Optional: Type *Yes* and press `Enter` to set up Cinderlib integration on this machine:
+
[source,terminal]
----
Set up Cinderlib integration
(Currently in tech preview)
(Yes, No) [No]:
----
+
[IMPORTANT]
====
Cinderlib is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features support scope, see link:https://access.redhat.com/support/offerings/techpreview/[Red Hat Technology Preview Features Support Scope].
====

. Press `Enter` to configure the {engine-name} on this machine:
+
[source,terminal]
----
Configure Engine on this host (Yes, No) [Yes]:
----
. Optional: Install Open Virtual Network (OVN). Selecting `Yes` installs an OVN server on the {engine-name} machine and adds it to {virt-product-fullname} as an external network provider. This action also configures the Default cluster to use OVN as its default network provider.
+
[IMPORTANT]
====
Also see the "Next steps" in link:{URL_virt_product_docs}{URL_format}administration_guide/index#Installing-OVN-next-steps[Adding Open Virtual Network (OVN) as an External Network Provider] in the _Administration Guide_.
====
+
[source,terminal]
----
Configuring ovirt-provider-ovn also sets the Default cluster's default network provider to ovirt-provider-ovn.
Non-Default clusters may be configured with an OVN after installation.
Configure ovirt-provider-ovn (Yes, No) [Yes]:
----
+
For more information on using OVN networks in {virt-product-fullname}, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Adding_OVN_as_an_External_Network_Provider[Adding Open Virtual Network (OVN) as an External Network Provider] in the _Administration Guide_.

. Optional: Allow `engine-setup` to configure a WebSocket Proxy server for allowing users to connect to virtual machines through the `noVNC` console:
+
[source,terminal]
----
Configure WebSocket Proxy on this machine? (Yes, No) [Yes]:
----
+
ifdef::rhv-doc[]
[IMPORTANT]
====
The WebSocket Proxy and noVNC are Technology Preview features only. Technology Preview features are not supported with Red Hat production service-level agreements (SLAs) and might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information see link:https://access.redhat.com/support/offerings/techpreview/[Red Hat Technology Preview Features Support Scope].
====
endif::[]
ifdef::SM_remoteDB_deploy[]
. To configure Data Warehouse on a remote server, answer `No` and see xref:Installing_and_Configuring_Data_Warehouse_on_a_Separate_Machine_install_RHVM[Installing and Configuring Data Warehouse on a Separate Machine] after completing the {engine-name} configuration.
+
[source,terminal]
----
Please note: Data Warehouse is required for the engine. If you choose to not configure it on this host, you have to configure it on a remote host, and then configure the engine on this host so that it can access the database of the remote Data Warehouse host.
Configure Data Warehouse on this host (Yes, No) [Yes]:
----
+
[IMPORTANT]
====
{org-fullname} only supports installing the Data Warehouse database, the Data Warehouse service, and Grafana all on the same machine as each other.
====
+
. To configure Grafana on the same machine as the Data Warehouse service, enter `No`:
+
[source,terminal]
----
Configure Grafana on this host (Yes, No) [Yes]:
----
endif::SM_remoteDB_deploy[]

ifdef::SM_localDB_deploy[]
. Choose whether to configure Data Warehouse on this machine.
+
[source,terminal]
----
Please note: Data Warehouse is required for the engine. If you choose to not configure it on this host, you have to configure it on a remote host, and then configure the engine on this host so that it can access the database of the remote Data Warehouse host.
Configure Data Warehouse on this host (Yes, No) [Yes]:
----
+
[IMPORTANT]
====
{org-fullname} only supports installing the Data Warehouse database, the Data Warehouse service, and Grafana all on the same machine as each other.
====
+
. Press `Enter` to configure Grafana on the {engine-name}:
+
[source,terminal]
----
Configure Grafana on this host (Yes, No) [Yes]:
----
endif::SM_localDB_deploy[]
+
. Optional: Allow access to a virtual machine's serial console from the command line.
+
[source,terminal]
----
Configure VM Console Proxy on this host (Yes, No) [Yes]:
----
Additional configuration is required on the client machine to use this feature. See link:{URL_virt_product_docs}{URL_format}virtual_machine_management_guide/index#Opening_a_Serial_Console_to_a_Virtual_Machine[Opening a Serial Console to a Virtual Machine] in the _Virtual Machine Management Guide_.

. Press `Enter` to accept the automatically detected host name, or enter an alternative host name and press `Enter`. Note that the automatically detected host name may be incorrect if you are using virtual hosts.
+
[source,terminal]
----
Host fully qualified DNS name of this server [_autodetected host name_]:
----

. The `engine-setup` command checks your firewall configuration and offers to open the ports used by the {engine-name} for external communication, such as ports 80 and 443. If you do not allow `engine-setup` to modify your firewall configuration, you must manually open the ports used by the {engine-name}. `firewalld` is configured as the firewall manager.
+
[source,terminal]
----
Setup can automatically configure the firewall on this system.
Note: automatic configuration of the firewall may overwrite current settings.
Do you want Setup to configure the firewall? (Yes, No) [Yes]:
----
+
If you choose to automatically configure the firewall, and no firewall managers are active, you are prompted to select your chosen firewall manager from a list of supported options. Type the name of the firewall manager and press `Enter`. This applies even in cases where only one option is listed.
+
ifdef::SM_localDB_deploy[]
//Only appears if you answer Yes to installing DWH on the {engine-name}
. Specify whether to configure the Data Warehouse database on this machine, or on another machine:
+
[source,terminal]
----
Where is the DWH database located? (Local, Remote) [Local]:
----

** If you select `Local`, the `engine-setup` script can configure your database automatically (including adding a user and a database), or it can connect to a preconfigured local database:
+
[source,terminal]
----
Setup can configure the local postgresql server automatically for the DWH to run. This may conflict with existing applications.
Would you like Setup to automatically configure postgresql and create DWH database, or prefer to perform that manually? (Automatic, Manual) [Automatic]:
----
+
*** If you select `Automatic` by pressing `Enter`, no further action is required here.
*** If you select `Manual`, input the following values for the manually configured local database:
+
[source,terminal]
----
DWH database secured connection (Yes, No) [No]:
DWH database name [ovirt_engine_history]:
DWH database user [ovirt_engine_history]:
DWH database password:
----
+
[NOTE]
====
`engine-setup` requests these values after the {engine-name} database is configured in the next step.
====

** If you select `Remote` (for example, if you are installing the Data Warehouse service on the {engine-name} machine, but have configured a remote Data Warehouse database), input the following values for the remote database server:
+
[source,terminal]
----
DWH database host [localhost]:
DWH database port [5432]:
DWH database secured connection (Yes, No) [No]:
DWH database name [ovirt_engine_history]:
DWH database user [ovirt_engine_history]:
DWH database password:
----
+
[NOTE]
====
`engine-setup` requests these values after the {engine-name} database is configured in the next step.
====

** If you select `Remote`, you are prompted to enter the username and password for the Grafana database user:
+
[source,terminal]
----
Grafana database user [ovirt_engine_history_grafana]:
Grafana database password:
----
endif::SM_localDB_deploy[]

. Specify whether to configure the {engine-name} database on this machine, or on another machine:
+
[source,terminal]
----
Where is the Engine database located? (Local, Remote) [Local]:
----

ifdef::SM_localDB_deploy[]
** If you select `Local`, the `engine-setup` command can configure your database automatically (including adding a user and a database), or it can connect to a preconfigured local database:
+
[source,terminal]
----
Setup can configure the local postgresql server automatically for the engine to run. This may conflict with existing applications.
Would you like Setup to automatically configure postgresql and create Engine database, or prefer to perform that manually? (Automatic, Manual) [Automatic]:
----

***  If you select `Automatic` by pressing `Enter`, no further action is required here.
*** If you select `Manual`, input the following values for the manually configured local database:
+
[source,terminal]
----
Engine database secured connection (Yes, No) [No]:
Engine database name [engine]:
Engine database user [engine]:
Engine database password:
----
endif::SM_localDB_deploy[]

ifdef::SM_remoteDB_deploy[]
+
[NOTE]
====
Deployment with a remote engine database is now deprecated. This functionality will be removed in a future release.
====
+
If you select `Remote`, input the following values for the preconfigured remote database server. Replace `localhost` with the ip address or FQDN of the remote database server:
+
[source,terminal]
----
Engine database host [localhost]:
Engine database port [5432]:
Engine database secured connection (Yes, No) [No]:
Engine database name [engine]:
Engine database user [engine]:
Engine database password:
----
endif::SM_remoteDB_deploy[]

. Set a password for the automatically created administrative user of the {virt-product-fullname} {engine-name}:
+
[source,terminal]
----
Engine admin password:
Confirm engine admin password:
----

. Select *Gluster*, *Virt*, or *Both*:
+
[source,terminal]
----
Application mode (Both, Virt, Gluster) [Both]:
----
* *Both* - offers the greatest flexibility. In most cases, select *Both*.
* *Virt* - allows you to run virtual machines in the environment.
* *Gluster* - only allows you to manage GlusterFS from the Administration Portal.

. If you installed the OVN provider, you can choose to use the default credentials, or specify an alternative.
+
[source,terminal]
----
Use default credentials (admin@internal) for ovirt-provider-ovn (Yes, No) [Yes]:
oVirt OVN provider user[admin@internal]:
oVirt OVN provider password:
----

. Set the default value for the `wipe_after_delete` flag, which wipes the blocks of a virtual disk when the disk is deleted.
+
[source,terminal]
----
Default SAN wipe after delete (Yes, No) [No]:
----

. The {engine-name} uses certificates to communicate securely with its hosts. This certificate can also optionally be used to secure HTTPS communications with the {engine-name}. Provide the organization name for the certificate:
+
[source,terminal]
----
Organization name for certificate [_autodetected domain-based name_]:
----

. Optionally allow `engine-setup` to make the landing page of the {engine-name} the default page presented by the Apache web server:
+
[source,terminal]
----
Setup can configure the default page of the web server to present the application home page. This may conflict with existing applications.
Do you wish to set the application as the default web page of the server? (Yes, No) [Yes]:
----

. By default, external SSL (HTTPS) communication with the {engine-name} is secured with the self-signed certificate created earlier in the configuration to securely communicate with hosts. Alternatively, choose another certificate for external HTTPS connections; this does not affect how the {engine-name} communicates with hosts:
+
[source,terminal]
----
Setup can configure apache to use SSL using a certificate issued from the internal CA.
Do you wish Setup to configure that, or prefer to perform that manually? (Automatic, Manual) [Automatic]:
----
+
. You can specify a unique password for the Grafana admin user, or use same one as the {engine-name} admin password:
+
[source,terminal]
----
Use Engine admin password as initial Grafana admin password (Yes, No) [Yes]:
----
+
ifdef::SM_localDB_deploy[]
//Only appears if you answer Yes to installing DWH on the {engine-name} machine
. Choose how long Data Warehouse will retain collected data:
+
[source,terminal]
----
Please choose Data Warehouse sampling scale:
(1) Basic
(2) Full
(1, 2)[1]:
----
`Full` uses the default values for the data storage settings listed in the link:{URL_virt_product_docs}{URL_format}data_warehouse_guide/index#Application_Settings_for_the_Data_Warehouse_service_in_ovirt-engine-dwhd_file[_Data Warehouse Guide_] (recommended when Data Warehouse is installed on a remote server).
+
`Basic` reduces the values of `DWH_TABLES_KEEP_HOURLY` to `720` and `DWH_TABLES_KEEP_DAILY` to `0`, easing the load on the {engine-name} machine. Use `Basic` when the {engine-name} and Data Warehouse are installed on the same machine.
endif::SM_localDB_deploy[]
. Review the installation settings, and press `Enter` to accept the values and proceed with the installation:
+
[source,terminal]
----
Please confirm installation settings (OK, Cancel) [OK]:
----


When your environment has been configured, `engine-setup` displays details about how to access your environment.

.Next steps
If you chose to manually configure the firewall, `engine-setup` provides a custom list of ports that need to be opened, based on the options selected during setup. `engine-setup` also saves your answers to a file that can be used to reconfigure the {engine-name} using the same values, and outputs the location of the log file for the {virt-product-fullname} {engine-name} configuration process.

* If you intend to link your {virt-product-fullname} environment with a directory server, configure the date and time to synchronize with the system clock used by the directory server to avoid unexpected account expiry issues. See link:{URL_rhel_docs_legacy}html/system_administrators_guide/chap-Configuring_the_Date_and_Time.html#sect-Configuring_the_Date_and_Time-timedatectl-NTP[Synchronizing the System Clock with a Remote Server] in the _{enterprise-linux} System Administrator's Guide_ for more information.

* Install the certificate authority according to the instructions provided by your browser. You can get the certificate authority's certificate by navigating to `http://<manager-fqdn>/ovirt-engine/services/pki-resource?resource=ca-certificate&amp;format=X509-PEM-CA`, replacing <manager-fqdn> with the FQDN that you provided during the installation.
