[id='Reinstalling_Hosts_{context}']
= Reinstalling Hosts

// Included in:
// Admin: chap-Hosts
// SHE:
// assembly-Backing_up_and_Restoring_a_Self-Hosted_Engine
// assembly-Recovering_a_Self-Hosted_Engine

Reinstall {hypervisor-fullname}s ({hypervisor-shortname}) and {enterprise-linux-host-fullname}s from the Administration Portal. The procedure includes stopping and restarting the host.

include::../upgrade/snip_WARNING-detach_data_storage.adoc[]

.Prerequisites

* If the cluster has migration enabled, virtual machines can automatically migrate to another host in the cluster. Therefore, reinstall a host while its usage is relatively low.

* Ensure that the cluster has sufficient memory for its hosts to perform maintenance. If a cluster lacks memory, migration of virtual machines will hang and then fail. To reduce memory usage, shut down some or all of the virtual machines before moving the host to maintenance.

* Ensure that the cluster contains more than one host before performing a reinstall. Do not attempt to reinstall all the hosts at the same time. One host must remain available to perform Storage Pool Manager (SPM) tasks.

.Procedure

. Click menu:Compute[Hosts] and select the host.

. Click menu:Management[Maintenance] and btn:[OK].

. Click menu:Installation[Reinstall]. This opens the *Install Host* window.

ifdef::SHE_backup_restore,SHE_restore_only[]
. Click the *Hosted Engine* tab and select *DEPLOY* from the drop-down list.
endif::SHE_backup_restore,SHE_restore_only[]

. Click btn:[OK] to reinstall the host.

After a host has been reinstalled and its status returns to *Up*, you can migrate virtual machines back to the host.

[IMPORTANT]
====
After you register a {hypervisor-fullname} to the {virt-product-fullname} {engine-name} and reinstall it, the Administration Portal may erroneously display its status as *Install Failed*. Click menu:Management[Activate], and the host will change to an *Up* status and be ready for use.
====
