[id='Enabling_the_Red_Hat_Virtualization_Manager_Repositories_{context}']
= Enabling the {virt-product-fullname} {engine-name} Repositories

ifdef::rhv-doc[]


You need to log in and register the
ifndef::offline_install,install_DWH_remote,remote_database_install,migrate_SHE_DB,migrate_DWH_DB[{engine-name} machine ]
ifdef::install_DWH_remote,migrate_DWH_DB[Data Warehouse machine ]
ifdef::remote_database_install,migrate_SHE_DB[database machine ]
ifdef::offline_install[online machine ]
with Red Hat Subscription Manager, attach the `{virt-product-fullname} {engine-name}` subscription, and enable the {engine-name} repositories.

.Procedure

. Register your system with the Content Delivery Network, entering your Customer Portal user name and password when prompted:
+
[options="nowrap" subs="normal"]
----
# subscription-manager register
----
+
[NOTE]
====
If you are using an IPv6 network, use an IPv6 transition mechanism to access the Content Delivery Network and subscription manager.
====

. Find the `{virt-product-fullname} {engine-name}` subscription pool and record the pool ID:
+
[options="nowrap" subs="normal"]
----
# subscription-manager list --available
----

. Use the pool ID to attach the subscription to the system:
+
[options="nowrap" subs="normal"]
----
# subscription-manager attach --pool=_pool_id_
----
+
[NOTE]
====
To view currently attached subscriptions:
[options="nowrap" subs="normal"]
----
# subscription-manager list --consumed
----
To list all enabled repositories:
[options="nowrap" subs="normal"]
----
# dnf repolist
----
====

. Configure the repositories:
+
ifndef::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms \
    --enable=rhv-4.4-manager-for-rhel-8-x86_64-rpms \
    --enable=fast-datapath-for-rhel-8-x86_64-rpms \
    --enable=jb-eap-7.3-for-rhel-8-x86_64-rpms
----
endif::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,install_DWH_remote,migrate_manager_db[]
ifdef::remote_database_install,manual_database_install,migrate_DWH_DB,install_DWH_remote[]
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms \
    --enable=rhv-4.4-manager-for-rhel-8-x86_64-rpms
----
endif::remote_database_install,manual_database_install,migrate_DWH_DB,install_DWH_remote[]
ifdef::migrate_SHE_DB,migrate_manager_db[]
[options="nowrap" subs="normal"]
----
# subscription-manager repos \
    --disable='*' \
    --enable=rhel-8-for-x86_64-baseos-rpms \
    --enable=rhel-8-for-x86_64-appstream-rpms
----
endif::migrate_SHE_DB,migrate_manager_db[]

endif::rhv-doc[]

ifdef::ovirt-doc[]

Ensure the correct repositories are enabled:

[options="nowrap" subs="normal"]
----
# dnf install https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm
----

You can check which repositories are currently enabled by running `dnf repolist`.

. Enable the `javapackages-tools` module.
+
[options="nowrap" subs="normal"]
----
# dnf module -y enable javapackages-tools
----

endif::ovirt-doc[]



ifndef::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,migrate_manager_db[]
. Enable the `pki-deps` module.
+
[options="nowrap" subs="normal"]
+
----
# dnf module -y enable pki-deps
----
endif::remote_database_install,manual_database_install,migrate_SHE_DB,migrate_DWH_DB,migrate_manager_db[]
. Enable version 12 of the `postgresql` module.
+
[options="nowrap" subs="normal"]
+
----
# dnf module -y enable postgresql:12
----
. Synchronize installed packages to update them to the latest available versions.
+
[options="nowrap" subs="normal"]
----
# dnf distro-sync --nobest
----
//ansible lock addition
.Additional resources
For information on modules and module streams, see the following sections in _Installing, managing, and removing user-space components_

* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#module-streams_introduction-to-modules[Module streams]
* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#selecting-a-stream-before-installation-of-packages_installing-rhel-8-content[Selecting a stream before installation of packages]
* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#resetting-module-streams_removing-rhel-8-content[Resetting module streams]
* link:{URL_rhel_docs_latest}html-single/installing_managing_and_removing_user-space_components/index#switching-to-a-later-stream_managing-versions-of-appstream-content[Switching to a later stream]
