// This assembly is included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This assembly can be included from other assemblies using the following
// include statement:
// include::assembly_managing-vgpu-devices.adoc[leveloffset=+1]

// The following line is necessary to allow assemblies be included in other
// assemblies. It restores the `context` variable to its previous state.

:_content-type: ASSEMBLY
[id='assembly_managing-vgpu-devices']
= Setting up a GPU and using it on a virtual machine

// The `context` attribute enables module reuse. Every module's ID
// includes {context}, which ensures that the module has a unique ID even if
// it is reused multiple times in a guide.
:context: assembly_managing-vgpu-devices


You can use a host with a compatible graphics processing unit (GPU) to run virtual machines that are suited for graphics-intensive tasks and for running software that cannot run without a GPU, such as CAD.

You can assign a GPU to a virtual machine in one of the following ways:

* *GPU passthrough*. In this usage model, you assign a host GPU to a single virtual machine, so the virtual machine, instead of the host, uses the GPU.

* You can divide a physical GPU device into one or more virtual devices, referred to as _mediated devices_. You can then assign these mediated devices to one or more virtual machines as virtual GPUs. These virtual machines share the performance of a single physical GPU. For some GPUs, only one mediated device can be assigned to a single guest. vGPU support is only available on selected NVIDIA GPUs.

// include::assembly_managing-nvidia-vgpu-devices.adoc[leveloffset=+1]
//include::assembly_managing-intel-vgpu-devices.adoc[leveloffset=+1]
