// Module included in the following assemblies:
//
// doc-Administration_Guide/common/security/assembly-Securing_Red_Hat_Virtualization.adoc
// THIS MODULE IS RHV ONLY.

:_content-type: CONCEPT
[id='disa-stig-for-red-hat-linux_{context}']
= DISA STIG for Red Hat Virtualization 4.4

The Defense Information Systems Agency (DISA) distributes Security Technical Implementation Guides (STIGs) for various platforms and operating systems.

When installing {hypervisor-fullname} ({hypervisor-shortname}), the *[DRAFT] DISA STIG for Red Hat Virtualization Host (RHVH)* profile is one of the security policies available. Enabling this profile as your security policy during installation removes the need to regenerate SSH keys, SSL certificates, or otherwise re-configure the host later in the deployment process.

When installing a RHEL host, you can use the *DISA STIG for Red Hat Enterprise Linux 8* profile. For information on applying a security policy, see link:{URL_rhel_docs_latest}html-single/performing_a_standard_rhel_installation/index#security-policy_configuring-system-settings[Configuring a security policy] in _Performing a standard RHEL installation_.

[IMPORTANT]
====
The DISA STIG security policy is the only security policy that Red Hat officially tests and certifies.
====

DISA STIGs are "configuration standards for DOD IA and IA-enabled devices/systems. Since 1998, DISA has played a critical role in enhancing the security posture of DoD’s security systems by providing the Security Technical Implementation Guides (STIGs). The STIGs contain technical guidance to 'lock down' information systems/software that might otherwise be vulnerable to a malicious computer attack."

These STIGs are based on requirements put forth by the National Institute of Standards and Technology (NIST) Special Publication 800-53, a catalog of security controls for all U.S. federal information systems except those related to national security.

To determine which various profiles overlap, Red Hat refers to the Cloud Security Alliance's Cloud Controls Matrix (CCM). This CCM specifies a comprehensive set of cloud-specific security controls, and maps each one to the requirements of leading standards, best practices, and regulations.

To help you verify your security policy, Red Hat provides OpenSCAP tools and Security Content Automation Protocol (SCAP) profiles for various Red Hat platforms, including RHEL and RHV.

Red Hat's OpenSCAP project provides open source tools for administrators and auditors to assess, measure, and enforce of SCAP baselines. NIST awarded SCAP 1.2 certification to OpenSCAP in 2014.

NIST maintains the SCAP standard. SCAP-compliant profiles provide detailed low-level guidance on setting the security configuration of operating systems and applications.

Red Hat publishes SCAP baselines for various products and platforms to two locations:

* The NIST National Checklist Program (NCP), the U.S. government repository of publicly available security checklists (or benchmarks).
* The Department of Defense (DoD) Cyber Exchange


.Additional resources

* link:https://nvd.nist.gov/ncp/repository?authority=Red+Hat&startIndex=0[NIST National Checklist Program Repository for Red Hat]
* link:https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=operating-systems%2Cunix-linux[The DoD Cyber Exchange download page for Unix/Linux-related STIGs]
* link:https://csrc.nist.gov/publications/detail/sp/800-53/rev-4/final[NIST Special Publication 800-53 Rev. 4]
* link:https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/draft[NIST Special Publication 800-53 Rev. 5 (DRAFT)]
* link:https://www.open-scap.org/[The OpenSCAP Project]
* link:https://cloudsecurityalliance.org/working-groups/cloud-controls-matrix/#_overview[Cloud Security Alliance: Cloud Controls Matrix]
