// Module included in the following assemblies:
//
// doc-Administration_Guide/common/security/assembly-Securing_Red_Hat_Virtualization.adoc
// THIS MODULE IS RHV ONLY.

:_content-type: PROCEDURE
[id='applying-the-disa-stig-profile-rhvh_{context}']
= Applying the DISA STIG profile in {enterprise-linux-shortname} based hosts and the standalone Manager

When installing {virt-product-shortname}, you can select the DISA STIG profile with the UI installer, which is the profile provided by {enterprise-linux-shortname} 8.

[IMPORTANT]
====
The DISA STIG profile is not supported for {hypervisor-fullname} ({hypervisor-shortname}).
====

.Procedure

. In the *Installation Summary* screen, select *Security Policy*.
. In the *Security Policy* screen, set the *Apply security policy* to *On*.
. Select *DISA STIG for Red Hat Enterprise Linux 8*.
. Click *Select profile*. This action adds a green checkmark next to the profile and adds packages to the list of *Changes that were done or need to be done*. Follow the onscreen instructions if they direct you to make any changes.
. Click *Done*.
. On the *Installation Summary* screen, verify that the status of *Security Policy* is *Everything okay*.
. Reboot the host.


[id="enabling-disa-stig-in-a-self-hosted-engine"]
== Enabling DISA STIG in a self-hosted engine

You can enable DISA STIG in a self-hosted engine during deployment when using the command-line.

.Procedure

. Start the self-hosted engine deployment script. See link:{URL_downstream_virt_product_docs}installing_{URL_product_virt}_as_a_self-hosted_engine_using_the_command_line/index[Installing {virt-product-fullname} as a self-hosted engine using the command line].
. When the deployment script prompts `Do you want to apply an OpenSCAP security profile?`, enter `Yes`.
. When the deployment script prompts `Please provide the security profile you would like to use?`, enter `stig`.
