:_content-type: CONCEPT
[id="Examples_overview"]
= Overview

This section provides examples demonstrating the steps to create a virtual machine within a basic {virt-product-fullname} environment, using the Python SDK.

These examples use the `ovirtsdk` Python library provided by the `ovirt-engine-sdk-python` package. This package is available to systems attached to a `{virt-product-fullname}` subscription pool in Red Hat Subscription Manager. See xref:Installing_the_Software_Development_Kit[Installing the Software Development Kit] for more information on subscribing your system(s) to download the software.


You will also need:

* A networked installation of {virt-product-fullname} {engine-name}.
* A networked and configured {hypervisor-fullname}.
* An ISO image file containing an operating system for installation on a virtual machine.
* A working understanding of both the logical and physical objects that make up a {virt-product-fullname} environment.
* A working understanding of the Python programming language.

The examples include placeholders for authentication details (`admin@internal` for user name, and `password` for password). Replace the placeholders with the authentication requirements of your environment.

{virt-product-fullname} {engine-name} generates a globally unique identifier (GUID) for the `id` attribute for each resource. Identifier codes in these examples differ from the identifier codes in your {virt-product-fullname} environment.

The examples contain only basic exception and error handling logic. For more information on the exception handling specific to the SDK, see the pydoc for the `ovirtsdk.infrastructure.errors` module:

[source,terminal,subs="normal"]
----
$ pydoc ovirtsdk.infrastructure.errors
----
