[id="Configure_grafana"]


.Installation

Grafana integration is enabled and installed by default when you run {virt-product-fullname} {engine-name} `engine-setup` in a Stand Alone Manager installation, and in the Self-Hosted engine installation.

[NOTE]
====
Grafana is not installed by default and you may need to install it manually under some scenarios such as performing an upgrade from an earlier version of {virt-product-shortname}, restoring a backup, or when the Data Warehouse is migrated to a separate machine. 
====

To enable Grafana integration manually:

. Put the environment in global maintenance mode:
+
[options="nowrap" subs="normal"]
----
# hosted-engine --set-maintenance --mode=global
----
. Log in to the machine where you want to install Grafana. This should be the same machine where the Data Warehouse is configured; usually the {engine-name} machine.
. Run the `engine-setup` command as follows:
+
----
# engine-setup --reconfigure-optional-components
----
+
. Answer `Yes` to install Grafana on this machine:
+
----
Configure Grafana on this host (Yes, No) [Yes]:
----
. Disable global maintenance mode:
+
[options="nowrap" subs="normal"]
----
# hosted-engine --set-maintenance --mode=none
----

To access the Grafana dashboards:

* Go to `\https://<engine FQDN or IP address>/ovirt-engine-grafana`

or

* Click *Monitoring Portal* in the web administration welcome page for the *Administration Portal*.

include::Configure_grafana_SSO.adoc[leveloffset=+1]
