:_content-type: ASSEMBLY
[id='Recovering_a_Self-hosted_Engine']
= Recovering a Self-Hosted Engine from an Existing Backup

:context: SHE_restore_only
:SHE_restore_only:

If a self-hosted engine is unavailable due to problems that cannot be repaired, you can restore it in a new self-hosted environment using a backup taken before the problem began, if one is available.

When you specify a backup file during deployment, the backup is restored on a new {engine-name} virtual machine, with a new self-hosted engine storage domain. The old {engine-name} is removed, and the old self-hosted engine storage domain is renamed and can be manually removed after you confirm that the new environment is working correctly. Deploying on a fresh host is highly recommended; if the host used for deployment existed in the backed up environment, it will be removed from the restored database to avoid conflicts in the new environment. If you deploy on a new host, you must assign a unique name to the host. Reusing the name of an existing host included in the backup can cause conflicts in the new environment.

Restoring a self-hosted engine involves the following key actions:

. xref:Restoring_the_Backup_on_a_New_Self-hosted_Engine_SHE_restore_only[Deploy a new self-hosted engine and restore the backup.]

. xref:Enabling_the_Red_Hat_Virtualization_Manager_Repositories_SHE_restore_only[Enable the {engine-name} repositories on the new {engine-name} virtual machine.]

. xref:Reinstalling_Hosts_SHE_restore_only[Reinstall the self-hosted engine nodes to update their configuration.]

. xref:Removing_a_Storage_Domain_SHE_restore_only[Remove the old self-hosted engine storage domain.]

This procedure assumes that you do not have access to the original {engine-name}, and that the new host can access the backup file.

.Prerequisites

* A fully qualified domain name prepared for your {engine-name} and the host. Forward and reverse lookup records must both be set in the DNS. The new {engine-name} must have the same fully qualified domain name as the original {engine-name}.

include::proc-Restoring_the_Backup_on_a_New_Self-hosted_Engine.adoc[leveloffset=+1]

When the deployment is complete, log in to the new {engine-name} virtual machine and enable the required repositories.

include::../install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc[leveloffset=+1]

The {engine-name} and its resources are now running in the new self-hosted environment. The self-hosted engine nodes must be reinstalled in the {engine-name} to update their self-hosted engine configuration. Standard hosts are not affected. Perform the following procedure for each self-hosted engine node.

include::../install/proc-Reinstalling_Hosts.adoc[leveloffset=+1]

After reinstalling the self-hosted engine nodes, you can check the status of the new environment by running the following command on one of the nodes:

----
# hosted-engine --vm-status
----

During the restoration, the old self-hosted engine storage domain was renamed, but was not removed from the new environment in case the restoration was faulty. After confirming that the environment is running normally, you can remove the old self-hosted engine storage domain.

include::../storage/proc-Removing_a_Storage_Domain.adoc[leveloffset=+1]

:SHE_restore_only!:
:context!: SHE_restore_only
