[id='Restoring_the_Backup_on_a_New_Self-hosted_Engine_{context}']
= Restoring the Backup on a New Self-Hosted Engine

// Included in:
// Migrating from a Standalone {engine-name} to a Self-hosted Engine
// Administration Guide, Backing up and Restoring a Self-hosted Engine
// Recovering a Self-Hosted Engine from an Existing Backup

Run the `hosted-engine` script on a new host, and use the `--restore-from-file=__path/to/file_name__` option to restore the {engine-name} backup during the deployment.

[IMPORTANT]
====
If you are using iSCSI storage, and your iSCSI target filters connections according to the initiator's ACL, the deployment may fail with a `STORAGE_DOMAIN_UNREACHABLE` error. To prevent this, you must update your iSCSI configuration before beginning the self-hosted engine deployment:

* If you are redeploying on an existing host, you must update the host's iSCSI initiator settings in `/etc/iscsi/initiatorname.iscsi`. The initiator IQN must be the same as was previously mapped on the iSCSI target, or updated to a new IQN, if applicable.
* If you are deploying on a fresh host, you must update the iSCSI target configuration to accept connections from that host.

Note that the IQN can be updated on the host side (iSCSI initiator), or on the storage side (iSCSI target).
====

.Procedure

. Copy the backup file to the new host. In the following example, `host.example.com` is the FQDN for the host, and `/backup/` is any designated folder or path.
+
[options="nowrap" subs="normal"]
----
# scp -p __file_name__ host.example.com:/backup/
----

. Log in to the new host.

. If you are deploying on {hypervisor-fullname}, `ovirt-hosted-engine-setup` is already installed, so skip this step. If you are deploying on {enterprise-linux}, install the `ovirt-hosted-engine-setup` package:
+
[options="nowrap" subs="normal"]
----
# dnf install ovirt-hosted-engine-setup
----
+
. Use the `tmux` window manager to run the script to avoid losing the session in case of network or terminal disruption.
+
Install and run `tmux`:
+
[options="nowrap" subs="normal"]
----
# dnf -y install tmux
# tmux
----
+
. Run the `hosted-engine` script, specifying the path to the backup file:
+
[options="nowrap" subs="normal"]
----
# hosted-engine --deploy --restore-from-file=backup/__file_name__
----
+
To escape the script at any time, use kbd:[CTRL+D] to abort deployment.

. Select *Yes* to begin the deployment.

. Configure the network. The script detects possible NICs to use as a management bridge for the environment.

. If you want to use a custom appliance for the virtual machine installation, enter the path to the OVA archive. Otherwise, leave this field empty to use the {engine-appliance-name}.

. Enter the root password for the {engine-name}.

. Enter an SSH public key that will allow you to log in to the {engine-name} as the root user, and specify whether to enable SSH access for the root user.

. Enter the virtual machine's CPU and memory configuration.
ifdef::migrating_to_SHE[]
+
[NOTE]
====
The virtual machine must have the same amount of RAM as the physical machine from which the {engine-name} is being migrated. If you must migrate to a virtual machine that has less RAM than the physical machine from which the {engine-name} is migrated, see link:https://access.redhat.com/articles/2705841[].
====
endif::migrating_to_SHE[]

. Enter a MAC address for the {engine-name} virtual machine, or accept a randomly generated one. If you want to provide the {engine-name} virtual machine with an IP address via DHCP, ensure that you have a valid DHCP reservation for this MAC address. The deployment script will not configure the DHCP server for you.

. Enter the virtual machine's networking details. If you specify *Static*, enter the IP address of the {engine-name}.
+
[IMPORTANT]
====
The static IP address must belong to the same subnet as the host. For example, if the host is in 10.1.1.0/24, the {engine-name} virtual machine's IP must be in the same subnet range (10.1.1.1-254/24).
====

. Specify whether to add entries for the {engine-name} virtual machine and the base host to the virtual machine's `/etc/hosts` file. You must ensure that the host names are resolvable.

. Provide the name and TCP port number of the SMTP server, the email address used to send email notifications, and a comma-separated list of email addresses to receive these notifications:

. Enter a password for the `admin@internal` user to access the Administration Portal.
+
The script creates the virtual machine. This can take some time if the {engine-appliance-name} needs to be installed.
+
[NOTE]
====
If the host becomes non operational, due to a missing required network or a similar problem, deployment will pause and a message such as the following will be displayed:
----
[ INFO  ] You can now connect to https://<host name>:6900/ovirt-engine/ and check the status of this host and eventually remediate it, please continue only when the host is listed as 'up'
[ INFO  ] TASK [ovirt.ovirt.hosted_engine_setup : include_tasks]
[ INFO  ] ok: [localhost]
[ INFO  ] TASK [ovirt.ovirt.hosted_engine_setup : Create temporary lock file]
[ INFO  ] changed: [localhost]
[ INFO  ] TASK [ovirt.ovirt.hosted_engine_setup : Pause execution until /tmp/ansible.<random>_he_setup_lock is removed, delete it once ready to proceed]
----
Pausing the process allows you to:

* Connect to the Administration Portal using the provided URL.
* Assess the situation, find out why the host is non operational, and fix whatever is needed.
* For example, if this deployment was restored from a backup, and the backup included _required networks_ for the host cluster, you should set up the networks accordingly, attaching the relevant host NICs to these networks as needed.
Once everything looks ok, and the host status is _Up_, remove the lock file presented in the message above, and deployment will continue.
* Connect to the restored engine manually, and review and remediate the configuration before proceeding with the deployment.
====
+
ifdef::rhv-doc[]
See also link:https://access.redhat.com/solutions/4088711[]
endif::rhv-doc[]

. Select the type of storage to use:

* For NFS, enter the version, full address and path to the storage, and any mount options.
ifdef::SHE_backup_restore,SHE_restore_only[]
+
[WARNING]
====
Do not use the old self-hosted engine storage domain's mount point for the new storage domain, as you risk losing virtual machine data.
====
endif::SHE_backup_restore,SHE_restore_only[]

* For iSCSI, enter the portal details and select a target and LUN from the auto-detected lists. You can only select one iSCSI target during the deployment, but multipathing is supported to connect all portals of the same portal group.
+
[NOTE]
====
To specify more than one iSCSI target, you must enable multipathing before deploying the self-hosted engine. See link:{URL_rhel_docs_legacy}html-single/dm_multipath/[_{enterprise-linux} DM Multipath_] for details. There is also a link:https://access.redhat.com/labs/multipathhelper/#/[Multipath Helper] tool that generates a script to install and configure multipath with different options.
====

* For Gluster storage, enter the full address and path to the storage, and any mount options.
ifdef::SHE_backup_restore,SHE_restore_only[]
+
[WARNING]
====
Do not use the old self-hosted engine storage domain's mount point for the new storage domain, as you risk losing virtual machine data.
====
endif::SHE_backup_restore,SHE_restore_only[]
+
[IMPORTANT]
====
Only replica 1 and replica 3 Gluster storage are supported. Ensure you configure the volume as follows:

[options="nowrap" subs="normal"]
----
gluster volume set _VOLUME_NAME_ group virt
gluster volume set _VOLUME_NAME_ performance.strict-o-direct on
gluster volume set _VOLUME_NAME_ network.remote-dio off
gluster volume set _VOLUME_NAME_ storage.owner-uid 36
gluster volume set _VOLUME_NAME_ storage.owner-gid 36
gluster volume set _VOLUME_NAME_ network.ping-timeout 30
----
====

* For Fibre Channel, select a LUN from the auto-detected list. The host bus adapters must be configured and connected, and the LUN must not contain any existing data. To reuse an existing LUN, see link:{URL_virt_product_docs}{URL_format}administration_guide/index#Reusing_LUNs[Reusing LUNs] in the _Administration Guide_.

. Enter the {engine-name} disk size.
+
The script continues until the deployment is complete.

. The deployment process changes the {engine-name}'s SSH keys. To allow client machines to access the new {engine-name} without SSH errors, remove the original {engine-name}'s entry from the `.ssh/known_hosts` file on any client machines that accessed the original {engine-name}.
