:_content-type: PROCEDURE
[id="start-a-full-backup_{context}"]
= Starting a full backup

[role="_abstract"]
After a full backup you can use the resulting checkpoint ID as the start point in the next incremental backup.

include::snip_scratch-disk.adoc[]

Starting a full backup requires a request call with a body, and includes a response.

.Procedure

. Send a request specifying a virtual machine to back up. For example, specify a virtual machine with ID `123` like this:
+
[source,terminal,subs="normal"]
----
POST /ovirt-engine/api/vms/123/backups
----

. In the request body, specify a disk to back up. For example, to start a full backup of a disk with ID `456`, send the following request body:
+
[source,terminal,subs="normal"]
----
<backup>
    <disks>
       <disk id="456" />
       ...
    </disks>
</backup>
----
+
The response body should look similar to this:
+
[source,terminal,subs="normal"]
----
<backup id="789">
    <disks>
       <disk id="456" />
       ...
       ...
    </disks>
    <status>initializing</status>
    <creation_date>
</backup>
----
+
The response includes the following:
+
** The backup id
** The status of the backup, indicating that the backup is initializing.

. Poll the backup until the status is `ready`. The response includes `to_checkpoint_id`. Note this ID and use it for `from_checkpoint_id` in the next incremental backup.

[role="_additional-resources"]
.Additional resources

* link:{URL_rest_api_doc}index#services-vm_backups[`add` method of the `VmBackups` service] in the _REST API Guide_ for {virt-product-shortname}
