:_content-type: PROCEDURE
[id="start-an-incremental-backup_{context}"]
= Starting an incremental backup

[role="_abstract"]

Once a full backup is completed for a given virtual disk, subsequent incremental backups that disk contain only the changes since the last backup. Use the value of `to_checkpoint_id` from the most recent backup as the value for `from_checkpoint_id` in the request body.

include::snip_scratch-disk.adoc[]

Starting an incremental backup or mixed backup requires a request call with a body, and includes a response.

.Procedure

. Send a request specifying a virtual machine to back up. For example, specify a virtual machine with ID `123` like this:
+
[source,terminal,subs="normal"]
----
POST /ovirt-engine/api/vms/123/backups
----

. In the request body, specify a disk to back up. For example, to start an incremental backup of a disk with ID `456`, send the following request body:
+
[source,terminal,subs="normal"]
----
<backup>
    <from_checkpoint_id>__previous-checkpoint-uuid__</from_checkpoint_id>
    <disks>
       <disk id="456" />
       ...
    </disks>
</backup>
----
+
[NOTE]
====
In the request body, if you include a disk that is not included in the previous checkpoint, the request also runs a full backup of this disk. For example, a disk with ID `789` has not been backed up yet. To add a full backup of `789` to the above request body, send a request body like this:

[source,terminal,subs="normal"]
----
<backup>
    <from_checkpoint_id>__previous-checkpoint-uuid__</from_checkpoint_id>
    <disks>
       <disk id="456" />
       **<disk id="789" />**
       ...
    </disks>
</backup>
----
====
+
The response body should look similar to this:
+
[source,terminal,subs="normal"]
----
<backup id="101112">
<from_checkpoint_id>__previous-checkpoint-uuid__</from_checkpoint_id>
<to_checkpoint_id>__new-checkpoint-uuid__</to_checkpoint_id>
    <disks>
       <disk id="456" />
       <disk id="789" />
       ...
       ...
    </disks>
    <status>initializing</status>
    <creation_date>
</backup>
----
+
The response includes the following:
+
** The backup ID.
** The ID of any disk that was included in the backup.
** The status, indicating that the backup is initializing.

. Poll the backup until the status is `ready`. The response includes `to_checkpoint_id`. Note this ID and use it for `from_checkpoint_id` in the next incremental backup.

[role=_additonal-resources]
.Additional resources
 * link:{URL_rest_api_doc}index#services-vm_backups-methods-add[`add` method of the VmBackups service]  in the _REST API Guide_ for {virt-product-shortname}.
