:_content-type: PROCEDURE
[id='proc_Manually_installing_the_appliance_{context}']
= Manually installing the {engine-appliance-name}

When you deploy the self-hosted engine, the following sequence of events takes place:

. The installer installs the {engine-appliance-name} to the deployment host.
. The appliance installs the {engine-name} virtual machine.
. The appliance installs the {engine-name} on the {engine-name} virtual machine.

However, you can install the appliance manually on the deployment host beforehand if you need to. The appliance is large and network connectivity issues might cause the appliance installation to take a long time, or possibly fail.

.Procedure

. On {enterprise-linux-host-fullname}s:
.. Reset the `virt` module:
+
[source,terminal,subs="normal"]
+
----
# dnf module reset virt
----
+
[NOTE]
====
If this module is already enabled in the Advanced Virtualization stream, this step is not necessary, but it has no negative impact.

You can see the value of the stream by entering:
----
# dnf module list virt
----
====
+
.. Enable the `virt` module in the Advanced Virtualization stream with the following command:

include::../install/snip-Enable_virt_module.adoc[]
+
. Synchronize installed packages to update them to the latest available versions:
+
[source,terminal,subs="normal"]
----
# dnf distro-sync --nobest
----
//ansible lock addition
. Install the {engine-appliance-name} to the host manually:
+
ifdef::rhv-doc[]
[source,terminal,subs="normal"]
----
# dnf install rhvm-appliance
----
endif::rhv-doc[]

ifdef::ovirt-doc[]
[source,terminal,subs="normal"]
----
# dnf install ovirt-engine-appliance
----
endif::ovirt-doc[]

Now, when you deploy the self-hosted engine, the installer detects that the appliance is already installed.
