:_content-type: CONCEPT
[id="host-types"]
= Host Types

Use the host type that best suits your environment. You can also use both types of host in the same cluster if required.

All managed hosts within a cluster must have the same CPU type. Intel and AMD CPUs cannot co-exist within the same cluster.

== {hypervisor-fullname}s

{hypervisor-fullname}s ({hypervisor-shortname}) have the following advantages over {enterprise-linux-host-fullname}s:

* {hypervisor-shortname} is included in the subscription for {virt-product-fullname}. {enterprise-linux-host-fullname}s may require additional subscriptions.

* {hypervisor-shortname} is deployed as a single image. This results in a streamlined update process; the entire image is updated as a whole, as opposed to packages being updated individually.

* Only the packages and services needed to host virtual machines or manage the host itself are included. This streamlines operations and reduces the overall attack vector; unnecessary packages and services are not deployed and, therefore, cannot be exploited.

* The Cockpit web interface is available by default and includes extensions specific to {virt-product-fullname}, including virtual machine monitoring tools and a GUI installer for the self-hosted engine. Cockpit is supported on {enterprise-linux-host-fullname}s, but must be manually installed.

== {enterprise-linux-host-fullname}s

{enterprise-linux-host-fullname}s have the following advantages over {hypervisor-fullname}s:

* {enterprise-linux-host-fullname}s are highly customizable, so may be preferable if, for example, your hosts require a specific file system layout.

* {enterprise-linux-host-fullname}s are better suited for frequent updates, especially if additional packages are installed. Individual packages can be updated, rather than a whole image.
