[[chap-Administrative_Tasks]]
== Administrative Tasks

:context: vm_guide_administrative_tasks

include::topics/Shutting_down_a_virtual_machine.adoc[]

include::topics/Suspending_a_virtual_machine.adoc[]

include::topics/Rebooting_a_Virtual_Machine.adoc[]

include::topics/Removing_a_virtual_machine.adoc[]

include::topics/Cloning_a_Virtual_Machine.adoc[]

[[sect-Updating_Virtual_Machine_Guest_Agents_and_Drivers]]
=== Updating Virtual Machine Guest Agents and Drivers

The {virt-product-fullname} guest agents, tools, and drivers provide additional functionality for virtual machines, such as gracefully shutting down or rebooting virtual machines from the VM Portal and Administration Portal. The tools and agents also provide information for virtual machines, including:

* Resource usage
* IP addresses
* Installed applications

The guest tools are distributed as an ISO file that you can attach to virtual machines. This ISO file is packaged as an RPM file that you can install and update from the {engine-name} machine.

include::topics/Updating_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux.adoc[]

include::topics/Updating_Win_Guest_Drivers_with_Windows_Update.adoc[leveloffset=+3]

include::topics/Updating_the_Guest_Agents_and_Drivers_on_Windows.adoc[leveloffset=+3]

include::topics/Viewing_Satellite_Errata.adoc[]

[[sect-Virtual_Machines_and_Permissions]]
=== Virtual Machines and Permissions

include::topics/Managing_System_Permissions_for_a_Virtual_Machine.adoc[]

include::topics/Virtual_Machine_Administrator_Roles_Explained.adoc[]

include::topics/Virtual_Machine_User_Roles_Explained.adoc[]

include::topics/Assigning_virtual_machines_to_users.adoc[]

include::topics/Removing_Access_to_Virtual_Machines_from_Users.adoc[]

[[sect-Snapshots]]
=== Snapshots

include::topics/Creating_a_snapshot_of_a_virtual_machine.adoc[]

include::topics/Using_a_snapshot_to_restore_a_virtual_machine.adoc[]

include::topics/Creating_a_virtual_machine_from_a_snapshot.adoc[]

include::topics/Deleting_a_snapshot.adoc[]

[[sect-Host_Devices]]
=== Host Devices

include::topics/Adding_Host_Devices_to_a_Virtual_Machine.adoc[]

include::topics/Removing_Host_Devices_from_a_Virtual_Machine.adoc[]

include::topics/Pinning_a_Virtual_Machine_to_Another_Host.adoc[]

include::topics/conc-nvdimm-host-devices.adoc[leveloffset=+3]


[[sect-Affinity_Groups]]
include::topics/Affinity_groups.adoc[]

include::topics/Creating_an_Affinity_Group.adoc[]

include::topics/Editing_an_Affinity_Group.adoc[]

include::topics/Removing_an_Affinity_Group.adoc[]

include::topics/Affinity_groups_examples.adoc[]

include::topics/Affinity_groups_troubleshooting.adoc[]


[[sect-Affinity_Labels]]
include::topics/Affinity_Labels.adoc[]

include::topics/Creating_an_Affinity_Label.adoc[]

include::topics/Editing_an_Affinity_Label.adoc[]

include::topics/Removing_an_Affinity_Label.adoc[]

[[sect-Exporting_and_Importing_Virtual_Machines_and_Templates]]
=== Exporting and Importing Virtual Machines and Templates


[NOTE]
====
The export storage domain is deprecated. Storage data domains can be unattached from a data center and imported to another data center in the same environment, or in a different environment. Virtual machines, floating virtual disks, and templates can then be uploaded from the imported storage domain to the attached data center. See the link:{URL_virt_product_docs}{URL_format}administration_guide#sect-Importing_Existing_Storage_Domains[Importing Existing Storage Domains] section in the _{virt-product-fullname} Administration Guide_ for information on importing storage domains.
====
You can export virtual machines and templates from, and import them to, data centers in the same or different Red Hat Virtualization environment. You can export or import virtual machines by using an export domain, a data domain, or by using a Red Hat Virtualization host.

When you export or import a virtual machine or template, properties including basic details such as the name and description, resource allocation, and high availability settings of that virtual machine or template are preserved.

The permissions and user roles of virtual machines and templates are included in the OVF files, so that when a storage domain is detached from one data center and attached to another, the virtual machines and templates can be imported with their original permissions and user roles. In order for permissions to be registered successfully, the users and roles related to the permissions of the virtual machines or templates must exist in the data center before the registration process.

You can also use the V2V feature to import virtual machines from other virtualization providers, such as RHEL 5 Xen or VMware, or import Windows virtual machines. V2V converts virtual machines so that they can be hosted by {virt-product-fullname}. For more information on installing and using V2V, see link:https://access.redhat.com/articles/1351473[Converting Virtual Machines from Other Hypervisors to KVM with virt-v2v].

[IMPORTANT]
====
Virtual machines must be shut down before being imported.
====

include::topics/Exporting_individual_virtual_machines_to_the_export_domain.adoc[]

include::topics/proc_Exporting_individual_virtual_machines_to_a_data_domain.adoc[leveloffset=+3]

include::topics/Importing_the_virtual_machine_from_the_export_domain.adoc[]

include::topics/Importing_a_Virtual_Machine_from_a_Data_Domain.adoc[leveloffset=+3]

include::topics/Importing_a_Virtual_Machine_from_a_VMware_Provider.adoc[]

include::topics/Exporting_a_virtual_machines_to_a_host.adoc[]

include::topics/Importing_an_OVA_file_from_a_host.adoc[]

include::topics/Importing_a_Virtual_Machine_from_Xen.adoc[]

include::topics/Importing_a_Virtual_Machine_from_KVM.adoc[]

include::topics/Importing_a_Red_Hat_KVM_Guest_Image.adoc[]

[[sect-Migrating_Virtual_Machines_Between_Hosts]]
=== Migrating Virtual Machines Between Hosts

Live migration provides the ability to move a running virtual machine between physical hosts with no interruption to service. The virtual machine remains powered on and user applications continue to run while the virtual machine is relocated to a new physical host. In the background, the virtual machine's RAM is copied from the source host to the destination host. Storage and network connectivity are not altered.

[NOTE]
====
A virtual machine that is using a vGPU cannot be migrated to a different host.
====

include::topics/Live_migration_prerequisites.adoc[]

include::topics/Optimizing_Live_Migration.adoc[]

// removed Optimizing live migration section - options no longer Existing
// dcdacosta: added back Optimizing live migration since the values still apply on some versions. [See https://bugzilla.redhat.com/show_bug.cgi?id=1946201]

include::topics/Guest_Agent_Hooks.adoc[]

include::topics/Automatic_virtual_machine_migration.adoc[]

include::topics/Preventing_automatic_migration_of_a_virtual_machine.adoc[]

include::topics/Manually_migrating_virtual_machines.adoc[]

include::topics/Setting_migration_priority.adoc[]

include::topics/Canceling_ongoing_virtual_machine_migrations.adoc[]

include::topics/Event_and_Log_Notification_upon_Automatic_Migration_of_Highly_Available_Virtual_Servers.adoc[]

[[sect-Improving_Uptime_with_Virtual_Machine_High_Availability]]
=== Improving Uptime with Virtual Machine High Availability

include::topics/What_is_high_availability.adoc[]

include::topics/High_availability_considerations.adoc[]

include::topics/Configuring_a_highly_available_virtual_machine.adoc[]

[[sect-Other_Virtual_Machine_Tasks]]
=== Other Virtual Machine Tasks

include::topics/Enabling_SAP_monitoring_for_a_virtual_machine_from_the_Administration_Portal.adoc[]

[[sect-Configuring_Red_Hat_Enterprise_Linux_5.4_and_Higher_Virtual_Machines_to_use_SPICE]]
==== Configuring {enterprise-linux} 5.4 and later Virtual Machines to use SPICE

SPICE is a remote display protocol designed for virtual environments, which enables you to view a virtualized desktop or server. SPICE delivers a high quality user experience, keeps CPU consumption low, and supports high quality video streaming.

Using SPICE on a Linux machine significantly improves the movement of the mouse cursor on the console of the virtual machine. To use SPICE, the X-Windows system requires additional QXL drivers. The QXL drivers are provided with {enterprise-linux} 5.4 and later. Earlier versions are not supported. Installing SPICE on a virtual machine running {enterprise-linux} significantly improves the performance of the graphical user interface.

[NOTE]
====
Typically, this is most useful for virtual machines where the user requires the use of the graphical user interface. System administrators who are creating virtual servers may prefer not to configure SPICE if their use of the graphical user interface is minimal.
====
include::topics/Configuring_qxl_drivers_on_virtual_machines.adoc[]

include::topics/Configuring_a_virtual_machines_tablet_and_mouse_to_use_SPICE.adoc[]

include::topics/KVM_virtual_machine_timing_management.adoc[]

include::topics/proc-Adding_TPM_devices.adoc[]

:context!: vm_guide_administrative_tasks
