[[chap-Introduction]]
== Introduction

A virtual machine is a software implementation of a computer. The {virt-product-fullname} environment enables you to create virtual desktops and virtual servers.

Virtual machines consolidate computing tasks and workloads. In traditional computing environments, workloads usually run on individually administered and upgraded servers. Virtual machines reduce the amount of hardware and administration required to run the same computing tasks and workloads.
include::topics/Audience.adoc[]

include::topics/Supported_virtual_machines.adoc[]

include::topics/Virtual_machine_performance_parameters.adoc[]

[[sect-Installing_Supporting_Components]]
=== Installing Supporting Components on Client Machines

[[sect-Installing_Console_Components]]
==== Installing Console Components

A console is a graphical window that allows you to view the start up screen, shut down screen, and desktop of a virtual machine, and to interact with that virtual machine in a similar way to a physical machine. In {virt-product-fullname}, the default application for opening a console to a virtual machine is Remote Viewer, which must be installed on the client machine prior to use.
include::topics/Installing_Remote_Viewer_on_Linux.adoc[]

include::topics/Installing_Remote_Viewer_on_Windows.adoc[]

include::topics/Installing_usbdk_on_Windows.adoc[]

