[id='Migrating_Data_Warehouse_to_a_Separate_Machine_{context}']
= Migrating Data Warehouse to a Separate Machine

ifdef::context[:parent-context: {context}]
:context: migrate_DWH

This section describes how to migrate the Data Warehouse database and service from the {virt-product-fullname} {engine-name} machine to a separate machine. Hosting the Data Warehouse service on a separate machine reduces the load on each individual machine, and avoids potential conflicts caused by sharing CPU and memory resources with other processes.

[NOTE]
====
{org-fullname} only supports installing the Data Warehouse database, the Data Warehouse service and Grafana all on the same machine as each other, even though you can install each of these components on separate machines from each other.
====

You have the following migration options:

* You can migrate the Data Warehouse service away from the {engine-name} machine and connect it with the existing Data Warehouse database (`ovirt_engine_history`).
* You can migrate the Data Warehouse database away from the {engine-name} machine and then migrate the Data Warehouse service.

include::proc-Migrating_the_Data_Warehouse_Database_to_a_Separate_Machine.adoc[leveloffset=+1]
//adding context back
:context: migrate_DWH

include::proc-Migrating_the_Data_Warehouse_Service_to_a_Separate_Machine.adoc[leveloffset=+1]


ifndef::parent-context[:!context:]
ifdef::parent-context[]
:context: {parent-context}
:!parent-context:
endif::[]
