:_content-type: PROCEDURE
[id="proc-configuring-the-new-data-warehouse-machine_{context}"]
= Configuring the New Data Warehouse Machine

The order of the options or settings shown in this section may differ depending on your environment.

. If you are migrating both the `ovirt_engine_history` database and the Data Warehouse service to the *same* machine, run the following, otherwise proceed to the next step.
+
[source,terminal,subs="normal"]
----
# sed -i '/^ENGINE_DB_/d' \
        /etc/ovirt-engine-dwh/ovirt-engine-dwhd.conf.d/10-setup-database.conf

# sed -i \
     -e 's;^\(OVESETUP_ENGINE_CORE/enable=bool\):True;\1:False;' \
     -e '/^OVESETUP_CONFIG\/fqdn/d' \
     /etc/ovirt-engine-setup.conf.d/20-setup-ovirt-post.conf
----
. Remove the apache/grafana PKI files, so that they are regenerated by `engine-setup`, if enabled, using correct values. 
//If they are missing, that's ok:
+
----
# rm -f \
        /etc/pki/ovirt-engine/certs/apache.cer \
        /etc/pki/ovirt-engine/certs/apache-grafana.cer \
        /etc/pki/ovirt-engine/keys/apache.key.nopass \
        /etc/pki/ovirt-engine/keys/apache-grafana.key.nopass \
        /etc/pki/ovirt-engine/apache-ca.pem \
        /etc/pki/ovirt-engine/apache-grafana-ca.pem
----
. Run the `engine-setup` command to begin configuration of Data Warehouse on the machine:
+
[source,terminal,subs="normal"]
----
# engine-setup
----

. Press *Enter* to accept the automatically detected host name, or enter an alternative host name and press *Enter*:
+
[source,terminal,subs="normal"]
----
Host fully qualified DNS name of this server [_autodetected host name_]:
----

. Press `Enter` to automatically configure the firewall, or type `No` and press `Enter` to maintain existing settings:
+
[source,terminal,subs="normal"]

----
Setup can automatically configure the firewall on this system.
Note: automatic configuration of the firewall may overwrite current settings.
Do you want Setup to configure the firewall? (Yes, No) [Yes]:
----
If you choose to automatically configure the firewall, and no firewall managers are active, you are prompted to select your chosen firewall manager from a list of supported options. Type the name of the firewall manager and press `Enter`. This applies even in cases where only one option is listed.

. Enter the fully qualified domain name and password for the {engine-name}. Press *Enter* to accept the default values in each other field:
+
[source,terminal,subs="normal"]
----
Host fully qualified DNS name of the engine server []: _engine-fqdn_
Setup needs to do some actions on the remote engine server. Either automatically, using ssh as root to access it, or you will be prompted to manually perform each such action.
Please choose one of the following:
1 - Access remote engine server using ssh as root
2 - Perform each action manually, use files to copy content around
(1, 2) [1]:
ssh port on remote engine server [22]:
root password on remote engine server _engine-fqdn_: _password_
----

. Enter the FQDN and password for the {engine-name} database machine. Press `Enter` to accept the default values in each other field:
+
[source,terminal,subs="normal"]
----
Engine database host []: _manager-db-fqdn_
Engine database port [5432]:
Engine database secured connection (Yes, No) [No]:
Engine database name [engine]:
Engine database user [engine]:
Engine database password: _password_
----

. Confirm your installation settings:
+
[source,terminal,subs="normal"]
----
Please confirm installation settings (OK, Cancel) [OK]:
----

The Data Warehouse service is now configured on the remote machine. Proceed to disable the Data Warehouse service on the {engine-name} machine.

ifdef::DWH[]
[NOTE]
====
If you want to change the Data Warehouse sampling scale to the recommended scale on a remote server, see
xref:Changing_the_Data_Warehouse_Sampling_Scale[Changing the Data Warehouse Sampling Scale].
====
endif::DWH[]
