:_content-type: PROCEDURE
[id='Preparing_a_Remote_PostgreSQL_Database_{context}']
= Preparing a Remote PostgreSQL Database

:context: remote_database_install
:remote_database_install:

In a remote database environment, you must create the {engine-name} database manually before running `engine-setup`.

[NOTE]
====
The `engine-setup` and `engine-backup --mode=restore` commands only support system error messages in the `en_US.UTF8` locale, even if the system locale is different.

The locale settings in the `postgresql.conf` file must be set to `en_US.UTF8`.
====

[IMPORTANT]
====
The database name must contain only numbers, underscores, and lowercase letters.
====

[discrete]
include::../install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc[leveloffset=+1]

[discrete]
== Initializing the PostgreSQL Database

. Install the PostgreSQL server package:
+
[source,terminal]
----
# dnf install postgresql-server postgresql-contrib
----

. Initialize the PostgreSQL database instance:
+
[options="nowrap" ]
----
# postgresql-setup --initdb
----

. Enable the `postgresql` service and configure it to start when the machine boots:
+
[options="nowrap" ]
----
# systemctl enable postgresql
# systemctl start postgresql
----

. Connect to the `psql` command line interface as the `postgres` user:
+
[options="nowrap" ]
----
# su - postgres -c psql
----

. Create a default user. The {engine-name}'s default user is `engine`:
+
[source,terminal]
----
postgres=# create role _user_name_ with login encrypted password '_password_';
----

. Create a database. The {engine-name}'s default database name is `engine`:
+
[source,terminal]
----
postgres=# create database _database_name_ owner _user_name_ template template0 encoding 'UTF8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8';
----

. Connect to the new database:
+
[source,terminal]
----
postgres=# \c _database_name_
----

. Add the `uuid-ossp` extension:
+
[source,terminal]
----
_database_name_=# CREATE EXTENSION "uuid-ossp";
----

. Add the `plpgsql` language if it does not exist:
+
[source,terminal]
----
_database_name_=# CREATE LANGUAGE plpgsql;
----

. Quit the `psql` interface:
+
[source,terminal]
----
_database_name_=# \q
----

. Edit the `/var/lib/pgsql/data/pg_hba.conf` file to enable md5 client authentication, so that the engine can access the database remotely. Add the following line immediately below the line that starts with `local` at the bottom of the file. Replace `X.X.X.X` with the IP address of the {engine-name} or Data Warehouse machine, and replace `0-32` or `0-128` with the CIDR mask length:
+
[source,terminal]
----
host    _database_name_    _user_name_    _X.X.X.X/0-32_    md5
host    _database_name_    _user_name_    _X.X.X.X::/0-128_   md5
----
+
For example:
+
[source,terminal]
----
# IPv4, 32-bit address:
host    engine    engine    192.168.12.10/32    md5

# IPv6, 128-bit address:
host    engine    engine    fe80::7a31:c1ff:0000:0000/96   md5
----

. Allow TCP/IP connections to the database. Edit the `/var/lib/pgsql/data/postgresql.conf` file and add the following line:
+
[source,terminal]
----
listen_addresses='*'
----
This example configures the `postgresql` service to listen for connections on all interfaces. You can specify an interface by giving its IP address.

. Update the PostgreSQL server's configuration. In the `/var/lib/pgsql/data/postgresql.conf` file, add the following lines to the bottom of the file:
+
[source,terminal]
----
autovacuum_vacuum_scale_factor=0.01
autovacuum_analyze_scale_factor=0.075
autovacuum_max_workers=6
maintenance_work_mem=65536
max_connections=150
work_mem=8192
----

. Open the default port used for PostgreSQL database connections, and save the updated firewall rules:
+
[source,terminal]
----
# firewall-cmd --zone=public --add-service=postgresql
# firewall-cmd --permanent --zone=public --add-service=postgresql
----

. Restart the `postgresql` service:
+
[source,terminal]
----
# systemctl restart postgresql
----
. Optionally, set up SSL to secure database connections using the instructions at link:https://www.postgresql.org/docs/12/ssl-tcp.html#SSL-FILE-USAGE[].

:context!: remote_database_install
:remote_database_install!:
