:_content-type: PROCEDURE
[id='Migrating_the_Manager_database_to_a_remote_server_{context}']
= Migrating the {engine-name} Database to a Remote Server

:context: migrate_manager_db
:migrate_manager_db:

You can migrate the {engine-name} (`engine`) database to a remote database server after the {virt-product-fullname} {engine-name} has been initially configured. Use `engine-backup` to create a database backup and restore it on the new database server.

The new database server must have {enterprise-linux} 8 installed and the required repositories enabled:

include::../install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc[leveloffset=+1]

[discrete]
== Migrating the {engine-name} Database to a Remote Server

. Log in to the {virt-product-fullname} {engine-name} machine and stop the `ovirt-engine` service so that it does not interfere with the engine backup:
+
[source,terminal,subs="normal"]
----
# systemctl stop ovirt-engine.service
----

. Create the `engine` database backup:
+
[source,terminal,subs="normal"]
----
# engine-backup --scope=files --scope=db --mode=backup --file=_file_name_ --log=_backup_log_name_
----

. Copy the backup file to the new database server:
+
[source,terminal,subs="normal"]
----
# scp _/tmp/engine.dump_ _root@new.database.server.com:/tmp_
----

. Log in to the new database server and install `engine-backup`:
+
[source,terminal,subs="normal"]
----
# dnf install ovirt-engine-tools-backup
----

. Restore the database on the new database server. _file_name_ is the backup file copied from the {engine-name}.
+
[source,terminal,subs="normal"]
----
# engine-backup --mode=restore --scope=files --scope=db --file=_file_name_ --log=_restore_log_name_ --provision-db --no-restore-permissions
----

. Now that the database has been migrated, start the `ovirt-engine` service:
+
[source,terminal,subs="normal"]
----
# systemctl start ovirt-engine.service
----

:context!: migrate_manager_db
:migrate_manager_db!:
