:_content-type: PROCEDURE
[id='proc-Migrating_the_Data_Warehouse_Database_to_a_Separate_Machine']
= Migrating the Data Warehouse Database to a Separate Machine

.Procedure

. Create a backup of the Data Warehouse database and configuration files on the {engine-name}:
+
[source,terminal,subs="normal"]
----
# engine-backup --mode=backup --scope=grafanadb --scope=dwhdb --scope=files --file=_file_name_ --log=_log_file_name_
----

. Copy the backup file from the {engine-name} to the new machine:
+
[source,terminal,subs="normal"]
----
# scp _/tmp/file_name_ _root@new.dwh.server.com:/tmp_
----

. Install `engine-backup` on the new machine:
+
[source,terminal,subs="normal"]
----
# dnf install ovirt-engine-tools-backup
----

. Install the PostgreSQL server package:
+
[source,terminal,subs="normal"]
----
# dnf install postgresql-server postgresql-contrib
----

. Initialize the PostgreSQL database, start the `postgresql` service, and ensure that this service starts on boot:
+
[options="nowrap" ]
----
# su - postgres -c 'initdb'
# systemctl enable postgresql
# systemctl start postgresql
----

. Restore the Data Warehouse database on the new machine. _file_name_ is the backup file copied from the {engine-name}.
+
[source,terminal,subs="normal"]
----
# engine-backup --mode=restore --scope=files --scope=grafanadb --scope=dwhdb --file=_file_name_ --log=_log_file_name_ --provision-dwh-db --restore-permissions
----

The Data Warehouse database is now hosted on a separate machine from that on which the {engine-name} is hosted. After successfully restoring the Data Warehouse database, a prompt instructs you to run the `engine-setup` command. Before running this command, migrate the Data Warehouse service.
