:_content-type: PROCEDURE
[id='Removing_Red_Hat_Virtualization_Manager_{context}']
= Removing the standalone {virt-product-fullname} {engine-name}

The `engine-cleanup` command removes all components of the {virt-product-fullname} {engine-name} and automatically backs up the following:

* the Grafana database, in `/var/lib/grafana/`
* the {engine-name} database in `/var/lib/ovirt-engine/backups/`
* a compressed archive of the PKI keys and configuration in `/var/lib/ovirt-engine/backups/`

Backup file names include the date and time. 

[WARNING]
====
You should use this procedure only on a standalone installation of the {virt-product-fullname} {engine-name}.
====

.Procedure

. Run the following command on the {engine-name} machine:
+
[source,terminal]
----
# engine-cleanup
----

. The {engine-name} service must be stopped before proceeding. You are prompted to confirm. Enter `OK` to proceed:
+
[source,terminal]
----
During execution engine service will be stopped (OK, Cancel) [OK]: 
----
. You are prompted to confirm that you want to remove all {engine-name} components. Enter `OK` to remove all components, or `Cancel` to exit `engine-cleanup`:
+
[source,terminal]
----
All the installed ovirt components are about to be removed, data will be lost (OK, Cancel) [Cancel]: OK
----
+
`engine-cleanup` details the components that are removed, and the location of backup files.

. Remove the {virt-product-fullname} packages:
+
[source,terminal]
----
# dnf remove {engine-package}* vdsm-bootstrap
----
