[id='Migrating_the_Websocket_Proxy_to_a_Separate_Machine_{context}']
= Migrating the Websocket Proxy to a Separate Machine
ifdef::rhv-doc[]
[IMPORTANT]
====
The websocket proxy and noVNC are Technology Preview features only. Technology Preview features are not supported with Red Hat production service-level agreements (SLAs) and might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information see link:https://access.redhat.com/support/offerings/techpreview/[Red Hat Technology Preview Features Support Scope].
====
endif::[]

For security or performance reasons the websocket proxy can run on a separate machine that does not run the {virt-product-fullname} {engine-name}. The procedure to migrate the websocket proxy from the {engine-name} machine to a separate machine involves removing the websocket proxy configuration from the {engine-name} machine, then installing the proxy on the separate machine.

The `engine-cleanup` command can be used to remove the websocket proxy from the {engine-name} machine:

[discrete]
== Removing the Websocket Proxy from the {engine-name} machine

. On the {engine-name} machine, run `engine-cleanup` to remove the required configuration.
+
[options="nowrap" subs="normal"]
----
# engine-cleanup
----
+
. Type `No` when asked to remove all components and press `Enter`.
+
[options="nowrap" subs="normal"]
----
Do you want to remove all components? (Yes, No) [Yes]: No
----
+
. Type `No` when asked to remove the engine and press `Enter`.
+
[options="nowrap" subs="normal"]
----
Do you want to remove the engine? (Yes, No) [Yes]: No
----
+
. Type `Yes` when asked to remove the websocket proxy and press `Enter`.
+
[options="nowrap" subs="normal"]
----
Do you want to remove the WebSocket proxy? (Yes, No) [No]: Yes
----
+
Select `No` if asked to remove any other components.

[discrete]
include::../install/proc-Installing_the_Websocket_Proxy_on_a_different_host.adoc[leveloffset=+1]
