[[chap-Automating_RHV_Configuration_using_Ansible]]
== Automating Configuration Tasks using Ansible

Ansible is an automation tool used to configure systems, deploy software, and perform rolling updates. Ansible includes support for {virt-product-fullname}, and Ansible modules are available to allow you to automate post-installation tasks such as data center setup and configuration, managing users, or virtual machine operations.

Ansible provides an easier method of automating {virt-product-fullname} configuration compared to REST APIs and SDKs, and allows you to integrate with other Ansible modules. For more information about the Ansible modules available for {virt-product-fullname}, see the link:http://docs.ansible.com/ansible/list_of_cloud_modules.html#ovirt[Ovirt modules] in the Ansible documentation.

[NOTE]
====
Ansible Tower is a graphically enabled framework accessible through a web interface and REST APIs for Ansible. If you want support for Ansible Tower, then you must have an Ansible Tower license, which is not part of the {virt-product-fullname} subscription.
====
Ansible is shipped with {virt-product-fullname}. To install Ansible, run the following command on the {engine-name} machine:

[options="nowrap" subs="normal"]
----
# dnf install ansible
----

See the link:http://docs.ansible.com/[Ansible Documentation] for alternate installation instructions, and information about using Ansible.

[NOTE]
====
To permanently increase the verbose level for the {engine-name} when running Ansible playbooks, create a configuration file in `/etc/ovirt-engine/engine.conf.d/` with following line:

`ANSIBLE_PLAYBOOK_VERBOSE_LEVEL=4`

You must restart the {engine-name} after creating the file by running `systemctl restart ovirt-engine`.
====

include::topics/Ansible_Roles.adoc[]
