:_content-type: ASSEMBLY
[id="chap-Renewing_certificates_{context}"]
= Renewing certificates before they expire

[role="_abstract"]
{virt-product-fullname} certificates now follow a standard 398 day lifetime and *must* be renewed once per year.

[WARNING]
====
Do not let certificates expire. If they expire, the environment becomes non-responsive and recovery is an error-prone and time-consuming process. If they do expire, you can manually renew them by following the instructions in link:https://access.redhat.com/solutions/3532921[How to manually renew RHV host SSL certificate if expired?]. Once you have completed the steps to manually renew the certificates, follow the steps in this procedure to properly enroll {virt-product-shortname} host certificates.
====

.Procedure

. In the Administration Portal, click menu:Compute[Hosts].
. Migrate the virtual machines away from the host.
. Click menu:Management[Maintenance] and btn:[OK].
. Once the host is in maintenance mode, click menu:Installation[Enroll Certificate].
. Once enrollment is complete, click menu:Management[Activate].

You must also renew {engine-name} certificates.
ifdef::SM_localDB_deploy,SM_remoteDB_deploy[]
.Renewing certificates in a standalone {engine-name}
. Log in as root via SSH or console session to the {engine-name} and run the following command:
----
# engine-setup --offline.
----
+
The `engine-setup` script prompts you with configuration questions.

. Respond to the questions as appropriate or use an answers file.
+
Be sure to answer the question about renewing certificates with "Y." This will renew the certificates without applying any updates.
+
If you want to apply updates, follow the procedure in the Upgrade Guide.
endif::SM_localDB_deploy,SM_remoteDB_deploy[]

ifdef::SHE_cli_deploy[]
.Renewing certificates in a self-hosted engine

. Log in as root via SSH or console session to the {engine-name} and a self-hosted engine hypervisor.

. In the hypervisor, run the following command to place the environment in global maintenance mode:
----
# hosted-engine --set-maintenance –mode=global
----
. In the {engine-name}, run the following command to renew the certificates:
----
# engine-setup --offline.
----
Respond to the questions as appropriate or use an answers file.
Be sure to answer the question about renewing certificates with "Y." This will renew the certificates without applying any updates.
+
If you want to apply updates, follow the procedure in the Upgrade Guide.

. In the hypervisor, run the following command to remove the environment from global maintenance mode:
----
# hosted-engine --set-maintenance –mode=none
----
endif::SHE_cli_deploy[]


[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/solutions/3532921[How to manually renew RHV host SSL certificate if expired?]
