name: Dashpanel
on:
  workflow_dispatch:
  schedule:
    - cron:  '8 0 * * *'

jobs:
  build:
    name: Dashpanel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dashpanel
        uses: haveyoudebuggedit/dashpanel@main
        with:
          orgnames: ovirt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -euo pipefail
          mv dashpanel-*.md source/community
          git config user.name "oVirt Dashpanel"
          git config user.email noreply@github.com
          git add source/community/dashpanel-*.md
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Updating Dashpanel for oVirt"
            git push --set-upstream origin master
          else
            echo -e "No changes found."
          fi