name: Deploy website

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Content check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Check for obsolete wiki headers
        run: |
          if grep -rEi "^wiki_[^ ]+: " source/; then
            echo '/!\ Wiki headers are obsolete (see previous log entries)'
            exit 2
          fi

      - name: Check for obsolete feature headers
        run: |
          if grep -rEi "^feature_[^ ]+: " source/; then
            echo '/!\ Feature headers are obsolete (see previous log entries)'
            exit 2
          fi

      - name: Check for non-breaking space in markdowns
        run: |
          if grep -P '\xa0' `find source/ -name "*.md"` ; then
            echo '/!\ nonbreaking spaces have been found within the markdown (see previous log entries)'
            exit 2
          fi

      # bundler just bump versions to the locally available ones
      # which means developers would always require bleeding edge versions not available on stable servers
      # this is too simplistic and breaks deployment
      # instead all changes are tested via CI on the same target OS and version than the production builder
      - name: Check for simplistic bundler requirement bump
        run: |
          if grep -E "^(RUBY VERSION|BUNDLED WITH)" Gemfile.lock; then
            echo '/!\ please remove "RUBY VERSION" and "BUNDLED WITH" requirements in Gemfile.lock'
            exit 2
          fi

  build:
    name: Build website
    needs: check
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        dnf install -y git ruby-devel rubygems-devel gcc-c++ curl-devel rubygem-bundler patch zlib-devel redhat-rpm-config openssl nodejs make glibc-langpack-en

    - name: Install bundler dependencies
      env:
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      run: |
        bundle config --local path 'vendor/bundle'
        bundle install --quiet

    - name: Set up Jekyll cache
      uses: actions/cache@v5
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

    - name: Build website
      env:
        LANG: en_US.UTF-8
        LANGUAGE: en_US:en
        LC_ALL: en_US.UTF-8
      run: bundle exec jekyll build

    - name: Upload generated content
      uses: actions/upload-artifact@v7
      with:
        name: ovirt-site
        if-no-files-found: error
        path: |
          _site

    - name: Run htmlproofer
      env:
        LANG: en_US.UTF-8
        LANGUAGE: en_US:en
        LC_ALL: en_US.UTF-8
      run: bundle exec ruby htmlproofer_test.rb

  deploy:
    name: Deploy website
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download generated content
        uses: actions/download-artifact@v8
        with:
          name: ovirt-site
          path: "ovirt-site"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_FOR_OVIRT_ORG }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan resources.ovirt.org >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: rsync -avz --delete ./ovirt-site/ "${{ secrets.SSH_USERNAME_FOR_OVIRT_ORG }}@resources.ovirt.org:/srv/website"
