:_content-type: REFERENCE
[id="discreet_failover"]
= Discreet Failover Test

This test simulates a failover while the primary site and all its storage domains remain active, allowing users to continue working in the primary site. To enable this scenario, you must disable replication between the primary storage domains and the replicated (secondary) storage domains. During this test the primary site is unaware of the failover activities on the secondary site.

This test will not allow you to test the failback functionality.

[IMPORTANT]
====
Ensure that no production tasks are performed after the failover. For example, ensure that email systems are blocked from sending emails to real users, or redirect emails elsewhere. If systems are used to directly manage other systems, prohibit access to the systems or ensure that they access parallel systems in the secondary site.
====

*Performing the discreet failover test:*

. Disable storage replication between the primary and replicated storage domains, and ensure that all replicated storage domains are in read/write mode.
. Run the command to fail over to the secondary site:
+
[source,terminal,subs="normal"]
----
# ansible-playbook _playbook_ --tags "fail_over"
----
+
For more information, see xref:execute_failback[Executing a Failback].
. Verify that all relevant storage domains, virtual machines, and templates are registered and running successfully.


*Restoring the environment to its active-passive state:*

. Detach the storage domains from the secondary site.
. Enable storage replication between the primary and secondary storage domains.
