[[discreet_failover_failback]]
= Discreet Failover and Failback Test

For this test you must define testable storage domains that will be used specifically for testing the failover and failback. These storage domains must be replicated so that the replicated storage can be attached to the secondary site. This allows you to test the failover while users continue to work in the primary site.

NOTE: You should define the testable storage domains on a separate storage server that can be offline without affecting the primary storage domains used for production in the primary site.

For more information about failing over the environment, cleaning the environment, and performing the failback, see <<execute_failover>>, <<clean>>, and <<execute_failback>>.

.Procedure: Discreet failover test:

. Stop the test storage domains in the primary site. You can do this by, for example, shutting down the server host or blocking it with a firewall rule.
. Disable the storage replication between the testable storage domains and ensure that all replicated storage domains used for the test are in read/write mode.
. Place the test primary storage domains into read-only mode.
. Run the command to fail over to the secondary site:
+
[source,terminal]
----
# ansible-playbook _playbook_ --tags "fail_over"
----
. Verify that all relevant storage domains, virtual machines, and templates are registered and running successfully.

.Procedure: Discreet failback test*

. Run the command to clean the primary site and remove all inactive storage domains and related virtual machines and templates:
+
[source,terminal]
----
# ansible-playbook _playbook_ --tags "clean_engine"
----
 . Run the failback command:
+
[source,terminal]
----
# ansible-playbook _playbook_ --tags "fail_back"
----
. Enable replication from the primary storage domains to the secondary storage domains.
. Verify that all relevant storage domains, virtual machines, and templates are registered and running successfully.
