= RHEA-2020:3246-04 RHV RHEL Host (ovirt-host) 4.4

The bugs in this chapter are addressed by advisory RHEA-2020:3246-04. Further information about this advisory is available at https://access.redhat.com/errata/RHEA-2020:3246.

== cockpit-ovirt

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1676582[1676582]


Previously, the user interface used the wrong unit of measure for the VM memory size in the VM settings of Hosted Engine deployment via cockpit: It showed MB instead of MiB. The current release fixes this issue: It uses MiB as the unit of measure.



== ovirt-host

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1725775[1725775]


Previously, the `screen` package was deprecated in RHEL 7.6. With this update to RHEL 8-based hosts, the `screen` package is removed. The current release installs the `tmux` package on RHEL 8-based hosts instead of `screen`.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1741792[1741792]


Previously, using LUKS alone was a problem because the RHV Manager could reboot a node using Power Management commands.  However, the node would not reboot because it was waiting for the user to enter a decrypt/open/unlock passphrase. This release fixes the issue by adding clevis RPMs to the Red Hat Virtualization Host (RHVH) image. As a result, a Manager can automatically unlock/decrypt/open an RHVH using TPM or NBDE.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1698016[1698016]


Previously, the cockpit-machines-ovirt package was deprecated in Red Hat Virtualization version 4.3 (reference bug #1698014). The current release removes the cockpit-machines-ovirt from the ovirt-host dependencies and RHV-H image.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1846596[1846596]


In previous versions, the katello-agent package was automatically installed on all hosts as a dependency of the ovirt-host package. The current release, RHV 4.4 removes this dependency to reflect the removal of the katello-agent from Satellite 6.7. Instead, you can now use katello-host-tools, which enables users to install the correct agent for their version of Satellite.



== ovirt-hosted-engine-ha

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1720747[1720747]


Previously, if ovirt-ha-broker restarted while the RHV Manager (engine) was querying the status of the self-hosted engine cluster, the query could get stuck. If that happened, the most straightforward workaround was to restart the RHV Manager.

This happened because the RHV Manager periodically checked the status of the self-hosted engine cluster by querying the VDSM daemon on the cluster host. With each query, VDSM checked the status of the ovirt-ha-broker daemon over a Unix Domain Socket. The communication between VDSM and ovirt-ha-broker wasn't enforcing a timeout. If ovirt-ha-broker was restarting, such as trying to recover from a storage issue, the VDSM request could get lost, causing VDSM and the RHV Manager to wait indefinitely.

The current release fixes this issue. It enforces a timeout in the communication channel between the VDSM and ovirt-ha-broker. If ovirt-ha-broker cannot reply to VDSM within a certain timeout, VDSM reports a self-hosted engine error to the RHV Manager.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1830730[1830730]


Previously, if the DNS query test timed out, it did not produce a log message. The current release fixes this issue: If a DNS query times out, it produces a "DNS query failed" message in the broker.log.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1821487[1821487]


Previously, network tests timed out after 2 seconds. The current release increases the timeout period from 2 seconds to 5 seconds. This reduces unnecessary timeouts when the network tests require more than 2 seconds to pass.



== ovirt-hosted-engine-setup

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1602816[1602816]


Previously, if you tried to deploy hosted-engine over a teaming device, it would try to proceed and then fail with an error. The current release fixes this issue. It filters out teaming devices. If only teaming devices are available, it rejects the deployment with a clear error message that describes the issue.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1641694[1641694]


With this update, you can start the self-hosted engine virtual machine in a paused state. To do so, enter the following command:

----
# hosted-engine --vm-start-paused
----

To un-pause the virtual machine, enter the following command:

----
# hosted-engine --vm-start
----


.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1654555[1654555]


Previously the `/` filesystem automatically grew to fit the whole disk, and the user could not increase the size of `/var` or `/var/log`.  This happened because, if a customer specified a disk larger than 49 GB while installing the Hosted Engine, the whole logical volume was allocated to the root (`/`) filesystem. In contrast, for the RHVM machine, the critical filesystems are `/var` and `/var/log`.

The current release fixes this issue. Now, the RHV Manager appliance is  based on the logical volume manager (LVM). At setup time, its PV and VG are automatically extended, but the logical volumes (LVs) are not. As a result, after installation is complete, you can extend all of the LVs in the Manager VM using the free space in the VG.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1686575[1686575]


Previously, the self-hosted engine high availability host’s management network was configured during deployment. The VDSM took over the Network Manager and configured the selected network interface during initial deployment, while the Network Manager remained disabled. During restore, there was no option to attach additional (non-default) networks,  and the restore process failed because the high-availability host had no connectivity to networks previously configured by the user that were listed in the backup file.

In this release, the user can pause the restore process, manually add the required networks, and resume the restore process to completion.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1756244[1756244]


Previously, in an IPv4-only host with a .local FQDN, the deployment kept looping searching for an available IPv6 prefix until it failed. This was because the hosted-engine setup picked a link-local IP address for the host. The hosted-engine setup could not ensure that the Engine and the host are on the same subnet when one of them used a link-local address. The Engine must not use on a link-local address to be reachable through a routed network. The current release fixes this issue: Even if the hostname is resolved to a link-local IP address, the hosted-engine setup ignores the link-local IP addresses and tries to use another IP address as the address for the host. The hosted-engine can deploy on hosts, even if the hostname is resolved to a link-local address.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1603591[1603591]


With this enhancement, while using cockpit or engine-setup to  deploy RHV Manager as a Self-Hosted Engine, the options for specifying the NFS version include two additional versions, 4.0 and 4.2.



== ovirt-imageio-daemon

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1622946[1622946]


With this update, the API reports extents information for sparse disks; which extents are data, read as zero, or unallocated (holes). This enhancement enables clients to use the imageio REST API to optimize image transfers and minimize storage requirements by skipping zero and unallocated extents.



== redhat-virtualization-host

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1794485[1794485]


This enhancement adds the vdsm-hook-nestedvt rpm package to the Red Hat Virtualization Host (RHVH) optional channel. This package enables you to run virtual machines within virtual machines. It is only intended for evaluation purposes and not supported for production purposes.



== v2v-conversion-host

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1749347[1749347]


Previously, systemd units from failed conversions were not removed from the host. These could cause collisions and prevent subsequent conversions from starting because the service name was already "in use." The current release fixes this issue. If the conversion fails, the units are explicitly removed so they cannot interfere with subsequent conversions.



== vdsm

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1684537[1684537]


Previously, a virtual machine could crash with the message "qemu-kvm: Failed to lock byte 100" during a live migration with storage problems. The current release fixes this issue in the underlying platform so the issue no longer happens.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1700623[1700623]


Previously, moving a disk resulted in the wrong SIZE/CAP key in the volume metadata. This happened because creating a volume that had a parent overwrote the size of the newly-created volume with the parent size. As a result, the volume metadata contained the wrong volume size value. The current release fixes this issue, so the volume metadata contains the correct value.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1746699[1746699]


Before this update,copying disks created by virt-v2v failed with an Invalid Parameter Exception, Invalid parameter:'DiskType=1'.
With this release, copying disks succeeds.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1818554[1818554]


The current version of RHV removes libvirt packages that provided non-socket activation. Now it contains only libvirt versions that provide socket activation. Socket activation  provides better resource handling: There is no dedicated active daemon; libvirt is activated for certain tasks and then exits.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1564280[1564280]


This enhancement adds support for OVMF with SecureBoot, which enables UEFI support for Virtual Machines.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1598266[1598266]


When a system had many FC LUNs with many paths per LUN, and a high I/O load, scanning of FC devices became slow, causing timeouts in monitoring VM disk size, and making VMs non-responsive.
In this release, FC scans have been optimized for speed, and VMs are much less likely to become non-responsive.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1612152[1612152]


Previously, Virtual Data Optimizer (VDO) statistics were not available for VDO volumes with an error, so VDO monitoring from VDSM caused a traceback. This update fixes the issue by correctly handling the different outputs from the VDO statistics tool.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1688159[1688159]


Previously, when a virtual machine migration entered post-copy mode and remained in that mode for a long time, the migration sometimes failed and the migrated virtual machine was powered off. In this release, post-copy migrations are maintained to completion.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1711902[1711902]


In a Red Hat Virtualization (RHV) environment with VDSM version 4.3 and Manager version 4.1, the DiskTypes are parsed as int values. However, in an RHV environment with Manager version > 4.1, the DiskTypes are parsed as strings. That compatibility mismatch produced an error: "VDSM error: Invalid parameter: 'DiskType=2'". The current release fixes this issue by changing the string value back to an int, so the operation succeeds with no error.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1759388[1759388]


Previously, ExecStopPost was present in the VDSM service file. This meant that, after stopping VDSM, some of its child processes could continue and, in some cases, lead to data corruption. The current release fixes this issue. It removes ExecStopPost from the VDSM service. As a result, terminating VDSM also stops its child processes.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1771977[1771977]


On RHV-4.4, NetworkManager manages the interface and static routes. As a result, you can make more robust modifications to static routes using Network Manager Stateful Configuration (nmstate).



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1783180[1783180]


Previously, a problem with AMD EPYC CPUs that were missing the virt-ssbd CPU flag prevented Hosted Engine installation. The current release fixes this issue.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1783815[1783815]


Previously, if a virtual machine (VM) was forcibly shut down by SIGTERM, in some cases the VDSM did not handle the libvirt shutdown event that contained information about why the VM was shut down and evaluated it as if the guest had initiated a clean shutdown. The current release fixes this issue: VDSM handles the shutdown event, and the Manager restarts the high-availability VMs as expected.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1813028[1813028]


Previously, if you exported a virtual machine (VM) as an Open Virtual Appliance (OVA) file from a host that was missing a loop device, and imported the OVA elsewhere, the resulting VM had an empty disk (no OS) and could not run. This was caused by a timing and permissions issue related to the missing loop device. The current release fixes the timing and permission issues. As a result, the VM to OVA export includes the guest OS. Now, when you create a VM from the OVA, the VM can run.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1816327[1816327]


Previously, if you tried to start an already-running virtual machine (VM) on the same host, VDSM failed this operation too late and the VM on the host became hidden from the RHV Manager. The current release fixes the issue: VDSM immediately rejects attempts to start a running VM on the same host.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1834873[1834873]


Previously, retrieving host capabilities failed for specific non-NUMA CPU topologies. The current release fixes this issue and correctly reports the host capabilities for those topologies.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1581417[1581417]


All new clusters with x86 architecture and compatibility version 4.4 or higher now set the BIOS Type to the Q35 Chipset by default, instead of the i440FX chipset.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1595536[1595536]


When a host is running in FIPS mode, VNC must use SASL authorization instead of regular passwords because of a weak algorithm inherent to the VNC protocol. The current release facilitates using SASL by providing an Ansible role, ovirt-host-setup-vnc-sasl, which you can run manually on FIPS-enabled hosts. This role does the following:

* Creates an empty SASL password database.
* Prepares the SASL config file for qemu.
* Changes the libvirt config file for qemu.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1639360[1639360]


Previously, mixing the Logical Volume Manager (LVM) activation and deactivation commands with other commands caused possible undefined LVM behavior and warnings in the logs. The current release fixes this issue. It runs the LVM activation and deactivation commands separately from other commands. This produces resulting well-defined LVM behavior and clear errors in case of failure.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1722854[1722854]


Previously, while VDSM was starting, the definition of the network filter vdsm-no-mac-spoofing was removed and recreated to ensure the filter was up to date. This occasionally resulted in a timeout during the start of VDSM. The current release fixes this issue. Instead of removing and recreating of the filter, the vdsm-no-mac-spoofing filter is updated during the start of the VDSM. This update takes less than a second, regardless of the number of vNICs using this filter.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1723668[1723668]


Previously, during virtual machine shut down, the VDSM command Get Host Statistics occasionally failed with an Internal JSON-RPC error `{'reason': '[Errno 19] vnet<x> is not present in the system'}`. This failure happened because the shutdown could make an interface disappear while statistics were being gathered. The current release fixes this issue. It prevents such failures from being reported.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1739557[1739557]


With this update, you can enable encryption for live migration of virtual machines between hosts in the same cluster. This provides more protection to data transferred between hosts. You can enable or disable encryption in the Administration Portal, in the Edit Cluster dialog box, under Migration Policy > Additional Properties. Encryption is disabled by default.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1788783[1788783]


Previously, when migrating a virtual machine, information about the running guest agent was not always passed to the destination host. In these cases, the migrated virtual machine on the destination host did not receive an after_migration life cycle event notification.
This update fixes this issue. The after_migration notification works as expected now.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1659574[1659574]


Previously, after upgrading RHV 4.1 to a later version, high-availability virtual machines (HA VMs) failed validation and did not run. To run the VMs, the user had to reset the lease Storage Domain ID. The current release fixes this issue: It removes the validation and regenerates the lease information data when the lease Storage Domain ID is set. After upgrading RHV 4.1, HA VMs with lease Storage Domain IDs run.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1684266[1684266]


When a large disk is converted as part of VM export to OVA, it takes a long time. Previously, the SSH channel the export script timed out and closed due to the long period of inactivity, leaving an orphan volume. The current release fixes this issue: Now, the export script adds some traffic to the SSH channel during disk conversion to prevent the SSH channel from being closed.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1713724[1713724]


Previously, converting a storage domain to the V5 format failed when, following an unsuccessful delete volume operation, partly-deleted volumes with cleared metadata remained in the storage domain. The current release fixes this issue. Converting a storage domain succeeds even when partly-deleted volumes with cleared metadata remain in the storage domain.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1724002[1724002]


Previously, cloud-init could not be used on hosts with FIPS enabled. With this update, cloud-init can be used on hosts with FIPS enabled.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1749630[1749630]


Previously, the Administration Portal showed very high memory usage for a host with no virtual machines running because it was not counting slab reclaimable memory. As a result, virtual machines could not be migrated to that host. The current release fixes that issue. The free host memory is evaluated correctly.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1688052[1688052]


Previously, the gluster fencing policy check failed due to a non-iterable object and threw an exception. The code also contained a minor typo. The current release fixes these issues.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1836609[1836609]


Previously, the `slot` parameter was parsed as a string, causing disk rollback to fail during the creation of a virtual machine from a template when using an Ansible script. Note that there was no such failure when using the Administration Portal to create a virtual machine from a template.
With this update, the `slot` parameter is parsed as an int, so disk rollback and virtual machine creation succeed.
