= RHSA-2021:1169-07 Moderate: RHV Manager (ovirt-engine) 4.4.z [ovirt-4.4.5] security, bug fix, enhancement

The bugs in this chapter are addressed by advisory RHSA-2021:1169-07. Further information about this advisory is available at https://errata.devel.redhat.com/advisory/68228.

== Ovirt-engine

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1145658[1145658]


This release allows the proper removal of a storage domain containing memory dumps, either by moving the memory dumps to another storage domain or deleting the memory dumps from the snapshot.




.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1155275[1155275]


With this update, you can synchronize a LUN's disk size on all hosts that are connected to the LUN's disk, and update its size on all running virtual machines to which it is attached.

To refresh a LUN's disk size:
1. In the Administration portal, go to Compute>Virtual Machines and select a virtual machine.
2. In the Disks tab, click Refresh LUN.

For connected virtual machines that are not running, update the disk on the virtual machines once they are running.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1688186[1688186]


Previously, the CPU and NUMA pinning were done manually or automatically only by using the REST API when adding a new virtual machine.

With this update, you can update the CPU and NUMA pinning using the Administration portal and when updating a virtual machine.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1837221[1837221]


Previously, the Manager was able to connect to hypervisors only using RSA public keys for SSH connection. With this update, the Manager can also use EcDSA and EdDSA public keys for SSH.

Previously, RHV used only the fingerprint of an SSH public key to verify the host. Now that RHV can use EcDSA and EdDSA public keys for SSH, the whole public SSH key must be stored in the RHV database. As a result, using the fingerprint of an SSH public key is deprecated.

When adding a new host to the Manager, the Manager will always use the strongest public key that the host offers, unless an administrator provides another specific public key to use.

For existing hosts, the Manager stores the entire RSA public key in its database on the next SSH connection. For example, if an administrator moves the host to maintenance mode and executes an enroll certificate or reinstalls the host, to use a different public key for the host, the administrator can provide a custom public key using the REST API or by fetching the strongest public key in the *Edit host* dialog in the Administration Portal.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1921104[1921104]


Ansible-2.9.17 is required for proper setup and functioning of Red Hat Virtualization Manager 4.4.5.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1431792[1431792]


This feature allows adding emulated TPM (Trusted Platform Module) devices to Virtual Machines.
TPM devices are useful in cryptographic operations (generating cryptographic keys, random numbers, hashes, etc.) or for storing data that can be used to verify software configurations securely. QEMU and libvirt implement support for emulated TPM 2.0 devices, which is what Red Hat Virtualization uses to add TPM devices to Virtual Machines.

Once an emulated TPM device is added to the Virtual Machine, it can be used as a normal TPM 2.0 device in the guest OS.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1910302[1910302]


Previously, the storage pool manager (SPM) failed to switch to another host if the SPM had uncleared tasks.
With this enhancement, a new UI menu has been added to enable cleaning up finished tasks.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1921119[1921119]


Previously, a cluster page indicated an out-of-sync cluster when in fact all networks were in sync. This was due to a logical error in the code when a host QoS was assigned to two networks on same host.
In this release, the cluster page does not show out-of-sync for this setup.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1895217[1895217]


Previously, after a host that virtual machines were pinned to  was removed, the Manager failed to start. As a result,the setup of the self-hosted engine failed.
In this release, when a host is removed, virtual machines no longer remain pinned to that host and the Manager can start successfully.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1905108[1905108]


Previously, plugging several virtual disks to a running virtual machine over a short time interval could cause a failure to plug some of the disks, and issued an error message: "Domain already contains a disk with that address".
In this release, this is avoided by making sure that a disk that is being plugged to a running virtual machine is not assigned with an address that has already been assigned to another disk that was previously plugged to the virtual machine.




.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1927851[1927851]


The timezone AUS Eastern Standard Time has been added to cover daylight saving time in Canberra, Melbourne and Sydney.




.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1931786[1931786]


Previously, the Red Hat Virtualization Manager missed the `SkuToAVLevel` configuration for 4.5 clusters.
In this release, the `SkuToAVLevel` is available for these clusters and allows Windows updates to update Red Hat related drivers for the guest host.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1884233[1884233]


The authz name is now used as the user domain on the RHVM (Red hat Virtualization Manager) home page. It replaces the profile name. Additionally, several log statements related to authorization/authentication flow have been made consistent by presenting both the user authz name and the profile name where applicable.
In this release, <username>@<authz name> is displayed on the home page once the user is successfully logged in to the RHVM. In addition, the log statements now contain both the authz name and the profile name as well as the username.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1922200[1922200]


Previously, records in the event_notification_hist table were only erased during regular cleanup of the audit_log table. By default, audit_log table records were only removed iof they were older than 30 days were removed.
In this release, because records in the event_notification_hist are much less important than records in the audit_log table, records in the event_notification_hist table are only kept for 7 days.
This limit can be overriden by creating a custom configuration file /etc/ovirt-engine/notifier/notifier.conf.d/history.conf with the following content:

 DAYS_TO_KEEP_HISTORY=NNN

where NNN is number of days to keep records in the event_notification_host table.
After changing this value ovirt-engine-notifier service needs to be restarted:

 systemctl restart ovirt-engine-notifier



== Vulnerability

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1889823[1889823]


A flaw was found in all released versions of m2crypto, where they are vulnerable to Bleichenbacher timing attacks in the RSA decryption API via the timed processing of valid PKCS#1 v1.5 Ciphertext. The highest threat from this vulnerability is to confidentiality.
