= RHSA-2020:5179-04 Low: Red Hat Virtualization security, bug fix, and enhancement update

The bugs in this chapter are addressed by advisory RHSA-2020:5179-04.
Further information about this advisory is available at https://access.redhat.com/errata/RHSA-2020:5179.


== ovirt-ansible-roles


.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1657294[1657294]


With this enhancement, the user can change the HostedEngine VM name after deployment.


== ovirt-engine


.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1702016[1702016]



Previously, the Manager allowed adding or migrating hosts configured as self-hosted engine hosts to a data center or cluster other than the one in which the self-hosted engine VM is running, even though all self-hosted engine hosts should be in the same data center and cluster. The hosts' IDs were identical to what they were when initially deployed, causing a Sanlock error. Consequently, the agent failed to start.

With this update, an error is raised when adding a new self-hosted engine host or migrating an existing one to a data center or cluster other than the one in which the self-hosted engine is running.

To add or migrate a self-hosted engine host to a data center or cluster other than the one in which the self-hosted engine is running, you need to disable the host from being a self-hosted engine host by reinstalling it. Follow these steps in the Administration Portal:

1. Move the host to Maintenance mode.
2. Invoke Reinstall with the *Hosted Engine UNDEPLOY* option selected. If using the REST API, use the `undeploy_hosted_engine` parameter.
3. Edit the host and select the target data center and cluster.
4. Activate the host.

For details, see the Administration Guide or REST API Guide.



.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1745024[1745024]


With this enhancement, the Intel Icelake Server Family is now supported in 4.4 and 4.5 compatibility levels.




.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1760170[1760170]


Previously, the MAC Pool search functionality failed to find unused addresses. As a result, creating a vNIC failed.
In this release, the MAC pool search is now able to locate an unused address in the pool, and all unused addresses are assigned from a pool.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1866862[1866862]


Previously, Virtual Machines deployed on AMD EPYC hosts without NUMA enabled sometimes failed to start, with an unsupported configuration error reported.
In this release, Virtual Machines start successfully on AMD EPYC hosts.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1888626[1888626]


Ansible-2.9.14 is required for proper setup and functioning of Red Hat Virtualization Manager 4.4.3.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1361718[1361718]


This enhancement provides support for attaching an emulated NVDIMM to virtual machines that are backed by NVDIMM on the host machine. For details, see https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/virtual_machine_management_guide/index#conc-nvdimm-host-devices_vm_guide_administrative_tasks






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1797717[1797717]


With this enhancement, you can now perform a free text search in the Administration Portal that includes internally defined keywords.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1808320[1808320]


Previously, users with specific Data Center or Cluster permissions could not edit the cluster they have access to.
In this release, users with specific Data Center or Cluster permissions can edit the cluster they have access to if they don't change the MAC pool associated with the cluster or attempt to add a new MAC pool.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1879280[1879280]


Default Data Center and Default Cluster, which are created during Red Hat Virtualization
installation, are created with 4.5 compatibility level by default in Red Hat Virtualization
4.4.3. Please be aware that compatibility level 4.5 requires RHEL 8.3 with
Advanced Virtualization 8.3.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1812316[1812316]


With this enhancement, when scheduling a Virtual Machine with pinned NUMA nodes, memory requirements are calculated correctly by taking into account the available memory as well as hugepages allocated on NUMA nodes.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1854888[1854888]


This enhancements adds error handling for OVA import and export operations, providing successful detection and reporting to the Red Hat Virtualization Manager if the qemu-img process fails to complete.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1855305[1855305]


Previously, hot-plugging a disk to Virtual Machine sometimes failed if the disk was assigned an address that was already assigned to a host-passthrough disk device.
In this release, conflicts are avoided by preventing an address that is assigned to host-passthrough disk device from being assigned to a disk that is hot-plugged to the Virtual Machine.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1871694[1871694]


Previously, changing a cluster's bios type to UEFI or UEFI+SecureBoot changed the Self-Hosted Engine Virtual Machine that runs within the cluster as well. As a result, the Self-Hosted Engine Virtual Machine failed to reboot upon restart.
In this release, the Self-Hosted Engine Virtual Machine is configured with a custom bios type, and does not change if the cluster's bios type changes.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1752751[1752751]


This enhancement enables customization of the columns displayed in the Virtual Machines table of the Administration Portal.
- Two new columns have been added to the Virtual Machines table - (number of) ‘vCPUs’, and ‘Memory (MB)’. These columns are not displayed by default.
- A new pop-up menu has been added to the Virtual Machines table that allows you to reset the table column settings, and to add or remove columns from the display.
- The selected column display settings (column visibility and order) are now persistent on the server by default, and are migrated (uploaded) to the server. This functionality can be disabled in the User > Options popup, by de-selecting the 'Persist grid settings' option.




== ovirt-engine-api-explorer


.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1884146[1884146]


The ovirt-engine-api-explorer package has been deprecated and removed in Red Hat Virtualization Manager 4.4.3.
Customers should use the official REST API Guide instead, which provides the same information as ovirt-engine-api-explorer.
See https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/rest_api_guide/index




== ovirt-engine-db-query


.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1866981[1866981]


Previously, unicode strings were not handled properly by the ovirt-engine-db-query after porting to Python3.
In this release, unicode strings are now handled properly.




== rhv-log-collector-analyzer


.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1859314[1859314]


Previously, unicode strings were not handled properly by the rhv-log-collector-analyzer after porting to python3.
In this release, unicode strings are now handled properly.





== vdsm


.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1613514[1613514]


This enhancement adds the ‘nowait’ option to the domain stats to help avoid instances of non-responsiveness in the VDSM.
As a result, libvirt now receives the ‘nowait’ option to avoid non-responsiveness.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1877632[1877632]


Previously, when the VDSM was restarted during a Virtual Machine migration on the migration destination host, the VM status wasn't identified correctly.
In this release, the VDSM identifies the migration destination status correctly.






.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1845397[1845397]

With this enhancement, the migration transfer speed in the VDSM log is now displayed as Mbps (Megabits per second).
