= RHSA-2020:3807-03 Moderate: Red Hat Virtualization security, bug fix, and enhancement update

The bugs in this chapter are addressed by advisory RHSA-2020:3807-03. Further information about this advisory is available at https://access.redhat.com/errata/RHSA-2020:3807.

== ovirt-engine

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1749803[1749803] 

This enhancement enables you to set the same target domain for multiple disks. 

Previously, when moving or copying multiple disks, you needed to set the target domain for each disk separately. Now, if a common target domain exists, you can set it as the target domain for all disks.

If there is no common storage domain, such that not all disks are moved or copied to the same storage domain, set the common target domain as 'Mixed'.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1804037[1804037]

Previously, the `Memory` scheduling filter did not correctly consider memory for huge pages. Consequently, the Manager tried to start virtual machines without huge pages on the memory dedicated to huge pages.

With this update, the `Memory` filter correctly considers huge page memory.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1804046[1804046] 

Previously the RHV Manager did not reduce scheduling memory when a virtual machine with dynamic hugepages was running. Instead, the Manager treated the memory occupied by dynamic hugepages as schedulable memory. As a result, the Manager scheduled more virtual machines on a host than could fit on it. The current release fixes this issue. Now, the Manager treats dynamic hugepages and the memory they occupy correctly.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1843234[1843234] 

Before this update, when using Firefox 74.0.1 and greater with Autofill enabled, the Administration Portal password was used to autofill the Sysprep Administrator password field in the *Initial Run* tab of the *Run Virtual Machine(s)* dialog. Validation of the dialog failed because the password did not match the *Verify admin password* field, which was not autofilled.

This issue has been resolved, and the browser no longer uses Autofill for the Sysprep admin password field.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1871235[1871235] 

Before this update, a virtual machine that was set with a High Performance profile using the REST API could not start if it had any USB devices, because the High Performance profile disabled the USB controller. Additionally, hosts in clusters with compatibility level 4.3 did not report the TSC frequency.

This update resolves these issues. TSC is no longer present for 4.3 clusters and the VM won't have USB devices when there is no USB controller, allowing VMs to run normally.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1643520[1643520] 

Before this update, when updating a disk profile using the REST API, sending an empty QoS tag `<qos />` had no effect. Consequently, it was not possible to remove QoS from the disk profile using the REST API.

This update resolves this issue, and now sending an empty QoS tag (`<qos />`) removes QoS from the disk profile.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1763812[1763812] 

The current release moves the button to *Remove* a virtual machine to the "more" menu (three dots in the upper-right area). This was done to improve usability: Too many users pressed the *Remove* button, mistakenly believing it would remove a selected item in the details view, such as a snapshot. They did not realize it would delete the virtual machine. The new location should help users avoid this kind of mistake.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1819260[1819260] 

The following search filter properties for Storage Domains have been enhanced: 
- 'size' changed to 'free_size'
- 'total_size' added to the search engine options
- 'used' changed to 'used_size'

For example , you can use now the following in the Storage Domains tab:

*free_size > 6 GB and total_size < 20 GB*

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1674420[1674420]

This update adds support for the following virtual CPU models:

- Intel Cascade Lake Server
- Intel Ivy Bridge

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1806339[1806339]

The current release changes the *Huge Pages* label to *Free Huge Pages* so it is easier to understand what the values represent.

== ovirt-engine-ui-extensions

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1875851[1875851] 

Firefox 68 ESR does not support several standard units in the <svg> tag. (For more information, see https://bugzilla.mozilla.org/show_bug.cgi?id=1287054.) Consequently, before this update, aggregated status card icons appeared larger than intended.

This update uses supported units to size icons, and as a result, icons appear correctly in FireFox 68 ESR and later.

== vdsm

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1869209[1869209] 

Before this update, adding hosts with newer Intel CPUs to IBRS family clusters could fail, and the spec_ctrl flag was not detected.

This update resolves the issue and you can now add hosts with modern Intel CPUs to the IBRS family clusters and the spec_ctrl flag is detected.

== vulnerability

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1828406[1828406] 

A Cross-site scripting (XSS) vulnerability exists in JQuery. This flaw allows an attacker with the ability to supply input to the ‘HTML’ function to inject Javascript into the page where that input is rendered, and have it delivered by the browser.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1850004[1850004] 

A flaw was found in jQuery in versions beginning in 1.0.3 through 3.5.0. HTML containing ` elements from untrusted sources are passed, even after sanitizing, to one of jQuery's DOM manipulation methods which may execute untrusted code. The highest threat from this vulnerability is to data confidentiality and integrity.

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1858184[1858184] 

A flaw was found in the web interface of ovirt-engine 4.4.2 and earlier, where it did not filter user-controllable parameters completely, resulting in a reflected cross-site scripting attack. This flaw allows an attacker to leverage a phishing attack, steal an unsuspecting user's cookies or other confidential information, or impersonate them within the application's context.
