= RHSA-2021:4626-06 Moderate: RHV Manager (ovirt-engine) security update [ovirt-4.4.9]


The bugs in this chapter are addressed by advisory RHSA-2021:4626-06. Further information about this advisory is available at https://errata.devel.redhat.com/advisory/81159.


== ovirt-engine

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1940991[1940991]


Previously, when hot unplugging memory in rapid succession using REST API, the same DIMMs could be hot unplugged multiple times instead of using different DIMMs for different hot unplug actions. This resulted in failed hot unplugs and could lead to invalid assumptions about the amount of RAM in the virtual machine.
In this release, this issue is fixed, and DIMMs that are hot unplugged are no longer used in followup hot unplugs.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1979730[1979730]


Previously, when upgrading a cluster from cluster level 4.5 to 4.6, the emulated machine changed to a newer one. This caused problems on some Windows virtual machines, such as - loss of static IP configuration or secondary disks going offline.
In this release, the Webadmin shows a confirmation dialog during the cluster upgrade from cluster level 4.5 or lower to cluster level 4.6 or higher if there are any virtual machines that could be affected.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=2004444[2004444]


During host installation or host upgrade, the Manager checks if cinderlib and Ceph packages are available. If not, it tries to enable the required channels specified in the documentation. If there is a problem during channel enablement, an error is raised in the audit_log, and customers need to enable the channel manually and retry the  installation or upgrade.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=2014017[2014017]


Previously, the status of the operation (download VM disks) was changed to one of the final statuses (FINISHED_SUCCESS / FINISHED_FAILURE) before the disk locks were actually released. As a result, in  some scenarios, the operation following  this one failed with a Disk is locked error.
In this release, the locks are released immediately before changing the command status to one of the final phases. AS a result, the operation that follows this one and uses the same disk will succeed.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1977276[1977276]


Previously, in some cases, adding a new disk for the upload succeeded, but the system handled the operation as a failure. AS a result, the upload failed silently without uploading any data and ending in an empty new disk.
In this release, the add disk success is detected correctly, and uploading completes successfully.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=2000364[2000364]


Previously, on Manager startup, system threads may have been used to retrieve the virtual machine configuration from stateless snapshots, causing the Manager to fail to start.
In this release, the way of retrieving the virtual machine configuration from stateless snapshots on the Manager was changed to avoid using the system thread and only use application threads. AS a result, the Manager can start when stateless snapshots with cloud-init network properties are defined.





== ovirt-engine-dwh

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1992690[1992690]


Previously, the Inventory dashboard showed CPU overcommit rates for each data center.
In this release, CPU overcommit rates are available in the Inventory dashboard for each cluster as well.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=2007550[2007550]


In this release, the data type for the virtual machines disk write/read rate was changed from integer to long.





== ovirt-engine-metrics

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1978655[1978655]


Previously, ELK integration failed due to missing configuration parameters when using certificates.
In this release, the missing parameters were added, and updated to the correct names according to the logging role. ELK integration now works with or without certificates.





== ovirt-web-ui

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1957830[1957830]


In this release, the VM Portal now allows creating preallocated or thin provisioned disk images on various types of storage domains.





== RFEs

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1352501[1352501]


In this release, using virtual TPM, it is now possible to inject a LUKS encryption key to the guest operating system.





== rhv-log-collector-analyzer

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1989324[1989324]


Previously, the UploadStreamCommand updated the OVF_STORE Actual disk size in the database incorrectly during an OVF update. As a result, rhv-image-discrepancies received the wrong disk size.
In this release, OVF and Self-Hosted Engine metadata are skipped by rhv-image-discrepancies, and the tool does not produce irrelevant warnings.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=2001551[2001551]


In this release, rhv-image-discrepancies now allows more granular checks.
Two new options have been added to rhv-image-discrepancies command line to restrict the run to specific data centers or storage domains. If both are specified it is restricted to the intersection of both.
-p --pool-uuid: limit run to data centers, can be specified multiple times
-s --storage-uuid: limit run to storage domains, can be specified multiple times
For example:
# rhv-image-discrepancies -p=5bbe9966-ea58-475f-863f -s=977ba581-23e5-460a-b1de





== vulnerability

.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1945459[1945459]


A flaw was found in nodejs-glob-parent. The enclosure regex used to check for glob enclosures containing backslashes is vulnerable to Regular Expression Denial of Service attacks. This flaw allows an attacker to cause a denial of service if they can supply a malicious string to the glob-parent function. The highest threat from this vulnerability is to system availability.





.BZ#link:https://bugzilla.redhat.com/show_bug.cgi?id=1879733[1879733]


A flaw was found in nodejs-ua-parser-js. The software is vulnerable to Regular Expression Denial of Service (ReDoS) via the regex for Redmi Phones and Mi Pad Tablets UA.
